GRANT EXECUTE ON TRANSP_UTL TO BARS_ACCESS_DEFROLE;
GRANT EXECUTE ON TRANSP_UTL TO BARS;
GRANT SELECT ON OUT_MAIN_REQ TO BARS;
GRANT SELECT ON OUT_REQS TO BARS;
GRANT SELECT ON OUT_TYPES TO BARS;
GRANT SELECT ON INPUT_REQS TO BARS;
GRANT SELECT ON INPUT_RESP_PARAMS TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON INPUT_TYPES TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON DICT_MIME_TYPES TO BARS_ACCESS_DEFROLE;
/
