/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.W4
{
    public sealed class VW4ProectGroupsRecord : BbRecord
    {
        public VW4ProectGroupsRecord(): base()
        {
            fillFields();
        }
        public VW4ProectGroupsRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VW4ProectGroupsRecord(BbDataSource Parent, OracleDecimal RowScn, String CODE, String NAME)
            : this(Parent)
        {
            this.CODE = CODE;
            this.NAME = NAME;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("CODE", OracleDbType.Varchar2, false, false, false, false, false, "V_W4_PROECT_GROUPS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_W4_PROECT_GROUPS", ObjectTypes.View, "", ""));        
        }
        public String CODE { get { return (String)FindField("CODE").Value; } set {SetField("CODE", value);} }
        public String NAME { get { return (String)FindField("NAME").Value; } set {SetField("NAME", value);} }
    }

    public sealed class VW4ProectGroupsFilters : BbFilters
    {
        public VW4ProectGroupsFilters(BbDataSource Parent) : base (Parent)
        {
            CODE = new BBVarchar2Filter(this, "CODE");
            NAME = new BBVarchar2Filter(this, "NAME");
        }
        public BBVarchar2Filter CODE;
        public BBVarchar2Filter NAME;
    }

    public partial class VW4ProectGroups : BbTable<VW4ProectGroupsRecord, VW4ProectGroupsFilters>
    {
        public VW4ProectGroups() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VW4ProectGroups(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VW4ProectGroupsRecord> Select(VW4ProectGroupsRecord Item)
        {
            List<VW4ProectGroupsRecord> res = new List<VW4ProectGroupsRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VW4ProectGroupsRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (String)null : Convert.ToString(rdr[1]), 
                        rdr.IsDBNull(2) ?  (String)null : Convert.ToString(rdr[2]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}