CREATE OR REPLACE FORCE VIEW BARS.CC_SOB_TXT_U
AS
   SELECT TXT
     FROM bars.CC_SOB_TXT;
     
GRANT SELECT ON BARS.CC_SOB_TXT_U TO BARS_ACCESS_DEFROLE;

GRANT SELECT ON BARS.CC_SOB_TXT_U TO START1;