CREATE OR REPLACE VIEW MOPER_NM3_ACC 
AS
SELECT * FROM ACCOUNTS WHERE TIP = '90D';

grant select on  MOPER_NM3_ACC to bars_access_defrole
/

CREATE or replace PUBLIC SYNONYM MOPER_NM3_ACC FOR BARS.MOPER_NM3_ACC
/