-- виртуальные  обороты  по лиц.счетам
CREATE OR REPLACE VIEW SALDO_V AS 
SELECT KF,acc,FDAT,kv,nls,NBS,ob22,DECODE (SIGN (ost), -1, -OST, 0) dOS,DECODE (SIGN (ost), 1, OST, 0) kOS,'NEW' POS,NBS NBS1,ob22 ob22_1     FROM SALDO_V1
   UNION ALL
SELECT KF,acc,FDAT,kv,nlsALt,SUBSTR (nlsalt,1,4),T2017.OB22_old(NBS,OB22,SUBSTR (nlsalt,1,4)),DECODE(SIGN(ost),1,OST,0), DECODE(SIGN(ost),-1,-OST,0), 'OLD',NBS NBS1,ob22 ob22_1     FROM SALDO_V1;

GRANT SELECT ON BARS.SALDO_V TO BARS_ACCESS_DEFROLE;

