CREATE OR REPLACE FORCE VIEW "BARS"."V_CUSTOMER_CORPORATIONS" ("RNK", "NMK", "EXTERNAL_ID", "CORPORATION_NAME", "ORG_ID", "ORG_NAME") AS 
  select c.RNK,
       c.NMK,
       --cwp.VALUE parent_id,
       vr.EXTERNAL_ID,
       vr.CORPORATION_NAME,
       --vo.base_corp_name,
       --cwc.VALUE child_id,
       vo.EXTERNAL_ID org_id,
       vo.CORPORATION_NAME org_name
from      customer  c
join      customerw cwp on c.RNK = cwp.RNK and cwp.TAG = 'OBPCP'
left join customerw cwc on c.RNK = cwc.RNK and cwc.TAG = 'OBCRP'
left join V_ROOT_CORPORATION vr on vr.EXTERNAL_ID = cwp.VALUE
left join V_ORG_CORPORATIONS vo  on vo.EXTERNAL_ID = cwc.VALUE and vo.base_extid = vr.EXTERNAL_ID
;
/
  GRANT SELECT ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "BARS_ACCESS_DEFROLE";
  GRANT SELECT ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "CORP_CLIENT";
  GRANT SELECT ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "WR_REFREAD";
  GRANT FLASHBACK ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "WR_REFREAD";
  GRANT DELETE ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "BARS_ACCESS_DEFROLE";
  GRANT INSERT ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "BARS_ACCESS_DEFROLE";
  GRANT UPDATE ON "BARS"."V_CUSTOMER_CORPORATIONS" TO "BARS_ACCESS_DEFROLE";
/