/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace cim
{
    public partial class VCimBeneficiaries
    {
        public List<VCimBeneficiariesRecord> SelectBEneficiar(Decimal? BENEF_ID)
        {
            this.Filter.BENEF_ID.Equal(BENEF_ID);

            return this.Select();
        }
    }


}