/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public partial class WcsSignTypes
    {
        public List<WcsSignTypesRecord> SelectWcsSignTypesMin()
        {
            this.Filter.ID.In(new List<String>(new String[] { "LESS", "LESS_OR_EQUAL" }));
            return Select();
        }
        public List<WcsSignTypesRecord> SelectWcsSignTypesMax()
        {
            this.Filter.ID.In(new List<String>(new String[] { "GREATER", "GREATER_OR_EQUAL" }));
            return Select();
        }
    }
}