

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/PFU/Table/PFU_EPP_LINE.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** Create  table PFU_EPP_LINE ***
begin 
  execute immediate '
  CREATE TABLE PFU.PFU_EPP_LINE 
   (	ID NUMBER(10,0), 
	BATCH_REQUEST_ID NUMBER(10,0), 
	LINE_ID NUMBER(10,0), 
	EPP_NUMBER VARCHAR2(4000), 
	EPP_EXPIRY_DATE VARCHAR2(4000), 
	PERSON_RECORD_NUMBER VARCHAR2(4000), 
	LAST_NAME VARCHAR2(4000), 
	FIRST_NAME VARCHAR2(4000), 
	MIDDLE_NAME VARCHAR2(4000), 
	GENDER VARCHAR2(4000), 
	DATE_OF_BIRTH VARCHAR2(4000), 
	PHONE_NUMBERS VARCHAR2(4000), 
	EMBOSSING_NAME VARCHAR2(4000), 
	TAX_REGISTRATION_NUMBER VARCHAR2(4000), 
	DOCUMENT_TYPE VARCHAR2(4000), 
	DOCUMENT_ID VARCHAR2(4000), 
	DOCUMENT_ISSUE_DATE VARCHAR2(4000), 
	DOCUMENT_ISSUER VARCHAR2(4000), 
	DISPLACED_PERSON_FLAG VARCHAR2(4000), 
	LEGAL_COUNTRY VARCHAR2(4000), 
	LEGAL_ZIP_CODE VARCHAR2(4000), 
	LEGAL_REGION VARCHAR2(4000), 
	LEGAL_DISTRICT VARCHAR2(4000), 
	LEGAL_SETTLEMENT VARCHAR2(4000), 
	LEGAL_STREET VARCHAR2(4000), 
	LEGAL_HOUSE VARCHAR2(4000), 
	LEGAL_HOUSE_PART VARCHAR2(4000), 
	LEGAL_APARTMENT VARCHAR2(4000), 
	ACTUAL_COUNTRY VARCHAR2(4000), 
	ACTUAL_ZIP_CODE VARCHAR2(4000), 
	ACTUAL_REGION VARCHAR2(4000), 
	ACTUAL_DISTRICT VARCHAR2(4000), 
	ACTUAL_SETTLEMENT VARCHAR2(4000), 
	ACTUAL_STREET VARCHAR2(4000), 
	ACTUAL_HOUSE VARCHAR2(4000), 
	ACTUAL_HOUSE_PART VARCHAR2(4000), 
	ACTUAL_APARTMENT VARCHAR2(4000), 
	BANK_MFO VARCHAR2(4000), 
	BANK_NUM VARCHAR2(4000), 
	BANK_NAME VARCHAR2(4000), 
	STATE_ID NUMBER(5,0), 
	LINE_SIGN RAW(128), 
	ACTIVATION_DATE DATE, 
	DESTRUCTION_DATE DATE, 
	BLOCK_DATE DATE, 
	UNBLOCK_DATE DATE, 
	ACCOUNT_NUMBER VARCHAR2(15), 
	SIGN_PASS_CHANGE_FLAG NUMBER(1,0), 
	BRANCH VARCHAR2(4000), 
	PENS_TYPE VARCHAR2(4000), 
	TYPE_CARD VARCHAR2(4000), 
	TERM_CARD NUMBER(3,0), 
	RNK NUMBER(38,0), 
	COMM VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSBIGD ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE PFU.PFU_EPP_LINE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.COMM IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ID IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.BATCH_REQUEST_ID IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LINE_ID IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.EPP_NUMBER IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.EPP_EXPIRY_DATE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.PERSON_RECORD_NUMBER IS 'Номер облікової картки застрахованої особи в Пенсійному фонді';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LAST_NAME IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.FIRST_NAME IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.MIDDLE_NAME IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.GENDER IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DATE_OF_BIRTH IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.PHONE_NUMBERS IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.EMBOSSING_NAME IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.TAX_REGISTRATION_NUMBER IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DOCUMENT_TYPE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DOCUMENT_ID IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DOCUMENT_ISSUE_DATE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DOCUMENT_ISSUER IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DISPLACED_PERSON_FLAG IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_COUNTRY IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_ZIP_CODE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_REGION IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_DISTRICT IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_SETTLEMENT IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_STREET IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_HOUSE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_HOUSE_PART IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LEGAL_APARTMENT IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_COUNTRY IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_ZIP_CODE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_REGION IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_DISTRICT IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_SETTLEMENT IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_STREET IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_HOUSE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_HOUSE_PART IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTUAL_APARTMENT IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.BANK_MFO IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.BANK_NUM IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.BANK_NAME IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.STATE_ID IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.LINE_SIGN IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACTIVATION_DATE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.DESTRUCTION_DATE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.BLOCK_DATE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.UNBLOCK_DATE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.SIGN_PASS_CHANGE_FLAG IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.BRANCH IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.PENS_TYPE IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.TYPE_CARD IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.TERM_CARD IS '';
COMMENT ON COLUMN PFU.PFU_EPP_LINE.RNK IS '';




PROMPT *** Create  constraint FK_EPP_LINE_REF_BATCH ***
begin   
 execute immediate '
  ALTER TABLE PFU.PFU_EPP_LINE ADD CONSTRAINT FK_EPP_LINE_REF_BATCH FOREIGN KEY (BATCH_REQUEST_ID)
	  REFERENCES PFU.PFU_EPP_BATCH_REQUEST (ID) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_PFU_EPP_LINE ***
begin   
 execute immediate '
  ALTER TABLE PFU.PFU_EPP_LINE ADD CONSTRAINT PK_PFU_EPP_LINE PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGD  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00111506 ***
begin   
 execute immediate '
  ALTER TABLE PFU.PFU_EPP_LINE MODIFY (BATCH_REQUEST_ID NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00111505 ***
begin   
 execute immediate '
  ALTER TABLE PFU.PFU_EPP_LINE MODIFY (ID NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_PFU_EPP_LINE ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX PFU.PK_PFU_EPP_LINE ON PFU.PFU_EPP_LINE (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGD ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index UI_PFU_EPP_LINE ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX PFU.UI_PFU_EPP_LINE ON PFU.PFU_EPP_LINE (CASE STATE_ID WHEN 3 THEN NULL ELSE EPP_NUMBER END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  TABLESPACE BRSBIGD ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/PFU/Table/PFU_EPP_LINE.sql =========*** End *** =
PROMPT ===================================================================================== 
