/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.Ins
{
    public partial class VInsPartnerTypeScans
    {
        public List<VInsPartnerTypeScansRecord> SelectPartnerTypeScans(Decimal? PARTNER_ID, Decimal? TYPE_ID)
        {
            this.Filter.PARTNER_ID.Equal(PARTNER_ID);
            this.Filter.TYPE_ID.Equal(TYPE_ID);
            return this.Select();
        }
    }
}