<input runat="server" type="hidden" id="Mes0" value='<%$ Resources:Deposit.GlobalResources, Mes0%>'/><!--"Некоректне значення"--> 
<input runat="server" type="hidden" id="Mes1" value='<%$ Resources:Deposit.GlobalResources, Mes1%>'/><!--"Очистіть поле рахунку и введіть спочатку МФО"--> 
<input runat="server" type="hidden" id="Mes2" value='<%$ Resources:Deposit.GlobalResources, Mes2%>'/><!--"Некоректно вказувати у цьому випадку рахунок каси"--> 
<input runat="server" type="hidden" id="Mes3" value='<%$ Resources:Deposit.GlobalResources, Mes3%>'/><!--"Змініть поле, чи залиште його порожнім"--> 
<input runat="server" type="hidden" id="Mes4" value='<%$ Resources:Deposit.GlobalResources, Mes4%>'/><!--"необхідно заповнити НОР!"--> 
<input runat="server" type="hidden" id="Mes5" value='<%$ Resources:Deposit.GlobalResources, Mes5%>'/><!--"необхідно заповнити МФО!"--> 
<input runat="server" type="hidden" id="Mes6" value='<%$ Resources:Deposit.GlobalResources, Mes6%>'/><!--"Неможливо виконати операцію."--> 
<input runat="server" type="hidden" id="Mes7" value='<%$ Resources:Deposit.GlobalResources, Mes7%>'/><!--"Нульова сума!"--> 
<input runat="server" type="hidden" id="Mes8" value='<%$ Resources:Deposit.GlobalResources, Mes8%>'/><!--"Сума менша мінімально допустимої!"--> 
<input runat="server" type="hidden" id="Mes9" value='<%$ Resources:Deposit.GlobalResources, Mes9%>'/><!--"Сума більша максимально допустимої допустимої!"--> 
<input runat="server" type="hidden" id="Mes44" value='<%$ Resources:Deposit.GlobalResources, Mes44%>'/><!--"Необхідно заповнити код ЄДРПОУ!"--> 
<input runat="server" type="hidden" id="Mes45" value='<%$ Resources:Deposit.GlobalResources, Mes45%>'/><!--"Необхідно заповнити одержувача!"--> 