/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.Ins
{
    public partial class VInsPartnerTypeScansAdm
    {
        public List<VInsPartnerTypeScansAdmRecord> SelectPartnerTypeScans()
        {
            return this.Select();
        }
    }
}