-- COBUMMFO-9690
@bars\Function\f_nbu_rpt_xml_row.sql
@bars\Package\accreg.sql
@bars\Package\bars_login.sql
@bars\Package\bars_loss_events.sql
@bars\Package\bars_utl_snapshot.sql
@bars\Package\csv.sql
@bars\Package\dpt_utils.sql
@bars\Package\dpt_web.sql
@bars\Package\dpu.sql
@bars\Package\dpu_agr.sql
@bars\Package\ebk_request_utl.sql
@bars\Package\nbur_objects.sql
@bars\Package\rs.sql
@bars\Package\tms_utl.sql
@bars\Procedure\make_int.sql
@bars\Procedure\rnk2rnk.sql
@bars\Script\ResMgr_Grant_privs.sql
@bars\Script\ResMgr_Create_Plan.sql
@bars\Script\ResMgr_Group_Mapping.sql
