

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARSUPL/Table/TMP_NBU23_REZ.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** Create  table TMP_NBU23_REZ ***
begin 
  execute immediate '
  CREATE TABLE BARSUPL.TMP_NBU23_REZ 
   (	KF VARCHAR2(4000), 
	FDAT DATE, 
	ID VARCHAR2(50), 
	RNK NUMBER, 
	NBS CHAR(4), 
	KV NUMBER, 
	ND NUMBER, 
	CC_ID VARCHAR2(50), 
	ACC NUMBER, 
	NLS VARCHAR2(20), 
	BRANCH VARCHAR2(30), 
	FIN NUMBER, 
	OBS NUMBER, 
	KAT NUMBER, 
	K NUMBER, 
	IRR NUMBER, 
	ZAL NUMBER, 
	BV NUMBER, 
	PV NUMBER, 
	REZ NUMBER, 
	REZQ NUMBER, 
	DD CHAR(1), 
	DDD CHAR(3), 
	BVQ NUMBER, 
	CUSTTYPE NUMBER, 
	IDR NUMBER, 
	WDATE DATE, 
	OKPO NUMBER, 
	NMK VARCHAR2(35), 
	RZ NUMBER, 
	PAWN NUMBER, 
	ISTVAL NUMBER, 
	R013 VARCHAR2(2), 
	REZN NUMBER, 
	REZNQ NUMBER, 
	ARJK NUMBER, 
	REZD NUMBER, 
	PVZ NUMBER, 
	PVZQ NUMBER, 
	ZALQ NUMBER, 
	ZPR NUMBER, 
	ZPRQ NUMBER, 
	PVQ NUMBER, 
	RU VARCHAR2(70), 
	INN VARCHAR2(20), 
	NRC VARCHAR2(70), 
	SDATE DATE, 
	IR NUMBER, 
	S031 VARCHAR2(2), 
	K040 VARCHAR2(3), 
	PROD VARCHAR2(50), 
	K110 VARCHAR2(5), 
	K070 VARCHAR2(5), 
	K051 VARCHAR2(2), 
	S260 VARCHAR2(2), 
	R011 VARCHAR2(1), 
	R012 VARCHAR2(1), 
	S240 VARCHAR2(1), 
	S180 VARCHAR2(1), 
	S580 VARCHAR2(1), 
	NLS_REZ VARCHAR2(15), 
	NLS_REZN VARCHAR2(15), 
	S250 CHAR(1), 
	ACC_REZ NUMBER, 
	FIN_R NUMBER(*,0), 
	DISKONT NUMBER, 
	ISP NUMBER(*,0), 
	OB22 CHAR(2), 
	TIP CHAR(3), 
	SPEC CHAR(1), 
	ZAL_BL NUMBER, 
	S280_290 CHAR(1), 
	ZAL_BLQ NUMBER, 
	ACC_REZN NUMBER, 
	OB22_REZ CHAR(2), 
	OB22_REZN CHAR(2), 
	IR0 NUMBER, 
	IRR0 NUMBER, 
	ND_CP NUMBER, 
	SUM_IMP NUMBER, 
	SUMQ_IMP NUMBER, 
	PV_ZAL NUMBER, 
	VKR VARCHAR2(10), 
	S_L NUMBER, 
	SQ_L NUMBER, 
	ZAL_SV NUMBER, 
	ZAL_SVQ NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSUPLD ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE BARSUPL.TMP_NBU23_REZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.KF IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.FDAT IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ID IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.RNK IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.NBS IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.KV IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ND IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.CC_ID IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ACC IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.NLS IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.BRANCH IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.FIN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.OBS IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.KAT IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.K IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.IRR IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZAL IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.BV IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PV IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.REZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.REZQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.DD IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.DDD IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.BVQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.CUSTTYPE IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.IDR IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.WDATE IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.OKPO IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.NMK IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.RZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PAWN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ISTVAL IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.R013 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.REZN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.REZNQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ARJK IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.REZD IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PVZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PVZQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZALQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZPR IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZPRQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PVQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.RU IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.INN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.NRC IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.SDATE IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.IR IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S031 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.K040 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PROD IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.K110 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.K070 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.K051 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S260 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.R011 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.R012 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S240 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S180 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S580 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.NLS_REZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.NLS_REZN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S250 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ACC_REZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.FIN_R IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.DISKONT IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ISP IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.OB22 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.TIP IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.SPEC IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZAL_BL IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S280_290 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZAL_BLQ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ACC_REZN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.OB22_REZ IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.OB22_REZN IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.IR0 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.IRR0 IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ND_CP IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.SUM_IMP IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.SUMQ_IMP IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.PV_ZAL IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.VKR IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.S_L IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.SQ_L IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZAL_SV IS '';
COMMENT ON COLUMN BARSUPL.TMP_NBU23_REZ.ZAL_SVQ IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARSUPL/Table/TMP_NBU23_REZ.sql =========*** End 
PROMPT ===================================================================================== 
