SET DEFINE OFF;
MERGE INTO BARS.CUSTOMER_FIELD_CODES A USING
 (SELECT
  'KRED' as CODE,
  'Для Кредитного реєстру' as NAME,
  7 as ORD
  FROM DUAL) B
ON (A.CODE = B.CODE)
WHEN NOT MATCHED THEN 
INSERT (
  CODE, NAME, ORD)
VALUES (
  B.CODE, B.NAME, B.ORD)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME = B.NAME,
  A.ORD = B.ORD;

COMMIT;
