SET DEFINE OFF;
MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  1 as SETTLEMENT_TP_ID,
  'місто' as SETTLEMENT_TP_NM,
  'город' as SETTLEMENT_TP_NM_RU,
  'м.' as SETTLEMENT_TP_CODE,
  'city' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  2 as SETTLEMENT_TP_ID,
  'смт' as SETTLEMENT_TP_NM,
  'пгт' as SETTLEMENT_TP_NM_RU,
  'смт.' as SETTLEMENT_TP_CODE,
  'urban-type settlement' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  3 as SETTLEMENT_TP_ID,
  'селище' as SETTLEMENT_TP_NM,
  'поселок' as SETTLEMENT_TP_NM_RU,
  'сел.' as SETTLEMENT_TP_CODE,
  'village' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  4 as SETTLEMENT_TP_ID,
  'село' as SETTLEMENT_TP_NM,
  'село' as SETTLEMENT_TP_NM_RU,
  'с.' as SETTLEMENT_TP_CODE,
  'village' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  5 as SETTLEMENT_TP_ID,
  'хутір' as SETTLEMENT_TP_NM,
  'хутор' as SETTLEMENT_TP_NM_RU,
  'хутір' as SETTLEMENT_TP_CODE,
  'farm' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  6 as SETTLEMENT_TP_ID,
  'ст.' as SETTLEMENT_TP_NM,
  'ст.' as SETTLEMENT_TP_NM_RU,
  'ст.' as SETTLEMENT_TP_CODE,
  NULL as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  7 as SETTLEMENT_TP_ID,
  'санат.' as SETTLEMENT_TP_NM,
  'санат.' as SETTLEMENT_TP_NM_RU,
  'санат.' as SETTLEMENT_TP_CODE,
  'sanatorium' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  8 as SETTLEMENT_TP_ID,
  'радгосп' as SETTLEMENT_TP_NM,
  'совхоз' as SETTLEMENT_TP_NM_RU,
  'радгосп' as SETTLEMENT_TP_CODE,
  'state farm' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  9 as SETTLEMENT_TP_ID,
  'вокзал' as SETTLEMENT_TP_NM,
  'вокзал' as SETTLEMENT_TP_NM_RU,
  'вокзал' as SETTLEMENT_TP_CODE,
  'station' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  10 as SETTLEMENT_TP_ID,
  'лісництво' as SETTLEMENT_TP_NM,
  'лесничество' as SETTLEMENT_TP_NM_RU,
  'лісництво' as SETTLEMENT_TP_CODE,
  'forestry' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  11 as SETTLEMENT_TP_ID,
  'док' as SETTLEMENT_TP_NM,
  'док' as SETTLEMENT_TP_NM_RU,
  'док' as SETTLEMENT_TP_CODE,
  'dock' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

MERGE INTO BARS.ADR_SETTLEMENT_TYPES A USING
 (SELECT
  12 as SETTLEMENT_TP_ID,
  'поселення' as SETTLEMENT_TP_NM,
  'поселение' as SETTLEMENT_TP_NM_RU,
  'поселення' as SETTLEMENT_TP_CODE,
  'settlement' as SETTLEMENT_TP_NM_ENG
  FROM DUAL) B
ON (A.SETTLEMENT_TP_ID = B.SETTLEMENT_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SETTLEMENT_TP_ID, SETTLEMENT_TP_NM, SETTLEMENT_TP_NM_RU, SETTLEMENT_TP_CODE, SETTLEMENT_TP_NM_ENG)
VALUES (
  B.SETTLEMENT_TP_ID, B.SETTLEMENT_TP_NM, B.SETTLEMENT_TP_NM_RU, B.SETTLEMENT_TP_CODE, B.SETTLEMENT_TP_NM_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.SETTLEMENT_TP_NM = B.SETTLEMENT_TP_NM,
  A.SETTLEMENT_TP_NM_RU = B.SETTLEMENT_TP_NM_RU,
  A.SETTLEMENT_TP_CODE = B.SETTLEMENT_TP_CODE,
  A.SETTLEMENT_TP_NM_ENG = B.SETTLEMENT_TP_NM_ENG;

COMMIT;
