SET DEFINE OFF;
MERGE INTO BARS.ADR_ROOM_TYPE A USING
 (SELECT
  1 as ID,
  'квартира' as NAME,
  'кв.' as VALUE,
  'apartment' as NAME_ENG
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, NAME, VALUE, NAME_ENG)
VALUES (
  B.ID, B.NAME, B.VALUE, B.NAME_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME = B.NAME,
  A.VALUE = B.VALUE,
  A.NAME_ENG = B.NAME_ENG;

MERGE INTO BARS.ADR_ROOM_TYPE A USING
 (SELECT
  2 as ID,
  'кімната' as NAME,
  'кімн.' as VALUE,
  'room' as NAME_ENG
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, NAME, VALUE, NAME_ENG)
VALUES (
  B.ID, B.NAME, B.VALUE, B.NAME_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME = B.NAME,
  A.VALUE = B.VALUE,
  A.NAME_ENG = B.NAME_ENG;

MERGE INTO BARS.ADR_ROOM_TYPE A USING
 (SELECT
  3 as ID,
  'офіс' as NAME,
  'оф.' as VALUE,
  'office' as NAME_ENG
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, NAME, VALUE, NAME_ENG)
VALUES (
  B.ID, B.NAME, B.VALUE, B.NAME_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME = B.NAME,
  A.VALUE = B.VALUE,
  A.NAME_ENG = B.NAME_ENG;

MERGE INTO BARS.ADR_ROOM_TYPE A USING
 (SELECT
  99 as ID,
  'інше' as NAME,
  NULL as VALUE,
  NULL as NAME_ENG
  FROM DUAL) B
ON (A.ID = B.ID)
WHEN NOT MATCHED THEN 
INSERT (
  ID, NAME, VALUE, NAME_ENG)
VALUES (
  B.ID, B.NAME, B.VALUE, B.NAME_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME = B.NAME,
  A.VALUE = B.VALUE,
  A.NAME_ENG = B.NAME_ENG;

COMMIT;
