--rename VW_ASP_CREDIT_LIST to V_ASP_CREDIT_LIST;
--rename VW_ASP_DEBIT_LIST to V_ASP_DEBIT_LIST;
rename VW_CCK_GLK to V_CCK_GLK;
rename VW_CCK_ND_ACCOUNT to V_CCK_ND_ACCOUNT;
rename VW_CC_LIM_COPY_BODY to V_CC_LIM_COPY_BODY;
rename VW_CC_LIM_COPY_HEADER to V_CC_LIM_COPY_HEADER;
--rename VW_GPK_ROUND_TYPE to V_GPK_ROUND_TYPE;
