MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  21 as TRANTYPE,
  'Пакетне відкриття карток (запит)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=BulkCardCreateMethod' as METHOD,
  'xrm_integration_oe.CardBulkInsert' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  22 as TRANTYPE,
  'Пакетне відкриття карток (квитанція)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=GetBulkCardTicketMethod' as METHOD,
  'xrm_integration_oe.CardBulkTicket' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  8 as TRANTYPE,
  'Додаткова угода за депозитами' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationdeposit.asmx?op=CreateDepositAgreement' as METHOD,
  'xrm_integration_oe.CreateDepositAgreement' as PROCNAME,
  'DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  10 as TRANTYPE,
  'Замовлення на рівні РУ БПК Instant' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=OrderInstant' as METHOD,
  'xrm_integration_oe.OrderInstant' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  11 as TRANTYPE,
  'Зміна додаткових параметрів рахунку 2625' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=SetCardCreditParam' as METHOD,
  'accreg.setAccountwParam' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  9 as TRANTYPE,
  'Встановлення дод.реквізитів БПК' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=SetCardParam' as METHOD,
  'xrm_integration_oe.SetGetCardParam' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  0 as TRANTYPE,
  'Пошук клієнта' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcustomer.asmx?op=SetClientMethod' as METHOD,
  'xrm_integration_oe.open_customer' as PROCNAME,
  'CLIENT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  1 as TRANTYPE,
  'Створення клієнта' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcustomer.asmx?op=SetClientMethod' as METHOD,
  'xrm_integration_oe.open_customer' as PROCNAME,
  'CLIENT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  2 as TRANTYPE,
  'Оновлення реквізитів клієнта' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcustomer.asmx?op=SetClientMethod' as METHOD,
  'xrm_integration_oe.open_customer' as PROCNAME,
  'CLIENT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  3 as TRANTYPE,
  'Закриття клієнта' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcustomer.asmx?op=SetClientMethod' as METHOD,
  'xrm_integration_oe.open_customer' as PROCNAME,
  'CLIENT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  4 as TRANTYPE,
  'Відкриття картрахунку' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=CreateCardMethod' as METHOD,
  'xrm_integration_oe.open_card' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  5 as TRANTYPE,
  'Відкриття депозитного договору' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationdeposit.asmx?op=CreateDepositMethod' as METHOD,
  'xrm_integration_oe.open_deposit' as PROCNAME,
  'DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  6 as TRANTYPE,
  'Підписання документів по ЕБП' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationdeposit.asmx?op=DocSignMethod' as METHOD,
  'xrm_integration_oe.sign_doc' as PROCNAME,
  'DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  7 as TRANTYPE,
  'Запит на бек-офіс' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationdeposit.asmx?op=RequestCreateMethod;/barsroot/webservices/xrmintegrationdeposit.asmx?op=GetRequestStateMethod' as METHOD,
  'xrm_integration_oe.request' as PROCNAME,
  'DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  12 as TRANTYPE,
  'Довідка про вкладний рахунок' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationdeposit.asmx?op=GetExtractFile' as METHOD,
  'dpt_views.get_rpt' as PROCNAME,
  'DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  13 as TRANTYPE,
  'Виписка вкладного рахунка' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationdeposit.asmx?op=GetExtractFile' as METHOD,
  'dpt_views.get_rpt' as PROCNAME,
  'DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  14 as TRANTYPE,
  'Регулярний платіж (простий)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationregpay.asmx?op=CreateRegPayMethod' as METHOD,
  'xrm_integration_oe.CreateRegular' as PROCNAME,
  'STO' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  15 as TRANTYPE,
  'Регулярний платіж (депозити)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationregpay.asmx?op=CreateDPTRegPayMethod' as METHOD,
  'xrm_integration_oe.CreateRegular;dpt_web.create_agreement' as PROCNAME,
  'STO/DEPOSIT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  16 as TRANTYPE,
  'Регулярний платіж (кредити)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationregpay.asmx?op=CreateCCKRegPayMethod' as METHOD,
  'xrm_integration_oe.CreateRegular;F_GET_SUM_CCK' as PROCNAME,
  'STO' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  17 as TRANTYPE,
  'Регулярний платіж (СБОН за контрактом)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationregpay.asmx?op=CreateSbonPayMethod' as METHOD,
  'xrm_integration_oe.CreateSbonContr' as PROCNAME,
  'STO/SBON' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  18 as TRANTYPE,
  'Регулярний платіж (СБОН без контракту)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationregpay.asmx?op=CreateSbonPayMethod' as METHOD,
  'xrm_integration_oe.CreateSbonNoContr' as PROCNAME,
  'STO/SBON' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  19 as TRANTYPE,
  'Регулярний платіж (СБОН на вільні реквізити)' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationregpay.asmx?op=CreateFreeSbonPayMethod' as METHOD,
  'xrm_integration_oe.CreateFreeSbonRegular' as PROCNAME,
  'STO/SBON' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;

MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  20 as TRANTYPE,
  'Документи клієнта перевірено' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcustomer.asmx?op=SetVerifiedClient' as METHOD,
  'xrm_integration_oe.SET_VERIFIED_STATE' as PROCNAME,
  'CLIENT' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;
  
MERGE INTO BARS.XRMSW_OPERATION_TYPES A USING
 (SELECT
  23 as TRANTYPE,
  'Приєднання до ДКБО' as DESCRIPTION,
  '/barsroot/webservices/xrmintegrationcard.asmx?op=MapDKBO' as METHOD,
  'xrm_integration_oe.MapDKBO' as PROCNAME,
  'CARD' as INTGTYPE
  FROM DUAL) B
ON (A.TRANTYPE = B.TRANTYPE)
WHEN NOT MATCHED THEN 
INSERT (
  TRANTYPE, DESCRIPTION, METHOD, PROCNAME, INTGTYPE)
VALUES (
  B.TRANTYPE, B.DESCRIPTION, B.METHOD, B.PROCNAME, B.INTGTYPE)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPTION = B.DESCRIPTION,
  A.METHOD = B.METHOD,
  A.PROCNAME = B.PROCNAME,
  A.INTGTYPE = B.INTGTYPE;  

COMMIT;
/