prompt Disabling foreign key constraints for ZVT_ROLE...
alter table ZVT_ROLE disable constraint FK_ZVTROLE_DEPARTMENT_ID;
alter table ZVT_ROLE disable constraint FK_ZVTROLE_ROLE_ID;
alter table ZVT_ROLE disable constraint FK_ZVTROLE_SECTOR_ID;
alter table ZVT_ROLE disable constraint FK_ZVTROLE_TEAM_ID;
prompt Deleting ZVT_ROLE...
delete from ZVT_ROLE;
prompt Deleting ZVT_TEAM...
delete from ZVT_TEAM;
prompt Deleting ZVT_SECTOR...
delete from ZVT_SECTOR;
prompt Deleting ZVT_DIVISION...
delete from ZVT_DIVISION;
prompt Deleting ZVT_DEPARTMENT...
delete from ZVT_DEPARTMENT;