GRANT SELECT,
      INSERT,
      UPDATE,
      DELETE
   ON INS_TYPES
   TO BARS_ACCESS_DEFROLE;

GRANT SELECT,
      INSERT,
      UPDATE,
      DELETE
   ON INS_EWA_TYPES
   TO BARS_ACCESS_DEFROLE;