/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace clientregister
{
    public sealed class VCustRelTypesRecord : BbRecord
    {
        public VCustRelTypesRecord(): base()
        {
            fillFields();
        }
        public VCustRelTypesRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VCustRelTypesRecord(BbDataSource Parent, OracleDecimal RowScn, Decimal? ID, String NAME, String DATASET_ID)
            : this(Parent)
        {
            this.ID = ID;
            this.NAME = NAME;
            this.DATASET_ID = DATASET_ID;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("ID", OracleDbType.Decimal, false, false, false, false, false, "V_CUST_REL_TYPES", ObjectTypes.View, "Типы связей клиента (Представление)", "Идентификатор"));
            Fields.Add( new BbField("NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_CUST_REL_TYPES", ObjectTypes.View, "Типы связей клиента (Представление)", "Наименование"));
            Fields.Add( new BbField("DATASET_ID", OracleDbType.Varchar2, true, false, false, false, false, "V_CUST_REL_TYPES", ObjectTypes.View, "Типы связей клиента (Представление)", "Идентификатор набора данных (TRUSTEE - довірена особа, VAGA - з врахуванням ваги, SIMPLE - базовий)"));        
        }
        public Decimal? ID { get { return (Decimal?)FindField("ID").Value; } set {SetField("ID", value);} }
        public String NAME { get { return (String)FindField("NAME").Value; } set {SetField("NAME", value);} }
        public String DATASET_ID { get { return (String)FindField("DATASET_ID").Value; } set {SetField("DATASET_ID", value);} }
    }

    public sealed class VCustRelTypesFilters : BbFilters
    {
        public VCustRelTypesFilters(BbDataSource Parent) : base (Parent)
        {
            ID = new BBDecimalFilter(this, "ID");
            NAME = new BBVarchar2Filter(this, "NAME");
            DATASET_ID = new BBVarchar2Filter(this, "DATASET_ID");
        }
        public BBDecimalFilter ID;
        public BBVarchar2Filter NAME;
        public BBVarchar2Filter DATASET_ID;
    }

    public partial class VCustRelTypes : BbTable<VCustRelTypesRecord, VCustRelTypesFilters>
    {
        public VCustRelTypes() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VCustRelTypes(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VCustRelTypesRecord> Select(VCustRelTypesRecord Item)
        {
            List<VCustRelTypesRecord> res = new List<VCustRelTypesRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VCustRelTypesRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (Decimal?)null : Convert.ToDecimal(rdr[1]), 
                        rdr.IsDBNull(2) ?  (String)null : Convert.ToString(rdr[2]), 
                        rdr.IsDBNull(3) ?  (String)null : Convert.ToString(rdr[3]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}