CREATE OR REPLACE FORCE VIEW V_CRCA_PORTFOLIO (ID, 
                                               FIO, 
                                               COUNTRY, 
                                               POSTINDEX, 
                                               OBL, 
                                               RAJON, 
                                               CITY, 
                                               ADDRESS, 
                                               FULLADDRESS, 
                                               ICOD, 
                                               DOCTYPE, 
                                               DOCSERIAL, 
                                               DOCNUMBER, 
                                               DOCORG, 
                                               DOCDATE, 
                                               CLIENTBDATE, 
                                               CLIENTBPLACE, 
                                               CLIENTSEX, 
                                               CLIENTPHONE, 
                                               REGISTRYDATE, 
                                               NSC, 
                                               IDA, 
                                               ND, 
                                               SUM, 
                                               OST, 
                                               DATO, 
                                               DATL, 
                                               ATTR, 
                                               CARD, 
                                               DATN, 
                                               VER, 
                                               STAT, 
                                               TVBV, 
                                               BRANCH, 
                                               PERCENT, 
                                               KKNAME, 
                                               RNK, 
                                               KV, 
                                               KV_SHORT, 
                                               STATE_ID, 
                                               STATUS, 
                                               DATE_IMPORT, 
                                               DBCODE, 
                                               OB22, 
                                               OB22_TEXT, 
                                               ACTUAL_STATE, 
                                               REASON_CHANGE_STATUS, 
                                               KK, 
                                               RNK_BUR, 
                                               FIO_RECEIVER,
                                               L_FIO) AS 
  SELECT cp.id,
       cp.fio,
       cp.country,
       cp.postindex,
       cp.obl,
       cp.rajon,
       cp.city,
       cp.address,
       cp.fulladdress,
       cp.icod,
       crkr_compen_web.convert_doctype_asvo_to_crkr(cp.doctype) doctype,
       cp.docserial,
       cp.docnumber,
       cp.docorg,
       cp.docdate,
       cp.clientbdate,
       cp.clientbplace,
       cp.clientsex,
       cp.clientphone,
       cp.registrydate,
       cp.nsc,
       cp.ida,
       cp.nd,
       cp.SUM,
       cp.ost,
       cp.dato,
       cp.datl,
       cp.attr,
       cp.card,
       cp.datn,
       cp.ver,
       cp.stat,
       cp.tvbv,
       cp.branch_crkr,
       cp.percent,
       cp.kkname,
       cp.rnk,
       cp.kv,
       val.lcv                              kv_short    ,
       --(SELECT lcv
       --   FROM tabval$global val
       --  WHERE val.kv = cp.kv)          AS kv_short,
       cp.status state_id,
       (select status_name from compen_portfolio_status where status_id = status) as status,
       cp.date_import,
       cp.dbcode,
       cp.ob22,
       co.text                           ob22_text   ,
       --(SELECT text
       --   FROM compen_ob22 co
       --  WHERE co.ob22 = cp.ob22)        ob22_text,
       DECODE (cp.rnk, NULL, 0, 1) actual_state,
       cp.reason_change_status,
       substr(cp.nd,1,instr(cp.nd,'_',1)-1) kk,
       cp.rnk_bur,
       (select c.fio from compen_clients c where c.rnk = cp.rnk_bur) fio_receiver,
       lower(cp.fio) l_fio
  FROM compen_portfolio cp,
       compen_ob22      co,
       tabval$global    val
  WHERE  co.ob22(+)=cp.ob22 and
         val.kv(+)=cp.kv    and
         (sys_context('bars_context','user_mfo') = '300465' or rnk IS NULL OR substr(branchact,2,6) = sys_context('bars_context','user_mfo'))
;
  GRANT SELECT ON V_CRCA_PORTFOLIO TO BARS_ACCESS_DEFROLE;