
PROMPT *** Create  table CUSTOMERS_PLT ***
begin 
  execute immediate '
  CREATE TABLE BARS_DM.CUSTOMERS_PLT 
   (	ID NUMBER(38,0), 
	PER_ID NUMBER, 
	KF VARCHAR2(12), 
	RU NUMBER(*,0), 
	RNK NUMBER(38,0), 
	BRANCH VARCHAR2(30), 
	LAST_NAME VARCHAR2(50), 
	FIRST_NAME VARCHAR2(50), 
	MIDDLE_NAME VARCHAR2(60), 
	SEX CHAR(1), 
	GR VARCHAR2(30), 
	BDAY DATE, 
	PASSP NUMBER(*,0), 
	SER VARCHAR2(10), 
	NUMDOC VARCHAR2(20), 
	PDATE DATE, 
	ORGAN VARCHAR2(70), 
	PASSP_EXPIRE_TO DATE, 
	PASSP_TO_BANK DATE, 
	OKPO VARCHAR2(14), 
	CUST_STATUS VARCHAR2(20), 
	CUST_ACTIVE NUMBER(38,0), 
	TELM VARCHAR2(20), 
	TELW VARCHAR2(20), 
	TELD VARCHAR2(20), 
	TELADD VARCHAR2(20), 
	EMAIL VARCHAR2(100), 
	ADR_POST_COUNTRY VARCHAR2(55), 
	ADR_POST_DOMAIN VARCHAR2(30), 
	ADR_POST_REGION VARCHAR2(30), 
	ADR_POST_LOC VARCHAR2(30), 
	ADR_POST_ADR VARCHAR2(100), 
	ADR_POST_ZIP VARCHAR2(20), 
	ADR_FACT_COUNTRY VARCHAR2(55), 
	ADR_FACT_DOMAIN VARCHAR2(30), 
	ADR_FACT_REGION VARCHAR2(30), 
	ADR_FACT_LOC VARCHAR2(30), 
	ADR_FACT_ADR VARCHAR2(100), 
	ADR_FACT_ZIP VARCHAR2(20), 
	ADR_WORK_COUNTRY VARCHAR2(55), 
	ADR_WORK_DOMAIN VARCHAR2(30), 
	ADR_WORK_REGION VARCHAR2(30), 
	ADR_WORK_LOC VARCHAR2(30), 
	ADR_WORK_ADR VARCHAR2(100), 
	ADR_WORK_ZIP VARCHAR2(20), 
	NEGATIV_STATUS VARCHAR2(10), 
	REESTR_MOB_BANK VARCHAR2(10), 
	REESTR_INET_BANK VARCHAR2(10), 
	REESTR_SMS_BANK VARCHAR2(10), 
	MONTH_INCOME NUMBER(10,0), 
	SUBJECT_ROLE VARCHAR2(10), 
	REZIDENT VARCHAR2(10), 
	MERRIED VARCHAR2(500), 
	EMP_STATUS VARCHAR2(10), 
	SUBJECT_CLASS VARCHAR2(10), 
	INSIDER VARCHAR2(10), 
	VIPK NUMBER(1,0), 
	VIP_FIO_MANAGER VARCHAR2(250), 
	VIP_PHONE_MANAGER VARCHAR2(30), 
	DATE_ON DATE, 
	DATE_OFF DATE, 
	EDDR_ID VARCHAR2(20), 
	ACTUAL_DATE DATE, 
	BPLACE VARCHAR2(70), 
	SUBSD VARCHAR2(500), 
	SUBSN VARCHAR2(500), 
	ELT_N VARCHAR2(500), 
	ELT_D VARCHAR2(500), 
	GCIF VARCHAR2(30), 
	NOMPDV VARCHAR2(9), 
	NOM_DOG VARCHAR2(10), 
	SW_RN VARCHAR2(500), 
	Y_ELT VARCHAR2(500), 
	ADM VARCHAR2(70), 
	ADR_ALT VARCHAR2(70), 
	BUSSS VARCHAR2(500), 
	PC_MF VARCHAR2(500), 
	PC_Z4 VARCHAR2(500), 
	PC_Z3 VARCHAR2(500), 
	PC_Z5 VARCHAR2(500), 
	PC_Z2 VARCHAR2(500), 
	PC_Z1 VARCHAR2(500), 
	AGENT VARCHAR2(500), 
	PC_SS VARCHAR2(500), 
	STMT VARCHAR2(500), 
	VIDKL VARCHAR2(500), 
	VED CHAR(5), 
	TIPA VARCHAR2(500), 
	PHKLI VARCHAR2(500), 
	AF1_9 VARCHAR2(500), 
	IDDPD VARCHAR2(500), 
	DAIDI VARCHAR2(500), 
	DATVR VARCHAR2(500), 
	DATZ VARCHAR2(500), 
	IDDPL VARCHAR2(500), 
	DATE_PHOTO DATE, 
	IDDPR VARCHAR2(500), 
	ISE CHAR(5), 
	OBSLU VARCHAR2(500), 
	CRSRC VARCHAR2(500), 
	DJOTH VARCHAR2(500), 
	DJAVI VARCHAR2(500), 
	DJ_TC VARCHAR2(500), 
	DJOWF VARCHAR2(500), 
	DJCFI VARCHAR2(500), 
	DJ_LN VARCHAR2(500), 
	DJ_FH VARCHAR2(500), 
	DJ_CP VARCHAR2(500), 
	CHORN VARCHAR2(500), 
	CRISK_KL VARCHAR2(1), 
	BC NUMBER(1,0), 
	SPMRK VARCHAR2(500), 
	K013 VARCHAR2(500), 
	KODID VARCHAR2(500), 
	COUNTRY NUMBER(3,0), 
	MS_FS VARCHAR2(500), 
	MS_VD VARCHAR2(500), 
	MS_GR VARCHAR2(500), 
	LIM_KASS NUMBER(24,0), 
	LIM NUMBER(24,0), 
	LICO VARCHAR2(500), 
	UADR VARCHAR2(500), 
	MOB01 VARCHAR2(500), 
	MOB02 VARCHAR2(500), 
	MOB03 VARCHAR2(500), 
	SUBS VARCHAR2(500), 
	K050 CHAR(3), 
	DEATH VARCHAR2(500), 
	NO_PHONE NUMBER(1,0), 
	NSMCV VARCHAR2(500), 
	NSMCC VARCHAR2(500), 
	NSMCT VARCHAR2(500), 
	NOTES VARCHAR2(140), 
	SAMZ VARCHAR2(500), 
	OREP VARCHAR2(500), 
	OVIFS VARCHAR2(500), 
	AF6 VARCHAR2(500), 
	FSKRK VARCHAR2(500), 
	FSOMD VARCHAR2(500), 
	FSVED VARCHAR2(500), 
	FSZPD VARCHAR2(500), 
	FSPOR VARCHAR2(500), 
	FSRKZ VARCHAR2(500), 
	FSZOP VARCHAR2(500), 
	FSKPK VARCHAR2(500), 
	FSKPR VARCHAR2(500), 
	FSDIB VARCHAR2(500), 
	FSCP VARCHAR2(500), 
	FSVLZ VARCHAR2(500), 
	FSVLA VARCHAR2(500), 
	FSVLN VARCHAR2(500), 
	FSVLO VARCHAR2(500), 
	FSSST VARCHAR2(500), 
	FSSOD VARCHAR2(500), 
	FSVSN VARCHAR2(500), 
	DOV_P VARCHAR2(500), 
	DOV_A VARCHAR2(500), 
	DOV_F VARCHAR2(500), 
	NMKV VARCHAR2(70), 
	SN_GC VARCHAR2(500), 
	NMKK VARCHAR2(38), 
	PRINSIDER NUMBER(38,0), 
	MB CHAR(1), 
	PUBLP VARCHAR2(500), 
	WORKB VARCHAR2(500), 
	CIGPO VARCHAR2(500), 
	COUNTRY_NAME VARCHAR2(70), 
	TARIF VARCHAR2(500), 
	AINAB VARCHAR2(500), 
	TGR NUMBER(1,0), 
	SNSDR VARCHAR2(500), 
	IDPIB VARCHAR2(500), 
	FS CHAR(2), 
	DJER VARCHAR2(500), 
	SUTD VARCHAR2(500), 
	RVDBC VARCHAR2(500), 
	RVIBA VARCHAR2(500), 
	RVIDT VARCHAR2(500), 
	RV_XA VARCHAR2(500), 
	RVIBR VARCHAR2(500), 
	RVIBB VARCHAR2(500), 
	RVRNK VARCHAR2(500), 
	RVPH1 VARCHAR2(500), 
	RVPH2 VARCHAR2(500), 
	RVPH3 VARCHAR2(500), 
	SAB VARCHAR2(6), 
	J_COUNTRY NUMBER(3,0), 
	J_ZIP VARCHAR2(20), 
	J_DOMAIN VARCHAR2(30), 
	J_REGION VARCHAR2(30), 
	J_LOCALITY VARCHAR2(30), 
	J_ADDRESS VARCHAR2(100), 
	J_TERRITORY_ID NUMBER(22,0), 
	J_LOCALITY_TYPE NUMBER(22,0), 
	J_STREET_TYPE NUMBER(22,0), 
	J_STREET VARCHAR2(100 CHAR), 
	J_HOME_TYPE NUMBER(22,0), 
	J_HOME VARCHAR2(100 CHAR), 
	J_HOMEPART_TYPE NUMBER(22,0), 
	J_HOMEPART VARCHAR2(100 CHAR), 
	J_ROOM_TYPE NUMBER(22,0), 
	J_ROOM VARCHAR2(100 CHAR), 
	F_COUNTRY NUMBER(3,0), 
	F_ZIP VARCHAR2(20), 
	F_DOMAIN VARCHAR2(30), 
	F_REGION VARCHAR2(30), 
	F_LOCALITY VARCHAR2(30), 
	FADR VARCHAR2(500), 
	F_TERRITORY_ID NUMBER(22,0), 
	F_LOCALITY_TYPE NUMBER(22,0), 
	F_STREET_TYPE NUMBER(22,0), 
	F_STREET VARCHAR2(100 CHAR), 
	F_HOME_TYPE NUMBER(22,0), 
	F_HOME VARCHAR2(100 CHAR), 
	F_HOMEPART_TYPE NUMBER(22,0), 
	F_HOMEPART VARCHAR2(100 CHAR), 
	F_ROOM_TYPE NUMBER(22,0), 
	F_ROOM VARCHAR2(100 CHAR), 
	P_COUNTRY NUMBER(3,0), 
	P_ZIP VARCHAR2(20), 
	P_DOMAIN VARCHAR2(30), 
	P_REGION VARCHAR2(30), 
	P_LOCALITY VARCHAR2(30), 
	P_ADDRESS VARCHAR2(100), 
	P_TERRITORY_ID NUMBER(22,0), 
	P_LOCALITY_TYPE NUMBER(22,0), 
	P_STREET_TYPE NUMBER(22,0), 
	P_STREET VARCHAR2(100 CHAR), 
	P_HOME_TYPE NUMBER(22,0), 
	P_HOME VARCHAR2(100 CHAR), 
	P_HOMEPART_TYPE NUMBER(22,0), 
	P_HOMEPART VARCHAR2(100 CHAR), 
	P_ROOM_TYPE NUMBER(22,0), 
	P_ROOM VARCHAR2(100 CHAR), 
	F_ADDRESS VARCHAR2(100), 
	NOTESEC VARCHAR2(256), 
	C_REG NUMBER(2,0), 
	C_DST NUMBER(2,0), 
	RGADM VARCHAR2(30), 
	RGTAX VARCHAR2(30), 
	DATEA DATE, 
	DATET DATE, 
	RNKP NUMBER(38,0), 
	CUSTTYPE NUMBER(1,0), 
	RIZIK VARCHAR2(500), 
	SED CHAR(4), 
	CODCAGENT NUMBER(1,0), 
	J_KOATUU VARCHAR2(15), 
	J_REGION_ID NUMBER(10,0), 
	J_AREA_ID NUMBER(10,0), 
	J_SETTLEMENT_ID NUMBER(10,0), 
	J_STREET_ID NUMBER(10,0), 
	J_HOUSE_ID NUMBER(10,0), 
	F_KOATUU VARCHAR2(15), 
	F_REGION_ID NUMBER(10,0), 
	F_AREA_ID NUMBER(10,0), 
	F_SETTLEMENT_ID NUMBER(10,0), 
	F_STREET_ID NUMBER(10,0), 
	F_HOUSE_ID NUMBER(10,0), 
	P_KOATUU VARCHAR2(15), 
	P_REGION_ID NUMBER(10,0), 
	P_AREA_ID NUMBER(10,0), 
	P_SETTLEMENT_ID NUMBER(10,0), 
	P_STREET_ID NUMBER(10,0), 
	P_HOUSE_ID NUMBER(10,0),
    VIP_ACCOUNT_MANAGER VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';exception when others then         if sqlcode=-955 then null; else raise; end if; end; /prompt alter column MERRIED varchar2(500)alter table bars_dm.customers_plt modify merried varchar2(500);
prompt alter column adr_work_adr modify varchar2(100)
alter table bars_dm.customers_plt modify ADR_WORK_ADR VARCHAR2(100);

PROMPT *** add column vip_account_manager ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT ADD vip_account_manager varchar2(4000)';exception when others then  if  sqlcode=-1430 then null; else raise; end if; end;/
PROMPT *** rename column MFO to KF ***begin    execute immediate '  ALTER TABLE BARS_DM.CUSTOMERS_PLT RENAME COLUMN MFO TO KF';exception when others then  if  sqlcode=-957 then null; else raise; end if; end;/
PROMPT *** Create  constraint PK_CUSTOMERS_PLT ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT ADD CONSTRAINT PK_CUSTOMERS_PLT PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI  ENABLE';exception when others then  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;end;/
PROMPT *** Create  constraint CC_CUSTOMERS_PLT_RNK_NN ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT ADD CONSTRAINT CC_CUSTOMERS_PLT_RNK_NN CHECK (RNK IS NOT NULL) ENABLE';exception when others then  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if; end;/
PROMPT *** Create  constraint CC_CUSTOMERS_PLT_PERID_NN ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT ADD CONSTRAINT CC_CUSTOMERS_PLT_PERID_NN CHECK (PER_ID IS NOT NULL) ENABLE';exception when others then  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;end;/
PROMPT *** Create  constraint CC_CUSTOMERS_PLT_MFO_NN ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT ADD CONSTRAINT CC_CUSTOMERS_PLT_MFO_NN CHECK (KF IS NOT NULL) ENABLE';exception when others then  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;end;/
PROMPT *** Create  constraint CC_CUSTOMERS_PLT_BRANCH_NN ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT ADD CONSTRAINT CC_CUSTOMERS_PLT_BRANCH_NN CHECK (BRANCH IS NOT NULL) ENABLE';exception when others then  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;end;/PROMPT *** Create  constraint SYS_C003232547 ***begin    execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_PLT MODIFY (ID NOT NULL ENABLE)';exception when others then  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;end;/
PROMPT *** Create  index I_CUSTOMERS_PLT_PERID ***begin    execute immediate '
  CREATE INDEX BARS_DM.I_CUSTOMERS_PLT_PERID ON BARS_DM.CUSTOMERS_PLT (PER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';exception when others then  if  sqlcode=-955  then null; else raise; end if;end;/
PROMPT *** Create  index PK_CUSTOMERS_PLT ***begin    execute immediate '
  CREATE UNIQUE INDEX BARS_DM.PK_CUSTOMERS_PLT ON BARS_DM.CUSTOMERS_PLT (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';exception when others then  if  sqlcode=-955  then null; else raise; end if;end;/
PROMPT *** Create  grants  CUSTOMERS_PLT ***
grant SELECT                                                                 on CUSTOMERS_PLT   to BARSUPL;