
grant SELECT  on VW_ESCR_REF_FOR_COMPENSATION to BARS_ACCESS_DEFROLE;
grant SELECT  on VW_escr_pay_log_body to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE  on ESCR_pay_log_header to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE  on ESCR_pay_log_body to BARS_ACCESS_DEFROLE;
grant execute  on ESCR to BARS_ACCESS_DEFROLE;