/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using barsroot.cim;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace cim
{
    public partial class VCimFoundPayments
    {
        public List<VCimFoundPaymentsRecord> SelectPayments(Boolean FILTER_RNK, Decimal? CUST_RNK, String DOC_DATE, String DOC_NLS, String DOC_KV, String DOC_SUM, String SortExpression, int maximumRows, int startRowIndex)
        {
            if (CUST_RNK.HasValue)
                this.Filter.REF.Equal(CUST_RNK);
            else
            {
                if (!string.IsNullOrEmpty(DOC_DATE))
                {
                    this.Filter.PDAT.Greater(CimManager.StrToDate(DOC_DATE).AddDays(-30));
                    this.Filter.PLAN_VDAT.Equal(CimManager.StrToDate(DOC_DATE));
                    if (!string.IsNullOrEmpty(DOC_NLS))
                        this.Filter.NLS.Equal(DOC_NLS);
                    if (!string.IsNullOrEmpty(DOC_KV))
                        this.Filter.KV.Equal(Convert.ToDecimal(DOC_KV));
                    if (!string.IsNullOrEmpty(DOC_SUM))
                        this.Filter.TOTAL_SUM.Equal(Convert.ToDecimal(DOC_SUM));
                }
                else
                    return new List<VCimFoundPaymentsRecord>();
            }
            return this.Select(SortExpression, maximumRows, startRowIndex);
        }
    }
}