/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace cim
{
    public sealed class VCimBoundPaymentsRecord : BbRecord
    {
        public VCimBoundPaymentsRecord(): base()
        {
            fillFields();
        }
        public VCimBoundPaymentsRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VCimBoundPaymentsRecord(BbDataSource Parent, OracleDecimal RowScn, Decimal? BOUND_ID, Decimal? CONTR_ID, Decimal? PAY_FLAG, String PAY_FLAG_NAME, Decimal? REF, Decimal? DIRECT, Decimal? TYPE_ID, String TYPE, DateTime? VDAT, String ACCOUNT, String NAZN, Decimal? V_PL, Decimal? S_VPL, Decimal? SK_VPL, Decimal? RATE, Decimal? S_VK)
            : this(Parent)
        {
            this.BOUND_ID = BOUND_ID;
            this.CONTR_ID = CONTR_ID;
            this.PAY_FLAG = PAY_FLAG;
            this.PAY_FLAG_NAME = PAY_FLAG_NAME;
            this.REF = REF;
            this.DIRECT = DIRECT;
            this.TYPE_ID = TYPE_ID;
            this.TYPE = TYPE;
            this.VDAT = VDAT;
            this.ACCOUNT = ACCOUNT;
            this.NAZN = NAZN;
            this.V_PL = V_PL;
            this.S_VPL = S_VPL;
            this.SK_VPL = SK_VPL;
            this.RATE = RATE;
            this.S_VK = S_VK;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("BOUND_ID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("CONTR_ID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PAY_FLAG", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PAY_FLAG_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("REF", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("DIRECT", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("TYPE_ID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("TYPE", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("VDAT", OracleDbType.Date, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ACCOUNT", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NAZN", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("V_PL", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("S_VPL", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("SK_VPL", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("RATE", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("S_VK", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_BOUND_PAYMENTS", ObjectTypes.View, "", ""));        
        }
        public Decimal? BOUND_ID { get { return (Decimal?)FindField("BOUND_ID").Value; } set {SetField("BOUND_ID", value);} }
        public Decimal? CONTR_ID { get { return (Decimal?)FindField("CONTR_ID").Value; } set {SetField("CONTR_ID", value);} }
        public Decimal? PAY_FLAG { get { return (Decimal?)FindField("PAY_FLAG").Value; } set {SetField("PAY_FLAG", value);} }
        public String PAY_FLAG_NAME { get { return (String)FindField("PAY_FLAG_NAME").Value; } set {SetField("PAY_FLAG_NAME", value);} }
        public Decimal? REF { get { return (Decimal?)FindField("REF").Value; } set {SetField("REF", value);} }
        public Decimal? DIRECT { get { return (Decimal?)FindField("DIRECT").Value; } set {SetField("DIRECT", value);} }
        public Decimal? TYPE_ID { get { return (Decimal?)FindField("TYPE_ID").Value; } set {SetField("TYPE_ID", value);} }
        public String TYPE { get { return (String)FindField("TYPE").Value; } set {SetField("TYPE", value);} }
        public DateTime? VDAT { get { return (DateTime?)FindField("VDAT").Value; } set {SetField("VDAT", value);} }
        public String ACCOUNT { get { return (String)FindField("ACCOUNT").Value; } set {SetField("ACCOUNT", value);} }
        public String NAZN { get { return (String)FindField("NAZN").Value; } set {SetField("NAZN", value);} }
        public Decimal? V_PL { get { return (Decimal?)FindField("V_PL").Value; } set {SetField("V_PL", value);} }
        public Decimal? S_VPL { get { return (Decimal?)FindField("S_VPL").Value; } set {SetField("S_VPL", value);} }
        public Decimal? SK_VPL { get { return (Decimal?)FindField("SK_VPL").Value; } set {SetField("SK_VPL", value);} }
        public Decimal? RATE { get { return (Decimal?)FindField("RATE").Value; } set {SetField("RATE", value);} }
        public Decimal? S_VK { get { return (Decimal?)FindField("S_VK").Value; } set {SetField("S_VK", value);} }
    }

    public sealed class VCimBoundPaymentsFilters : BbFilters
    {
        public VCimBoundPaymentsFilters(BbDataSource Parent) : base (Parent)
        {
            BOUND_ID = new BBDecimalFilter(this, "BOUND_ID");
            CONTR_ID = new BBDecimalFilter(this, "CONTR_ID");
            PAY_FLAG = new BBDecimalFilter(this, "PAY_FLAG");
            PAY_FLAG_NAME = new BBVarchar2Filter(this, "PAY_FLAG_NAME");
            REF = new BBDecimalFilter(this, "REF");
            DIRECT = new BBDecimalFilter(this, "DIRECT");
            TYPE_ID = new BBDecimalFilter(this, "TYPE_ID");
            TYPE = new BBVarchar2Filter(this, "TYPE");
            VDAT = new BBDateFilter(this, "VDAT");
            ACCOUNT = new BBVarchar2Filter(this, "ACCOUNT");
            NAZN = new BBVarchar2Filter(this, "NAZN");
            V_PL = new BBDecimalFilter(this, "V_PL");
            S_VPL = new BBDecimalFilter(this, "S_VPL");
            SK_VPL = new BBDecimalFilter(this, "SK_VPL");
            RATE = new BBDecimalFilter(this, "RATE");
            S_VK = new BBDecimalFilter(this, "S_VK");
        }
        public BBDecimalFilter BOUND_ID;
        public BBDecimalFilter CONTR_ID;
        public BBDecimalFilter PAY_FLAG;
        public BBVarchar2Filter PAY_FLAG_NAME;
        public BBDecimalFilter REF;
        public BBDecimalFilter DIRECT;
        public BBDecimalFilter TYPE_ID;
        public BBVarchar2Filter TYPE;
        public BBDateFilter VDAT;
        public BBVarchar2Filter ACCOUNT;
        public BBVarchar2Filter NAZN;
        public BBDecimalFilter V_PL;
        public BBDecimalFilter S_VPL;
        public BBDecimalFilter SK_VPL;
        public BBDecimalFilter RATE;
        public BBDecimalFilter S_VK;
    }

    public partial class VCimBoundPayments : BbTable<VCimBoundPaymentsRecord, VCimBoundPaymentsFilters>
    {
        public VCimBoundPayments() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VCimBoundPayments(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VCimBoundPaymentsRecord> Select(VCimBoundPaymentsRecord Item)
        {
            List<VCimBoundPaymentsRecord> res = new List<VCimBoundPaymentsRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VCimBoundPaymentsRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (Decimal?)null : Convert.ToDecimal(rdr[1]), 
                        rdr.IsDBNull(2) ?  (Decimal?)null : Convert.ToDecimal(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]), 
                        rdr.IsDBNull(4) ?  (String)null : Convert.ToString(rdr[4]), 
                        rdr.IsDBNull(5) ?  (Decimal?)null : Convert.ToDecimal(rdr[5]), 
                        rdr.IsDBNull(6) ?  (Decimal?)null : Convert.ToDecimal(rdr[6]), 
                        rdr.IsDBNull(7) ?  (Decimal?)null : Convert.ToDecimal(rdr[7]), 
                        rdr.IsDBNull(8) ?  (String)null : Convert.ToString(rdr[8]), 
                        rdr.IsDBNull(9) ?  (DateTime?)null : Convert.ToDateTime(rdr[9]), 
                        rdr.IsDBNull(10) ?  (String)null : Convert.ToString(rdr[10]), 
                        rdr.IsDBNull(11) ?  (String)null : Convert.ToString(rdr[11]), 
                        rdr.IsDBNull(12) ?  (Decimal?)null : Convert.ToDecimal(rdr[12]), 
                        rdr.IsDBNull(13) ?  (Decimal?)null : Convert.ToDecimal(rdr[13]), 
                        rdr.IsDBNull(14) ?  (Decimal?)null : Convert.ToDecimal(rdr[14]), 
                        rdr.IsDBNull(15) ?  (Decimal?)null : Convert.ToDecimal(rdr[15]), 
                        rdr.IsDBNull(16) ?  (Decimal?)null : Convert.ToDecimal(rdr[16]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}