/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.W4
{
    public sealed class VOwSalaryDataRecord : BbRecord
    {
        public VOwSalaryDataRecord(): base()
        {
            fillFields();
        }
        public VOwSalaryDataRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VOwSalaryDataRecord(BbDataSource Parent, OracleDecimal RowScn, Decimal? ID, Decimal? IDN, Decimal? ND, Decimal? RNK, String NLS, String OKPO, String FIRST_NAME, String LAST_NAME, String MIDDLE_NAME, Decimal? TYPE_DOC, String PASPSERIES, String PASPNUM, String PASPISSUER, DateTime? PASPDATE, DateTime? BDAY, String COUNTRY, String RESIDENT, String GENDER, String PHONE_HOME, String PHONE_MOB, String EMAIL, String ENG_FIRST_NAME, String ENG_LAST_NAME, String MNAME, String ADDR1_CITYNAME, String ADDR1_PCODE, String ADDR1_DOMAIN, String ADDR1_REGION, String ADDR1_STREET, String ADDR2_CITYNAME, String ADDR2_PCODE, String ADDR2_DOMAIN, String ADDR2_REGION, String ADDR2_STREET, String WORK, String OFFICE, DateTime? DATE_W, String OKPO_W, String PERS_CAT, Decimal? AVER_SUM, String TABN, String STR_ERR, Decimal? FLAG_OPEN)
            : this(Parent)
        {
            this.ID = ID;
            this.IDN = IDN;
            this.ND = ND;
            this.RNK = RNK;
            this.NLS = NLS;
            this.OKPO = OKPO;
            this.FIRST_NAME = FIRST_NAME;
            this.LAST_NAME = LAST_NAME;
            this.MIDDLE_NAME = MIDDLE_NAME;
            this.TYPE_DOC = TYPE_DOC;
            this.PASPSERIES = PASPSERIES;
            this.PASPNUM = PASPNUM;
            this.PASPISSUER = PASPISSUER;
            this.PASPDATE = PASPDATE;
            this.BDAY = BDAY;
            this.COUNTRY = COUNTRY;
            this.RESIDENT = RESIDENT;
            this.GENDER = GENDER;
            this.PHONE_HOME = PHONE_HOME;
            this.PHONE_MOB = PHONE_MOB;
            this.EMAIL = EMAIL;
            this.ENG_FIRST_NAME = ENG_FIRST_NAME;
            this.ENG_LAST_NAME = ENG_LAST_NAME;
            this.MNAME = MNAME;
            this.ADDR1_CITYNAME = ADDR1_CITYNAME;
            this.ADDR1_PCODE = ADDR1_PCODE;
            this.ADDR1_DOMAIN = ADDR1_DOMAIN;
            this.ADDR1_REGION = ADDR1_REGION;
            this.ADDR1_STREET = ADDR1_STREET;
            this.ADDR2_CITYNAME = ADDR2_CITYNAME;
            this.ADDR2_PCODE = ADDR2_PCODE;
            this.ADDR2_DOMAIN = ADDR2_DOMAIN;
            this.ADDR2_REGION = ADDR2_REGION;
            this.ADDR2_STREET = ADDR2_STREET;
            this.WORK = WORK;
            this.OFFICE = OFFICE;
            this.DATE_W = DATE_W;
            this.OKPO_W = OKPO_W;
            this.PERS_CAT = PERS_CAT;
            this.AVER_SUM = AVER_SUM;
            this.TABN = TABN;
            this.STR_ERR = STR_ERR;
            this.FLAG_OPEN = FLAG_OPEN;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("ID", OracleDbType.Decimal, false, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("IDN", OracleDbType.Decimal, false, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ND", OracleDbType.Decimal, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("RNK", OracleDbType.Decimal, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NLS", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("OKPO", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("FIRST_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("LAST_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("MIDDLE_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("TYPE_DOC", OracleDbType.Decimal, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PASPSERIES", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PASPNUM", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PASPISSUER", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PASPDATE", OracleDbType.Date, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("BDAY", OracleDbType.Date, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("COUNTRY", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("RESIDENT", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("GENDER", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PHONE_HOME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PHONE_MOB", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("EMAIL", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ENG_FIRST_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ENG_LAST_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("MNAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR1_CITYNAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR1_PCODE", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR1_DOMAIN", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR1_REGION", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR1_STREET", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR2_CITYNAME", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR2_PCODE", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR2_DOMAIN", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR2_REGION", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ADDR2_STREET", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("WORK", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("OFFICE", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("DATE_W", OracleDbType.Date, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("OKPO_W", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("PERS_CAT", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("AVER_SUM", OracleDbType.Decimal, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("TABN", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("STR_ERR", OracleDbType.Varchar2, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("FLAG_OPEN", OracleDbType.Decimal, true, false, false, false, false, "V_OW_SALARY_DATA", ObjectTypes.View, "", ""));        
        }
        public Decimal? ID { get { return (Decimal?)FindField("ID").Value; } set {SetField("ID", value);} }
        public Decimal? IDN { get { return (Decimal?)FindField("IDN").Value; } set {SetField("IDN", value);} }
        public Decimal? ND { get { return (Decimal?)FindField("ND").Value; } set {SetField("ND", value);} }
        public Decimal? RNK { get { return (Decimal?)FindField("RNK").Value; } set {SetField("RNK", value);} }
        public String NLS { get { return (String)FindField("NLS").Value; } set {SetField("NLS", value);} }
        public String OKPO { get { return (String)FindField("OKPO").Value; } set {SetField("OKPO", value);} }
        public String FIRST_NAME { get { return (String)FindField("FIRST_NAME").Value; } set {SetField("FIRST_NAME", value);} }
        public String LAST_NAME { get { return (String)FindField("LAST_NAME").Value; } set {SetField("LAST_NAME", value);} }
        public String MIDDLE_NAME { get { return (String)FindField("MIDDLE_NAME").Value; } set {SetField("MIDDLE_NAME", value);} }
        public Decimal? TYPE_DOC { get { return (Decimal?)FindField("TYPE_DOC").Value; } set {SetField("TYPE_DOC", value);} }
        public String PASPSERIES { get { return (String)FindField("PASPSERIES").Value; } set {SetField("PASPSERIES", value);} }
        public String PASPNUM { get { return (String)FindField("PASPNUM").Value; } set {SetField("PASPNUM", value);} }
        public String PASPISSUER { get { return (String)FindField("PASPISSUER").Value; } set {SetField("PASPISSUER", value);} }
        public DateTime? PASPDATE { get { return (DateTime?)FindField("PASPDATE").Value; } set {SetField("PASPDATE", value);} }
        public DateTime? BDAY { get { return (DateTime?)FindField("BDAY").Value; } set {SetField("BDAY", value);} }
        public String COUNTRY { get { return (String)FindField("COUNTRY").Value; } set {SetField("COUNTRY", value);} }
        public String RESIDENT { get { return (String)FindField("RESIDENT").Value; } set {SetField("RESIDENT", value);} }
        public String GENDER { get { return (String)FindField("GENDER").Value; } set {SetField("GENDER", value);} }
        public String PHONE_HOME { get { return (String)FindField("PHONE_HOME").Value; } set {SetField("PHONE_HOME", value);} }
        public String PHONE_MOB { get { return (String)FindField("PHONE_MOB").Value; } set {SetField("PHONE_MOB", value);} }
        public String EMAIL { get { return (String)FindField("EMAIL").Value; } set {SetField("EMAIL", value);} }
        public String ENG_FIRST_NAME { get { return (String)FindField("ENG_FIRST_NAME").Value; } set {SetField("ENG_FIRST_NAME", value);} }
        public String ENG_LAST_NAME { get { return (String)FindField("ENG_LAST_NAME").Value; } set {SetField("ENG_LAST_NAME", value);} }
        public String MNAME { get { return (String)FindField("MNAME").Value; } set {SetField("MNAME", value);} }
        public String ADDR1_CITYNAME { get { return (String)FindField("ADDR1_CITYNAME").Value; } set {SetField("ADDR1_CITYNAME", value);} }
        public String ADDR1_PCODE { get { return (String)FindField("ADDR1_PCODE").Value; } set {SetField("ADDR1_PCODE", value);} }
        public String ADDR1_DOMAIN { get { return (String)FindField("ADDR1_DOMAIN").Value; } set {SetField("ADDR1_DOMAIN", value);} }
        public String ADDR1_REGION { get { return (String)FindField("ADDR1_REGION").Value; } set {SetField("ADDR1_REGION", value);} }
        public String ADDR1_STREET { get { return (String)FindField("ADDR1_STREET").Value; } set {SetField("ADDR1_STREET", value);} }
        public String ADDR2_CITYNAME { get { return (String)FindField("ADDR2_CITYNAME").Value; } set {SetField("ADDR2_CITYNAME", value);} }
        public String ADDR2_PCODE { get { return (String)FindField("ADDR2_PCODE").Value; } set {SetField("ADDR2_PCODE", value);} }
        public String ADDR2_DOMAIN { get { return (String)FindField("ADDR2_DOMAIN").Value; } set {SetField("ADDR2_DOMAIN", value);} }
        public String ADDR2_REGION { get { return (String)FindField("ADDR2_REGION").Value; } set {SetField("ADDR2_REGION", value);} }
        public String ADDR2_STREET { get { return (String)FindField("ADDR2_STREET").Value; } set {SetField("ADDR2_STREET", value);} }
        public String WORK { get { return (String)FindField("WORK").Value; } set {SetField("WORK", value);} }
        public String OFFICE { get { return (String)FindField("OFFICE").Value; } set {SetField("OFFICE", value);} }
        public DateTime? DATE_W { get { return (DateTime?)FindField("DATE_W").Value; } set {SetField("DATE_W", value);} }
        public String OKPO_W { get { return (String)FindField("OKPO_W").Value; } set {SetField("OKPO_W", value);} }
        public String PERS_CAT { get { return (String)FindField("PERS_CAT").Value; } set {SetField("PERS_CAT", value);} }
        public Decimal? AVER_SUM { get { return (Decimal?)FindField("AVER_SUM").Value; } set {SetField("AVER_SUM", value);} }
        public String TABN { get { return (String)FindField("TABN").Value; } set {SetField("TABN", value);} }
        public String STR_ERR { get { return (String)FindField("STR_ERR").Value; } set {SetField("STR_ERR", value);} }
        public Decimal? FLAG_OPEN { get { return (Decimal?)FindField("FLAG_OPEN").Value; } set {SetField("FLAG_OPEN", value);} }
    }

    public sealed class VOwSalaryDataFilters : BbFilters
    {
        public VOwSalaryDataFilters(BbDataSource Parent) : base (Parent)
        {
            ID = new BBDecimalFilter(this, "ID");
            IDN = new BBDecimalFilter(this, "IDN");
            ND = new BBDecimalFilter(this, "ND");
            RNK = new BBDecimalFilter(this, "RNK");
            NLS = new BBVarchar2Filter(this, "NLS");
            OKPO = new BBVarchar2Filter(this, "OKPO");
            FIRST_NAME = new BBVarchar2Filter(this, "FIRST_NAME");
            LAST_NAME = new BBVarchar2Filter(this, "LAST_NAME");
            MIDDLE_NAME = new BBVarchar2Filter(this, "MIDDLE_NAME");
            TYPE_DOC = new BBDecimalFilter(this, "TYPE_DOC");
            PASPSERIES = new BBVarchar2Filter(this, "PASPSERIES");
            PASPNUM = new BBVarchar2Filter(this, "PASPNUM");
            PASPISSUER = new BBVarchar2Filter(this, "PASPISSUER");
            PASPDATE = new BBDateFilter(this, "PASPDATE");
            BDAY = new BBDateFilter(this, "BDAY");
            COUNTRY = new BBVarchar2Filter(this, "COUNTRY");
            RESIDENT = new BBVarchar2Filter(this, "RESIDENT");
            GENDER = new BBVarchar2Filter(this, "GENDER");
            PHONE_HOME = new BBVarchar2Filter(this, "PHONE_HOME");
            PHONE_MOB = new BBVarchar2Filter(this, "PHONE_MOB");
            EMAIL = new BBVarchar2Filter(this, "EMAIL");
            ENG_FIRST_NAME = new BBVarchar2Filter(this, "ENG_FIRST_NAME");
            ENG_LAST_NAME = new BBVarchar2Filter(this, "ENG_LAST_NAME");
            MNAME = new BBVarchar2Filter(this, "MNAME");
            ADDR1_CITYNAME = new BBVarchar2Filter(this, "ADDR1_CITYNAME");
            ADDR1_PCODE = new BBVarchar2Filter(this, "ADDR1_PCODE");
            ADDR1_DOMAIN = new BBVarchar2Filter(this, "ADDR1_DOMAIN");
            ADDR1_REGION = new BBVarchar2Filter(this, "ADDR1_REGION");
            ADDR1_STREET = new BBVarchar2Filter(this, "ADDR1_STREET");
            ADDR2_CITYNAME = new BBVarchar2Filter(this, "ADDR2_CITYNAME");
            ADDR2_PCODE = new BBVarchar2Filter(this, "ADDR2_PCODE");
            ADDR2_DOMAIN = new BBVarchar2Filter(this, "ADDR2_DOMAIN");
            ADDR2_REGION = new BBVarchar2Filter(this, "ADDR2_REGION");
            ADDR2_STREET = new BBVarchar2Filter(this, "ADDR2_STREET");
            WORK = new BBVarchar2Filter(this, "WORK");
            OFFICE = new BBVarchar2Filter(this, "OFFICE");
            DATE_W = new BBDateFilter(this, "DATE_W");
            OKPO_W = new BBVarchar2Filter(this, "OKPO_W");
            PERS_CAT = new BBVarchar2Filter(this, "PERS_CAT");
            AVER_SUM = new BBDecimalFilter(this, "AVER_SUM");
            TABN = new BBVarchar2Filter(this, "TABN");
            STR_ERR = new BBVarchar2Filter(this, "STR_ERR");
            FLAG_OPEN = new BBDecimalFilter(this, "FLAG_OPEN");
        }
        public BBDecimalFilter ID;
        public BBDecimalFilter IDN;
        public BBDecimalFilter ND;
        public BBDecimalFilter RNK;
        public BBVarchar2Filter NLS;
        public BBVarchar2Filter OKPO;
        public BBVarchar2Filter FIRST_NAME;
        public BBVarchar2Filter LAST_NAME;
        public BBVarchar2Filter MIDDLE_NAME;
        public BBDecimalFilter TYPE_DOC;
        public BBVarchar2Filter PASPSERIES;
        public BBVarchar2Filter PASPNUM;
        public BBVarchar2Filter PASPISSUER;
        public BBDateFilter PASPDATE;
        public BBDateFilter BDAY;
        public BBVarchar2Filter COUNTRY;
        public BBVarchar2Filter RESIDENT;
        public BBVarchar2Filter GENDER;
        public BBVarchar2Filter PHONE_HOME;
        public BBVarchar2Filter PHONE_MOB;
        public BBVarchar2Filter EMAIL;
        public BBVarchar2Filter ENG_FIRST_NAME;
        public BBVarchar2Filter ENG_LAST_NAME;
        public BBVarchar2Filter MNAME;
        public BBVarchar2Filter ADDR1_CITYNAME;
        public BBVarchar2Filter ADDR1_PCODE;
        public BBVarchar2Filter ADDR1_DOMAIN;
        public BBVarchar2Filter ADDR1_REGION;
        public BBVarchar2Filter ADDR1_STREET;
        public BBVarchar2Filter ADDR2_CITYNAME;
        public BBVarchar2Filter ADDR2_PCODE;
        public BBVarchar2Filter ADDR2_DOMAIN;
        public BBVarchar2Filter ADDR2_REGION;
        public BBVarchar2Filter ADDR2_STREET;
        public BBVarchar2Filter WORK;
        public BBVarchar2Filter OFFICE;
        public BBDateFilter DATE_W;
        public BBVarchar2Filter OKPO_W;
        public BBVarchar2Filter PERS_CAT;
        public BBDecimalFilter AVER_SUM;
        public BBVarchar2Filter TABN;
        public BBVarchar2Filter STR_ERR;
        public BBDecimalFilter FLAG_OPEN;
    }

    public partial class VOwSalaryData : BbTable<VOwSalaryDataRecord, VOwSalaryDataFilters>
    {
        public VOwSalaryData() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VOwSalaryData(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VOwSalaryDataRecord> Select(VOwSalaryDataRecord Item)
        {
            List<VOwSalaryDataRecord> res = new List<VOwSalaryDataRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VOwSalaryDataRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (Decimal?)null : Convert.ToDecimal(rdr[1]), 
                        rdr.IsDBNull(2) ?  (Decimal?)null : Convert.ToDecimal(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]), 
                        rdr.IsDBNull(4) ?  (Decimal?)null : Convert.ToDecimal(rdr[4]), 
                        rdr.IsDBNull(5) ?  (String)null : Convert.ToString(rdr[5]), 
                        rdr.IsDBNull(6) ?  (String)null : Convert.ToString(rdr[6]), 
                        rdr.IsDBNull(7) ?  (String)null : Convert.ToString(rdr[7]), 
                        rdr.IsDBNull(8) ?  (String)null : Convert.ToString(rdr[8]), 
                        rdr.IsDBNull(9) ?  (String)null : Convert.ToString(rdr[9]), 
                        rdr.IsDBNull(10) ?  (Decimal?)null : Convert.ToDecimal(rdr[10]), 
                        rdr.IsDBNull(11) ?  (String)null : Convert.ToString(rdr[11]), 
                        rdr.IsDBNull(12) ?  (String)null : Convert.ToString(rdr[12]), 
                        rdr.IsDBNull(13) ?  (String)null : Convert.ToString(rdr[13]), 
                        rdr.IsDBNull(14) ?  (DateTime?)null : Convert.ToDateTime(rdr[14]), 
                        rdr.IsDBNull(15) ?  (DateTime?)null : Convert.ToDateTime(rdr[15]), 
                        rdr.IsDBNull(16) ?  (String)null : Convert.ToString(rdr[16]), 
                        rdr.IsDBNull(17) ?  (String)null : Convert.ToString(rdr[17]), 
                        rdr.IsDBNull(18) ?  (String)null : Convert.ToString(rdr[18]), 
                        rdr.IsDBNull(19) ?  (String)null : Convert.ToString(rdr[19]), 
                        rdr.IsDBNull(20) ?  (String)null : Convert.ToString(rdr[20]), 
                        rdr.IsDBNull(21) ?  (String)null : Convert.ToString(rdr[21]), 
                        rdr.IsDBNull(22) ?  (String)null : Convert.ToString(rdr[22]), 
                        rdr.IsDBNull(23) ?  (String)null : Convert.ToString(rdr[23]), 
                        rdr.IsDBNull(24) ?  (String)null : Convert.ToString(rdr[24]), 
                        rdr.IsDBNull(25) ?  (String)null : Convert.ToString(rdr[25]), 
                        rdr.IsDBNull(26) ?  (String)null : Convert.ToString(rdr[26]), 
                        rdr.IsDBNull(27) ?  (String)null : Convert.ToString(rdr[27]), 
                        rdr.IsDBNull(28) ?  (String)null : Convert.ToString(rdr[28]), 
                        rdr.IsDBNull(29) ?  (String)null : Convert.ToString(rdr[29]), 
                        rdr.IsDBNull(30) ?  (String)null : Convert.ToString(rdr[30]), 
                        rdr.IsDBNull(31) ?  (String)null : Convert.ToString(rdr[31]), 
                        rdr.IsDBNull(32) ?  (String)null : Convert.ToString(rdr[32]), 
                        rdr.IsDBNull(33) ?  (String)null : Convert.ToString(rdr[33]), 
                        rdr.IsDBNull(34) ?  (String)null : Convert.ToString(rdr[34]), 
                        rdr.IsDBNull(35) ?  (String)null : Convert.ToString(rdr[35]), 
                        rdr.IsDBNull(36) ?  (String)null : Convert.ToString(rdr[36]), 
                        rdr.IsDBNull(37) ?  (DateTime?)null : Convert.ToDateTime(rdr[37]), 
                        rdr.IsDBNull(38) ?  (String)null : Convert.ToString(rdr[38]), 
                        rdr.IsDBNull(39) ?  (String)null : Convert.ToString(rdr[39]), 
                        rdr.IsDBNull(40) ?  (Decimal?)null : Convert.ToDecimal(rdr[40]), 
                        rdr.IsDBNull(41) ?  (String)null : Convert.ToString(rdr[41]), 
                        rdr.IsDBNull(42) ?  (String)null : Convert.ToString(rdr[42]), 
                        rdr.IsDBNull(43) ?  (Decimal?)null : Convert.ToDecimal(rdr[43]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}