/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public partial class VWcsSubproductInfoqueries
    {
        public List<VWcsSubproductInfoqueriesRecord> SelectSbpInfoqueries(String SUBPRODUCT_ID, String SortExpression)
        {
            this.Filter.SUBPRODUCT_ID.Equal(SUBPRODUCT_ID);
            return Select(SortExpression);
        }
        public List<VWcsSubproductInfoqueriesRecord> SelectSbpInfoquery(String SUBPRODUCT_ID, String IQUERY_ID)
        {
            this.Filter.SUBPRODUCT_ID.Equal(SUBPRODUCT_ID);
            this.Filter.IQUERY_ID.Equal(IQUERY_ID);
            return Select();
        }
        public new void Insert(VWcsSubproductInfoqueriesRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SBPROD_IQUERY_SET(Item.SUBPRODUCT_ID, Item.IQUERY_ID, Item.ACT_LEVEL, Item.SERVICE_ID, Item.IS_REQUIRED);
        }
        public new void Update(VWcsSubproductInfoqueriesRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SBPROD_IQUERY_SET(Item.SUBPRODUCT_ID, Item.IQUERY_ID, Item.ACT_LEVEL, Item.SERVICE_ID, Item.IS_REQUIRED);
        }
        public new void Delete(VWcsSubproductInfoqueriesRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SBPROD_IQUERY_DEL(Item.SUBPRODUCT_ID, Item.IQUERY_ID);
        }
    }
}