/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public partial class VWcsSubproductTemplates
    {
        public List<VWcsSubproductTemplatesRecord> SelectSubproductTemplates(String SUBPRODUCT_ID, String SortExpression)
        {
            this.Filter.SUBPRODUCT_ID.Equal(SUBPRODUCT_ID);
            return Select(SortExpression);
        }
        public List<VWcsSubproductTemplatesRecord> SelectSubproductTemplate(String SUBPRODUCT_ID, String TEMPLATE_ID)
        {
            this.Filter.SUBPRODUCT_ID.Equal(SUBPRODUCT_ID);
            this.Filter.TEMPLATE_ID.Equal(TEMPLATE_ID);
            return Select();
        }
        public new void Update(VWcsSubproductTemplatesRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SBP_TEMPLATE_SET(Item.SUBPRODUCT_ID, Item.TEMPLATE_ID, Item.PRINT_STATE_ID, Item.IS_SCAN_REQUIRED);
        }
        public new void Insert(VWcsSubproductTemplatesRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SBP_TEMPLATE_SET(Item.SUBPRODUCT_ID, Item.TEMPLATE_ID, Item.PRINT_STATE_ID, Item.IS_SCAN_REQUIRED);
        }
        public new void Delete(VWcsSubproductTemplatesRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SBP_TEMPLATE_DEL(Item.SUBPRODUCT_ID, Item.TEMPLATE_ID);
        }
    }
}