using System;

public class PrepareWndDealModel
{
    public string WNDTITLE { get; set; }
    public DateTime? DDATE { get; set; }
    public DateTime? DAT_OPL { get; set; }
    public DateTime? DAT_KOM { get; set; }
    public DateTime? DAT_ROZ { get; set; }
    public DateTime? DAT_UG { get; set; }
    public decimal? CB_SWIFT { get; set; }
    public string NMKA { get; set; }
    public string NLSA { get; set; }
    public string SVIDD { get; set; }
    public decimal? RNKA { get; set; }
    public string MFOA { get; set; }
    public string OKPOA { get; set; }
    public decimal? NLS { get; set; }
    public string NLST { get; set; }
    public string NLS9 { get; set; }
    public string NLS8 { get; set; }
    public string KOD_NB { get; set; }
    public string S_KOD_NB { get; set; }
    public string BICA { get; set; }
    public string KOD_BA { get; set; }
    public decimal? BASEVAL { get; set; }
    public DateTime? VDAT { get; set; }
    public decimal? SUMBK { get; set; }
    public decimal? NKV { get; set; }
    public decimal? NLSB_VISIBLE { get; set; }
    public decimal? CB_NO_PAY { get; set; }
    public decimal? CB_NO_PAY_VISIBLE { get; set; }
    public decimal? CB_NO_PAY_ENABLE { get; set; }
    public decimal? CB_ZO { get; set; }
    public decimal? CB_ZO_VISIBLE { get; set; }
    public decimal? CB_ZO_ENABLED { get; set; }
    public decimal? CB_STP { get; set; }
    public decimal? CB_STP_VISIBLE { get; set; }
    public decimal? CB_STP_ENABLED { get; set; }
    public decimal? RB_A_I { get; set; }
    public decimal? RB_A_VISIBLE { get; set; }
    public decimal? RB_A_ENABLED { get; set; }
    public decimal? RB_I_VISIBLE { get; set; }
    public decimal? RB_I_ENABLED { get; set; }
    public string RB_P_TITLE { get; set; }
    public decimal? RB_P_VISIBLE { get; set; }
    public decimal? RB_P_ENABLED { get; set; }
    public string RB_K_TITLE { get; set; }
    public decimal? RB_K_P { get; set; }
    public decimal? RB_K_VISIBLE { get; set; }
    public decimal? RB_K_ENABLED { get; set; }
    public string SNLS_FXC { get; set; }
    public decimal? SNLS_FXC_VISIBLE { get; set; }
    public decimal? SNLS_FXC_ENABLE { get; set; }
    public string SNMS_FXC { get; set; }
    public decimal? SNMS_FXC_VISIBLE { get; set; }
    public decimal? SNMS_FXC_ENABLE { get; set; }
    public decimal? TRASSA_PL_VISIBLE { get; set; }
    public string TRASSA_PL_TITLE { get; set; }
    public decimal? SSA_VISIBLE { get; set; }
    public decimal? NBKA_VISIBLE { get; set; }
    public decimal? BICA_VISIBLE { get; set; }
    public decimal? BICKA_VISIBLE { get; set; }
    public decimal? SSLA_VISIBLE { get; set; }
    public decimal? KOD_NB_VISIBLE { get; set; }
    public decimal? S_KOD_NB_VISIBLE { get; set; }
    public decimal? BICB_VISIBLE { get; set; }
    public decimal? KOD_BB_VISIBLE { get; set; }
    public decimal? KOD_GB_VISIBLE { get; set; }
    public decimal? NGB_VISIBLE { get; set; }
    public decimal? BICKB_VISIBLE { get; set; }
    public decimal? NBKB_VISIBLE { get; set; }
    public decimal? SSB_VISIBLE { get; set; }
    public decimal? BICB__VISIBLE { get; set; }
    public decimal? KOD_BB__VISIBLE { get; set; }
    public decimal? KOD_GB__VISIBLE { get; set; }
    public decimal? NGB__VISIBLE { get; set; }
    public decimal? BICKB__VISIBLE { get; set; }
    public decimal? NBKB__VISIBLE { get; set; }
    public decimal? SSB__VISIBLE { get; set; }
    public decimal? A_ { get; set; }
    public decimal? A__VISIBLE { get; set; }
    public decimal? DP_ { get; set; }
    public decimal? DP__VISIBLE { get; set; }
    public decimal? R_ { get; set; }
    public decimal? R__VISIBLE { get; set; }
    public decimal? RB_AKT_PAS { get; set; }
    public decimal? RB_AKT_VISIBLE { get; set; }
    public decimal? RB_AKT_ENABLED { get; set; }
    public decimal? NID { get; set; }
    public string CP_ID { get; set; }
    public string NBKA_ { get; set; }
    public DateTime? DAT_EMI { get; set; }
    public DateTime? DAT_P { get; set; }
    public string P_NAMECP { get; set; }
    public decimal? P_NEMI { get; set; }
    public string P_NAMEEMI { get; set; }
    public decimal? P_DOX { get; set; }
    public string P_CP_ID { get; set; }
    public decimal? P_KV { get; set; }
    public DateTime? P_DATP { get; set; }
    public decimal? P_RATE { get; set; }
    public decimal? P_TIPD { get; set; }
    public DateTime? P_DAT_EM { get; set; }
    public DateTime? P_DOK { get; set; }
    public decimal? P_AMORT { get; set; }
    public decimal? P_NDCP { get; set; }
    public decimal? P_CENA { get; set; }
    public string P_SBASEY { get; set; }
    public decimal? P_NBASEY { get; set; }
    public decimal? P_KY { get; set; }
    public DateTime? P_DAT_DNK { get; set; }
    public DateTime? P_DAT_RR { get; set; }
    public decimal? P_CENA_KUP { get; set; }
    public decimal? RR_ { get; set; }   
    public decimal? P_NCOUNTRY { get; set; }
    public string S6300 { get; set; }
    public string B_4621 { get; set; }
    public string B_1819 { get; set; }
    public string B_1919 { get; set; }    
    public decimal? P_REPO { get; set;}
}