create or replace view v_middle_names as
select "MIDDLEID","MIDDLEUA","MIDDLERU","SEXID","FIRSTID","MIDDLEUAOF","MIDDLEUAROD","MIDDLEUADAT","MIDDLEUAVIN","MIDDLEUATVO","MIDDLEUAPRE","MIDDLERUROD","MIDDLERUDAT","MIDDLERUVIN","MIDDLERUTVO","MIDDLERUPRE" from MIDDLE_NAMES;


GRANT SELECT ON v_middle_names TO BARS_ACCESS_DEFROLE;