CREATE OR REPLACE FORCE VIEW BARS.V_OB_CORP_REPORT_LAST
(
   CORPORATION_ID,
   FILE_DATE,
   ROWTYPE,
   KF,
   NLS,
   KV,
   OKPO,
   OBDB,
   OBDBQ,
   OBKR,
   OBKRQ,
   OST,
   OSTQ,
   KOD_CORP,
   KOD_USTAN,
   KOD_ANALYT,
   DAPP,
   POSTDAT,
   DOCDAT,
   VALDAT,
   ND,
   VOB,
   DK,
   MFOA,
   NLSA,
   KVA,
   NAMA,
   OKPOA,
   MFOB,
   NLSB,
   KVB,
   NAMB,
   OKPOB,
   S,
   DOCKV,
   SQ,
   NAZN,
   DOCTYPE,
   POSTTIME,
   NAMK,
   NMS,
   TT,
   SESSION_ID
)
AS
   SELECT a.corp_id AS CORPORATION_ID,
          a.fdat AS FILE_DATE,
          0 AS ROWTYPE,
          a.kf AS KF,
          a.nls AS NLS,
          a.kv AS KV,
          a.okpo AS OKPO,
          a.obdb AS OBDB,
          a.obdbq AS OBDBQ,
          a.obkr AS OBKR,
          a.obkrq AS OBKRQ,
          a.ost AS OST,
          a.ostq AS OSTQ,
          a.corp_id AS KOD_CORP,
          a.kod_ustan AS KOD_USTAN,
          a.kod_analyt AS KOD_ANALYT,
          a.dapp AS DAPP,
          a.postdat AS POSTDAT,
          NULL AS DOCDAT,
          NULL AS VALDAT,
          NULL AS ND,
          NULL AS VOB,
          NULL AS DK,
          NULL AS MFOA,
          NULL AS NLSA,
          NULL AS KVA,
          NULL AS NAMA,
          NULL AS OKPOA,
          NULL AS MFOB,
          NULL AS NLSB,
          NULL AS KVB,
          NULL AS NAMB,
          NULL AS OKPOB,
          NULL AS S,
          NULL AS DOCKV,
          NULL AS SQ,
          NULL AS NAZN,
          NULL AS DOCTYPE,
          NULL AS POSTTIME,
          a.namk AS NAMK,
          a.nms AS NMS,
          NULL AS TT,
          a.sess_id AS SESSION_ID
     FROM OB_CORP_DATA_ACC a
    WHERE a.is_last = 1
   UNION ALL
   SELECT a.corp_id AS CORPORATION_ID,
          a.fdat AS FILE_DATE,
          1 AS ROWTYPE,
          a.kf AS KF,
          a.nls AS NLS,
          a.kv AS KV,
          NULL AS OKPO,
          NULL AS OBDB,
          NULL AS OBDBQ,
          NULL AS OBKR,
          NULL AS OBKRQ,
          NULL AS OST,
          NULL AS OSTQ,
          a.corp_id AS KOD_CORP,
          a.kod_ustan AS KOD_USTAN,
          a.kod_analyt AS KOD_ANALYT,
          NULL AS DAPP,
          d.postdat AS POSTDAT,
          d.docdat AS DOCDAT,
          d.valdat AS VALDAT,
          d.nd AS ND,
          d.vob AS VOB,
          1 AS DK,
          d.mfoa AS MFOA,
          d.nlsa AS NLSA,
          d.kva AS KVA,
          d.nama AS NAMA,
          d.okpoa AS OKPOA,
          d.mfob AS MFOB,
          d.nlsb AS NLSB,
          d.kvb AS KVB,
          d.namb AS NAMB,
          d.okpob AS OKPOB,
          d.s AS S,
          d.dockv AS DOCKV,
          d.sq AS SQ,
          d.nazn AS NAZN,
          d.dk AS DOCTYPE,
          d.postdat AS POSTTIME,
          a.namk AS NAMK,
          a.nms AS NMS,
          d.tt AS TT,
          a.sess_id AS SESSION_ID
     FROM OB_CORP_DATA_ACC a
          JOIN OB_CORP_DATA_DOC d
             ON a.sess_id = d.sess_id AND a.acc = d.acc AND a.kf = d.kf
    WHERE a.is_last = 1
   UNION ALL
     SELECT a.corp_id AS CORPORATION_ID,
            a.fdat AS FILE_DATE,
            2 AS ROWTYPE,
            a.kf AS KF,
            TO_CHAR (COUNT (*)) AS NLS,
            NULL AS KV,
            NULL AS OKPO,
            NULL AS OBDB,
            NULL AS OBDBQ,
            NULL AS OBKR,
            NULL AS OBKRQ,
            NULL AS OST,
            NULL AS OSTQ,
            a.corp_id AS KOD_CORP,
            NULL AS KOD_USTAN,
            NULL AS KOD_ANALYT,
            NULL AS DAPP,
            NULL AS POSTDAT,
            NULL AS DOCDAT,
            NULL AS VALDAT,
            NULL AS ND,
            NULL AS VOB,
            NULL AS DK,
            NULL AS MFOA,
            NULL AS NLSA,
            NULL AS KVA,
            NULL AS NAMA,
            NULL AS OKPOA,
            NULL AS MFOB,
            NULL AS NLSB,
            NULL AS KVB,
            NULL AS NAMB,
            NULL AS OKPOB,
            NULL AS S,
            NULL AS DOCKV,
            NULL AS SQ,
            NULL AS NAZN,
            NULL AS DOCTYPE,
            NULL AS POSTTIME,
            NULL AS NAMK,
            NULL AS NMS,
            NULL AS TT,
            a.sess_id AS SESSION_ID
       FROM OB_CORP_DATA_ACC a
      WHERE a.is_last = 1
   GROUP BY a.corp_id,
            a.sess_id,
            a.fdat,
            a.kf;
/
GRANT SELECT ON BARS.V_OB_CORP_REPORT_LAST TO BARS_ACCESS_DEFROLE;
/