DELETE FROM K9;
insert into k9 (K9, IFRS, POCI, NAME) values (1, 'AC', 0, 'IFRS=AC, POCI=ЭГ');
insert into k9 (K9, IFRS, POCI, NAME) values (2, 'FVOCI', 0, 'IFRS=FVOCI, POCI=ЭГ');
insert into k9 (K9, IFRS, POCI, NAME) values (3, 'FVTPL/Other', 0, 'IFRS=FVTPL/Other, POCI=ЭГ');
insert into k9 (K9, IFRS, POCI, NAME) values (4, 'AC', 1, 'IFRS=AC, POCI=връ');
insert into k9 (K9, IFRS, POCI, NAME) values (5, 'FVOCI', 1, 'IFRS=FVOCI, POCI=връ');
COMMIT;
/

