prompt create tablespace FMNTBS

begin
	execute immediate q'[
		CREATE TABLESPACE FMNTBS DATAFILE 
		'+DATA1' SIZE 7M AUTOEXTEND ON NEXT 512K MAXSIZE UNLIMITED,
		'+DATA1' SIZE 7M AUTOEXTEND ON NEXT 512K MAXSIZE UNLIMITED,
		'+DATA1' SIZE 7M AUTOEXTEND ON NEXT 512K MAXSIZE UNLIMITED
		LOGGING
		ONLINE
		EXTENT MANAGEMENT LOCAL AUTOALLOCATE
		SEGMENT SPACE MANAGEMENT AUTO]';
exception
	when others then
		if sqlcode = -1543 then null; else raise; end if;
end;
/