
<input runat="server" type="hidden" id="Mes30" value='<%$ Resources:Deposit.GlobalResources, Mes30%>'/><!--"Сумма пополнения меньше минимальной допустимой суммы!"--> 
<input runat="server" type="hidden" id="Mes31" value='<%$ Resources:Deposit.GlobalResources, Mes31%>'/><!--"Не выбрана операция!" />-->
<input runat="server" type="hidden" id="Mes32" value='<%$ Resources:Deposit.GlobalResources, Mes32%>'/><!--"Для продолжения выберите операцию." />-->
<input runat="server" type="hidden" id="Mes33" value='<%$ Resources:Deposit.GlobalResources, Mes33%>'/><!--"Документ пустой!" />-->
<input runat="server" type="hidden" id="Mes34" value='<%$ Resources:Deposit.GlobalResources, Mes34%>'/><!--"Не выбран ни один депозит!" />-->
<input runat="server" type="hidden" id="Mes35" value='<%$ Resources:Deposit.GlobalResources, Mes35%>'/><!--"Не выбран ни один документ!" />-->
<input runat="server" type="hidden" id="Mes42" value='<%$ Resources:Deposit.GlobalResources, Mes42%>'/><!--"Коментар успішно збережено!" />-->