-- ================================================================================
-- Module : UPL
-- Date : 13.05.2017
-- ================================================================================
-- Опис полів файлу вивантаження
-- ================================================================================

delete from BARSUPL.UPL_COLUMNS
 where file_id in ( 566);

--- 
--- UPL - ETL-18729 - выгрузить справочник S080_FIN с созданием соответствующей ссылки на nbu23rez
--- 
prompt 134 справочник S080_FIN

Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 1, 'TOBO', 'Відділення', 'CHAR', 
    30, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 2, 'NLS', 'Номер рахунку', 'VARCHAR2', 
    20, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 3, 'KV', 'Валюта', 'NUMBER', 
    3, 0, NULL, NULL, 'Y', 
    NULL, NULL, '0', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 4, 'DATF', 'Робоча дата', 'DATE', 
    8, NULL, 'ddmmyyyy', NULL, 'Y', 
    NULL, NULL, '31.12.9999', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 5, 'ACC', 'ACC', 'NUMBER', 
    38, 0, NULL, NULL, 'Y', 
    NULL, NULL, '0', NULL, 'TRUNC_E2');
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 6, 'DK', '1-Дт 2-Кт (код)', 'CHAR', 
    1, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 7, 'NBS', 'Бал. рах. (код)', 'CHAR', 
    4, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 8, 'KV1', 'Код валюти (код)', 'CHAR', 
    3, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 9, 'S181', '1-короткостр. 2-довгостр. (код)', 'CHAR', 
    1, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 10, 'R013', 'Параметр R013 (код)', 'CHAR', 
    1, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 11, 'S240', 'Код сроку до погашення (код)', 'CHAR', 
    1, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 12, 'K030', 'Резидент нiсть (код)', 'CHAR', 
    1, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 13, 'R012', 'Вид рахунку (код)', 'CHAR', 
    1, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 14, 'ZNAP', 'Значення показника', 'VARCHAR2', 
    256, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 15, 'RNK', 'Реєстр. номер контрагента', 'NUMBER', 
    38, 0, NULL, NULL, 'Y', 
    NULL, NULL, '0', NULL, 'TRUNC_E2');
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 16, 'OKPO', 'ІНН контрагента', 'VARCHAR2', 
    14, NULL, NULL, NULL, 'Y', 
    NULL, NULL, 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 17, 'NMK', 'ПІБ (назва) контрагента', 'VARCHAR2', 
    70, NULL, NULL, NULL, 'Y', 
    NULL, '09,13,10|32,32,32', 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 18, 'MDATE', 'Дата погашення', 'DATE', 
    8, NULL, 'ddmmyyyy', NULL, 'Y', 
    NULL, NULL, '31.12.9999', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 19, 'ISP', 'Код відп. виконавця', 'NUMBER', 
    38, 0, NULL, NULL, 'Y', 
    NULL, NULL, '0', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 20, 'ND', 'Номер кред. договору', 'NUMBER', 
    38, 0, NULL, NULL, 'Y', 
    NULL, NULL, '0', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 21, 'CC_ID', 'Ід. договору', 'VARCHAR2', 
    50, NULL, NULL, NULL, 'Y', 
    NULL, '09,13,10|32,32,32', 'N/A', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 22, 'SDATE', 'Дата заключення договору', 'DATE', 
    8, NULL, 'ddmmyyyy', NULL, 'Y', 
    NULL, NULL, '31.12.9999', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 23, 'WDATE', 'Дата завершення договору', 'DATE', 
    8, NULL, 'ddmmyyyy', NULL, 'Y', 
    NULL, NULL, '31.12.9999', NULL, NULL);
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 24, 'REF', 'Номер документу', 'NUMBER', 
    38, 0, NULL, NULL, 'Y', 
    NULL, NULL, '0', NULL, 'TRUNC_E2');
Insert into BARSUPL.UPL_COLUMNS
   (FILE_ID, COL_ID, COL_NAME, COL_DESC, COL_TYPE, 
    COL_LENGTH, COL_SCALE, COL_FORMAT, PK_CONSTR, NULLABLE, 
    NULL_VALUES, REPL_CHARS_WITH, SKELETON_VALUES, PK_CONSTR_ID, PREFUN)
 Values
   (566, 25, 'COMM', 'Коментар', 'VARCHAR2', 
    250, NULL, NULL, NULL, 'Y', 
    NULL, '09,13,10|32,32,32', 'N/A', NULL, NULL);

COMMIT;



--
-- FINISH
--