/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace ibank.core
{
    public sealed class VXmlimpdocsUiRecord : BbRecord
    {
        public VXmlimpdocsUiRecord(): base()
        {
            fillFields();
        }
        public VXmlimpdocsUiRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VXmlimpdocsUiRecord(BbDataSource Parent, OracleDecimal RowScn, String FN, DateTime? DAT, Decimal? IMPREF, Decimal? REF, String MFOA, String NLSA, String ID_A, String NAM_A, String MFOB, String NLSB, String ID_B, String NAM_B, Decimal? S, Decimal? S2, Decimal? KV, Decimal? KV2, Decimal? DK, String ND, String TT, Decimal? SK, String NAZN, DateTime? DATD, DateTime? DATP, DateTime? VDAT, Decimal? VOB, String ERRCODE, String ERRMSG, Decimal? STATUS, String TXTSTATUS, String D_REC, Decimal? BIS)
            : this(Parent)
        {
            this.FN = FN;
            this.DAT = DAT;
            this.IMPREF = IMPREF;
            this.REF = REF;
            this.MFOA = MFOA;
            this.NLSA = NLSA;
            this.ID_A = ID_A;
            this.NAM_A = NAM_A;
            this.MFOB = MFOB;
            this.NLSB = NLSB;
            this.ID_B = ID_B;
            this.NAM_B = NAM_B;
            this.S = S;
            this.S2 = S2;
            this.KV = KV;
            this.KV2 = KV2;
            this.DK = DK;
            this.ND = ND;
            this.TT = TT;
            this.SK = SK;
            this.NAZN = NAZN;
            this.DATD = DATD;
            this.DATP = DATP;
            this.VDAT = VDAT;
            this.VOB = VOB;
            this.ERRCODE = ERRCODE;
            this.ERRMSG = ERRMSG;
            this.STATUS = STATUS;
            this.TXTSTATUS = TXTSTATUS;
            this.D_REC = D_REC;
            this.BIS = BIS;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("FN", OracleDbType.Varchar2, false, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("DAT", OracleDbType.Date, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("IMPREF", OracleDbType.Decimal, false, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("REF", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("MFOA", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NLSA", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ID_A", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NAM_A", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("MFOB", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NLSB", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ID_B", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NAM_B", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("S", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("S2", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("KV", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("KV2", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("DK", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ND", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("TT", OracleDbType.Char, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("SK", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("NAZN", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("DATD", OracleDbType.Date, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("DATP", OracleDbType.Date, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("VDAT", OracleDbType.Date, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("VOB", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ERRCODE", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("ERRMSG", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("STATUS", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("TXTSTATUS", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("D_REC", OracleDbType.Varchar2, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));
            Fields.Add( new BbField("BIS", OracleDbType.Decimal, true, false, false, false, false, "V_XMLIMPDOCS_UI", ObjectTypes.View, "", ""));        
        }
        public String FN { get { return (String)FindField("FN").Value; } set {SetField("FN", value);} }
        public DateTime? DAT { get { return (DateTime?)FindField("DAT").Value; } set {SetField("DAT", value);} }
        public Decimal? IMPREF { get { return (Decimal?)FindField("IMPREF").Value; } set {SetField("IMPREF", value);} }
        public Decimal? REF { get { return (Decimal?)FindField("REF").Value; } set {SetField("REF", value);} }
        public String MFOA { get { return (String)FindField("MFOA").Value; } set {SetField("MFOA", value);} }
        public String NLSA { get { return (String)FindField("NLSA").Value; } set {SetField("NLSA", value);} }
        public String ID_A { get { return (String)FindField("ID_A").Value; } set {SetField("ID_A", value);} }
        public String NAM_A { get { return (String)FindField("NAM_A").Value; } set {SetField("NAM_A", value);} }
        public String MFOB { get { return (String)FindField("MFOB").Value; } set {SetField("MFOB", value);} }
        public String NLSB { get { return (String)FindField("NLSB").Value; } set {SetField("NLSB", value);} }
        public String ID_B { get { return (String)FindField("ID_B").Value; } set {SetField("ID_B", value);} }
        public String NAM_B { get { return (String)FindField("NAM_B").Value; } set {SetField("NAM_B", value);} }
        public Decimal? S { get { return (Decimal?)FindField("S").Value; } set {SetField("S", value);} }
        public Decimal? S2 { get { return (Decimal?)FindField("S2").Value; } set {SetField("S2", value);} }
        public Decimal? KV { get { return (Decimal?)FindField("KV").Value; } set {SetField("KV", value);} }
        public Decimal? KV2 { get { return (Decimal?)FindField("KV2").Value; } set {SetField("KV2", value);} }
        public Decimal? DK { get { return (Decimal?)FindField("DK").Value; } set {SetField("DK", value);} }
        public String ND { get { return (String)FindField("ND").Value; } set {SetField("ND", value);} }
        public String TT { get { return (String)FindField("TT").Value; } set {SetField("TT", value);} }
        public Decimal? SK { get { return (Decimal?)FindField("SK").Value; } set {SetField("SK", value);} }
        public String NAZN { get { return (String)FindField("NAZN").Value; } set {SetField("NAZN", value);} }
        public DateTime? DATD { get { return (DateTime?)FindField("DATD").Value; } set {SetField("DATD", value);} }
        public DateTime? DATP { get { return (DateTime?)FindField("DATP").Value; } set {SetField("DATP", value);} }
        public DateTime? VDAT { get { return (DateTime?)FindField("VDAT").Value; } set {SetField("VDAT", value);} }
        public Decimal? VOB { get { return (Decimal?)FindField("VOB").Value; } set {SetField("VOB", value);} }
        public String ERRCODE { get { return (String)FindField("ERRCODE").Value; } set {SetField("ERRCODE", value);} }
        public String ERRMSG { get { return (String)FindField("ERRMSG").Value; } set {SetField("ERRMSG", value);} }
        public Decimal? STATUS { get { return (Decimal?)FindField("STATUS").Value; } set {SetField("STATUS", value);} }
        public String TXTSTATUS { get { return (String)FindField("TXTSTATUS").Value; } set {SetField("TXTSTATUS", value);} }
        public String D_REC { get { return (String)FindField("D_REC").Value; } set {SetField("D_REC", value);} }
        public Decimal? BIS { get { return (Decimal?)FindField("BIS").Value; } set {SetField("BIS", value);} }
    }

    public sealed class VXmlimpdocsUiFilters : BbFilters
    {
        public VXmlimpdocsUiFilters(BbDataSource Parent) : base (Parent)
        {
            FN = new BBVarchar2Filter(this, "FN");
            DAT = new BBDateFilter(this, "DAT");
            IMPREF = new BBDecimalFilter(this, "IMPREF");
            REF = new BBDecimalFilter(this, "REF");
            MFOA = new BBVarchar2Filter(this, "MFOA");
            NLSA = new BBVarchar2Filter(this, "NLSA");
            ID_A = new BBVarchar2Filter(this, "ID_A");
            NAM_A = new BBVarchar2Filter(this, "NAM_A");
            MFOB = new BBVarchar2Filter(this, "MFOB");
            NLSB = new BBVarchar2Filter(this, "NLSB");
            ID_B = new BBVarchar2Filter(this, "ID_B");
            NAM_B = new BBVarchar2Filter(this, "NAM_B");
            S = new BBDecimalFilter(this, "S");
            S2 = new BBDecimalFilter(this, "S2");
            KV = new BBDecimalFilter(this, "KV");
            KV2 = new BBDecimalFilter(this, "KV2");
            DK = new BBDecimalFilter(this, "DK");
            ND = new BBVarchar2Filter(this, "ND");
            TT = new BBCharFilter(this, "TT");
            SK = new BBDecimalFilter(this, "SK");
            NAZN = new BBVarchar2Filter(this, "NAZN");
            DATD = new BBDateFilter(this, "DATD");
            DATP = new BBDateFilter(this, "DATP");
            VDAT = new BBDateFilter(this, "VDAT");
            VOB = new BBDecimalFilter(this, "VOB");
            ERRCODE = new BBVarchar2Filter(this, "ERRCODE");
            ERRMSG = new BBVarchar2Filter(this, "ERRMSG");
            STATUS = new BBDecimalFilter(this, "STATUS");
            TXTSTATUS = new BBVarchar2Filter(this, "TXTSTATUS");
            D_REC = new BBVarchar2Filter(this, "D_REC");
            BIS = new BBDecimalFilter(this, "BIS");
        }
        public BBVarchar2Filter FN;
        public BBDateFilter DAT;
        public BBDecimalFilter IMPREF;
        public BBDecimalFilter REF;
        public BBVarchar2Filter MFOA;
        public BBVarchar2Filter NLSA;
        public BBVarchar2Filter ID_A;
        public BBVarchar2Filter NAM_A;
        public BBVarchar2Filter MFOB;
        public BBVarchar2Filter NLSB;
        public BBVarchar2Filter ID_B;
        public BBVarchar2Filter NAM_B;
        public BBDecimalFilter S;
        public BBDecimalFilter S2;
        public BBDecimalFilter KV;
        public BBDecimalFilter KV2;
        public BBDecimalFilter DK;
        public BBVarchar2Filter ND;
        public BBCharFilter TT;
        public BBDecimalFilter SK;
        public BBVarchar2Filter NAZN;
        public BBDateFilter DATD;
        public BBDateFilter DATP;
        public BBDateFilter VDAT;
        public BBDecimalFilter VOB;
        public BBVarchar2Filter ERRCODE;
        public BBVarchar2Filter ERRMSG;
        public BBDecimalFilter STATUS;
        public BBVarchar2Filter TXTSTATUS;
        public BBVarchar2Filter D_REC;
        public BBDecimalFilter BIS;
    }

    public partial class VXmlimpdocsUi : BbTable<VXmlimpdocsUiRecord, VXmlimpdocsUiFilters>
    {
        public VXmlimpdocsUi() : base(new BbConnection())
        {
            base.Connection.RoleName = "OPER000";
        }
        public VXmlimpdocsUi(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VXmlimpdocsUiRecord> Select(VXmlimpdocsUiRecord Item)
        {
            List<VXmlimpdocsUiRecord> res = new List<VXmlimpdocsUiRecord>();
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                OracleDataReader rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VXmlimpdocsUiRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (String)null : Convert.ToString(rdr[1]), 
                        rdr.IsDBNull(2) ?  (DateTime?)null : Convert.ToDateTime(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]), 
                        rdr.IsDBNull(4) ?  (Decimal?)null : Convert.ToDecimal(rdr[4]), 
                        rdr.IsDBNull(5) ?  (String)null : Convert.ToString(rdr[5]), 
                        rdr.IsDBNull(6) ?  (String)null : Convert.ToString(rdr[6]), 
                        rdr.IsDBNull(7) ?  (String)null : Convert.ToString(rdr[7]), 
                        rdr.IsDBNull(8) ?  (String)null : Convert.ToString(rdr[8]), 
                        rdr.IsDBNull(9) ?  (String)null : Convert.ToString(rdr[9]), 
                        rdr.IsDBNull(10) ?  (String)null : Convert.ToString(rdr[10]), 
                        rdr.IsDBNull(11) ?  (String)null : Convert.ToString(rdr[11]), 
                        rdr.IsDBNull(12) ?  (String)null : Convert.ToString(rdr[12]), 
                        rdr.IsDBNull(13) ?  (Decimal?)null : Convert.ToDecimal(rdr[13]), 
                        rdr.IsDBNull(14) ?  (Decimal?)null : Convert.ToDecimal(rdr[14]), 
                        rdr.IsDBNull(15) ?  (Decimal?)null : Convert.ToDecimal(rdr[15]), 
                        rdr.IsDBNull(16) ?  (Decimal?)null : Convert.ToDecimal(rdr[16]), 
                        rdr.IsDBNull(17) ?  (Decimal?)null : Convert.ToDecimal(rdr[17]), 
                        rdr.IsDBNull(18) ?  (String)null : Convert.ToString(rdr[18]), 
                        rdr.IsDBNull(19) ?  (String)null : Convert.ToString(rdr[19]), 
                        rdr.IsDBNull(20) ?  (Decimal?)null : Convert.ToDecimal(rdr[20]), 
                        rdr.IsDBNull(21) ?  (String)null : Convert.ToString(rdr[21]), 
                        rdr.IsDBNull(22) ?  (DateTime?)null : Convert.ToDateTime(rdr[22]), 
                        rdr.IsDBNull(23) ?  (DateTime?)null : Convert.ToDateTime(rdr[23]), 
                        rdr.IsDBNull(24) ?  (DateTime?)null : Convert.ToDateTime(rdr[24]), 
                        rdr.IsDBNull(25) ?  (Decimal?)null : Convert.ToDecimal(rdr[25]), 
                        rdr.IsDBNull(26) ?  (String)null : Convert.ToString(rdr[26]), 
                        rdr.IsDBNull(27) ?  (String)null : Convert.ToString(rdr[27]), 
                        rdr.IsDBNull(28) ?  (Decimal?)null : Convert.ToDecimal(rdr[28]), 
                        rdr.IsDBNull(29) ?  (String)null : Convert.ToString(rdr[29]), 
                        rdr.IsDBNull(30) ?  (String)null : Convert.ToString(rdr[30]), 
                        rdr.IsDBNull(31) ?  (Decimal?)null : Convert.ToDecimal(rdr[31]))
                    );
                }
                rdr.Close();
                rdr.Dispose();
            }
            finally
            {
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
        public List<VXmlimpdocsUiRecord> Select(String SortExpression)
        {
            return Select(SortExpression);            
        }
    }
}