//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Areas.Admin.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<APPLIST> APPLIST
        {
            get
            {
                if ((_APPLIST == null))
                {
                    _APPLIST = base.CreateObjectSet<APPLIST>("APPLIST");
                }
                return _APPLIST;
            }
        }
        private ObjectSet<APPLIST> _APPLIST;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<STAFF_BASE> STAFF_BASE
        {
            get
            {
                if ((_STAFF_BASE == null))
                {
                    _STAFF_BASE = base.CreateObjectSet<STAFF_BASE>("STAFF_BASE");
                }
                return _STAFF_BASE;
            }
        }
        private ObjectSet<STAFF_BASE> _STAFF_BASE;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the APPLIST EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAPPLIST(APPLIST aPPLIST)
        {
            base.AddObject("APPLIST", aPPLIST);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the STAFF_BASE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSTAFF_BASE(STAFF_BASE sTAFF_BASE)
        {
            base.AddObject("STAFF_BASE", sTAFF_BASE);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="p_CODEAPP">No Metadata Documentation available.</param>
        /// <param name="p_NAME">No Metadata Documentation available.</param>
        /// <param name="p_HOTKEY">No Metadata Documentation available.</param>
        /// <param name="p_FRONTEND">No Metadata Documentation available.</param>
        /// <param name="p_ICON">No Metadata Documentation available.</param>
        public int FUNC_MGR_ADD_APPLICATION(global::System.String p_CODEAPP, global::System.String p_NAME, global::System.String p_HOTKEY, Nullable<global::System.Decimal> p_FRONTEND, global::System.String p_ICON)
        {
            ObjectParameter p_CODEAPPParameter;
            if (p_CODEAPP != null)
            {
                p_CODEAPPParameter = new ObjectParameter("P_CODEAPP", p_CODEAPP);
            }
            else
            {
                p_CODEAPPParameter = new ObjectParameter("P_CODEAPP", typeof(global::System.String));
            }
    
            ObjectParameter p_NAMEParameter;
            if (p_NAME != null)
            {
                p_NAMEParameter = new ObjectParameter("P_NAME", p_NAME);
            }
            else
            {
                p_NAMEParameter = new ObjectParameter("P_NAME", typeof(global::System.String));
            }
    
            ObjectParameter p_HOTKEYParameter;
            if (p_HOTKEY != null)
            {
                p_HOTKEYParameter = new ObjectParameter("P_HOTKEY", p_HOTKEY);
            }
            else
            {
                p_HOTKEYParameter = new ObjectParameter("P_HOTKEY", typeof(global::System.String));
            }
    
            ObjectParameter p_FRONTENDParameter;
            if (p_FRONTEND.HasValue)
            {
                p_FRONTENDParameter = new ObjectParameter("P_FRONTEND", p_FRONTEND);
            }
            else
            {
                p_FRONTENDParameter = new ObjectParameter("P_FRONTEND", typeof(global::System.Decimal));
            }
    
            ObjectParameter p_ICONParameter;
            if (p_ICON != null)
            {
                p_ICONParameter = new ObjectParameter("P_ICON", p_ICON);
            }
            else
            {
                p_ICONParameter = new ObjectParameter("P_ICON", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("FUNC_MGR_ADD_APPLICATION", p_CODEAPPParameter, p_NAMEParameter, p_HOTKEYParameter, p_FRONTENDParameter, p_ICONParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="p_CODEAPP">No Metadata Documentation available.</param>
        public int BARS_USERADM_SET_APP_CONTEXT(global::System.String p_CODEAPP)
        {
            ObjectParameter p_CODEAPPParameter;
            if (p_CODEAPP != null)
            {
                p_CODEAPPParameter = new ObjectParameter("P_CODEAPP", p_CODEAPP);
            }
            else
            {
                p_CODEAPPParameter = new ObjectParameter("P_CODEAPP", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("BARS_USERADM_SET_APP_CONTEXT", p_CODEAPPParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="p_APPID">No Metadata Documentation available.</param>
        /// <param name="p_RESID">No Metadata Documentation available.</param>
        public int BARS_USERADM_GRANT_APP_RESOURCE(global::System.String p_APPID, Nullable<global::System.Decimal> p_RESID)
        {
            ObjectParameter p_APPIDParameter;
            if (p_APPID != null)
            {
                p_APPIDParameter = new ObjectParameter("P_APPID", p_APPID);
            }
            else
            {
                p_APPIDParameter = new ObjectParameter("P_APPID", typeof(global::System.String));
            }
    
            ObjectParameter p_RESIDParameter;
            if (p_RESID.HasValue)
            {
                p_RESIDParameter = new ObjectParameter("P_RESID", p_RESID);
            }
            else
            {
                p_RESIDParameter = new ObjectParameter("P_RESID", typeof(global::System.Decimal));
            }
    
            return base.ExecuteFunction("BARS_USERADM_GRANT_APP_RESOURCE", p_APPIDParameter, p_RESIDParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="APPLIST")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class APPLIST : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new APPLIST object.
        /// </summary>
        /// <param name="cODEAPP">Initial value of the CODEAPP property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        /// <param name="fRONTEND">Initial value of the FRONTEND property.</param>
        public static APPLIST CreateAPPLIST(global::System.String cODEAPP, global::System.String nAME, global::System.Decimal fRONTEND)
        {
            APPLIST aPPLIST = new APPLIST();
            aPPLIST.CODEAPP = cODEAPP;
            aPPLIST.NAME = nAME;
            aPPLIST.FRONTEND = fRONTEND;
            return aPPLIST;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODEAPP
        {
            get
            {
                return _CODEAPP;
            }
            set
            {
                if (_CODEAPP != value)
                {
                    OnCODEAPPChanging(value);
                    ReportPropertyChanging("CODEAPP");
                    _CODEAPP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CODEAPP");
                    OnCODEAPPChanged();
                }
            }
        }
        private global::System.String _CODEAPP;
        partial void OnCODEAPPChanging(global::System.String value);
        partial void OnCODEAPPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HOTKEY
        {
            get
            {
                return _HOTKEY;
            }
            set
            {
                OnHOTKEYChanging(value);
                ReportPropertyChanging("HOTKEY");
                _HOTKEY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HOTKEY");
                OnHOTKEYChanged();
            }
        }
        private global::System.String _HOTKEY;
        partial void OnHOTKEYChanging(global::System.String value);
        partial void OnHOTKEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FRONTEND
        {
            get
            {
                return _FRONTEND;
            }
            set
            {
                OnFRONTENDChanging(value);
                ReportPropertyChanging("FRONTEND");
                _FRONTEND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FRONTEND");
                OnFRONTENDChanged();
            }
        }
        private global::System.Decimal _FRONTEND;
        partial void OnFRONTENDChanging(global::System.Decimal value);
        partial void OnFRONTENDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _ID;
        partial void OnIDChanging(Nullable<global::System.Decimal> value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ICON
        {
            get
            {
                return _ICON;
            }
            set
            {
                OnICONChanging(value);
                ReportPropertyChanging("ICON");
                _ICON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ICON");
                OnICONChanged();
            }
        }
        private global::System.String _ICON;
        partial void OnICONChanging(global::System.String value);
        partial void OnICONChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdminModel", Name="STAFF_BASE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class STAFF_BASE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new STAFF_BASE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fIO">Initial value of the FIO property.</param>
        /// <param name="lOGNAME">Initial value of the LOGNAME property.</param>
        /// <param name="tYPE">Initial value of the TYPE property.</param>
        /// <param name="cLSID">Initial value of the CLSID property.</param>
        /// <param name="bRANCH">Initial value of the BRANCH property.</param>
        /// <param name="uSEARC">Initial value of the USEARC property.</param>
        /// <param name="cSCHEMA">Initial value of the CSCHEMA property.</param>
        /// <param name="wEB_PROFILE">Initial value of the WEB_PROFILE property.</param>
        /// <param name="pOLICY_GROUP">Initial value of the POLICY_GROUP property.</param>
        /// <param name="aCTIVE">Initial value of the ACTIVE property.</param>
        /// <param name="cREATED">Initial value of the CREATED property.</param>
        /// <param name="uSEGTW">Initial value of the USEGTW property.</param>
        /// <param name="tEMPL_ID">Initial value of the TEMPL_ID property.</param>
        public static STAFF_BASE CreateSTAFF_BASE(global::System.Decimal id, global::System.String fIO, global::System.String lOGNAME, global::System.Int16 tYPE, global::System.Decimal cLSID, global::System.String bRANCH, global::System.Int16 uSEARC, global::System.String cSCHEMA, global::System.String wEB_PROFILE, global::System.String pOLICY_GROUP, global::System.Int16 aCTIVE, global::System.DateTime cREATED, global::System.Int16 uSEGTW, global::System.Decimal tEMPL_ID)
        {
            STAFF_BASE sTAFF_BASE = new STAFF_BASE();
            sTAFF_BASE.ID = id;
            sTAFF_BASE.FIO = fIO;
            sTAFF_BASE.LOGNAME = lOGNAME;
            sTAFF_BASE.TYPE = tYPE;
            sTAFF_BASE.CLSID = cLSID;
            sTAFF_BASE.BRANCH = bRANCH;
            sTAFF_BASE.USEARC = uSEARC;
            sTAFF_BASE.CSCHEMA = cSCHEMA;
            sTAFF_BASE.WEB_PROFILE = wEB_PROFILE;
            sTAFF_BASE.POLICY_GROUP = pOLICY_GROUP;
            sTAFF_BASE.ACTIVE = aCTIVE;
            sTAFF_BASE.CREATED = cREATED;
            sTAFF_BASE.USEGTW = uSEGTW;
            sTAFF_BASE.TEMPL_ID = tEMPL_ID;
            return sTAFF_BASE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LOGNAME
        {
            get
            {
                return _LOGNAME;
            }
            set
            {
                OnLOGNAMEChanging(value);
                ReportPropertyChanging("LOGNAME");
                _LOGNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LOGNAME");
                OnLOGNAMEChanged();
            }
        }
        private global::System.String _LOGNAME;
        partial void OnLOGNAMEChanging(global::System.String value);
        partial void OnLOGNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.Int16 _TYPE;
        partial void OnTYPEChanging(global::System.Int16 value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TABN
        {
            get
            {
                return _TABN;
            }
            set
            {
                OnTABNChanging(value);
                ReportPropertyChanging("TABN");
                _TABN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TABN");
                OnTABNChanged();
            }
        }
        private global::System.String _TABN;
        partial void OnTABNChanging(global::System.String value);
        partial void OnTABNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BAX
        {
            get
            {
                return _BAX;
            }
            set
            {
                OnBAXChanging(value);
                ReportPropertyChanging("BAX");
                _BAX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BAX");
                OnBAXChanged();
            }
        }
        private Nullable<global::System.Int16> _BAX;
        partial void OnBAXChanging(Nullable<global::System.Int16> value);
        partial void OnBAXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TBAX
        {
            get
            {
                return _TBAX;
            }
            set
            {
                OnTBAXChanging(value);
                ReportPropertyChanging("TBAX");
                _TBAX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TBAX");
                OnTBAXChanged();
            }
        }
        private Nullable<global::System.DateTime> _TBAX;
        partial void OnTBAXChanging(Nullable<global::System.DateTime> value);
        partial void OnTBAXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> DISABLE
        {
            get
            {
                return _DISABLE;
            }
            set
            {
                OnDISABLEChanging(value);
                ReportPropertyChanging("DISABLE");
                _DISABLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DISABLE");
                OnDISABLEChanged();
            }
        }
        private Nullable<global::System.Int16> _DISABLE;
        partial void OnDISABLEChanging(Nullable<global::System.Int16> value);
        partial void OnDISABLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ADATE1
        {
            get
            {
                return _ADATE1;
            }
            set
            {
                OnADATE1Changing(value);
                ReportPropertyChanging("ADATE1");
                _ADATE1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ADATE1");
                OnADATE1Changed();
            }
        }
        private Nullable<global::System.DateTime> _ADATE1;
        partial void OnADATE1Changing(Nullable<global::System.DateTime> value);
        partial void OnADATE1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ADATE2
        {
            get
            {
                return _ADATE2;
            }
            set
            {
                OnADATE2Changing(value);
                ReportPropertyChanging("ADATE2");
                _ADATE2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ADATE2");
                OnADATE2Changed();
            }
        }
        private Nullable<global::System.DateTime> _ADATE2;
        partial void OnADATE2Changing(Nullable<global::System.DateTime> value);
        partial void OnADATE2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RDATE1
        {
            get
            {
                return _RDATE1;
            }
            set
            {
                OnRDATE1Changing(value);
                ReportPropertyChanging("RDATE1");
                _RDATE1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RDATE1");
                OnRDATE1Changed();
            }
        }
        private Nullable<global::System.DateTime> _RDATE1;
        partial void OnRDATE1Changing(Nullable<global::System.DateTime> value);
        partial void OnRDATE1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RDATE2
        {
            get
            {
                return _RDATE2;
            }
            set
            {
                OnRDATE2Changing(value);
                ReportPropertyChanging("RDATE2");
                _RDATE2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RDATE2");
                OnRDATE2Changed();
            }
        }
        private Nullable<global::System.DateTime> _RDATE2;
        partial void OnRDATE2Changing(Nullable<global::System.DateTime> value);
        partial void OnRDATE2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CLSID
        {
            get
            {
                return _CLSID;
            }
            set
            {
                OnCLSIDChanging(value);
                ReportPropertyChanging("CLSID");
                _CLSID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLSID");
                OnCLSIDChanged();
            }
        }
        private global::System.Decimal _CLSID;
        partial void OnCLSIDChanging(global::System.Decimal value);
        partial void OnCLSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> APPROVE
        {
            get
            {
                return _APPROVE;
            }
            set
            {
                OnAPPROVEChanging(value);
                ReportPropertyChanging("APPROVE");
                _APPROVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("APPROVE");
                OnAPPROVEChanged();
            }
        }
        private Nullable<global::System.Int16> _APPROVE;
        partial void OnAPPROVEChanging(Nullable<global::System.Int16> value);
        partial void OnAPPROVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BRANCH
        {
            get
            {
                return _BRANCH;
            }
            set
            {
                OnBRANCHChanging(value);
                ReportPropertyChanging("BRANCH");
                _BRANCH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BRANCH");
                OnBRANCHChanged();
            }
        }
        private global::System.String _BRANCH;
        partial void OnBRANCHChanging(global::System.String value);
        partial void OnBRANCHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> COUNTCONN
        {
            get
            {
                return _COUNTCONN;
            }
            set
            {
                OnCOUNTCONNChanging(value);
                ReportPropertyChanging("COUNTCONN");
                _COUNTCONN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COUNTCONN");
                OnCOUNTCONNChanged();
            }
        }
        private Nullable<global::System.Int64> _COUNTCONN;
        partial void OnCOUNTCONNChanging(Nullable<global::System.Int64> value);
        partial void OnCOUNTCONNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> COUNTPASS
        {
            get
            {
                return _COUNTPASS;
            }
            set
            {
                OnCOUNTPASSChanging(value);
                ReportPropertyChanging("COUNTPASS");
                _COUNTPASS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COUNTPASS");
                OnCOUNTPASSChanged();
            }
        }
        private Nullable<global::System.Int64> _COUNTPASS;
        partial void OnCOUNTPASSChanging(Nullable<global::System.Int64> value);
        partial void OnCOUNTPASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROFILE
        {
            get
            {
                return _PROFILE;
            }
            set
            {
                OnPROFILEChanging(value);
                ReportPropertyChanging("PROFILE");
                _PROFILE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROFILE");
                OnPROFILEChanged();
            }
        }
        private global::System.String _PROFILE;
        partial void OnPROFILEChanging(global::System.String value);
        partial void OnPROFILEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 USEARC
        {
            get
            {
                return _USEARC;
            }
            set
            {
                OnUSEARCChanging(value);
                ReportPropertyChanging("USEARC");
                _USEARC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USEARC");
                OnUSEARCChanged();
            }
        }
        private global::System.Int16 _USEARC;
        partial void OnUSEARCChanging(global::System.Int16 value);
        partial void OnUSEARCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CSCHEMA
        {
            get
            {
                return _CSCHEMA;
            }
            set
            {
                OnCSCHEMAChanging(value);
                ReportPropertyChanging("CSCHEMA");
                _CSCHEMA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CSCHEMA");
                OnCSCHEMAChanged();
            }
        }
        private global::System.String _CSCHEMA;
        partial void OnCSCHEMAChanging(global::System.String value);
        partial void OnCSCHEMAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WEB_PROFILE
        {
            get
            {
                return _WEB_PROFILE;
            }
            set
            {
                OnWEB_PROFILEChanging(value);
                ReportPropertyChanging("WEB_PROFILE");
                _WEB_PROFILE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("WEB_PROFILE");
                OnWEB_PROFILEChanged();
            }
        }
        private global::System.String _WEB_PROFILE;
        partial void OnWEB_PROFILEChanging(global::System.String value);
        partial void OnWEB_PROFILEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POLICY_GROUP
        {
            get
            {
                return _POLICY_GROUP;
            }
            set
            {
                OnPOLICY_GROUPChanging(value);
                ReportPropertyChanging("POLICY_GROUP");
                _POLICY_GROUP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("POLICY_GROUP");
                OnPOLICY_GROUPChanged();
            }
        }
        private global::System.String _POLICY_GROUP;
        partial void OnPOLICY_GROUPChanging(global::System.String value);
        partial void OnPOLICY_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ACTIVE
        {
            get
            {
                return _ACTIVE;
            }
            set
            {
                OnACTIVEChanging(value);
                ReportPropertyChanging("ACTIVE");
                _ACTIVE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTIVE");
                OnACTIVEChanged();
            }
        }
        private global::System.Int16 _ACTIVE;
        partial void OnACTIVEChanging(global::System.Int16 value);
        partial void OnACTIVEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                OnCREATEDChanging(value);
                ReportPropertyChanging("CREATED");
                _CREATED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED");
                OnCREATEDChanged();
            }
        }
        private global::System.DateTime _CREATED;
        partial void OnCREATEDChanging(global::System.DateTime value);
        partial void OnCREATEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EXPIRED
        {
            get
            {
                return _EXPIRED;
            }
            set
            {
                OnEXPIREDChanging(value);
                ReportPropertyChanging("EXPIRED");
                _EXPIRED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXPIRED");
                OnEXPIREDChanged();
            }
        }
        private Nullable<global::System.DateTime> _EXPIRED;
        partial void OnEXPIREDChanging(Nullable<global::System.DateTime> value);
        partial void OnEXPIREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHKSUM
        {
            get
            {
                return _CHKSUM;
            }
            set
            {
                OnCHKSUMChanging(value);
                ReportPropertyChanging("CHKSUM");
                _CHKSUM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHKSUM");
                OnCHKSUMChanged();
            }
        }
        private global::System.String _CHKSUM;
        partial void OnCHKSUMChanging(global::System.String value);
        partial void OnCHKSUMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 USEGTW
        {
            get
            {
                return _USEGTW;
            }
            set
            {
                OnUSEGTWChanging(value);
                ReportPropertyChanging("USEGTW");
                _USEGTW = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USEGTW");
                OnUSEGTWChanged();
            }
        }
        private global::System.Int16 _USEGTW;
        partial void OnUSEGTWChanging(global::System.Int16 value);
        partial void OnUSEGTWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BLK
        {
            get
            {
                return _BLK;
            }
            set
            {
                OnBLKChanging(value);
                ReportPropertyChanging("BLK");
                _BLK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BLK");
                OnBLKChanged();
            }
        }
        private global::System.String _BLK;
        partial void OnBLKChanging(global::System.String value);
        partial void OnBLKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TBLK
        {
            get
            {
                return _TBLK;
            }
            set
            {
                OnTBLKChanging(value);
                ReportPropertyChanging("TBLK");
                _TBLK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TBLK");
                OnTBLKChanged();
            }
        }
        private Nullable<global::System.DateTime> _TBLK;
        partial void OnTBLKChanging(Nullable<global::System.DateTime> value);
        partial void OnTBLKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TEMPL_ID
        {
            get
            {
                return _TEMPL_ID;
            }
            set
            {
                OnTEMPL_IDChanging(value);
                ReportPropertyChanging("TEMPL_ID");
                _TEMPL_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TEMPL_ID");
                OnTEMPL_IDChanged();
            }
        }
        private global::System.Decimal _TEMPL_ID;
        partial void OnTEMPL_IDChanging(global::System.Decimal value);
        partial void OnTEMPL_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CAN_SELECT_BRANCH
        {
            get
            {
                return _CAN_SELECT_BRANCH;
            }
            set
            {
                OnCAN_SELECT_BRANCHChanging(value);
                ReportPropertyChanging("CAN_SELECT_BRANCH");
                _CAN_SELECT_BRANCH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CAN_SELECT_BRANCH");
                OnCAN_SELECT_BRANCHChanged();
            }
        }
        private global::System.String _CAN_SELECT_BRANCH;
        partial void OnCAN_SELECT_BRANCHChanging(global::System.String value);
        partial void OnCAN_SELECT_BRANCHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHGPWD
        {
            get
            {
                return _CHGPWD;
            }
            set
            {
                OnCHGPWDChanging(value);
                ReportPropertyChanging("CHGPWD");
                _CHGPWD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHGPWD");
                OnCHGPWDChanged();
            }
        }
        private global::System.String _CHGPWD;
        partial void OnCHGPWDChanging(global::System.String value);
        partial void OnCHGPWDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TIP
        {
            get
            {
                return _TIP;
            }
            set
            {
                OnTIPChanging(value);
                ReportPropertyChanging("TIP");
                _TIP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIP");
                OnTIPChanged();
            }
        }
        private Nullable<global::System.Decimal> _TIP;
        partial void OnTIPChanging(Nullable<global::System.Decimal> value);
        partial void OnTIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CURRENT_BRANCH
        {
            get
            {
                return _CURRENT_BRANCH;
            }
            set
            {
                OnCURRENT_BRANCHChanging(value);
                ReportPropertyChanging("CURRENT_BRANCH");
                _CURRENT_BRANCH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CURRENT_BRANCH");
                OnCURRENT_BRANCHChanged();
            }
        }
        private global::System.String _CURRENT_BRANCH;
        partial void OnCURRENT_BRANCHChanging(global::System.String value);
        partial void OnCURRENT_BRANCHChanged();

        #endregion

    
    }

    #endregion

    
}
