MERGE INTO BARS.PARAMS$GLOBAL A USING
 (SELECT
  'EWAEMAIL' as PAR,
  'bars@unity-bars.com' as VAL,
  'Логин користувача EWA' as COMM,
  0 as SRV_FLAG
  FROM DUAL) B
ON (A.PAR = B.PAR)
WHEN NOT MATCHED THEN 
INSERT (
  PAR, VAL, COMM, SRV_FLAG)
VALUES (
  B.PAR, B.VAL, B.COMM, B.SRV_FLAG)
WHEN MATCHED THEN
UPDATE SET 
  A.VAL = B.VAL,
  A.COMM = B.COMM,
  A.SRV_FLAG = B.SRV_FLAG;

MERGE INTO BARS.PARAMS$GLOBAL A USING
 (SELECT
  'EWAHASH' as PAR,
  '3f2774623a1e0aec808df1ba3000fdc679c6693b' as VAL,
  'Хеш пароля' as COMM,
  0 as SRV_FLAG
  FROM DUAL) B
ON (A.PAR = B.PAR)
WHEN NOT MATCHED THEN 
INSERT (
  PAR, VAL, COMM, SRV_FLAG)
VALUES (
  B.PAR, B.VAL, B.COMM, B.SRV_FLAG)
WHEN MATCHED THEN
UPDATE SET 
  A.VAL = B.VAL,
  A.COMM = B.COMM,
  A.SRV_FLAG = B.SRV_FLAG;

MERGE INTO BARS.PARAMS$GLOBAL A USING
 (SELECT
  'EWAID' as PAR,
  '43' as VAL,
  'Код технічного користувача' as COMM,
  0 as SRV_FLAG
  FROM DUAL) B
ON (A.PAR = B.PAR)
WHEN NOT MATCHED THEN 
INSERT (
  PAR, VAL, COMM, SRV_FLAG)
VALUES (
  B.PAR, B.VAL, B.COMM, B.SRV_FLAG)
WHEN MATCHED THEN
UPDATE SET 
  A.VAL = B.VAL,
  A.COMM = B.COMM,
  A.SRV_FLAG = B.SRV_FLAG;

MERGE INTO BARS.PARAMS$GLOBAL A USING
 (SELECT
  'EWAURL' as PAR,
  'https://oschadbank.ewa.ua/ewa/api/v2/' as VAL,
  'Адреса сервісів ПЗ EWA' as COMM,
  0 as SRV_FLAG
  FROM DUAL) B
ON (A.PAR = B.PAR)
WHEN NOT MATCHED THEN 
INSERT (
  PAR, VAL, COMM, SRV_FLAG)
VALUES (
  B.PAR, B.VAL, B.COMM, B.SRV_FLAG)
WHEN MATCHED THEN
UPDATE SET 
  A.VAL = B.VAL,
  A.COMM = B.COMM,
  A.SRV_FLAG = B.SRV_FLAG;

COMMIT;
