MERGE INTO BARS.SPPI A USING
 (SELECT
  'Так' as SPPI_ID,
  'Відповідність критерію SPPI («Пройдено»)' as SPPI_NAME,
  1 as SPPI_VALUE
  FROM DUAL) B
ON (A.SPPI_ID = B.SPPI_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SPPI_ID, SPPI_NAME, SPPI_VALUE)
VALUES (
  B.SPPI_ID, B.SPPI_NAME, B.SPPI_VALUE)
WHEN MATCHED THEN
UPDATE SET 
  A.SPPI_NAME = B.SPPI_NAME,
  A.SPPI_VALUE = B.SPPI_VALUE;

MERGE INTO BARS.SPPI A USING
 (SELECT
  'Ні' as SPPI_ID,
  'Відповідність критерію SPPI («Не пройдено»)' as SPPI_NAME,
  0 as SPPI_VALUE
  FROM DUAL) B
ON (A.SPPI_ID = B.SPPI_ID)
WHEN NOT MATCHED THEN 
INSERT (
  SPPI_ID, SPPI_NAME, SPPI_VALUE)
VALUES (
  B.SPPI_ID, B.SPPI_NAME, B.SPPI_VALUE)
WHEN MATCHED THEN
UPDATE SET 
  A.SPPI_NAME = B.SPPI_NAME,
  A.SPPI_VALUE = B.SPPI_VALUE;

COMMIT;
