

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_GARANTEE_INSURANCES.sql =====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_WCS_GARANTEE_INSURANCES ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_WCS_GARANTEE_INSURANCES ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_WCS_GARANTEE_INSURANCES 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	GARANTEE_ID VARCHAR2(4000), 
	INSURANCE_ID VARCHAR2(4000), 
	IS_REQUIRED VARCHAR2(4000), 
	ORD VARCHAR2(4000), 
	WS_QID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_WCS_GARANTEE_INSURANCES ***
 exec bpa.alter_policies('ERR$_WCS_GARANTEE_INSURANCES');


COMMENT ON TABLE BARS.ERR$_WCS_GARANTEE_INSURANCES IS 'DML Error Logging table for "WCS_GARANTEE_INSURANCES"';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.GARANTEE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.INSURANCE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.IS_REQUIRED IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.ORD IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_GARANTEE_INSURANCES.WS_QID IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_GARANTEE_INSURANCES.sql =====
PROMPT ===================================================================================== 
