

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_SCORING_QS_MATRIX.sql =======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_WCS_SCORING_QS_MATRIX ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_WCS_SCORING_QS_MATRIX ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_WCS_SCORING_QS_MATRIX 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	SCORING_ID VARCHAR2(4000), 
	QUESTION_ID VARCHAR2(4000), 
	SCORE VARCHAR2(4000), 
	AXIS0_ORD VARCHAR2(4000), 
	AXIS1_ORD VARCHAR2(4000), 
	AXIS2_ORD VARCHAR2(4000), 
	AXIS3_ORD VARCHAR2(4000), 
	AXIS4_ORD VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_WCS_SCORING_QS_MATRIX ***
 exec bpa.alter_policies('ERR$_WCS_SCORING_QS_MATRIX');


COMMENT ON TABLE BARS.ERR$_WCS_SCORING_QS_MATRIX IS 'DML Error Logging table for "WCS_SCORING_QS_MATRIX"';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.SCORING_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.QUESTION_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.SCORE IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.AXIS0_ORD IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.AXIS1_ORD IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.AXIS2_ORD IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.AXIS3_ORD IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SCORING_QS_MATRIX.AXIS4_ORD IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_SCORING_QS_MATRIX.sql =======
PROMPT ===================================================================================== 
