

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/OPER.sql =========*** Run *** ========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to OPER ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''OPER'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''OPER'', ''WHOLE'' , null, ''E'', ''E'', ''E'');
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table OPER ***
begin 
  execute immediate '
  CREATE TABLE BARS.OPER 
   (	REF NUMBER(38,0), 
	DEAL_TAG NUMBER(38,0), 
	TT CHAR(3), 
	VOB NUMBER(38,0), 
	ND VARCHAR2(10), 
	PDAT DATE DEFAULT SYSDATE, 
	VDAT DATE DEFAULT SYSDATE, 
	KV NUMBER(3,0), 
	DK NUMBER(1,0), 
	S NUMBER(24,0), 
	SQ NUMBER(24,0), 
	SK NUMBER(2,0), 
	DATD DATE, 
	DATP DATE, 
	NAM_A VARCHAR2(38), 
	NLSA VARCHAR2(15), 
	MFOA VARCHAR2(12), 
	NAM_B VARCHAR2(38), 
	NLSB VARCHAR2(15), 
	MFOB VARCHAR2(12), 
	NAZN VARCHAR2(160), 
	D_REC VARCHAR2(60), 
	ID_A VARCHAR2(14), 
	ID_B VARCHAR2(14), 
	ID_O VARCHAR2(6), 
	SIGN RAW(128), 
	SOS NUMBER(2,0) DEFAULT 0, 
	VP NUMBER(1,0), 
	CHK CHAR(70), 
	S2 NUMBER(24,0), 
	KV2 NUMBER(3,0), 
	KVQ NUMBER(3,0), 
	REFL NUMBER(38,0), 
	PRTY NUMBER(1,0), 
	SQ2 NUMBER(24,0), 
	CURRVISAGRP VARCHAR2(4), 
	NEXTVISAGRP VARCHAR2(4), 
	REF_A VARCHAR2(9), 
	TOBO VARCHAR2(30) DEFAULT sys_context(''bars_context'',''user_branch''), 
	OTM NUMBER(1,0) DEFAULT NULL, 
	SIGNED CHAR(1), 
	BRANCH VARCHAR2(30) DEFAULT sys_context(''bars_context'',''user_branch''), 
	USERID NUMBER(38,0), 
	RESPID NUMBER, 
	KF VARCHAR2(6) DEFAULT sys_context(''bars_context'',''user_mfo''), 
	BIS NUMBER(*,0), 
	SOS_TRACKER NUMBER(*,0), 
	NEXT_VISA_BRANCHES VARCHAR2(128), 
	SOS_CHANGE_TIME DATE, 
	ODAT DATE, 
	BDAT DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255  LOGGING 
  TABLESPACE BRSOPLDOK2006D 
  PARTITION BY RANGE (PDAT) 
 (PARTITION OPER_Y2009_Q1  VALUES LESS THAN (TO_DATE('' 2009-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2009_Q2  VALUES LESS THAN (TO_DATE('' 2009-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2009_Q3  VALUES LESS THAN (TO_DATE('' 2009-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2009_Q4  VALUES LESS THAN (TO_DATE('' 2010-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2010_Q1  VALUES LESS THAN (TO_DATE('' 2010-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2010_Q2  VALUES LESS THAN (TO_DATE('' 2010-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2010_Q3  VALUES LESS THAN (TO_DATE('' 2010-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2010_Q4  VALUES LESS THAN (TO_DATE('' 2011-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2011_Q1  VALUES LESS THAN (TO_DATE('' 2011-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2011_Q2  VALUES LESS THAN (TO_DATE('' 2011-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2011_Q3  VALUES LESS THAN (TO_DATE('' 2011-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2011_Q4  VALUES LESS THAN (TO_DATE('' 2012-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2012_Q1  VALUES LESS THAN (TO_DATE('' 2012-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2012_Q2  VALUES LESS THAN (TO_DATE('' 2012-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2012_Q3  VALUES LESS THAN (TO_DATE('' 2012-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2012_Q4  VALUES LESS THAN (TO_DATE('' 2013-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2013_Q1  VALUES LESS THAN (TO_DATE('' 2013-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2013_Q2  VALUES LESS THAN (TO_DATE('' 2013-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2013_Q3  VALUES LESS THAN (TO_DATE('' 2013-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2013_Q4  VALUES LESS THAN (TO_DATE('' 2014-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2014_Q1  VALUES LESS THAN (TO_DATE('' 2014-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2014_Q2  VALUES LESS THAN (TO_DATE('' 2014-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2014_Q3  VALUES LESS THAN (TO_DATE('' 2014-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2014_Q4  VALUES LESS THAN (TO_DATE('' 2015-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2015_Q1  VALUES LESS THAN (TO_DATE('' 2015-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2015_Q2  VALUES LESS THAN (TO_DATE('' 2015-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2015_Q3  VALUES LESS THAN (TO_DATE('' 2015-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2015_Q4  VALUES LESS THAN (TO_DATE('' 2016-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2016_Q1  VALUES LESS THAN (TO_DATE('' 2016-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2016_Q2  VALUES LESS THAN (TO_DATE('' 2016-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2016_Q3  VALUES LESS THAN (TO_DATE('' 2016-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2016_Q4  VALUES LESS THAN (TO_DATE('' 2017-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2017_Q1  VALUES LESS THAN (TO_DATE('' 2017-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2017D , 
 PARTITION OPER_Y2017_Q2  VALUES LESS THAN (TO_DATE('' 2017-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2017D , 
 PARTITION OPER_Y2017_Q3  VALUES LESS THAN (TO_DATE('' 2017-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2017D , 
 PARTITION OPER_Y2017_Q4  VALUES LESS THAN (TO_DATE('' 2018-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPER2017D )  ENABLE ROW MOVEMENT ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to OPER ***
 exec bpa.alter_policies('OPER');


COMMENT ON TABLE BARS.OPER IS 'Главное хранилище банковских документов';
COMMENT ON COLUMN BARS.OPER.SOS_CHANGE_TIME IS '';
COMMENT ON COLUMN BARS.OPER.ODAT IS 'Дата оплати';
COMMENT ON COLUMN BARS.OPER.BDAT IS 'Дата проведення';
COMMENT ON COLUMN BARS.OPER.REF IS 'Внутренний номер документа';
COMMENT ON COLUMN BARS.OPER.DEAL_TAG IS 'Номер сделки';
COMMENT ON COLUMN BARS.OPER.TT IS 'Тип транзакции';
COMMENT ON COLUMN BARS.OPER.VOB IS 'Вид банковского документа';
COMMENT ON COLUMN BARS.OPER.ND IS 'Номер документа';
COMMENT ON COLUMN BARS.OPER.PDAT IS 'Дата поступления';
COMMENT ON COLUMN BARS.OPER.VDAT IS 'Плановая дата валютирования';
COMMENT ON COLUMN BARS.OPER.KV IS 'Код валюты';
COMMENT ON COLUMN BARS.OPER.DK IS 'Д/К';
COMMENT ON COLUMN BARS.OPER.S IS 'Сумма';
COMMENT ON COLUMN BARS.OPER.SQ IS 'Эквивалент суммы документа';
COMMENT ON COLUMN BARS.OPER.SK IS 'Символ кассплана';
COMMENT ON COLUMN BARS.OPER.DATD IS 'Дата документа';
COMMENT ON COLUMN BARS.OPER.DATP IS 'Дата поступления';
COMMENT ON COLUMN BARS.OPER.NAM_A IS 'Наименование отправителя';
COMMENT ON COLUMN BARS.OPER.NLSA IS 'Счет отправителя';
COMMENT ON COLUMN BARS.OPER.MFOA IS 'МФО отправителя';
COMMENT ON COLUMN BARS.OPER.NAM_B IS 'Наименование получателя';
COMMENT ON COLUMN BARS.OPER.NLSB IS 'Счет получателя';
COMMENT ON COLUMN BARS.OPER.BIS IS 'Флаг БИС';
COMMENT ON COLUMN BARS.OPER.SOS_TRACKER IS 'Номер зміни статусу документа';
COMMENT ON COLUMN BARS.OPER.NEXT_VISA_BRANCHES IS 'Список бранчів слідуючої групи візування';
COMMENT ON COLUMN BARS.OPER.MFOB IS 'МФО получателя';
COMMENT ON COLUMN BARS.OPER.NAZN IS 'Назначение платежа';
COMMENT ON COLUMN BARS.OPER.D_REC IS 'Доп. реквизиты СЭП';
COMMENT ON COLUMN BARS.OPER.ID_A IS 'Идент. код отправителя';
COMMENT ON COLUMN BARS.OPER.ID_B IS 'Идент. код получателя';
COMMENT ON COLUMN BARS.OPER.ID_O IS 'Идентификатор ключа подписи';
COMMENT ON COLUMN BARS.OPER.SIGN IS 'Подпись';
COMMENT ON COLUMN BARS.OPER.SOS IS 'Состояние документа';
COMMENT ON COLUMN BARS.OPER.VP IS '';
COMMENT ON COLUMN BARS.OPER.CHK IS 'подпись (Виза)';
COMMENT ON COLUMN BARS.OPER.S2 IS 'Сумма документа 2';
COMMENT ON COLUMN BARS.OPER.KV2 IS 'Код валюты 2';
COMMENT ON COLUMN BARS.OPER.KVQ IS 'Код валюты эквивалент';
COMMENT ON COLUMN BARS.OPER.REFL IS 'Реф. связанного документа';
COMMENT ON COLUMN BARS.OPER.PRTY IS 'Приоритет документа';
COMMENT ON COLUMN BARS.OPER.SQ2 IS 'Эквивалент суммы 2 документа';
COMMENT ON COLUMN BARS.OPER.CURRVISAGRP IS 'Текущая группа контроля';
COMMENT ON COLUMN BARS.OPER.NEXTVISAGRP IS 'След. группа контроля';
COMMENT ON COLUMN BARS.OPER.REF_A IS 'Референция отправителя';
COMMENT ON COLUMN BARS.OPER.TOBO IS 'Код безбалансового отделения';
COMMENT ON COLUMN BARS.OPER.OTM IS 'Отметка об оплате документа между подразделениями';
COMMENT ON COLUMN BARS.OPER.SIGNED IS 'Признак подписанного документа. NULL-ЭЦП(внутр) отсутствует."Y"-присутствует.';
COMMENT ON COLUMN BARS.OPER.BRANCH IS 'Код безбалансового отделения, в котором документ создан';
COMMENT ON COLUMN BARS.OPER.USERID IS '';
COMMENT ON COLUMN BARS.OPER.RESPID IS 'Віповідальний виконавець';
COMMENT ON COLUMN BARS.OPER.KF IS '';




PROMPT *** Create  constraint FK_OPER_TOBO ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_TOBO FOREIGN KEY (TOBO)
	  REFERENCES BARS.BRANCH (BRANCH) DEFERRABLE ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_OPER ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_OPER FOREIGN KEY (KF, REFL)
	  REFERENCES BARS.OPER (KF, REF) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_KF ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_KF FOREIGN KEY (KF)
	  REFERENCES BARS.BANKS$BASE (MFO) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_BRANCH3 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_BRANCH3 FOREIGN KEY (BRANCH)
	  REFERENCES BARS.BRANCH (BRANCH) DEFERRABLE ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_VOB ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_VOB FOREIGN KEY (VOB)
	  REFERENCES BARS.VOB (VOB) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_TTS ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_TTS FOREIGN KEY (TT)
	  REFERENCES BARS.TTS (TT) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_BANKS ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_BANKS FOREIGN KEY (MFOB)
	  REFERENCES BARS.BANKS$BASE (MFO) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_BANKS2 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_BANKS2 FOREIGN KEY (MFOA)
	  REFERENCES BARS.BANKS$BASE (MFO) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_TABVAL3 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_TABVAL3 FOREIGN KEY (KVQ)
	  REFERENCES BARS.TABVAL$GLOBAL (KV) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_TABVAL ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_TABVAL FOREIGN KEY (KV)
	  REFERENCES BARS.TABVAL$GLOBAL (KV) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_TABVAL2 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_TABVAL2 FOREIGN KEY (KV2)
	  REFERENCES BARS.TABVAL$GLOBAL (KV) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_DK ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_DK FOREIGN KEY (DK)
	  REFERENCES BARS.DK (DK) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_SK ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_SK FOREIGN KEY (SK)
	  REFERENCES BARS.SK (SK) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPER_OPSOS ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT FK_OPER_OPSOS FOREIGN KEY (SOS)
	  REFERENCES BARS.OP_SOS (SOS) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint UK_OPER ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT UK_OPER UNIQUE (KF, REF)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPERI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_BRANCH_CC2 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT CC_OPER_BRANCH_CC2 CHECK (branch like ''/''||kf||''/%'') ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_BRANCH_CC ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT CC_OPER_BRANCH_CC CHECK (branch<>''/'') ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_OTM ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT CC_OPER_OTM CHECK (otm in (0,1,-1,-2)) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_OPER ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT PK_OPER PRIMARY KEY (REF)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPERI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_DK ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT CC_OPER_DK CHECK (dk in (0, 1, 2, 3)) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (KF CONSTRAINT CC_OPER_KF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_BRANCH_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (BRANCH CONSTRAINT CC_OPER_BRANCH_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_TOBO_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (TOBO CONSTRAINT CC_OPER_TOBO_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_VDAT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (VDAT CONSTRAINT CC_OPER_VDAT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_PDAT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (PDAT CONSTRAINT CC_OPER_PDAT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_TT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (TT CONSTRAINT CC_OPER_TT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_REF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (REF CONSTRAINT CC_OPER_REF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_SOSCHTIME_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (SOS_CHANGE_TIME CONSTRAINT CC_OPER_SOSCHTIME_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_SOSTRACKER_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER MODIFY (SOS_TRACKER CONSTRAINT CC_OPER_SOSTRACKER_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPER_BRANCH_TOBO_CC ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPER ADD CONSTRAINT CC_OPER_BRANCH_TOBO_CC CHECK (branch=tobo) DEFERRABLE ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_OPER_REF_A ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OPER_REF_A ON BARS.OPER (REF_A) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255  LOCAL
 (PARTITION OPER_Y2009_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2009_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2009_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2009_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2009D , 
 PARTITION OPER_Y2010_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2010_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2010_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2010_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010D , 
 PARTITION OPER_Y2011_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2011_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2011_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2011_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011D , 
 PARTITION OPER_Y2012_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2012_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2012_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2012_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012D , 
 PARTITION OPER_Y2013_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2013_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2013_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2013_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013D , 
 PARTITION OPER_Y2014_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2014_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2014_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2014_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014D , 
 PARTITION OPER_Y2015_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2015_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2015_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2015_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015D , 
 PARTITION OPER_Y2016_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2016_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2016_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2016_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016D , 
 PARTITION OPER_Y2017_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017D , 
 PARTITION OPER_Y2017_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017D , 
 PARTITION OPER_Y2017_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017D , 
 PARTITION OPER_Y2017_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017D ) ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_PDAT_OPER ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_PDAT_OPER ON BARS.OPER (PDAT) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255  LOGGING 
  TABLESPACE BRSOPERI  LOCAL
 (PARTITION OPER_Y2009_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPERI , 
 PARTITION OPER_Y2009_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPERI , 
 PARTITION OPER_Y2009_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPERI , 
 PARTITION OPER_Y2009_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPERI , 
 PARTITION OPER_Y2010_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010I , 
 PARTITION OPER_Y2010_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010I , 
 PARTITION OPER_Y2010_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010I , 
 PARTITION OPER_Y2010_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2010I , 
 PARTITION OPER_Y2011_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011I , 
 PARTITION OPER_Y2011_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011I , 
 PARTITION OPER_Y2011_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011I , 
 PARTITION OPER_Y2011_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2011I , 
 PARTITION OPER_Y2012_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012I , 
 PARTITION OPER_Y2012_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012I , 
 PARTITION OPER_Y2012_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012I , 
 PARTITION OPER_Y2012_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2012I , 
 PARTITION OPER_Y2013_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013I , 
 PARTITION OPER_Y2013_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013I , 
 PARTITION OPER_Y2013_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013I , 
 PARTITION OPER_Y2013_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2013I , 
 PARTITION OPER_Y2014_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014I , 
 PARTITION OPER_Y2014_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014I , 
 PARTITION OPER_Y2014_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014I , 
 PARTITION OPER_Y2014_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2014I , 
 PARTITION OPER_Y2015_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015I , 
 PARTITION OPER_Y2015_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015I , 
 PARTITION OPER_Y2015_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015I , 
 PARTITION OPER_Y2015_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2015I , 
 PARTITION OPER_Y2016_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016I , 
 PARTITION OPER_Y2016_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016I , 
 PARTITION OPER_Y2016_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016I , 
 PARTITION OPER_Y2016_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2016I , 
 PARTITION OPER_Y2017_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017I , 
 PARTITION OPER_Y2017_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017I , 
 PARTITION OPER_Y2017_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017I , 
 PARTITION OPER_Y2017_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPER2017I ) ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_VDAT_OPER ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_VDAT_OPER ON BARS.OPER (VDAT) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS 1 
  TABLESPACE BRSOPERI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_REFL_OPER ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_REFL_OPER ON BARS.OPER (REFL) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPERI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_OPER ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_OPER ON BARS.OPER (REF) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPERI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_OPER ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_OPER ON BARS.OPER (KF, REF) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPERI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  OPER ***
grant DELETE,INSERT,SELECT,UPDATE                                            on OPER            to ABS_ADMIN;
grant ALTER,DEBUG,DELETE,FLASHBACK,INSERT,ON COMMIT REFRESH,QUERY REWRITE,SELECT,UPDATE on OPER            to BARS009;
grant UPDATE                                                                 on OPER            to BARS010;
grant UPDATE                                                                 on OPER            to BARS014;
grant FLASHBACK,REFERENCES,SELECT,UPDATE                                     on OPER            to BARSAQ with grant option;
grant REFERENCES,SELECT,UPDATE                                               on OPER            to BARSAQ_ADM with grant option;
grant SELECT                                                                 on OPER            to BARSUPL;
grant ALTER,DELETE,INSERT,SELECT,UPDATE                                      on OPER            to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on OPER            to BARS_DM;
grant SELECT                                                                 on OPER            to BARS_SUP;
grant SELECT,UPDATE                                                          on OPER            to CHCK;
grant UPDATE                                                                 on OPER            to CP_ROLE;
grant SELECT                                                                 on OPER            to DEP_SKRN;
grant INSERT,SELECT                                                          on OPER            to DPT_ROLE;
grant SELECT                                                                 on OPER            to FINMON;
grant SELECT                                                                 on OPER            to FINMON01;
grant UPDATE                                                                 on OPER            to FOREX;
grant SELECT                                                                 on OPER            to JBOSS_USR;
grant SELECT                                                                 on OPER            to OBPC;
grant UPDATE                                                                 on OPER            to OPER000;
grant INSERT,UPDATE                                                          on OPER            to OPERKKK;
grant SELECT                                                                 on OPER            to OW;
grant UPDATE                                                                 on OPER            to PYOD001;
grant ALTER,DELETE,INSERT,SELECT,UPDATE                                      on OPER            to RCC_DEAL;
grant SELECT                                                                 on OPER            to RPBN001;
grant SELECT                                                                 on OPER            to RPBN002;
grant SELECT,UPDATE                                                          on OPER            to START1;
grant SELECT                                                                 on OPER            to TASK_LIST;
grant SELECT                                                                 on OPER            to TECH004;
grant UPDATE                                                                 on OPER            to TECH005;
grant ALTER,DEBUG,DELETE,FLASHBACK,INSERT,ON COMMIT REFRESH,QUERY REWRITE,SELECT,UPDATE on OPER            to TEST;
grant ALTER,DEBUG,DELETE,FLASHBACK,INSERT,ON COMMIT REFRESH,QUERY REWRITE,SELECT,UPDATE on OPER            to TEST2;
grant SELECT                                                                 on OPER            to TOSS;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on OPER            to WR_ALL_RIGHTS;
grant SELECT                                                                 on OPER            to WR_CUSTLIST;
grant SELECT                                                                 on OPER            to WR_DEPOSIT_U;
grant SELECT                                                                 on OPER            to WR_DOCVIEW;
grant SELECT                                                                 on OPER            to WR_ND_ACCOUNTS;
grant SELECT                                                                 on OPER            to WR_TOBO_ACCOUNTS_LIST;
grant SELECT                                                                 on OPER            to WR_USER_ACCOUNTS_LIST;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/OPER.sql =========*** End *** ========
PROMPT ===================================================================================== 
