

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/S6_S6_VID_CONTRACT.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to S6_S6_VID_CONTRACT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table S6_S6_VID_CONTRACT ***
begin 
  execute immediate '
  CREATE TABLE BARS.S6_S6_VID_CONTRACT 
   (	ID NUMBER(11,0), 
	NAME VARCHAR2(80), 
	TARGET NUMBER(11,0), 
	STRPERCEN NUMBER(11,0), 
	D_RETURN NUMBER(11,0), 
	D_DIST NUMBER(11,0), 
	VID_KRED NUMBER(11,0), 
	V_MAIN NUMBER(11,0), 
	N_PROLONG NUMBER(11,0), 
	C_RISK NUMBER(11,0), 
	EMITENT NUMBER(11,0), 
	EMIS NUMBER(11,0), 
	PAPER NUMBER(11,0), 
	QUOT NUMBER(11,0), 
	TERM NUMBER(11,0), 
	T_KR NUMBER(11,0), 
	PROLONG NUMBER(11,0), 
	SOURCE NUMBER(11,0), 
	PERREP NUMBER(11,0), 
	N_APPL NUMBER(11,0), 
	D_APPL NUMBER(11,0), 
	N_DCC NUMBER(11,0), 
	D_DCC NUMBER(11,0), 
	NAM_TXT_DO VARCHAR2(25), 
	D_BEGIN NUMBER(11,0), 
	D_CANCEL NUMBER(11,0), 
	V_PLEDGE NUMBER(11,0), 
	PREFIX VARCHAR2(10), 
	CONTRPAREN NUMBER(11,0), 
	STATUS NUMBER(11,0), 
	SUMMA NUMBER(11,0), 
	I_VA NUMBER(11,0), 
	DF__TARGET NUMBER(11,0), 
	DF__STRPER NUMBER(11,4), 
	DF__I_VA NUMBER(11,0), 
	DF__VID_KR NUMBER(11,0), 
	DF__V_MAIN NUMBER(11,0), 
	DF__N_PROL NUMBER(11,0), 
	DF__C_RISK NUMBER(11,0), 
	DF__EMITEN NUMBER(11,0), 
	DF__EMIS NUMBER(11,0), 
	DF__PAPER VARCHAR2(2), 
	DF__QUOT NUMBER(11,0), 
	DF__TERM VARCHAR2(1), 
	DF__T_KR NUMBER(11,0), 
	DF__PROLON VARCHAR2(1), 
	DF__SOURCE NUMBER(11,0), 
	DF__PERREP NUMBER(11,0), 
	DF__N_APPL VARCHAR2(20), 
	DF__N_DCC VARCHAR2(20), 
	EVENTLIST VARCHAR2(150), 
	METHODLIST CLOB, 
	JURIDNUMBE NUMBER(11,0), 
	DF_JURIDNU VARCHAR2(40), 
	EXCEPTAUTO NUMBER(11,0), 
	METHODCI NUMBER(11,0), 
	DF__METHOD NUMBER(11,0), 
	PERIODPR NUMBER(11,0), 
	DF__PERIOD NUMBER(11,0), 
	GENNUM NUMBER(11,0), 
	EKOLVL NUMBER(11,0), 
	CONTRLIMIT NUMBER(11,0), 
	VIDGRAF CLOB, 
	EXCEPTAUT2 NUMBER(11,0), 
	EFFECTPRC NUMBER(11,0), 
	ETALONPRC NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND 
 LOB (METHODLIST) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB (VIDGRAF) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to S6_S6_VID_CONTRACT ***
 exec bpa.alter_policies('S6_S6_VID_CONTRACT');


COMMENT ON TABLE BARS.S6_S6_VID_CONTRACT IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.ID IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.NAME IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.TARGET IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.STRPERCEN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.D_RETURN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.D_DIST IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.VID_KRED IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.V_MAIN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.N_PROLONG IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.C_RISK IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EMITENT IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EMIS IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.PAPER IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.QUOT IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.TERM IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.T_KR IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.PROLONG IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.SOURCE IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.PERREP IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.N_APPL IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.D_APPL IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.N_DCC IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.D_DCC IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.NAM_TXT_DO IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.D_BEGIN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.D_CANCEL IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.V_PLEDGE IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.PREFIX IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.CONTRPAREN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.STATUS IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.SUMMA IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.I_VA IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__TARGET IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__STRPER IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__I_VA IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__VID_KR IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__V_MAIN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__N_PROL IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__C_RISK IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__EMITEN IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__EMIS IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__PAPER IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__QUOT IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__TERM IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__T_KR IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__PROLON IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__SOURCE IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__PERREP IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__N_APPL IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__N_DCC IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EVENTLIST IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.METHODLIST IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.JURIDNUMBE IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF_JURIDNU IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EXCEPTAUTO IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.METHODCI IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__METHOD IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.PERIODPR IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.DF__PERIOD IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.GENNUM IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EKOLVL IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.CONTRLIMIT IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.VIDGRAF IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EXCEPTAUT2 IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.EFFECTPRC IS '';
COMMENT ON COLUMN BARS.S6_S6_VID_CONTRACT.ETALONPRC IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/S6_S6_VID_CONTRACT.sql =========*** En
PROMPT ===================================================================================== 
