

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/S6_S6_USERS.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to S6_S6_USERS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table S6_S6_USERS ***
begin 
  execute immediate '
  CREATE TABLE BARS.S6_S6_USERS 
   (	ISP NUMBER(11,0), 
	FIO VARCHAR2(40), 
	LOGIN VARCHAR2(30), 
	HOST VARCHAR2(30), 
	PASSWORD VARCHAR2(16), 
	D_OD DATE, 
	PR_END NUMBER(1,0), 
	PR_ACT NUMBER(1,0), 
	PR_PERMIT NUMBER(1,0), 
	IKEY VARCHAR2(8), 
	SIGN_TYPE NUMBER(11,0), 
	DEV_TYPE NUMBER(11,0), 
	ACCESS CLOB, 
	PR_LPMB NUMBER(1,0), 
	PR_HOST NUMBER(1,0), 
	TM_ID VARCHAR2(16), 
	TM_ADAPT NUMBER(11,0), 
	TM_TYPE NUMBER(11,0), 
	PASSWORDEN DATE, 
	PASSWORDAD NUMBER(11,0), 
	PASSWORDTE NUMBER(11,0), 
	BIC NUMBER(11,0), 
	DEPART NUMBER(11,0), 
	DISTRSGN NUMBER(11,0), 
	EMAIL VARCHAR2(20), 
	PHONE VARCHAR2(20), 
	REGIMEBEG VARCHAR2(5), 
	REGIMEEND VARCHAR2(5), 
	ADMKEY VARCHAR2(8), 
	ADMEP VARCHAR2(180)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND 
 LOB (ACCESS) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to S6_S6_USERS ***
 exec bpa.alter_policies('S6_S6_USERS');


COMMENT ON TABLE BARS.S6_S6_USERS IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.ISP IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.FIO IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.LOGIN IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.HOST IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PASSWORD IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.D_OD IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PR_END IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PR_ACT IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PR_PERMIT IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.IKEY IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.SIGN_TYPE IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.DEV_TYPE IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.ACCESS IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PR_LPMB IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PR_HOST IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.TM_ID IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.TM_ADAPT IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.TM_TYPE IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PASSWORDEN IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PASSWORDAD IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PASSWORDTE IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.BIC IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.DEPART IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.DISTRSGN IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.EMAIL IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.PHONE IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.REGIMEBEG IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.REGIMEEND IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.ADMKEY IS '';
COMMENT ON COLUMN BARS.S6_S6_USERS.ADMEP IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/S6_S6_USERS.sql =========*** End *** =
PROMPT ===================================================================================== 
