

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/S6_S6_CLIENTS.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to S6_S6_CLIENTS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table S6_S6_CLIENTS ***
begin 
  execute immediate '
  CREATE TABLE BARS.S6_S6_CLIENTS 
   (	BIC NUMBER(11,0), 
	GROUP_C NUMBER(11,0), 
	IDCLIENT NUMBER(11,0), 
	TYPECLIENT NUMBER(11,0), 
	IDCODE VARCHAR2(10), 
	NAME VARCHAR2(40), 
	KEYSEARCH VARCHAR2(40), 
	FULLNAME VARCHAR2(150), 
	REZIDENT NUMBER(11,0), 
	INSIDER NUMBER(11,0), 
	IDCOUNTRY NUMBER(11,0), 
	TINKEY NUMBER(11,0), 
	D_OPEN DATE, 
	D_CLOSE DATE, 
	ISP_OWNER NUMBER(11,0), 
	FORMXOZ NUMBER(11,0), 
	FORMPRIVAT NUMBER(11,0), 
	SECTOR VARCHAR2(5), 
	OTRASL NUMBER(11,0), 
	VIDECO NUMBER(11,0), 
	MINISTRY NUMBER(11,0), 
	CODNAL NUMBER(11,0), 
	IDREG NUMBER(11,0), 
	IDNAL NUMBER(11,0), 
	D_REGSA DATE, 
	D_REGSTI DATE, 
	BUDGET NUMBER(11,0), 
	FUND NUMBER(18,2), 
	WORKING NUMBER(11,0), 
	NUMBERADM VARCHAR2(20), 
	B010 VARCHAR2(10), 
	SEX NUMBER(11,0), 
	DATEBIRTH DATE, 
	DESCRIPTIO CLOB, 
	ADDRESS NUMBER(11,0), 
	D_MODIFY DATE, 
	IDCORPCLIE NUMBER(11,0), 
	IDCORPDEPA NUMBER(11,0), 
	SMBUSINES NUMBER(11,0), 
	DOC_MODIFY NUMBER(11,0), 
	CLINUMCODE NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND 
 LOB (DESCRIPTIO) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to S6_S6_CLIENTS ***
 exec bpa.alter_policies('S6_S6_CLIENTS');


COMMENT ON TABLE BARS.S6_S6_CLIENTS IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.BIC IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.GROUP_C IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDCLIENT IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.TYPECLIENT IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDCODE IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.NAME IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.KEYSEARCH IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.FULLNAME IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.REZIDENT IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.INSIDER IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDCOUNTRY IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.TINKEY IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.D_OPEN IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.D_CLOSE IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.ISP_OWNER IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.FORMXOZ IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.FORMPRIVAT IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.SECTOR IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.OTRASL IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.VIDECO IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.MINISTRY IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.CODNAL IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDREG IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDNAL IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.D_REGSA IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.D_REGSTI IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.BUDGET IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.FUND IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.WORKING IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.NUMBERADM IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.B010 IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.SEX IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.DATEBIRTH IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.DESCRIPTIO IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.ADDRESS IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.D_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDCORPCLIE IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.IDCORPDEPA IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.SMBUSINES IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.DOC_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_CLIENTS.CLINUMCODE IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/S6_S6_CLIENTS.sql =========*** End ***
PROMPT ===================================================================================== 
