

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/S6_S6_ADDRESSES.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to S6_S6_ADDRESSES ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table S6_S6_ADDRESSES ***
begin 
  execute immediate '
  CREATE TABLE BARS.S6_S6_ADDRESSES 
   (	BIC NUMBER(11,0), 
	ID NUMBER(11,0), 
	TYPEADDRES NUMBER(11,0), 
	POSTIND VARCHAR2(10), 
	REGION VARCHAR2(40), 
	CITY VARCHAR2(40), 
	STREET VARCHAR2(40), 
	HOUSE VARCHAR2(20), 
	APARTMENT VARCHAR2(20), 
	DESCRIPTIO VARCHAR2(200), 
	D_MODIFY DATE, 
	ISP_MODIFY NUMBER(11,0), 
	DOC_MODIFY NUMBER(11,0), 
	COUNTRY VARCHAR2(20), 
	RAYON VARCHAR2(25), 
	PHONE VARCHAR2(20), 
	FAX VARCHAR2(20), 
	MOBILE VARCHAR2(20), 
	EMAIL VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to S6_S6_ADDRESSES ***
 exec bpa.alter_policies('S6_S6_ADDRESSES');


COMMENT ON TABLE BARS.S6_S6_ADDRESSES IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.BIC IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.ID IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.TYPEADDRES IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.POSTIND IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.REGION IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.CITY IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.STREET IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.HOUSE IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.APARTMENT IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.DESCRIPTIO IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.D_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.ISP_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.DOC_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.COUNTRY IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.RAYON IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.PHONE IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.FAX IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.MOBILE IS '';
COMMENT ON COLUMN BARS.S6_S6_ADDRESSES.EMAIL IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/S6_S6_ADDRESSES.sql =========*** End *
PROMPT ===================================================================================== 
