

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_AS_ZH.sql =========*** Run *** ===
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_AS_ZH ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_AS_ZH ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_AS_ZH 
   (	TVBV CHAR(3), 
	KEY NUMBER, 
	FIO VARCHAR2(70), 
	IDCODE VARCHAR2(10), 
	DOCTYPE NUMBER(2,0), 
	PASP_S VARCHAR2(4), 
	PASP_N VARCHAR2(9), 
	PASP_W VARCHAR2(120), 
	PASP_D DATE, 
	BIRTHDAT DATE, 
	BIRTHPL VARCHAR2(120), 
	SEX NUMBER(1,0), 
	POSTIDX VARCHAR2(10), 
	REGION VARCHAR2(30), 
	DISTRICT VARCHAR2(30), 
	CITY VARCHAR2(30), 
	ADDRESS VARCHAR2(120), 
	PHONE_H VARCHAR2(20), 
	PHONE_J VARCHAR2(20), 
	LANDCOD NUMBER(5,0), 
	REGDATE DATE, 
	DEPCODE VARCHAR2(16), 
	DEPVIDNAME VARCHAR2(120), 
	ACC_CARD VARCHAR2(10), 
	DEPNAME VARCHAR2(120), 
	NLS VARCHAR2(20), 
	ID VARCHAR2(7), 
	DATO DATE, 
	OST NUMBER(16,0), 
	SUM NUMBER(16,0), 
	DATN DATE, 
	ATTR VARCHAR2(16), 
	MARK VARCHAR2(1), 
	VER NUMBER(4,0), 
	KOD_OTD VARCHAR2(10), 
	BRANCH VARCHAR2(30), 
	BSD VARCHAR2(7), 
	OB22DE VARCHAR2(2), 
	BSN VARCHAR2(7), 
	OB22IE VARCHAR2(7), 
	BSD7 VARCHAR2(7), 
	OB22D7 VARCHAR2(2), 
	FL NUMBER(*,0), 
	DZAGR DATE, 
	REF NUMBER, 
	REFOUT NUMBER, 
	REFPAY NUMBER, 
	SOURCE VARCHAR2(64), 
	KV NUMBER, 
	ND VARCHAR2(35), 
	DPTID NUMBER, 
	ERRMSG VARCHAR2(4000), 
	BATCH_ID NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_AS_ZH ***
 exec bpa.alter_policies('TMP_AS_ZH');


COMMENT ON TABLE BARS.TMP_AS_ZH IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.TVBV IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.KEY IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.FIO IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.IDCODE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DOCTYPE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.PASP_S IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.PASP_N IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.PASP_W IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.PASP_D IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BIRTHDAT IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BIRTHPL IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.SEX IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.POSTIDX IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.REGION IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DISTRICT IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.CITY IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.ADDRESS IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.PHONE_H IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.PHONE_J IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.LANDCOD IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.REGDATE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DEPCODE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DEPVIDNAME IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.ACC_CARD IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DEPNAME IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.NLS IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.ID IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DATO IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.OST IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.SUM IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DATN IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.ATTR IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.MARK IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.VER IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.KOD_OTD IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BSD IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.OB22DE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BSN IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.OB22IE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BSD7 IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.OB22D7 IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.FL IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DZAGR IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.REF IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.REFOUT IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.REFPAY IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.SOURCE IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.KV IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.ND IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.DPTID IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.ERRMSG IS '';
COMMENT ON COLUMN BARS.TMP_AS_ZH.BATCH_ID IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_AS_ZH.sql =========*** End *** ===
PROMPT ===================================================================================== 
