MERGE INTO BARS.CC_TAG A USING
 (SELECT
  'ASSET' as TAG,
  'Заміна активу' as NAME,
  'CCK' as TAGTYPE,
  'V_REPLACEMENT_ASSET' as TABLE_NAME,
  NULL as TYPE,
  NULL as NSISQLWHERE,
  NULL as EDIT_IN_FORM,
  0 as NOT_TO_EDIT,
  'ADD' as CODE
  FROM DUAL) B
ON (A.TAG = B.TAG)
WHEN NOT MATCHED THEN 
INSERT (
  TAG, NAME, TAGTYPE, TABLE_NAME, TYPE, 
  NSISQLWHERE, EDIT_IN_FORM, NOT_TO_EDIT, CODE)
VALUES (
  B.TAG, B.NAME, B.TAGTYPE, B.TABLE_NAME, B.TYPE, 
  B.NSISQLWHERE, B.EDIT_IN_FORM, B.NOT_TO_EDIT, B.CODE)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME = B.NAME,
  A.TAGTYPE = B.TAGTYPE,
  A.TABLE_NAME = B.TABLE_NAME,
  A.TYPE = B.TYPE,
  A.NSISQLWHERE = B.NSISQLWHERE,
  A.EDIT_IN_FORM = B.EDIT_IN_FORM,
  A.NOT_TO_EDIT = B.NOT_TO_EDIT,
  A.CODE = B.CODE;

COMMIT;
