MERGE INTO BARS.CCK_RESTR_VID A USING
 (SELECT
  18 as VID_RESTR,
  'заміна активу (цінні папери) внаслідок реструктуризації' as NAME_RESTR
  FROM DUAL) B
ON (A.VID_RESTR = B.VID_RESTR)
WHEN NOT MATCHED THEN 
INSERT (
  VID_RESTR, NAME_RESTR)
VALUES (
  B.VID_RESTR, B.NAME_RESTR)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME_RESTR = B.NAME_RESTR;

MERGE INTO BARS.CCK_RESTR_VID A USING
 (SELECT
  19 as VID_RESTR,
  'заміна активу (цінні папери), не пов’язана з реструктуризацією' as NAME_RESTR
  FROM DUAL) B
ON (A.VID_RESTR = B.VID_RESTR)
WHEN NOT MATCHED THEN 
INSERT (
  VID_RESTR, NAME_RESTR)
VALUES (
  B.VID_RESTR, B.NAME_RESTR)
WHEN MATCHED THEN
UPDATE SET 
  A.NAME_RESTR = B.NAME_RESTR;

COMMIT;
