begin
UPDATE  META_NSIFUNCTION T set t.web_form_name='/barsroot/CreditUi/glk/Index/?id=:ND' WHERE t.tabid=get_tabid('CC_W_LIM1_EXT') and t.funcid=15;
end;
/
commit;
begin
UPDATE  META_NSIFUNCTION T set t.proc_name='cck.cc_gpk(:GPK,pul.Get_Mas_Ini_Val (''ND''),null,null,null,null,null,null,null ,:TYPE)' WHERE t.tabid=get_tabid('CC_W_LIM1_EXT') and t.funcid=1;
end;
/
commit;
begin
  UPDATE META_NSIFUNCTION T
     set t.web_form_name = '/barsroot/CreditUi/provide/Index/?id=:ND',
     t.descr='КД: Забезпечення існуючі/нові',
	 T.PROC_EXEC='EACH'
   WHERE t.tabid = get_tabid('V_CCK_NF')
     and t.funcid = 9;
end;
/ 
commit;


/*
begin
MERGE INTO BARS.META_COLUMNS A USING
 (SELECT
  1011623 as TABID,
  2 as COLID,
  'ACCC' as COLNAME,
  'B' as COLTYPE,
  'Контроль~за недоп.~лімітом' as SEMANTIC,
  1 as SHOWWIDTH,
  NULL as SHOWMAXCHAR,
  100 as SHOWPOS,
  0 as SHOWIN_RO,
  0 as SHOWRETVAL,
  0 as INSTNSSEMANTIC,
  0 as EXTRNVAL,
  NULL as SHOWREL_CTYPE,
  NULL as SHOWFORMAT,
  0 as SHOWIN_FLTR,
  0 as SHOWREF,
  NULL as SHOWRESULT,
  NULL as CASE_SENSITIVE,
  1 as NOT_TO_EDIT,
  0 as NOT_TO_SHOW,
  0 as SIMPLE_FILTER,
  NULL as FORM_NAME,
  '/' as BRANCH,
  NULL as WEB_FORM_NAME,
  NULL as OPER_ID,
  0 as INPUT_IN_NEW_RECORD
  FROM DUAL) B
ON (A.TABID = B.TABID and A.COLID = B.COLID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, COLID, COLNAME, COLTYPE, SEMANTIC, 
  SHOWWIDTH, SHOWMAXCHAR, SHOWPOS, SHOWIN_RO, SHOWRETVAL, 
  INSTNSSEMANTIC, EXTRNVAL, SHOWREL_CTYPE, SHOWFORMAT, SHOWIN_FLTR, 
  SHOWREF, SHOWRESULT, CASE_SENSITIVE, NOT_TO_EDIT, NOT_TO_SHOW, 
  SIMPLE_FILTER, FORM_NAME, BRANCH, WEB_FORM_NAME, OPER_ID, 
  INPUT_IN_NEW_RECORD)
VALUES (
  B.TABID, B.COLID, B.COLNAME, B.COLTYPE, B.SEMANTIC, 
  B.SHOWWIDTH, B.SHOWMAXCHAR, B.SHOWPOS, B.SHOWIN_RO, B.SHOWRETVAL, 
  B.INSTNSSEMANTIC, B.EXTRNVAL, B.SHOWREL_CTYPE, B.SHOWFORMAT, B.SHOWIN_FLTR, 
  B.SHOWREF, B.SHOWRESULT, B.CASE_SENSITIVE, B.NOT_TO_EDIT, B.NOT_TO_SHOW, 
  B.SIMPLE_FILTER, B.FORM_NAME, B.BRANCH, B.WEB_FORM_NAME, B.OPER_ID, 
  B.INPUT_IN_NEW_RECORD)
WHEN MATCHED THEN
UPDATE SET 
  A.COLNAME = B.COLNAME,
  A.COLTYPE = B.COLTYPE,
  A.SEMANTIC = B.SEMANTIC,
  A.SHOWWIDTH = B.SHOWWIDTH,
  A.SHOWMAXCHAR = B.SHOWMAXCHAR,
  A.SHOWPOS = B.SHOWPOS,
  A.SHOWIN_RO = B.SHOWIN_RO,
  A.SHOWRETVAL = B.SHOWRETVAL,
  A.INSTNSSEMANTIC = B.INSTNSSEMANTIC,
  A.EXTRNVAL = B.EXTRNVAL,
  A.SHOWREL_CTYPE = B.SHOWREL_CTYPE,
  A.SHOWFORMAT = B.SHOWFORMAT,
  A.SHOWIN_FLTR = B.SHOWIN_FLTR,
  A.SHOWREF = B.SHOWREF,
  A.SHOWRESULT = B.SHOWRESULT,
  A.CASE_SENSITIVE = B.CASE_SENSITIVE,
  A.NOT_TO_EDIT = B.NOT_TO_EDIT,
  A.NOT_TO_SHOW = B.NOT_TO_SHOW,
  A.SIMPLE_FILTER = B.SIMPLE_FILTER,
  A.FORM_NAME = B.FORM_NAME,
  A.BRANCH = B.BRANCH,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.OPER_ID = B.OPER_ID,
  A.INPUT_IN_NEW_RECORD = B.INPUT_IN_NEW_RECORD;

MERGE INTO BARS.META_COLUMNS A USING
 (SELECT
  1011623 as TABID,
  3 as COLID,
  'BASEM' as COLNAME,
  'B' as COLTYPE,
  'Новий~ануїтет' as SEMANTIC,
  0.7 as SHOWWIDTH,
  NULL as SHOWMAXCHAR,
  101 as SHOWPOS,
  0 as SHOWIN_RO,
  0 as SHOWRETVAL,
  0 as INSTNSSEMANTIC,
  0 as EXTRNVAL,
  NULL as SHOWREL_CTYPE,
  NULL as SHOWFORMAT,
  0 as SHOWIN_FLTR,
  0 as SHOWREF,
  NULL as SHOWRESULT,
  NULL as CASE_SENSITIVE,
  1 as NOT_TO_EDIT,
  0 as NOT_TO_SHOW,
  0 as SIMPLE_FILTER,
  NULL as FORM_NAME,
  '/' as BRANCH,
  NULL as WEB_FORM_NAME,
  NULL as OPER_ID,
  0 as INPUT_IN_NEW_RECORD
  FROM DUAL) B
ON (A.TABID = B.TABID and A.COLID = B.COLID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, COLID, COLNAME, COLTYPE, SEMANTIC, 
  SHOWWIDTH, SHOWMAXCHAR, SHOWPOS, SHOWIN_RO, SHOWRETVAL, 
  INSTNSSEMANTIC, EXTRNVAL, SHOWREL_CTYPE, SHOWFORMAT, SHOWIN_FLTR, 
  SHOWREF, SHOWRESULT, CASE_SENSITIVE, NOT_TO_EDIT, NOT_TO_SHOW, 
  SIMPLE_FILTER, FORM_NAME, BRANCH, WEB_FORM_NAME, OPER_ID, 
  INPUT_IN_NEW_RECORD)
VALUES (
  B.TABID, B.COLID, B.COLNAME, B.COLTYPE, B.SEMANTIC, 
  B.SHOWWIDTH, B.SHOWMAXCHAR, B.SHOWPOS, B.SHOWIN_RO, B.SHOWRETVAL, 
  B.INSTNSSEMANTIC, B.EXTRNVAL, B.SHOWREL_CTYPE, B.SHOWFORMAT, B.SHOWIN_FLTR, 
  B.SHOWREF, B.SHOWRESULT, B.CASE_SENSITIVE, B.NOT_TO_EDIT, B.NOT_TO_SHOW, 
  B.SIMPLE_FILTER, B.FORM_NAME, B.BRANCH, B.WEB_FORM_NAME, B.OPER_ID, 
  B.INPUT_IN_NEW_RECORD)
WHEN MATCHED THEN
UPDATE SET 
  A.COLNAME = B.COLNAME,
  A.COLTYPE = B.COLTYPE,
  A.SEMANTIC = B.SEMANTIC,
  A.SHOWWIDTH = B.SHOWWIDTH,
  A.SHOWMAXCHAR = B.SHOWMAXCHAR,
  A.SHOWPOS = B.SHOWPOS,
  A.SHOWIN_RO = B.SHOWIN_RO,
  A.SHOWRETVAL = B.SHOWRETVAL,
  A.INSTNSSEMANTIC = B.INSTNSSEMANTIC,
  A.EXTRNVAL = B.EXTRNVAL,
  A.SHOWREL_CTYPE = B.SHOWREL_CTYPE,
  A.SHOWFORMAT = B.SHOWFORMAT,
  A.SHOWIN_FLTR = B.SHOWIN_FLTR,
  A.SHOWREF = B.SHOWREF,
  A.SHOWRESULT = B.SHOWRESULT,
  A.CASE_SENSITIVE = B.CASE_SENSITIVE,
  A.NOT_TO_EDIT = B.NOT_TO_EDIT,
  A.NOT_TO_SHOW = B.NOT_TO_SHOW,
  A.SIMPLE_FILTER = B.SIMPLE_FILTER,
  A.FORM_NAME = B.FORM_NAME,
  A.BRANCH = B.BRANCH,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.OPER_ID = B.OPER_ID,
  A.INPUT_IN_NEW_RECORD = B.INPUT_IN_NEW_RECORD;

MERGE INTO BARS.META_COLUMNS A USING
 (SELECT
  1011623 as TABID,
  4 as COLID,
  'BASEY_NAME' as COLNAME,
  'C' as COLTYPE,
  'База~нарах.' as SEMANTIC,
  1.6 as SHOWWIDTH,
  NULL as SHOWMAXCHAR,
  102 as SHOWPOS,
  0 as SHOWIN_RO,
  0 as SHOWRETVAL,
  0 as INSTNSSEMANTIC,
  0 as EXTRNVAL,
  NULL as SHOWREL_CTYPE,
  NULL as SHOWFORMAT,
  0 as SHOWIN_FLTR,
  0 as SHOWREF,
  NULL as SHOWRESULT,
  NULL as CASE_SENSITIVE,
  1 as NOT_TO_EDIT,
  0 as NOT_TO_SHOW,
  0 as SIMPLE_FILTER,
  NULL as FORM_NAME,
  '/' as BRANCH,
  NULL as WEB_FORM_NAME,
  NULL as OPER_ID,
  0 as INPUT_IN_NEW_RECORD
  FROM DUAL) B
ON (A.TABID = B.TABID and A.COLID = B.COLID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, COLID, COLNAME, COLTYPE, SEMANTIC, 
  SHOWWIDTH, SHOWMAXCHAR, SHOWPOS, SHOWIN_RO, SHOWRETVAL, 
  INSTNSSEMANTIC, EXTRNVAL, SHOWREL_CTYPE, SHOWFORMAT, SHOWIN_FLTR, 
  SHOWREF, SHOWRESULT, CASE_SENSITIVE, NOT_TO_EDIT, NOT_TO_SHOW, 
  SIMPLE_FILTER, FORM_NAME, BRANCH, WEB_FORM_NAME, OPER_ID, 
  INPUT_IN_NEW_RECORD)
VALUES (
  B.TABID, B.COLID, B.COLNAME, B.COLTYPE, B.SEMANTIC, 
  B.SHOWWIDTH, B.SHOWMAXCHAR, B.SHOWPOS, B.SHOWIN_RO, B.SHOWRETVAL, 
  B.INSTNSSEMANTIC, B.EXTRNVAL, B.SHOWREL_CTYPE, B.SHOWFORMAT, B.SHOWIN_FLTR, 
  B.SHOWREF, B.SHOWRESULT, B.CASE_SENSITIVE, B.NOT_TO_EDIT, B.NOT_TO_SHOW, 
  B.SIMPLE_FILTER, B.FORM_NAME, B.BRANCH, B.WEB_FORM_NAME, B.OPER_ID, 
  B.INPUT_IN_NEW_RECORD)
WHEN MATCHED THEN
UPDATE SET 
  A.COLNAME = B.COLNAME,
  A.COLTYPE = B.COLTYPE,
  A.SEMANTIC = B.SEMANTIC,
  A.SHOWWIDTH = B.SHOWWIDTH,
  A.SHOWMAXCHAR = B.SHOWMAXCHAR,
  A.SHOWPOS = B.SHOWPOS,
  A.SHOWIN_RO = B.SHOWIN_RO,
  A.SHOWRETVAL = B.SHOWRETVAL,
  A.INSTNSSEMANTIC = B.INSTNSSEMANTIC,
  A.EXTRNVAL = B.EXTRNVAL,
  A.SHOWREL_CTYPE = B.SHOWREL_CTYPE,
  A.SHOWFORMAT = B.SHOWFORMAT,
  A.SHOWIN_FLTR = B.SHOWIN_FLTR,
  A.SHOWREF = B.SHOWREF,
  A.SHOWRESULT = B.SHOWRESULT,
  A.CASE_SENSITIVE = B.CASE_SENSITIVE,
  A.NOT_TO_EDIT = B.NOT_TO_EDIT,
  A.NOT_TO_SHOW = B.NOT_TO_SHOW,
  A.SIMPLE_FILTER = B.SIMPLE_FILTER,
  A.FORM_NAME = B.FORM_NAME,
  A.BRANCH = B.BRANCH,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.OPER_ID = B.OPER_ID,
  A.INPUT_IN_NEW_RECORD = B.INPUT_IN_NEW_RECORD;
end;
/
COMMIT;
begin
MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  222 as FUNCID,
  'Установка/знаття контролю за недопустимий ліміт' as DESCR,
  'cck_ui.p_repay_multi_ss(PUL.Get_Mas_Ini_Val (''ND''))' as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  'Змінити контроль для рахунку SS для проведення операцій ?' as QST,
  'Виконано!' as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  NULL as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;
end;
/
COMMIT;
*/