/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public partial class VWcsSurveyGroupQuestions
    {
        public List<VWcsSurveyGroupQuestionsRecord> SelectSurveyGroupQuestions(String SURVEY_ID, String GROUP_ID, String SortExpression)
        {
            this.Filter.SURVEY_ID.Equal(SURVEY_ID);
            this.Filter.GROUP_ID.Equal(GROUP_ID);
            return this.Select(SortExpression);
        }
        public List<VWcsSurveyGroupQuestionsRecord> SelectSurveyGroupQuestion(String SURVEY_ID, String GROUP_ID, String QUESTION_ID)
        {
            this.Filter.SURVEY_ID.Equal(SURVEY_ID);
            this.Filter.GROUP_ID.Equal(GROUP_ID);
            this.Filter.QUESTION_ID.Equal(QUESTION_ID);
            return this.Select();
        }
        public new void Insert(VWcsSurveyGroupQuestionsRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SURVEY_GROUP_QUEST_SET(Item.SURVEY_ID, Item.GROUP_ID, Item.RECTYPE_ID, Item.QUESTION_ID, Item.DNSHOW_IF, Item.IS_REQUIRED, Item.IS_READONLY, Item.IS_REWRITABLE, Item.IS_CHECKABLE, Item.CHECK_PROC);
        }
        public new void Update(VWcsSurveyGroupQuestionsRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SURVEY_GROUP_QUEST_SET(Item.SURVEY_ID, Item.GROUP_ID, Item.RECTYPE_ID, Item.QUESTION_ID, Item.DNSHOW_IF, Item.IS_REQUIRED, Item.IS_READONLY, Item.IS_REWRITABLE, Item.IS_CHECKABLE, Item.CHECK_PROC);
        }
        public new void Delete(VWcsSurveyGroupQuestionsRecord Item)
        {
            WcsPack wp = new WcsPack(this.Connection);
            wp.SURVEY_GROUP_QUEST_DEL(Item.SURVEY_ID, Item.GROUP_ID, Item.QUESTION_ID);
        }
    }
}