

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/AGG_MONBALS_EXCHANGE_ALL.sql =========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to AGG_MONBALS_EXCHANGE_ALL ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''AGG_MONBALS_EXCHANGE_ALL'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table AGG_MONBALS_EXCHANGE_ALL ***
begin 
  execute immediate '
  CREATE TABLE BARS.AGG_MONBALS_EXCHANGE_ALL 
   (	FDAT DATE, 
	KF VARCHAR2(6), 
	ACC NUMBER(*,0), 
	RNK NUMBER(*,0), 
	OST NUMBER(24,0), 
	OSTQ NUMBER(24,0), 
	DOS NUMBER(24,0), 
	DOSQ NUMBER(24,0), 
	KOS NUMBER(24,0), 
	KOSQ NUMBER(24,0), 
	CRDOS NUMBER(24,0) DEFAULT 0, 
	CRDOSQ NUMBER(24,0) DEFAULT 0, 
	CRKOS NUMBER(24,0) DEFAULT 0, 
	CRKOSQ NUMBER(24,0) DEFAULT 0, 
	CUDOS NUMBER(24,0) DEFAULT 0, 
	CUDOSQ NUMBER(24,0) DEFAULT 0, 
	CUKOS NUMBER(24,0) DEFAULT 0, 
	CUKOSQ NUMBER(24,0) DEFAULT 0, 
	CALDT_ID NUMBER(38,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR(FDAT,''j''))-2447892) VIRTUAL VISIBLE 
   ) PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC 
  TABLESPACE BRSACCM 
  PARTITION BY LIST (KF) 
 (PARTITION SP_300465  VALUES (''300465'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_304665  VALUES (''304665'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_322669  VALUES (''322669'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_324805  VALUES (''324805'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_335106  VALUES (''335106'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_351823  VALUES (''351823'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  TABLESPACE BRSACCM ) 
  PARALLEL 26 ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to AGG_MONBALS_EXCHANGE_ALL ***
 exec bpa.alter_policies('AGG_MONBALS_EXCHANGE_ALL');


COMMENT ON TABLE BARS.AGG_MONBALS_EXCHANGE_ALL IS 'Ќакопительные балансы за мес€ц';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.FDAT IS 'ƒата балансу';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.KF IS ' од ф≥л≥алу (ћ‘ќ)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.ACC IS '≤д. рахунка';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.RNK IS '≤д. кл≥Їнта';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.OST IS '¬их≥дний залишок по рахунку (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.OSTQ IS '¬их≥дний залишок по рахунку (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.DOS IS '—ума дебетових оборот≥в (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.DOSQ IS '—ума дебетових оборот≥в (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.KOS IS '—ума кредитових оборот≥в (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.KOSQ IS '—ума кредитових оборот≥в (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CRDOS IS '—ума корегуючих дебетових  оборот≥в (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CRDOSQ IS '—ума корегуючих дебетових  оборот≥в (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CRKOS IS '—ума корегуючих кредитових оборот≥в (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CRKOSQ IS '—ума корегуючих кредитових оборот≥в (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CUDOS IS '—ума корегуючих дебетових  оборот≥в минулого м≥с€ц€ (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CUDOSQ IS '—ума корегуючих дебетових  оборот≥в минулого м≥с€ц€ (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CUKOS IS '—ума корегуючих кредитових оборот≥в минулого м≥с€ц€ (ном≥нал)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CUKOSQ IS '—ума корегуючих кредитових оборот≥в минулого м≥с€ц€ (екв≥валент)';
COMMENT ON COLUMN BARS.AGG_MONBALS_EXCHANGE_ALL.CALDT_ID IS '≤д. дати балансу (дл€ сум≥сност≥ ≥з попередньою верс≥Їю)';




PROMPT *** Create  constraint SYS_C00110021 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (FDAT NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110022 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (KF NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110023 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (ACC NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110024 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (RNK NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110025 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (OST NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110026 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (OSTQ NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110027 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (DOS NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110028 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (DOSQ NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110029 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (KOS NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C00110030 ***
begin   
 execute immediate '
  ALTER TABLE BARS.AGG_MONBALS_EXCHANGE_ALL MODIFY (KOSQ NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_AGG_MONBALS_EXCHANGE_ALL ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_AGG_MONBALS_EXCHANGE_ALL ON BARS.AGG_MONBALS_EXCHANGE_ALL (FDAT, KF, ACC) 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSACCM  LOCAL
 (PARTITION SP_300465 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_302076 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_303398 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_304665 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_305482 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_311647 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_312356 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_313957 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_315784 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_322669 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_323475 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_324805 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_325796 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_326461 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_328845 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_331467 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_333368 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_335106 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_336503 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_337568 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_338545 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_351823 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_352457 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_353553 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_354507 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM , 
 PARTITION SP_356334 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSACCM ) COMPRESS 2 ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  AGG_MONBALS_EXCHANGE_ALL ***
grant SELECT                                                                 on AGG_MONBALS_EXCHANGE_ALL to BARSREADER_ROLE;
grant ALTER,SELECT                                                           on AGG_MONBALS_EXCHANGE_ALL to DM;
grant SELECT                                                                 on AGG_MONBALS_EXCHANGE_ALL to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/AGG_MONBALS_EXCHANGE_ALL.sql =========
PROMPT ===================================================================================== 
