

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CREDGRAPH_PERIOD.sql ========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_CREDGRAPH_PERIOD ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_CREDGRAPH_PERIOD ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_CREDGRAPH_PERIOD 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	CONTR_ID VARCHAR2(4000), 
	END_DATE VARCHAR2(4000), 
	CR_METHOD VARCHAR2(4000), 
	PAYMENT_PERIOD VARCHAR2(4000), 
	PAYMENT_DELAY VARCHAR2(4000), 
	Z VARCHAR2(4000), 
	ADAPTIVE VARCHAR2(4000), 
	PERCENT VARCHAR2(4000), 
	PERCENT_NBU VARCHAR2(4000), 
	PERCENT_BASE VARCHAR2(4000), 
	PERCENT_PERIOD VARCHAR2(4000), 
	PERCENT_DELAY VARCHAR2(4000), 
	GET_DAY VARCHAR2(4000), 
	PAY_DAY VARCHAR2(4000), 
	PAYMENT_DAY VARCHAR2(4000), 
	PERCENT_DAY VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_CREDGRAPH_PERIOD ***
 exec bpa.alter_policies('ERR$_CIM_CREDGRAPH_PERIOD');


COMMENT ON TABLE BARS.ERR$_CIM_CREDGRAPH_PERIOD IS 'DML Error Logging table for "CIM_CREDGRAPH_PERIOD"';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.CONTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.CR_METHOD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PAYMENT_PERIOD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PAYMENT_DELAY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.Z IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.ADAPTIVE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PERCENT IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PERCENT_NBU IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PERCENT_BASE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PERCENT_PERIOD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PERCENT_DELAY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.GET_DAY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PAY_DAY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PAYMENT_DAY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CREDGRAPH_PERIOD.PERCENT_DAY IS '';



PROMPT *** Create  grants  ERR$_CIM_CREDGRAPH_PERIOD ***
grant SELECT                                                                 on ERR$_CIM_CREDGRAPH_PERIOD to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CIM_CREDGRAPH_PERIOD to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CREDGRAPH_PERIOD.sql ========
PROMPT ===================================================================================== 
