

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_PAWN_ACC_UPDATE.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_PAWN_ACC_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_PAWN_ACC_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_PAWN_ACC_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	PAWN VARCHAR2(4000), 
	MPAWN VARCHAR2(4000), 
	NREE VARCHAR2(4000), 
	IDZ VARCHAR2(4000), 
	NDZ VARCHAR2(4000), 
	DEPOSIT_ID VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	SV VARCHAR2(4000), 
	CC_IDZ VARCHAR2(4000), 
	SDATZ VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_PAWN_ACC_UPDATE ***
 exec bpa.alter_policies('ERR$_PAWN_ACC_UPDATE');


COMMENT ON TABLE BARS.ERR$_PAWN_ACC_UPDATE IS 'DML Error Logging table for "PAWN_ACC_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.PAWN IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.MPAWN IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.NREE IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.IDZ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.NDZ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.DEPOSIT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.SV IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.CC_IDZ IS '';
COMMENT ON COLUMN BARS.ERR$_PAWN_ACC_UPDATE.SDATZ IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_PAWN_ACC_UPDATE.sql =========*** 
PROMPT ===================================================================================== 
