

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIN_CUST.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIN_CUST ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIN_CUST ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIN_CUST 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	RNK VARCHAR2(4000), 
	MFO_2600 VARCHAR2(4000), 
	NLS_2600 VARCHAR2(4000), 
	NLS_2909 VARCHAR2(4000), 
	S_A2 VARCHAR2(4000), 
	S_B2 VARCHAR2(4000), 
	PR_B1 VARCHAR2(4000), 
	S_C0 VARCHAR2(4000), 
	NLS_3739 VARCHAR2(4000), 
	DAPP VARCHAR2(4000), 
	PA1 VARCHAR2(4000), 
	PA2 VARCHAR2(4000), 
	PB1 VARCHAR2(4000), 
	PB2 VARCHAR2(4000), 
	PC0 VARCHAR2(4000), 
	TXT1 VARCHAR2(4000), 
	TXT2 VARCHAR2(4000), 
	TXT3 VARCHAR2(4000), 
	TXT4 VARCHAR2(4000), 
	TXT5 VARCHAR2(4000), 
	TXT6 VARCHAR2(4000), 
	SB1_MIN VARCHAR2(4000), 
	NLS_3578 VARCHAR2(4000), 
	S_B3 VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIN_CUST ***
 exec bpa.alter_policies('ERR$_CIN_CUST');


COMMENT ON TABLE BARS.ERR$_CIN_CUST IS 'DML Error Logging table for "CIN_CUST"';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.MFO_2600 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.NLS_2600 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.NLS_2909 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.S_A2 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.S_B2 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.PR_B1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.S_C0 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.NLS_3739 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.DAPP IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.PA1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.PA2 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.PB1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.PB2 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.PC0 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.TXT1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.TXT2 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.TXT3 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.TXT4 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.TXT5 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.TXT6 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.SB1_MIN IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.NLS_3578 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.S_B3 IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIN_CUST.RNK IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIN_CUST.sql =========*** End ***
PROMPT ===================================================================================== 
