

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ACCOUNTS.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ACCOUNTS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ACCOUNTS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ACCOUNTS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACC VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	NLSALT VARCHAR2(4000), 
	NBS VARCHAR2(4000), 
	NBS2 VARCHAR2(4000), 
	DAOS VARCHAR2(4000), 
	DAPP VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	NMS VARCHAR2(4000), 
	LIM VARCHAR2(4000), 
	OSTB VARCHAR2(4000), 
	OSTC VARCHAR2(4000), 
	OSTF VARCHAR2(4000), 
	OSTQ VARCHAR2(4000), 
	DOS VARCHAR2(4000), 
	KOS VARCHAR2(4000), 
	DOSQ VARCHAR2(4000), 
	KOSQ VARCHAR2(4000), 
	PAP VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	VID VARCHAR2(4000), 
	TRCN VARCHAR2(4000), 
	MDATE VARCHAR2(4000), 
	DAZS VARCHAR2(4000), 
	SEC RAW(2000), 
	ACCC VARCHAR2(4000), 
	BLKD VARCHAR2(4000), 
	BLKK VARCHAR2(4000), 
	POS VARCHAR2(4000), 
	SECI VARCHAR2(4000), 
	SECO VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	OSTX VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	NOTIFIER_REF VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	BDATE VARCHAR2(4000), 
	OPT VARCHAR2(4000), 
	OB22 VARCHAR2(4000), 
	DAPPQ VARCHAR2(4000), 
	SEND_SMS VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ACCOUNTS ***
 exec bpa.alter_policies('ERR$_ACCOUNTS');


COMMENT ON TABLE BARS.ERR$_ACCOUNTS IS 'DML Error Logging table for "ACCOUNTS"';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.NBS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.NBS2 IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.DAOS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.DAPP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.NMS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.LIM IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OSTB IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OSTC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OSTF IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OSTQ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.DOS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.KOS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.DOSQ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.KOSQ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.PAP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.VID IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.TRCN IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.MDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.DAZS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.SEC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ACCC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.BLKD IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.BLKK IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.POS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.SECI IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.SECO IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OSTX IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.NOTIFIER_REF IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.BDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OPT IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.OB22 IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.DAPPQ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.SEND_SMS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.KF IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.KV IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS.NLSALT IS '';



PROMPT *** Create  grants  ERR$_ACCOUNTS ***
grant SELECT                                                                 on ERR$_ACCOUNTS   to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ACCOUNTS.sql =========*** End ***
PROMPT ===================================================================================== 
