

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_V_REZ_BPK.sql =========*** Run **
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_V_REZ_BPK ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_V_REZ_BPK ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_V_REZ_BPK 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	FDAT VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	BPK VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	NBS VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	OBS VARCHAR2(4000), 
	KAT VARCHAR2(4000), 
	K VARCHAR2(4000), 
	BV VARCHAR2(4000), 
	BVQ VARCHAR2(4000), 
	PV VARCHAR2(4000), 
	PVQ VARCHAR2(4000), 
	REZ VARCHAR2(4000), 
	REZQ VARCHAR2(4000), 
	ZAL VARCHAR2(4000), 
	ZALQ VARCHAR2(4000), 
	DAT_S VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	BRANCH VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_V_REZ_BPK ***
 exec bpa.alter_policies('ERR$_V_REZ_BPK');


COMMENT ON TABLE BARS.ERR$_V_REZ_BPK IS 'DML Error Logging table for "V_REZ_BPK"';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.BPK IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ND IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.KV IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.NBS IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.OBS IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.KAT IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.K IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.BV IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.BVQ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.PV IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.PVQ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.REZ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.REZQ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ZAL IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.ZALQ IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.DAT_S IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.KF IS '';
COMMENT ON COLUMN BARS.ERR$_V_REZ_BPK.BRANCH IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_V_REZ_BPK.sql =========*** End **
PROMPT ===================================================================================== 
