

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OW_CNG_DATA.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OW_CNG_DATA ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OW_CNG_DATA ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OW_CNG_DATA 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	IDN VARCHAR2(4000), 
	CONTRACT_ID VARCHAR2(4000), 
	CONTRACT_ACC VARCHAR2(4000), 
	CONTRACT_CURRENCY VARCHAR2(4000), 
	CONTRACT_NAME VARCHAR2(4000), 
	CONTRACT_DATEOPEN VARCHAR2(4000), 
	PLASTIC_TITLE VARCHAR2(4000), 
	PLASTIC_FIRSTNAME VARCHAR2(4000), 
	PLASTIC_LASTNAME VARCHAR2(4000), 
	PLASTIC_COMPANYNAME VARCHAR2(4000), 
	AVL_AMOUNT VARCHAR2(4000), 
	OWN_AMOUNT VARCHAR2(4000), 
	BLK_AMOUNT VARCHAR2(4000), 
	CR_AMOUNT VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	MOB_AMOUNT VARCHAR2(4000), 
	SEC_AMOUNT VARCHAR2(4000), 
	CNGDATE VARCHAR2(4000), 
	AD_AMOUNT VARCHAR2(4000), 
	VIRTUAL_AMOUNT VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OW_CNG_DATA ***
 exec bpa.alter_policies('ERR$_OW_CNG_DATA');


COMMENT ON TABLE BARS.ERR$_OW_CNG_DATA IS 'DML Error Logging table for "OW_CNG_DATA"';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ID IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.IDN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CONTRACT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CONTRACT_ACC IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CONTRACT_CURRENCY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CONTRACT_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CONTRACT_DATEOPEN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.PLASTIC_TITLE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.PLASTIC_FIRSTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.PLASTIC_LASTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.PLASTIC_COMPANYNAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.AVL_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.OWN_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.BLK_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CR_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.MOB_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.SEC_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.CNGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.AD_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.VIRTUAL_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CNG_DATA.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OW_CNG_DATA.sql =========*** End 
PROMPT ===================================================================================== 
