

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONTRACTS_CREDIT.sql ========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_CONTRACTS_CREDIT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_CONTRACTS_CREDIT ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_CONTRACTS_CREDIT 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	CONTR_ID VARCHAR2(4000), 
	PERCENT_NBU VARCHAR2(4000), 
	S_LIMIT VARCHAR2(4000), 
	CREDITOR_TYPE VARCHAR2(4000), 
	BORROWER VARCHAR2(4000), 
	CREDIT_TYPE VARCHAR2(4000), 
	CREDIT_TERM VARCHAR2(4000), 
	CREDIT_PREPAY VARCHAR2(4000), 
	NAME VARCHAR2(4000), 
	ADD_AGREE VARCHAR2(4000), 
	PERCENT_NBU_TYPE VARCHAR2(4000), 
	PERCENT_NBU_INFO VARCHAR2(4000), 
	R_AGREE_DATE VARCHAR2(4000), 
	R_AGREE_NO VARCHAR2(4000), 
	PREV_DOC_KEY VARCHAR2(4000), 
	PREV_REESTR_ATTR VARCHAR2(4000), 
	ENDING_DATE_INDIV VARCHAR2(4000), 
	PARENT_CH_DATA VARCHAR2(4000), 
	ENDING_DATE VARCHAR2(4000), 
	DATE_TERM_CHANGE VARCHAR2(4000), 
	F503_REASON VARCHAR2(4000), 
	F503_STATE VARCHAR2(4000), 
	F503_NOTE VARCHAR2(4000), 
	F504_REASON VARCHAR2(4000), 
	F504_NOTE VARCHAR2(4000), 
	F503_PERCENT_TYPE VARCHAR2(4000), 
	F503_PERCENT_BASE VARCHAR2(4000), 
	F503_PERCENT_MARGIN VARCHAR2(4000), 
	F503_PERCENT VARCHAR2(4000), 
	F503_PURPOSE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_CONTRACTS_CREDIT ***
 exec bpa.alter_policies('ERR$_CIM_CONTRACTS_CREDIT');


COMMENT ON TABLE BARS.ERR$_CIM_CONTRACTS_CREDIT IS 'DML Error Logging table for "CIM_CONTRACTS_CREDIT"';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.CONTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.PERCENT_NBU IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.S_LIMIT IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.CREDITOR_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.BORROWER IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.CREDIT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.CREDIT_TERM IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.CREDIT_PREPAY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.NAME IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ADD_AGREE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.PERCENT_NBU_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.PERCENT_NBU_INFO IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.R_AGREE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.R_AGREE_NO IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.PREV_DOC_KEY IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.PREV_REESTR_ATTR IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ENDING_DATE_INDIV IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.PARENT_CH_DATA IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.ENDING_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.DATE_TERM_CHANGE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_REASON IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_STATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_NOTE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F504_REASON IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F504_NOTE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_PERCENT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_PERCENT_BASE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_PERCENT_MARGIN IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_PERCENT IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_CREDIT.F503_PURPOSE IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONTRACTS_CREDIT.sql ========
PROMPT ===================================================================================== 
