

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SB_PARA.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SB_PARA ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SB_PARA ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SB_PARA 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	NLS_SP VARCHAR2(4000), 
	I_VA_SP VARCHAR2(4000), 
	R011 VARCHAR2(4000), 
	R013 VARCHAR2(4000), 
	S230 VARCHAR2(4000), 
	K120 VARCHAR2(4000), 
	S180 VARCHAR2(4000), 
	START_DAT VARCHAR2(4000), 
	END_DAT VARCHAR2(4000), 
	FIRST_DAT VARCHAR2(4000), 
	VID_KRE VARCHAR2(4000), 
	OBESP VARCHAR2(4000), 
	RISK VARCHAR2(4000), 
	TARGET VARCHAR2(4000), 
	K_PROLONA VARCHAR2(4000), 
	EMITENT VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	S120 VARCHAR2(4000), 
	BIRGA VARCHAR2(4000), 
	VID_CB VARCHAR2(4000), 
	NLS_PRO VARCHAR2(4000), 
	KOD_PRO VARCHAR2(4000), 
	NLG_DEC VARCHAR2(4000), 
	PR_DBS VARCHAR2(4000), 
	PR_KRS VARCHAR2(4000), 
	RS_DBS VARCHAR2(4000), 
	RS_KRS VARCHAR2(4000), 
	P080 VARCHAR2(4000), 
	OB22 VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	R020_FA VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SB_PARA ***
 exec bpa.alter_policies('ERR$_SB_PARA');


COMMENT ON TABLE BARS.ERR$_SB_PARA IS 'DML Error Logging table for "SB_PARA"';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.NLS_SP IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.I_VA_SP IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.R011 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.R013 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.S230 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.K120 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.S180 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.START_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.END_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.FIRST_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.VID_KRE IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.OBESP IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.RISK IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.TARGET IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.K_PROLONA IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.EMITENT IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.S120 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.BIRGA IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.VID_CB IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.NLS_PRO IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.KOD_PRO IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.NLG_DEC IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.PR_DBS IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.PR_KRS IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.RS_DBS IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.RS_KRS IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.P080 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.OB22 IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_SB_PARA.R020_FA IS '';



PROMPT *** Create  grants  ERR$_SB_PARA ***
grant SELECT                                                                 on ERR$_SB_PARA    to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_SB_PARA    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SB_PARA.sql =========*** End *** 
PROMPT ===================================================================================== 
