

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CC_DEAL_UPDATE.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CC_DEAL_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CC_DEAL_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CC_DEAL_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	VIDD VARCHAR2(4000), 
	LIMIT VARCHAR2(4000), 
	KPROLOG VARCHAR2(4000), 
	USER_ID VARCHAR2(4000), 
	OBS VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	IR VARCHAR2(4000), 
	PROD VARCHAR2(4000), 
	SDOG VARCHAR2(4000), 
	SKARB_ID VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	NDI VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	OBS23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	KOL_SP VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	GRP VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CC_DEAL_UPDATE ***
 exec bpa.alter_policies('ERR$_CC_DEAL_UPDATE');


COMMENT ON TABLE BARS.ERR$_CC_DEAL_UPDATE IS 'DML Error Logging table for "CC_DEAL_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.VIDD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.LIMIT IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.KPROLOG IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.USER_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.OBS IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.IR IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.PROD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.SDOG IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.SKARB_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.NDI IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.OBS23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.KOL_SP IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL_UPDATE.GRP IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CC_DEAL_UPDATE.sql =========*** E
PROMPT ===================================================================================== 
