

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_REE_TMP.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_REE_TMP ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_REE_TMP ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_REE_TMP 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	MFO VARCHAR2(4000), 
	ID_A VARCHAR2(4000), 
	RT VARCHAR2(4000), 
	OT VARCHAR2(4000), 
	ODAT VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	PRZ VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	C_AG VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	NMKW VARCHAR2(4000), 
	C_REG VARCHAR2(4000), 
	C_DST VARCHAR2(4000), 
	ID_O VARCHAR2(4000), 
	SIGN RAW(2000), 
	FN_I VARCHAR2(4000), 
	DAT_I VARCHAR2(4000), 
	REC_I VARCHAR2(4000), 
	FN_O VARCHAR2(4000), 
	DAT_O VARCHAR2(4000), 
	REC_O VARCHAR2(4000), 
	ERRK VARCHAR2(4000), 
	REC VARCHAR2(4000), 
	OTM VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_REE_TMP ***
 exec bpa.alter_policies('ERR$_REE_TMP');


COMMENT ON TABLE BARS.ERR$_REE_TMP IS 'DML Error Logging table for "REE_TMP"';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ID_A IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.RT IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.OT IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ODAT IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.PRZ IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.KV IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.C_AG IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.NMKW IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.C_REG IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.C_DST IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ID_O IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.SIGN IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.FN_I IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.DAT_I IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.REC_I IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.FN_O IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.DAT_O IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.REC_O IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.ERRK IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.REC IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.OTM IS '';
COMMENT ON COLUMN BARS.ERR$_REE_TMP.KF IS '';



PROMPT *** Create  grants  ERR$_REE_TMP ***
grant SELECT                                                                 on ERR$_REE_TMP    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_REE_TMP.sql =========*** End *** 
PROMPT ===================================================================================== 
