

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_XML_IMPDOCS.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_XML_IMPDOCS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_XML_IMPDOCS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_XML_IMPDOCS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	FN VARCHAR2(4000), 
	DAT VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	SEQ VARCHAR2(4000), 
	IMPREF VARCHAR2(4000), 
	MFOA VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	ID_A VARCHAR2(4000), 
	NAM_A VARCHAR2(4000), 
	MFOB VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	ID_B VARCHAR2(4000), 
	NAM_B VARCHAR2(4000), 
	S VARCHAR2(4000), 
	S2 VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	KV2 VARCHAR2(4000), 
	DK VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	SK VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	DATD VARCHAR2(4000), 
	DATP VARCHAR2(4000), 
	VDAT VARCHAR2(4000), 
	VOB VARCHAR2(4000), 
	BIS VARCHAR2(4000), 
	D_REC VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	ERRCODE VARCHAR2(4000), 
	ERRMSG VARCHAR2(4000), 
	STATUS VARCHAR2(4000), 
	REF_A VARCHAR2(4000), 
	USERID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_XML_IMPDOCS ***
 exec bpa.alter_policies('ERR$_XML_IMPDOCS');


COMMENT ON TABLE BARS.ERR$_XML_IMPDOCS IS 'DML Error Logging table for "XML_IMPDOCS"';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.VOB IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.BIS IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.D_REC IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.REF IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ERRCODE IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ERRMSG IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.STATUS IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.REF_A IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.FN IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.DAT IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.KF IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.SEQ IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.IMPREF IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.MFOA IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ID_A IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.NAM_A IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.MFOB IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ID_B IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.NAM_B IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.S IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.S2 IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.KV IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.KV2 IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.DK IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.ND IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.TT IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.SK IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.DATD IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.DATP IS '';
COMMENT ON COLUMN BARS.ERR$_XML_IMPDOCS.VDAT IS '';



PROMPT *** Create  grants  ERR$_XML_IMPDOCS ***
grant SELECT                                                                 on ERR$_XML_IMPDOCS to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_XML_IMPDOCS.sql =========*** End 
PROMPT ===================================================================================== 
