

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER_REL_UPDATE.sql =========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CUSTOMER_REL_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CUSTOMER_REL_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CUSTOMER_REL_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	REL_ID VARCHAR2(4000), 
	REL_RNK VARCHAR2(4000), 
	REL_INTEXT VARCHAR2(4000), 
	VAGA1 VARCHAR2(4000), 
	VAGA2 VARCHAR2(4000), 
	TYPE_ID VARCHAR2(4000), 
	POSITION VARCHAR2(4000), 
	FIRST_NAME VARCHAR2(4000), 
	MIDDLE_NAME VARCHAR2(4000), 
	LAST_NAME VARCHAR2(4000), 
	DOCUMENT_TYPE_ID VARCHAR2(4000), 
	DOCUMENT VARCHAR2(4000), 
	TRUST_REGNUM VARCHAR2(4000), 
	TRUST_REGDAT VARCHAR2(4000), 
	BDATE VARCHAR2(4000), 
	EDATE VARCHAR2(4000), 
	NOTARY_NAME VARCHAR2(4000), 
	NOTARY_REGION VARCHAR2(4000), 
	SIGN_PRIVS VARCHAR2(4000), 
	SIGN_ID VARCHAR2(4000), 
	NAME_R VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	GLOBAL_BDATE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CUSTOMER_REL_UPDATE ***
 exec bpa.alter_policies('ERR$_CUSTOMER_REL_UPDATE');


COMMENT ON TABLE BARS.ERR$_CUSTOMER_REL_UPDATE IS 'DML Error Logging table for "CUSTOMER_REL_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.REL_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.REL_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.REL_INTEXT IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.VAGA1 IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.VAGA2 IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.POSITION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.FIRST_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.MIDDLE_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.LAST_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.DOCUMENT_TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.DOCUMENT IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.TRUST_REGNUM IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.TRUST_REGDAT IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.BDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.EDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.NOTARY_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.NOTARY_REGION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.SIGN_PRIVS IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.SIGN_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.NAME_R IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_REL_UPDATE.GLOBAL_BDATE IS '';



PROMPT *** Create  grants  ERR$_CUSTOMER_REL_UPDATE ***
grant SELECT                                                                 on ERR$_CUSTOMER_REL_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CUSTOMER_REL_UPDATE to BARS_DM;
grant SELECT                                                                 on ERR$_CUSTOMER_REL_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER_REL_UPDATE.sql =========
PROMPT ===================================================================================== 
