

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OTCN_F08_HISTORY.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OTCN_F08_HISTORY ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OTCN_F08_HISTORY ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OTCN_F08_HISTORY 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACCD VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	NLSD VARCHAR2(4000), 
	S VARCHAR2(4000), 
	SQ VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	ACCK VARCHAR2(4000), 
	NLSK VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	USERID VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	VOB VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OTCN_F08_HISTORY ***
 exec bpa.alter_policies('ERR$_OTCN_F08_HISTORY');


COMMENT ON TABLE BARS.ERR$_OTCN_F08_HISTORY IS 'DML Error Logging table for "OTCN_F08_HISTORY"';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ACCD IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.TT IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.REF IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.KV IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.NLSD IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.S IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.SQ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ACCK IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.NLSK IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.KF IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_HISTORY.VOB IS '';



PROMPT *** Create  grants  ERR$_OTCN_F08_HISTORY ***
grant SELECT                                                                 on ERR$_OTCN_F08_HISTORY to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_OTCN_F08_HISTORY to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OTCN_F08_HISTORY.sql =========***
PROMPT ===================================================================================== 
