

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_STAFF$BASE.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_STAFF$BASE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_STAFF$BASE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_STAFF$BASE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	FIO VARCHAR2(4000), 
	LOGNAME VARCHAR2(4000), 
	TYPE VARCHAR2(4000), 
	TABN VARCHAR2(4000), 
	BAX VARCHAR2(4000), 
	TBAX VARCHAR2(4000), 
	DISABLE VARCHAR2(4000), 
	ADATE1 VARCHAR2(4000), 
	ADATE2 VARCHAR2(4000), 
	RDATE1 VARCHAR2(4000), 
	RDATE2 VARCHAR2(4000), 
	CLSID VARCHAR2(4000), 
	APPROVE VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	COUNTCONN VARCHAR2(4000), 
	COUNTPASS VARCHAR2(4000), 
	PROFILE VARCHAR2(4000), 
	USEARC VARCHAR2(4000), 
	CSCHEMA VARCHAR2(4000), 
	WEB_PROFILE VARCHAR2(4000), 
	POLICY_GROUP VARCHAR2(4000), 
	ACTIVE VARCHAR2(4000), 
	CREATED VARCHAR2(4000), 
	EXPIRED VARCHAR2(4000), 
	CHKSUM VARCHAR2(4000), 
	USEGTW VARCHAR2(4000), 
	BLK VARCHAR2(4000), 
	TBLK VARCHAR2(4000), 
	TEMPL_ID VARCHAR2(4000), 
	CAN_SELECT_BRANCH VARCHAR2(4000), 
	CHGPWD VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	CURRENT_BRANCH VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_STAFF$BASE ***
 exec bpa.alter_policies('ERR$_STAFF$BASE');


COMMENT ON TABLE BARS.ERR$_STAFF$BASE IS 'DML Error Logging table for "STAFF$BASE"';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.FIO IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.LOGNAME IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.TABN IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.BAX IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.TBAX IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.DISABLE IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ADATE1 IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ADATE2 IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.RDATE1 IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.RDATE2 IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CLSID IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.APPROVE IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.COUNTCONN IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.COUNTPASS IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.PROFILE IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.USEARC IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CSCHEMA IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.WEB_PROFILE IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.POLICY_GROUP IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.ACTIVE IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CREATED IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.EXPIRED IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CHKSUM IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.USEGTW IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.BLK IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.TBLK IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.TEMPL_ID IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CAN_SELECT_BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CHGPWD IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_STAFF$BASE.CURRENT_BRANCH IS '';



PROMPT *** Create  grants  ERR$_STAFF$BASE ***
grant SELECT                                                                 on ERR$_STAFF$BASE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_STAFF$BASE to BARS_DM;
grant SELECT                                                                 on ERR$_STAFF$BASE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_STAFF$BASE.sql =========*** End *
PROMPT ===================================================================================== 
