

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OW_OIC_ATRANSFERS_DATA.sql ======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OW_OIC_ATRANSFERS_DATA ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OW_OIC_ATRANSFERS_DATA ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OW_OIC_ATRANSFERS_DATA 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	IDN VARCHAR2(4000), 
	ANL_SYNTHREFN VARCHAR2(4000), 
	ANL_SYNTHCODE VARCHAR2(4000), 
	ANL_TRNDESCR VARCHAR2(4000), 
	ANL_ANALYTICREFN VARCHAR2(4000), 
	CREDIT_ANLACCOUNT VARCHAR2(4000), 
	CREDIT_SYNTACCOUNT VARCHAR2(4000), 
	CREDIT_AMOUNT VARCHAR2(4000), 
	CREDIT_CURRENCY VARCHAR2(4000), 
	DEBIT_ANLACCOUNT VARCHAR2(4000), 
	DEBIT_SYNTACCOUNT VARCHAR2(4000), 
	DEBIT_AMOUNT VARCHAR2(4000), 
	DEBIT_CURRENCY VARCHAR2(4000), 
	ANL_POSTINGDATE VARCHAR2(4000), 
	DOC_DRN VARCHAR2(4000), 
	DOC_LOCALDATE VARCHAR2(4000), 
	DOC_DESCR VARCHAR2(4000), 
	DOC_AMOUNT VARCHAR2(4000), 
	DOC_CURRENCY VARCHAR2(4000), 
	ERR_TEXT VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	NAM_A VARCHAR2(4000), 
	ID_A VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	NAM_B VARCHAR2(4000), 
	ID_B VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	DOC_ORN VARCHAR2(4000), 
	ACCOUNT_2924_016 VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OW_OIC_ATRANSFERS_DATA ***
 exec bpa.alter_policies('ERR$_OW_OIC_ATRANSFERS_DATA');


COMMENT ON TABLE BARS.ERR$_OW_OIC_ATRANSFERS_DATA IS 'DML Error Logging table for "OW_OIC_ATRANSFERS_DATA"';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ID IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.IDN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ANL_SYNTHREFN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ANL_SYNTHCODE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ANL_TRNDESCR IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ANL_ANALYTICREFN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.CREDIT_ANLACCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.CREDIT_SYNTACCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.CREDIT_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.CREDIT_CURRENCY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DEBIT_ANLACCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DEBIT_SYNTACCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DEBIT_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DEBIT_CURRENCY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ANL_POSTINGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DOC_DRN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DOC_LOCALDATE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DOC_DESCR IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DOC_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DOC_CURRENCY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ERR_TEXT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.NAM_A IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ID_A IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.NAM_B IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ID_B IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.DOC_ORN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.ACCOUNT_2924_016 IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_ATRANSFERS_DATA.KF IS '';



PROMPT *** Create  grants  ERR$_OW_OIC_ATRANSFERS_DATA ***
grant SELECT                                                                 on ERR$_OW_OIC_ATRANSFERS_DATA to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_OW_OIC_ATRANSFERS_DATA to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OW_OIC_ATRANSFERS_DATA.sql ======
PROMPT ===================================================================================== 
