

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SKRYNKA_STAFF.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SKRYNKA_STAFF ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SKRYNKA_STAFF ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SKRYNKA_STAFF 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	USERID VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	FIO VARCHAR2(4000), 
	FIO_R VARCHAR2(4000), 
	DOVER VARCHAR2(4000), 
	POSADA VARCHAR2(4000), 
	POSADA_R VARCHAR2(4000), 
	TOWN VARCHAR2(4000), 
	ADRESS VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	TELEFON VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	MODE_TIME VARCHAR2(4000), 
	WEEKEND VARCHAR2(4000), 
	APPROVED VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	ACTIV VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SKRYNKA_STAFF ***
 exec bpa.alter_policies('ERR$_SKRYNKA_STAFF');


COMMENT ON TABLE BARS.ERR$_SKRYNKA_STAFF IS 'DML Error Logging table for "SKRYNKA_STAFF"';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.FIO IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.FIO_R IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.DOVER IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.POSADA IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.POSADA_R IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.TOWN IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ADRESS IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.TELEFON IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.KF IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.MODE_TIME IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.WEEKEND IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.APPROVED IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ID IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_STAFF.ACTIV IS '';



PROMPT *** Create  grants  ERR$_SKRYNKA_STAFF ***
grant SELECT                                                                 on ERR$_SKRYNKA_STAFF to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SKRYNKA_STAFF.sql =========*** En
PROMPT ===================================================================================== 
