

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CC_TRANS_UPDATE.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CC_TRANS_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CC_TRANS_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CC_TRANS_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	NPP VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	SV VARCHAR2(4000), 
	SZ VARCHAR2(4000), 
	D_PLAN VARCHAR2(4000), 
	D_FAKT VARCHAR2(4000), 
	DAPP VARCHAR2(4000), 
	REFP VARCHAR2(4000), 
	COMM VARCHAR2(4000), 
	ID0 VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CC_TRANS_UPDATE ***
 exec bpa.alter_policies('ERR$_CC_TRANS_UPDATE');


COMMENT ON TABLE BARS.ERR$_CC_TRANS_UPDATE IS 'DML Error Logging table for "CC_TRANS_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.NPP IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.REF IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.SV IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.SZ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.D_PLAN IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.D_FAKT IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.DAPP IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.REFP IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.COMM IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.ID0 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_TRANS_UPDATE.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CC_TRANS_UPDATE.sql =========*** 
PROMPT ===================================================================================== 
