

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_W4_ACC.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_W4_ACC ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_W4_ACC ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_W4_ACC 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ND VARCHAR2(4000), 
	ACC_PK VARCHAR2(4000), 
	ACC_OVR VARCHAR2(4000), 
	ACC_9129 VARCHAR2(4000), 
	ACC_3570 VARCHAR2(4000), 
	ACC_2208 VARCHAR2(4000), 
	ACC_2627 VARCHAR2(4000), 
	ACC_2207 VARCHAR2(4000), 
	ACC_3579 VARCHAR2(4000), 
	ACC_2209 VARCHAR2(4000), 
	CARD_CODE VARCHAR2(4000), 
	ACC_2625X VARCHAR2(4000), 
	ACC_2627X VARCHAR2(4000), 
	ACC_2625D VARCHAR2(4000), 
	ACC_2628 VARCHAR2(4000), 
	ACC_2203 VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	OBS23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	DAT_BEGIN VARCHAR2(4000), 
	DAT_END VARCHAR2(4000), 
	DAT_CLOSE VARCHAR2(4000), 
	PASS_DATE VARCHAR2(4000), 
	PASS_STATE VARCHAR2(4000), 
	KOL_SP VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	NOT_USE_REZ23 VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_W4_ACC ***
 exec bpa.alter_policies('ERR$_W4_ACC');


COMMENT ON TABLE BARS.ERR$_W4_ACC IS 'DML Error Logging table for "W4_ACC"';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ND IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_PK IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_OVR IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_9129 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_3570 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2208 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2627 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2207 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_3579 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2209 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.CARD_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2625X IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2627X IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2625D IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2628 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.ACC_2203 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.OBS23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.DAT_BEGIN IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.DAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.DAT_CLOSE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.PASS_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.PASS_STATE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.KOL_SP IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.NOT_USE_REZ23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_W4_ACC.sql =========*** End *** =
PROMPT ===================================================================================== 
