

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CP_KOD_UPDATE.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CP_KOD_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CP_KOD_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CP_KOD_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	EMI VARCHAR2(4000), 
	DOX VARCHAR2(4000), 
	CP_ID VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	NAME VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	DATP VARCHAR2(4000), 
	IR VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	DAT_EM VARCHAR2(4000), 
	AMORT VARCHAR2(4000), 
	DCP VARCHAR2(4000), 
	CENA VARCHAR2(4000), 
	BASEY VARCHAR2(4000), 
	CENA_KUP VARCHAR2(4000), 
	KY VARCHAR2(4000), 
	DOK VARCHAR2(4000), 
	DNK VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	PERIOD_KUP VARCHAR2(4000), 
	IDT VARCHAR2(4000), 
	DAT_RR VARCHAR2(4000), 
	PR1_KUP VARCHAR2(4000), 
	PR_AMR VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	VNCRR VARCHAR2(4000), 
	PR_AKT VARCHAR2(4000), 
	METR VARCHAR2(4000), 
	GS VARCHAR2(4000), 
	CENA_KUP0 VARCHAR2(4000), 
	CENA_START VARCHAR2(4000), 
	QUOT_SIGN VARCHAR2(4000), 
	DATZR VARCHAR2(4000), 
	DATVK VARCHAR2(4000), 
	IO VARCHAR2(4000), 
	RIVEN VARCHAR2(4000), 
	IN_BR VARCHAR2(4000), 
	EXPIRY VARCHAR2(4000), 
	ZAL_CP VARCHAR2(4000), 
	PAWN VARCHAR2(4000), 
	HIERARCHY_ID VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CP_KOD_UPDATE ***
 exec bpa.alter_policies('ERR$_CP_KOD_UPDATE');


COMMENT ON TABLE BARS.ERR$_CP_KOD_UPDATE IS 'DML Error Logging table for "CP_KOD_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.EMI IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DOX IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CP_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.KV IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.NAME IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DATP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.IR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DAT_EM IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.AMORT IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DCP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CENA IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.BASEY IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CENA_KUP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.KY IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DOK IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DNK IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.PERIOD_KUP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.IDT IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DAT_RR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.PR1_KUP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.PR_AMR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.VNCRR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.PR_AKT IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.METR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.GS IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CENA_KUP0 IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.CENA_START IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.QUOT_SIGN IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DATZR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.DATVK IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.IO IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.RIVEN IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.IN_BR IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.EXPIRY IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.ZAL_CP IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.PAWN IS '';
COMMENT ON COLUMN BARS.ERR$_CP_KOD_UPDATE.HIERARCHY_ID IS '';



PROMPT *** Create  grants  ERR$_CP_KOD_UPDATE ***
grant SELECT                                                                 on ERR$_CP_KOD_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CP_KOD_UPDATE to BARS_DM;
grant SELECT                                                                 on ERR$_CP_KOD_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CP_KOD_UPDATE.sql =========*** En
PROMPT ===================================================================================== 
