

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_FILE_ROW.sql =========*** Run
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_DPT_FILE_ROW ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_DPT_FILE_ROW ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_DPT_FILE_ROW 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	INFO_ID VARCHAR2(4000), 
	FILENAME VARCHAR2(4000), 
	DAT VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	BRANCH_CODE VARCHAR2(4000), 
	DPT_CODE VARCHAR2(4000), 
	SUM VARCHAR2(4000), 
	FIO VARCHAR2(4000), 
	PASP VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	INCORRECT VARCHAR2(4000), 
	CLOSED VARCHAR2(4000), 
	EXCLUDED VARCHAR2(4000), 
	HEADER_ID VARCHAR2(4000), 
	AGENCY_ID VARCHAR2(4000), 
	AGENCY_NAME VARCHAR2(4000), 
	ID_CODE VARCHAR2(4000), 
	FILE_PAYOFF_DATE VARCHAR2(4000), 
	PAYOFF_DATE VARCHAR2(4000), 
	MARKED4PAYMENT VARCHAR2(4000), 
	DEAL_CREATED VARCHAR2(4000), 
	ACC_TYPE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_DPT_FILE_ROW ***
 exec bpa.alter_policies('ERR$_DPT_FILE_ROW');


COMMENT ON TABLE BARS.ERR$_DPT_FILE_ROW IS 'DML Error Logging table for "DPT_FILE_ROW"';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.INCORRECT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.CLOSED IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.EXCLUDED IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.HEADER_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.AGENCY_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.AGENCY_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ID_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.FILE_PAYOFF_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.PAYOFF_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.MARKED4PAYMENT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.DEAL_CREATED IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ACC_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.INFO_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.FILENAME IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.DAT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.BRANCH_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.DPT_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.SUM IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.FIO IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.PASP IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_FILE_ROW.REF IS '';



PROMPT *** Create  grants  ERR$_DPT_FILE_ROW ***
grant SELECT                                                                 on ERR$_DPT_FILE_ROW to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_DPT_FILE_ROW to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_FILE_ROW.sql =========*** End
PROMPT ===================================================================================== 
