

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONCLUSION.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_CONCLUSION ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_CONCLUSION ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_CONCLUSION 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	CONTR_ID VARCHAR2(4000), 
	ORG_ID VARCHAR2(4000), 
	OUT_NUM VARCHAR2(4000), 
	OUT_DATE VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	S VARCHAR2(4000), 
	BEGIN_DATE VARCHAR2(4000), 
	END_DATE VARCHAR2(4000), 
	CREATE_DATE VARCHAR2(4000), 
	CREATE_UID VARCHAR2(4000), 
	DELETE_DATE VARCHAR2(4000), 
	DELETE_UID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_CONCLUSION ***
 exec bpa.alter_policies('ERR$_CIM_CONCLUSION');


COMMENT ON TABLE BARS.ERR$_CIM_CONCLUSION IS 'DML Error Logging table for "CIM_CONCLUSION"';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.OUT_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.OUT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.KV IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.S IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.BEGIN_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.CREATE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.CREATE_UID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.DELETE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.DELETE_UID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.CONTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONCLUSION.ORG_ID IS '';



PROMPT *** Create  grants  ERR$_CIM_CONCLUSION ***
grant SELECT                                                                 on ERR$_CIM_CONCLUSION to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CIM_CONCLUSION to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONCLUSION.sql =========*** E
PROMPT ===================================================================================== 
