

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SPECPARAM.sql =========*** Run **
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SPECPARAM ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SPECPARAM ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SPECPARAM 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACC VARCHAR2(4000), 
	R011 VARCHAR2(4000), 
	R013 VARCHAR2(4000), 
	S080 VARCHAR2(4000), 
	S180 VARCHAR2(4000), 
	S181 VARCHAR2(4000), 
	S190 VARCHAR2(4000), 
	S200 VARCHAR2(4000), 
	S230 VARCHAR2(4000), 
	S240 VARCHAR2(4000), 
	D020 VARCHAR2(4000), 
	KEKD VARCHAR2(4000), 
	KTK VARCHAR2(4000), 
	KVK VARCHAR2(4000), 
	IDG VARCHAR2(4000), 
	IDS VARCHAR2(4000), 
	SPS VARCHAR2(4000), 
	KBK VARCHAR2(4000), 
	S120 VARCHAR2(4000), 
	S130 VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	NKD VARCHAR2(4000), 
	S031 VARCHAR2(4000), 
	S182 VARCHAR2(4000), 
	ISTVAL VARCHAR2(4000), 
	R014 VARCHAR2(4000), 
	K072 VARCHAR2(4000), 
	S090 VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	S270 VARCHAR2(4000), 
	S260 VARCHAR2(4000), 
	K150 VARCHAR2(4000), 
	R114 VARCHAR2(4000), 
	S280 VARCHAR2(4000), 
	S290 VARCHAR2(4000), 
	S370 VARCHAR2(4000), 
	D1#F9 VARCHAR2(4000), 
	NF#F9 VARCHAR2(4000), 
	Z290 VARCHAR2(4000), 
	DP1 VARCHAR2(4000), 
	R012 VARCHAR2(4000), 
	S580 VARCHAR2(4000), 
	KVD VARCHAR2(4000), 
	R016 VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SPECPARAM ***
 exec bpa.alter_policies('ERR$_SPECPARAM');


COMMENT ON TABLE BARS.ERR$_SPECPARAM IS 'DML Error Logging table for "SPECPARAM"';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.R011 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.R013 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S080 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S180 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S181 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S190 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S200 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S230 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S240 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.D020 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.KEKD IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.KTK IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.KVK IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.IDG IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.IDS IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.SPS IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.KBK IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S120 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S130 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.NKD IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S031 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S182 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.ISTVAL IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.R014 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.K072 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S090 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.KF IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S270 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S260 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.K150 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.R114 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S280 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S290 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S370 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.D1#F9 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.NF#F9 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.Z290 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.DP1 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.R012 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.S580 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.KVD IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM.R016 IS '';



PROMPT *** Create  grants  ERR$_SPECPARAM ***
grant SELECT                                                                 on ERR$_SPECPARAM  to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_SPECPARAM  to BARS_DM;
grant SELECT                                                                 on ERR$_SPECPARAM  to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SPECPARAM.sql =========*** End **
PROMPT ===================================================================================== 
