

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SKR_IMPORT_DEALS.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SKR_IMPORT_DEALS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SKR_IMPORT_DEALS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SKR_IMPORT_DEALS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	SAFE_NUM VARCHAR2(4000), 
	SAFE_TYPE_ID VARCHAR2(4000), 
	KEY_USED VARCHAR2(4000), 
	KEY_NUMBER VARCHAR2(4000), 
	KEY_COUNT VARCHAR2(4000), 
	BAIL_SUM VARCHAR2(4000), 
	DAY_SUM VARCHAR2(4000), 
	PENY_SUM VARCHAR2(4000), 
	FUTURE_SUM VARCHAR2(4000), 
	DEAL_NUM VARCHAR2(4000), 
	DEAL_DATE VARCHAR2(4000), 
	DEAL_START_DATE VARCHAR2(4000), 
	DEAL_END_DATE VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	FIO VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	DOC VARCHAR2(4000), 
	ISSUED VARCHAR2(4000), 
	ADDRESS VARCHAR2(4000), 
	BIRTHPLACE VARCHAR2(4000), 
	BIRTHDATE VARCHAR2(4000), 
	PHONE VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	NLSK VARCHAR2(4000), 
	MFOK VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	ERROR VARCHAR2(4000), 
	IMPORTED VARCHAR2(4000), 
	NLS2909 VARCHAR2(4000), 
	NLS3600 VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SKR_IMPORT_DEALS ***
 exec bpa.alter_policies('ERR$_SKR_IMPORT_DEALS');


COMMENT ON TABLE BARS.ERR$_SKR_IMPORT_DEALS IS 'DML Error Logging table for "SKR_IMPORT_DEALS"';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.SAFE_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.SAFE_TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.KEY_USED IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.KEY_NUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.KEY_COUNT IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.BAIL_SUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.DAY_SUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.PENY_SUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.FUTURE_SUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.DEAL_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.DEAL_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.DEAL_START_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.DEAL_END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.FIO IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.DOC IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ISSUED IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ADDRESS IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.BIRTHPLACE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.BIRTHDATE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.PHONE IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.NLSK IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.MFOK IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.ERROR IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.IMPORTED IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.NLS2909 IS '';
COMMENT ON COLUMN BARS.ERR$_SKR_IMPORT_DEALS.NLS3600 IS '';



PROMPT *** Create  grants  ERR$_SKR_IMPORT_DEALS ***
grant SELECT                                                                 on ERR$_SKR_IMPORT_DEALS to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_SKR_IMPORT_DEALS to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SKR_IMPORT_DEALS.sql =========***
PROMPT ===================================================================================== 
