

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_BONUS_REQUESTS.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_DPT_BONUS_REQUESTS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_DPT_BONUS_REQUESTS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_DPT_BONUS_REQUESTS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	DPT_ID VARCHAR2(4000), 
	BONUS_ID VARCHAR2(4000), 
	BONUS_VALUE_PLAN VARCHAR2(4000), 
	BONUS_VALUE_FACT VARCHAR2(4000), 
	REQUEST_DATE VARCHAR2(4000), 
	REQUEST_USER VARCHAR2(4000), 
	REQUEST_AUTO VARCHAR2(4000), 
	REQUEST_CONFIRM VARCHAR2(4000), 
	REQUEST_RECALC VARCHAR2(4000), 
	REQUEST_DELETED VARCHAR2(4000), 
	REQUEST_STATE VARCHAR2(4000), 
	PROCESS_DATE VARCHAR2(4000), 
	PROCESS_USER VARCHAR2(4000), 
	REQ_ID VARCHAR2(4000), 
	REQUEST_BDATE VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	BRANCH VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_DPT_BONUS_REQUESTS ***
 exec bpa.alter_policies('ERR$_DPT_BONUS_REQUESTS');


COMMENT ON TABLE BARS.ERR$_DPT_BONUS_REQUESTS IS 'DML Error Logging table for "DPT_BONUS_REQUESTS"';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.DPT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.BONUS_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.BONUS_VALUE_PLAN IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.BONUS_VALUE_FACT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_USER IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_AUTO IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_CONFIRM IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_RECALC IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_DELETED IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_STATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.PROCESS_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.PROCESS_USER IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQ_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.REQUEST_BDATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.KF IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_BONUS_REQUESTS.BRANCH IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_BONUS_REQUESTS.sql =========*
PROMPT ===================================================================================== 
