

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OPER.sql =========*** Run *** ===
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OPER ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OPER ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OPER 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	REF VARCHAR2(4000), 
	DEAL_TAG VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	VOB VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	PDAT VARCHAR2(4000), 
	VDAT VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	DK VARCHAR2(4000), 
	S VARCHAR2(4000), 
	SQ VARCHAR2(4000), 
	SK VARCHAR2(4000), 
	DATD VARCHAR2(4000), 
	DATP VARCHAR2(4000), 
	NAM_A VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	MFOA VARCHAR2(4000), 
	NAM_B VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	MFOB VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	D_REC VARCHAR2(4000), 
	ID_A VARCHAR2(4000), 
	ID_B VARCHAR2(4000), 
	ID_O VARCHAR2(4000), 
	SIGN RAW(2000), 
	SOS VARCHAR2(4000), 
	VP VARCHAR2(4000), 
	CHK VARCHAR2(4000), 
	S2 VARCHAR2(4000), 
	KV2 VARCHAR2(4000), 
	KVQ VARCHAR2(4000), 
	REFL VARCHAR2(4000), 
	PRTY VARCHAR2(4000), 
	SQ2 VARCHAR2(4000), 
	CURRVISAGRP VARCHAR2(4000), 
	NEXTVISAGRP VARCHAR2(4000), 
	REF_A VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	OTM VARCHAR2(4000), 
	SIGNED VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	USERID VARCHAR2(4000), 
	RESPID VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	BIS VARCHAR2(4000), 
	SOS_TRACKER VARCHAR2(4000), 
	NEXT_VISA_BRANCHES VARCHAR2(4000), 
	SOS_CHANGE_TIME VARCHAR2(4000), 
	ODAT VARCHAR2(4000), 
	BDAT VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OPER ***
 exec bpa.alter_policies('ERR$_OPER');


COMMENT ON TABLE BARS.ERR$_OPER IS 'DML Error Logging table for "OPER"';
COMMENT ON COLUMN BARS.ERR$_OPER.SOS_TRACKER IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NEXT_VISA_BRANCHES IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SOS_CHANGE_TIME IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ODAT IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.BDAT IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.REF IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.DEAL_TAG IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.TT IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.VOB IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ND IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.PDAT IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.VDAT IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.KV IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.DK IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.S IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SQ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SK IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.DATD IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.DATP IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NAM_A IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.MFOA IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NAM_B IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.MFOB IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.D_REC IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ID_A IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ID_B IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.ID_O IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SIGN IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.VP IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.CHK IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.S2 IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.KV2 IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.KVQ IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.REFL IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.PRTY IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SQ2 IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.CURRVISAGRP IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.NEXTVISAGRP IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.REF_A IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.OTM IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.SIGNED IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.RESPID IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.KF IS '';
COMMENT ON COLUMN BARS.ERR$_OPER.BIS IS '';



PROMPT *** Create  grants  ERR$_OPER ***
grant SELECT                                                                 on ERR$_OPER       to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_OPER       to BARS_DM;
grant SELECT                                                                 on ERR$_OPER       to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OPER.sql =========*** End *** ===
PROMPT ===================================================================================== 
