

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_MBM_REL_CUSTOMERS.sql =========**
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_MBM_REL_CUSTOMERS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_MBM_REL_CUSTOMERS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_MBM_REL_CUSTOMERS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	TAX_CODE VARCHAR2(4000), 
	FIRST_NAME VARCHAR2(4000), 
	LAST_NAME VARCHAR2(4000), 
	SECOND_NAME VARCHAR2(4000), 
	DOC_TYPE VARCHAR2(4000), 
	DOC_SERIES VARCHAR2(4000), 
	DOC_NUMBER VARCHAR2(4000), 
	DOC_ORGANIZATION VARCHAR2(4000), 
	DOC_DATE VARCHAR2(4000), 
	BIRTH_DATE VARCHAR2(4000), 
	CREATED_DATE VARCHAR2(4000), 
	CELL_PHONE VARCHAR2(4000), 
	ADDRESS VARCHAR2(4000), 
	EMAIL VARCHAR2(4000), 
	NO_INN VARCHAR2(4000), 
	ACSK_ACTUAL VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_MBM_REL_CUSTOMERS ***
 exec bpa.alter_policies('ERR$_MBM_REL_CUSTOMERS');


COMMENT ON TABLE BARS.ERR$_MBM_REL_CUSTOMERS IS 'DML Error Logging table for "MBM_REL_CUSTOMERS"';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ID IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.TAX_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.FIRST_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.LAST_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.SECOND_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.DOC_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.DOC_SERIES IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.DOC_NUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.DOC_ORGANIZATION IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.DOC_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.BIRTH_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.CREATED_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.CELL_PHONE IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ADDRESS IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.EMAIL IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.NO_INN IS '';
COMMENT ON COLUMN BARS.ERR$_MBM_REL_CUSTOMERS.ACSK_ACTUAL IS '';



PROMPT *** Create  grants  ERR$_MBM_REL_CUSTOMERS ***
grant SELECT                                                                 on ERR$_MBM_REL_CUSTOMERS to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_MBM_REL_CUSTOMERS.sql =========**
PROMPT ===================================================================================== 
