

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_INS_DEALS.sql =========*** Run **
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_INS_DEALS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_INS_DEALS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_INS_DEALS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	STAFF_ID VARCHAR2(4000), 
	CRT_DATE VARCHAR2(4000), 
	PARTNER_ID VARCHAR2(4000), 
	TYPE_ID VARCHAR2(4000), 
	STATUS_ID VARCHAR2(4000), 
	STATUS_DATE VARCHAR2(4000), 
	STATUS_COMM VARCHAR2(4000), 
	INS_RNK VARCHAR2(4000), 
	SER VARCHAR2(4000), 
	NUM VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	EDATE VARCHAR2(4000), 
	SUM VARCHAR2(4000), 
	SUM_KV VARCHAR2(4000), 
	INSU_TARIFF VARCHAR2(4000), 
	INSU_SUM VARCHAR2(4000), 
	OBJECT_TYPE VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	GRT_ID VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	PAY_FREQ VARCHAR2(4000), 
	RENEW_NEED VARCHAR2(4000), 
	RENEW_NEWID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_INS_DEALS ***
 exec bpa.alter_policies('ERR$_INS_DEALS');


COMMENT ON TABLE BARS.ERR$_INS_DEALS IS 'DML Error Logging table for "INS_DEALS"';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ID IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.STAFF_ID IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.CRT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.PARTNER_ID IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.STATUS_ID IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.STATUS_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.STATUS_COMM IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.INS_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.SER IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.NUM IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.EDATE IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.SUM IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.SUM_KV IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.INSU_TARIFF IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.INSU_SUM IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.OBJECT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.GRT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.ND IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.PAY_FREQ IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.RENEW_NEED IS '';
COMMENT ON COLUMN BARS.ERR$_INS_DEALS.RENEW_NEWID IS '';



PROMPT *** Create  grants  ERR$_INS_DEALS ***
grant SELECT                                                                 on ERR$_INS_DEALS  to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_INS_DEALS  to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_INS_DEALS.sql =========*** End **
PROMPT ===================================================================================== 
