

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_BPK_ACC.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_BPK_ACC ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_BPK_ACC ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_BPK_ACC 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACC_PK VARCHAR2(4000), 
	ACC_OVR VARCHAR2(4000), 
	ACC_9129 VARCHAR2(4000), 
	ACC_TOVR VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	ACC_3570 VARCHAR2(4000), 
	ACC_2208 VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	PRODUCT_ID VARCHAR2(4000), 
	ACC_2207 VARCHAR2(4000), 
	ACC_3579 VARCHAR2(4000), 
	ACC_2209 VARCHAR2(4000), 
	ACC_W4 VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	OBS23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	DAT_END VARCHAR2(4000), 
	KOL_SP VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	DAT_CLOSE VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_BPK_ACC ***
 exec bpa.alter_policies('ERR$_BPK_ACC');


COMMENT ON TABLE BARS.ERR$_BPK_ACC IS 'DML Error Logging table for "BPK_ACC"';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_PK IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_OVR IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_9129 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_TOVR IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.KF IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_3570 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_2208 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ND IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.PRODUCT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_2207 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_3579 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_2209 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.ACC_W4 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.OBS23 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.DAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.KOL_SP IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_ACC.DAT_CLOSE IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_BPK_ACC.sql =========*** End *** 
PROMPT ===================================================================================== 
