

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_LINES_R.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_LINES_R ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_LINES_R ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_LINES_R 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	FN VARCHAR2(4000), 
	DAT VARCHAR2(4000), 
	N VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	BANK_OKPO VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	RTYPE VARCHAR2(4000), 
	NMKK VARCHAR2(4000), 
	ODATE VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	RESID VARCHAR2(4000), 
	DAT_IN_DPA VARCHAR2(4000), 
	DAT_ACC_DPA VARCHAR2(4000), 
	ID_PR VARCHAR2(4000), 
	ID_DPA VARCHAR2(4000), 
	ID_DPS VARCHAR2(4000), 
	ID_REC VARCHAR2(4000), 
	FN_F VARCHAR2(4000), 
	N_F VARCHAR2(4000), 
	ERR VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_LINES_R ***
 exec bpa.alter_policies('ERR$_LINES_R');


COMMENT ON TABLE BARS.ERR$_LINES_R IS 'DML Error Logging table for "LINES_R"';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.FN IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.DAT IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.N IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.BANK_OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.RTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.NMKK IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ODATE IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.KV IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.RESID IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.DAT_IN_DPA IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.DAT_ACC_DPA IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ID_PR IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ID_DPA IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ID_DPS IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ID_REC IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.FN_F IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.N_F IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.ERR IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_R.KF IS '';



PROMPT *** Create  grants  ERR$_LINES_R ***
grant SELECT                                                                 on ERR$_LINES_R    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_LINES_R.sql =========*** End *** 
PROMPT ===================================================================================== 
