

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_PEREKR_B_UPDATE.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_PEREKR_B_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_PEREKR_B_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_PEREKR_B_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	IDS VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	MFOB VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	POLU VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	IDR VARCHAR2(4000), 
	KOEF VARCHAR2(4000), 
	VOB VARCHAR2(4000), 
	FORMULA VARCHAR2(4000), 
	KOD VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	USER_NAME VARCHAR2(4000), 
	IDUPD VARCHAR2(4000), 
	CHACTION VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_PEREKR_B_UPDATE ***
 exec bpa.alter_policies('ERR$_PEREKR_B_UPDATE');


COMMENT ON TABLE BARS.ERR$_PEREKR_B_UPDATE IS 'DML Error Logging table for "PEREKR_B_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.IDS IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.TT IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.MFOB IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.POLU IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.IDR IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.KOEF IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.VOB IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.FORMULA IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.KOD IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.USER_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.CHACTION IS '';
COMMENT ON COLUMN BARS.ERR$_PEREKR_B_UPDATE.KF IS '';



PROMPT *** Create  grants  ERR$_PEREKR_B_UPDATE ***
grant SELECT                                                                 on ERR$_PEREKR_B_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_PEREKR_B_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_PEREKR_B_UPDATE.sql =========*** 
PROMPT ===================================================================================== 
