

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ACC_OVER.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ACC_OVER ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ACC_OVER ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ACC_OVER 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACC VARCHAR2(4000), 
	ACCO VARCHAR2(4000), 
	TIPO VARCHAR2(4000), 
	FLAG VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	DAY VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	DATD VARCHAR2(4000), 
	SD VARCHAR2(4000), 
	NDOC VARCHAR2(4000), 
	VIDD VARCHAR2(4000), 
	DATD2 VARCHAR2(4000), 
	KRL VARCHAR2(4000), 
	USEOSTF VARCHAR2(4000), 
	USELIM VARCHAR2(4000), 
	ACC_9129 VARCHAR2(4000), 
	ACC_8000 VARCHAR2(4000), 
	OBS VARCHAR2(4000), 
	TXT VARCHAR2(4000), 
	USERID VARCHAR2(4000), 
	DELETED VARCHAR2(4000), 
	PR_2600A VARCHAR2(4000), 
	PR_KOMIS VARCHAR2(4000), 
	PR_9129 VARCHAR2(4000), 
	PR_2069 VARCHAR2(4000), 
	ACC_2067 VARCHAR2(4000), 
	ACC_2069 VARCHAR2(4000), 
	ACC_2096 VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	ACC_3739 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	OBS23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	ACC_3600 VARCHAR2(4000), 
	S_3600 VARCHAR2(4000), 
	FLAG_3600 VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ACC_OVER ***
 exec bpa.alter_policies('ERR$_ACC_OVER');


COMMENT ON TABLE BARS.ERR$_ACC_OVER IS 'DML Error Logging table for "ACC_OVER"';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACCO IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.TIPO IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.FLAG IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ND IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.DAY IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.DATD IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.SD IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.NDOC IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.VIDD IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.DATD2 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.KRL IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.USEOSTF IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.USELIM IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_9129 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_8000 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.OBS IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.TXT IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.DELETED IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.PR_2600A IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.PR_KOMIS IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.PR_9129 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.PR_2069 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_2067 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_2069 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_2096 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.KF IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_3739 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.OBS23 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.ACC_3600 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.S_3600 IS '';
COMMENT ON COLUMN BARS.ERR$_ACC_OVER.FLAG_3600 IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ACC_OVER.sql =========*** End ***
PROMPT ===================================================================================== 
