

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ARC_RRP.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ARC_RRP ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ARC_RRP ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ARC_RRP 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	REC VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	MFOA VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	MFOB VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	DK VARCHAR2(4000), 
	S VARCHAR2(4000), 
	VOB VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	DATD VARCHAR2(4000), 
	DATP VARCHAR2(4000), 
	NAM_A VARCHAR2(4000), 
	NAM_B VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	NAZNK VARCHAR2(4000), 
	NAZNS VARCHAR2(4000), 
	ID_A VARCHAR2(4000), 
	ID_B VARCHAR2(4000), 
	ID_O VARCHAR2(4000), 
	REF_A VARCHAR2(4000), 
	BIS VARCHAR2(4000), 
	SIGN RAW(2000), 
	FN_A VARCHAR2(4000), 
	DAT_A VARCHAR2(4000), 
	REC_A VARCHAR2(4000), 
	FN_B VARCHAR2(4000), 
	DAT_B VARCHAR2(4000), 
	REC_B VARCHAR2(4000), 
	D_REC VARCHAR2(4000), 
	BLK VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	PRTY VARCHAR2(4000), 
	FA_NAME VARCHAR2(4000), 
	FA_LN VARCHAR2(4000), 
	FA_T_ARM3 VARCHAR2(4000), 
	FA_T_ARM2 VARCHAR2(4000), 
	FC_NAME VARCHAR2(4000), 
	FC_LN VARCHAR2(4000), 
	FC_T1_ARM2 VARCHAR2(4000), 
	FC_T2_ARM2 VARCHAR2(4000), 
	FB_NAME VARCHAR2(4000), 
	FB_LN VARCHAR2(4000), 
	FB_T_ARM2 VARCHAR2(4000), 
	FB_T_ARM3 VARCHAR2(4000), 
	FB_D_ARM3 VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ARC_RRP ***
 exec bpa.alter_policies('ERR$_ARC_RRP');


COMMENT ON TABLE BARS.ERR$_ARC_RRP IS 'DML Error Logging table for "ARC_RRP"';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.REC IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.REF IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.MFOA IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.MFOB IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.DK IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.S IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.VOB IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ND IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.KV IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.DATD IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.DATP IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NAM_A IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NAM_B IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NAZNK IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.NAZNS IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ID_A IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ID_B IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.ID_O IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.REF_A IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.BIS IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.SIGN IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FN_A IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.DAT_A IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.REC_A IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FN_B IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.DAT_B IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.REC_B IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.D_REC IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.BLK IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.PRTY IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FA_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FA_LN IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FA_T_ARM3 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FA_T_ARM2 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FC_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FC_LN IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FC_T1_ARM2 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FC_T2_ARM2 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FB_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FB_LN IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FB_T_ARM2 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FB_T_ARM3 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.FB_D_ARM3 IS '';
COMMENT ON COLUMN BARS.ERR$_ARC_RRP.KF IS '';



PROMPT *** Create  grants  ERR$_ARC_RRP ***
grant SELECT                                                                 on ERR$_ARC_RRP    to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_ARC_RRP    to BARS_DM;
grant SELECT                                                                 on ERR$_ARC_RRP    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ARC_RRP.sql =========*** End *** 
PROMPT ===================================================================================== 
