

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CC_DEAL.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CC_DEAL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CC_DEAL ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CC_DEAL 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ND VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	VIDD VARCHAR2(4000), 
	LIMIT VARCHAR2(4000), 
	KPROLOG VARCHAR2(4000), 
	USER_ID VARCHAR2(4000), 
	OBS VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	IR VARCHAR2(4000), 
	PROD VARCHAR2(4000), 
	SDOG VARCHAR2(4000), 
	SKARB_ID VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	NDI VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	OBS23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	KOL_SP VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	GRP VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CC_DEAL ***
 exec bpa.alter_policies('ERR$_CC_DEAL');


COMMENT ON TABLE BARS.ERR$_CC_DEAL IS 'DML Error Logging table for "CC_DEAL"';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.VIDD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.LIMIT IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.KPROLOG IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.USER_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.OBS IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.KF IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.IR IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.PROD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.SDOG IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.SKARB_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.NDI IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.OBS23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.KOL_SP IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_CC_DEAL.GRP IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CC_DEAL.sql =========*** End *** 
PROMPT ===================================================================================== 
