

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_RKO_SIGNATORY.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_RKO_SIGNATORY ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_RKO_SIGNATORY ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_RKO_SIGNATORY 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	FULL_NM_NOM VARCHAR2(4000), 
	FULL_NM_GEN VARCHAR2(4000), 
	SHORT_NM_NOM VARCHAR2(4000), 
	POSITION_PRSN_NOM VARCHAR2(4000), 
	DIVISION_PRSN_GEN VARCHAR2(4000), 
	POSITION_PRSN_GEN VARCHAR2(4000), 
	DOC_NM_GEN VARCHAR2(4000), 
	NOTARY_NM_GEN VARCHAR2(4000), 
	NOTARY_TP_GEN VARCHAR2(4000), 
	ATTORNEY_DT VARCHAR2(4000), 
	ATTORNEY_NUM VARCHAR2(4000), 
	NOTARIAL_DISTRICT_GEN VARCHAR2(4000), 
	ACTIVE_F VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_RKO_SIGNATORY ***
 exec bpa.alter_policies('ERR$_RKO_SIGNATORY');


COMMENT ON TABLE BARS.ERR$_RKO_SIGNATORY IS 'DML Error Logging table for "RKO_SIGNATORY"';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ID IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.FULL_NM_NOM IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.FULL_NM_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.SHORT_NM_NOM IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.POSITION_PRSN_NOM IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.DIVISION_PRSN_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.POSITION_PRSN_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.DOC_NM_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.NOTARY_NM_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.NOTARY_TP_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ATTORNEY_DT IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ATTORNEY_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.NOTARIAL_DISTRICT_GEN IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ACTIVE_F IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.KF IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_RKO_SIGNATORY.ORA_ERR_TAG$ IS '';



PROMPT *** Create  grants  ERR$_RKO_SIGNATORY ***
grant SELECT                                                                 on ERR$_RKO_SIGNATORY to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_RKO_SIGNATORY.sql =========*** En
PROMPT ===================================================================================== 
