

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_BPK_CREDIT_DEAL.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_BPK_CREDIT_DEAL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_BPK_CREDIT_DEAL ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_BPK_CREDIT_DEAL 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	CARD_ND VARCHAR2(4000), 
	DEAL_ND VARCHAR2(4000), 
	DEAL_SUM VARCHAR2(4000), 
	DEAL_KV VARCHAR2(4000), 
	DEAL_RNK VARCHAR2(4000), 
	OPEN_DT VARCHAR2(4000), 
	MATUR_DT VARCHAR2(4000), 
	CLOSE_DT VARCHAR2(4000), 
	ACC_9129 VARCHAR2(4000), 
	ACC_OVR VARCHAR2(4000), 
	ACC_2208 VARCHAR2(4000), 
	ACC_2207 VARCHAR2(4000), 
	ACC_2209 VARCHAR2(4000), 
	PC_TYPE VARCHAR2(4000), 
	CREATE_DT VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_BPK_CREDIT_DEAL ***
 exec bpa.alter_policies('ERR$_BPK_CREDIT_DEAL');


COMMENT ON TABLE BARS.ERR$_BPK_CREDIT_DEAL IS 'DML Error Logging table for "BPK_CREDIT_DEAL"';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.CARD_ND IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.DEAL_ND IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.DEAL_SUM IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.DEAL_KV IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.DEAL_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.OPEN_DT IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.MATUR_DT IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.CLOSE_DT IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ACC_9129 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ACC_OVR IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ACC_2208 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ACC_2207 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.ACC_2209 IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.PC_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.CREATE_DT IS '';
COMMENT ON COLUMN BARS.ERR$_BPK_CREDIT_DEAL.KF IS '';



PROMPT *** Create  grants  ERR$_BPK_CREDIT_DEAL ***
grant SELECT                                                                 on ERR$_BPK_CREDIT_DEAL to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_BPK_CREDIT_DEAL to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_BPK_CREDIT_DEAL.sql =========*** 
PROMPT ===================================================================================== 
