

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/INV_CCK_FL_ARH.sql =========*** Run **
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to INV_CCK_FL_ARH ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''INV_CCK_FL_ARH'', ''CENTER'' , ''C'', ''C'', ''C'', null);
               bpa.alter_policy_info(''INV_CCK_FL_ARH'', ''FILIAL'' , ''F'', ''F'', ''F'', null);
               bpa.alter_policy_info(''INV_CCK_FL_ARH'', ''WHOLE'' , ''C'', ''C'', ''C'', null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table INV_CCK_FL_ARH ***
begin 
  execute immediate '
  CREATE TABLE BARS.INV_CCK_FL_ARH 
   (	G00 DATE, 
	G01 VARCHAR2(70), 
	G02 VARCHAR2(30), 
	G03 VARCHAR2(70), 
	G04 VARCHAR2(10), 
	G05 NUMBER, 
	G06 NUMBER(*,0), 
	G07 VARCHAR2(20), 
	G08 CHAR(10), 
	G09 CHAR(10), 
	G10 CHAR(10), 
	G11 NUMBER, 
	G12 NUMBER, 
	G13 CHAR(10), 
	G14 CHAR(10), 
	G15 NUMBER, 
	G16 CHAR(4), 
	G17 NUMBER, 
	G18 NUMBER, 
	G19 NUMBER, 
	G20 NUMBER, 
	G21 NUMBER, 
	G22 NUMBER, 
	G23 NUMBER, 
	G24 NUMBER, 
	G25 NUMBER, 
	G26 NUMBER, 
	G27 CHAR(1), 
	G28 CHAR(1), 
	G29 CHAR(1), 
	G30 VARCHAR2(30), 
	G31 NUMBER, 
	G32 NUMBER, 
	G33 NUMBER, 
	G34 NUMBER, 
	G35 NUMBER, 
	G36 NUMBER, 
	G37 NUMBER, 
	G38 NUMBER, 
	G39 CHAR(1), 
	G40 NUMBER, 
	G41 NUMBER, 
	G42 VARCHAR2(9), 
	G43 CHAR(1), 
	G44 VARCHAR2(2), 
	G45 VARCHAR2(110), 
	G46 NUMBER, 
	G47 CHAR(10), 
	G48 NUMBER, 
	G49 NUMBER, 
	G50 NUMBER(*,0), 
	G51 NUMBER(*,0), 
	G52 NUMBER, 
	G53 NUMBER, 
	G54 NUMBER, 
	G55 NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to INV_CCK_FL_ARH ***
 exec bpa.alter_policies('INV_CCK_FL_ARH');


COMMENT ON TABLE BARS.INV_CCK_FL_ARH IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G00 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G01 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G02 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G03 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G04 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G05 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G06 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G07 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G08 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G09 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G10 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G11 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G12 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G13 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G14 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G15 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G16 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G17 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G18 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G19 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G20 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G21 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G22 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G23 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G24 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G25 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G26 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G27 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G28 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G29 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G30 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G31 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G32 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G33 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G34 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G35 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G36 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G37 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G38 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G39 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G40 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G41 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G42 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G43 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G44 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G45 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G46 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G47 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G48 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G49 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G50 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G51 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G52 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G53 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G54 IS '';
COMMENT ON COLUMN BARS.INV_CCK_FL_ARH.G55 IS '';



PROMPT *** Create  grants  INV_CCK_FL_ARH ***
grant SELECT                                                                 on INV_CCK_FL_ARH  to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on INV_CCK_FL_ARH  to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on INV_CCK_FL_ARH  to START1;
grant SELECT                                                                 on INV_CCK_FL_ARH  to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/INV_CCK_FL_ARH.sql =========*** End **
PROMPT ===================================================================================== 
