

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/KOD_A030.sql =========*** Run *** ====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to KOD_A030 ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''KOD_A030'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''KOD_A030'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''KOD_A030'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table KOD_A030 ***
begin 
  execute immediate '
  CREATE TABLE BARS.KOD_A030 
   (	A010 VARCHAR2(2), 
	A011_2 VARCHAR2(5), 
	A014_2 VARCHAR2(3), 
	A017_2 VARCHAR2(3), 
	A018_2 VARCHAR2(3), 
	A017_1 VARCHAR2(1), 
	A018_1 VARCHAR2(1), 
	A017_0 VARCHAR2(1), 
	A018_0 VARCHAR2(1), 
	PC NUMBER(1,0), 
	KOL_FILE NUMBER(3,0), 
	IM_PRG VARCHAR2(8), 
	MOD_LNN VARCHAR2(8), 
	CONST VARCHAR2(2), 
	POLE_F VARCHAR2(4), 
	PI NUMBER(1,0), 
	STR_POISK VARCHAR2(70), 
	Z NUMBER(1,0), 
	NAME_P VARCHAR2(254), 
	NAME1P VARCHAR2(50), 
	VAL_P VARCHAR2(254), 
	EMPTY_POK VARCHAR2(36), 
	EMPTY_NBU VARCHAR2(34), 
	PR_PRDAT NUMBER(1,0), 
	IM_PRGV VARCHAR2(8), 
	MOD_FVVOD VARCHAR2(8), 
	SEL_03 VARCHAR2(20), 
	ORD_03 VARCHAR2(10), 
	GROUP_03 VARCHAR2(10), 
	SEL_08 VARCHAR2(20), 
	ORD_08 VARCHAR2(10), 
	GROUP_08 VARCHAR2(10), 
	K_VAL NUMBER(1,0), 
	PR_V030 NUMBER(1,0), 
	PR_V_NBU NUMBER(1,0), 
	LEN_VVOD VARCHAR2(2), 
	MAIL_PRIOR VARCHAR2(1), 
	Z_D NUMBER(1,0), 
	PR_ARC NUMBER(1,0), 
	FDBF_ARC NUMBER(1,0), 
	PR_COP_IN NUMBER(1,0), 
	PR_DAT NUMBER(1,0), 
	DATA_O DATE, 
	DATA_C DATE, 
	O_D_P NUMBER(3,0), 
	O_T_P VARCHAR2(5), 
	O_D_P1 NUMBER(3,0), 
	A_PR NUMBER(1,0), 
	A_SD NUMBER(1,0), 
	PR_FUTURE NUMBER(1,0), 
	REM VARCHAR2(6), 
	SPRAV_VVOD VARCHAR2(10), 
	FILT_B040 VARCHAR2(18), 
	NINF_BANK NUMBER(1,0), 
	PR_APPE NUMBER(1,0), 
	PR_SDF NUMBER(1,0), 
	PR_FGVFO VARCHAR2(1), 
	REMN NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to KOD_A030 ***
 exec bpa.alter_policies('KOD_A030');


COMMENT ON TABLE BARS.KOD_A030 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A010 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A011_2 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A014_2 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A017_2 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A018_2 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A017_1 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A018_1 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A017_0 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A018_0 IS '';
COMMENT ON COLUMN BARS.KOD_A030.PC IS '';
COMMENT ON COLUMN BARS.KOD_A030.KOL_FILE IS '';
COMMENT ON COLUMN BARS.KOD_A030.IM_PRG IS '';
COMMENT ON COLUMN BARS.KOD_A030.MOD_LNN IS '';
COMMENT ON COLUMN BARS.KOD_A030.CONST IS '';
COMMENT ON COLUMN BARS.KOD_A030.POLE_F IS '';
COMMENT ON COLUMN BARS.KOD_A030.PI IS '';
COMMENT ON COLUMN BARS.KOD_A030.STR_POISK IS '';
COMMENT ON COLUMN BARS.KOD_A030.Z IS '';
COMMENT ON COLUMN BARS.KOD_A030.NAME_P IS '';
COMMENT ON COLUMN BARS.KOD_A030.NAME1P IS '';
COMMENT ON COLUMN BARS.KOD_A030.VAL_P IS '';
COMMENT ON COLUMN BARS.KOD_A030.EMPTY_POK IS '';
COMMENT ON COLUMN BARS.KOD_A030.EMPTY_NBU IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_PRDAT IS '';
COMMENT ON COLUMN BARS.KOD_A030.IM_PRGV IS '';
COMMENT ON COLUMN BARS.KOD_A030.MOD_FVVOD IS '';
COMMENT ON COLUMN BARS.KOD_A030.SEL_03 IS '';
COMMENT ON COLUMN BARS.KOD_A030.ORD_03 IS '';
COMMENT ON COLUMN BARS.KOD_A030.GROUP_03 IS '';
COMMENT ON COLUMN BARS.KOD_A030.SEL_08 IS '';
COMMENT ON COLUMN BARS.KOD_A030.ORD_08 IS '';
COMMENT ON COLUMN BARS.KOD_A030.GROUP_08 IS '';
COMMENT ON COLUMN BARS.KOD_A030.K_VAL IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_V030 IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_V_NBU IS '';
COMMENT ON COLUMN BARS.KOD_A030.LEN_VVOD IS '';
COMMENT ON COLUMN BARS.KOD_A030.MAIL_PRIOR IS '';
COMMENT ON COLUMN BARS.KOD_A030.Z_D IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_ARC IS '';
COMMENT ON COLUMN BARS.KOD_A030.FDBF_ARC IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_COP_IN IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_DAT IS '';
COMMENT ON COLUMN BARS.KOD_A030.DATA_O IS '';
COMMENT ON COLUMN BARS.KOD_A030.DATA_C IS '';
COMMENT ON COLUMN BARS.KOD_A030.O_D_P IS '';
COMMENT ON COLUMN BARS.KOD_A030.O_T_P IS '';
COMMENT ON COLUMN BARS.KOD_A030.O_D_P1 IS '';
COMMENT ON COLUMN BARS.KOD_A030.A_PR IS '';
COMMENT ON COLUMN BARS.KOD_A030.A_SD IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_FUTURE IS '';
COMMENT ON COLUMN BARS.KOD_A030.REM IS '';
COMMENT ON COLUMN BARS.KOD_A030.SPRAV_VVOD IS '';
COMMENT ON COLUMN BARS.KOD_A030.FILT_B040 IS '';
COMMENT ON COLUMN BARS.KOD_A030.NINF_BANK IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_APPE IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_SDF IS '';
COMMENT ON COLUMN BARS.KOD_A030.PR_FGVFO IS '';
COMMENT ON COLUMN BARS.KOD_A030.REMN IS '';



PROMPT *** Create  grants  KOD_A030 ***
grant SELECT                                                                 on KOD_A030        to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/KOD_A030.sql =========*** End *** ====
PROMPT ===================================================================================== 
