

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/NBUR_DM_CUSTOMERS.sql =========*** Run
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to NBUR_DM_CUSTOMERS ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''NBUR_DM_CUSTOMERS'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table NBUR_DM_CUSTOMERS ***
begin 
  execute immediate '
  CREATE TABLE BARS.NBUR_DM_CUSTOMERS 
   (	REPORT_DATE DATE, 
	KF VARCHAR2(6), 
	CUST_ID NUMBER(38,0), 
	CUST_TYPE NUMBER(1,0), 
	CUST_CODE VARCHAR2(14), 
	CUST_NAME VARCHAR2(38), 
	CUST_ADR VARCHAR2(70), 
	OPEN_DATE DATE, 
	CLOSE_DATE DATE, 
	BRANCH VARCHAR2(30), 
	TAX_REG_ID NUMBER(2,0), 
	TAX_DST_ID NUMBER(2,0), 
	CRISK CHAR(2), 
	CUST_PID NUMBER(38,0), 
	BC NUMBER(1,0), 
	K030 CHAR(1), 
	K040 CHAR(3), 
	K041 CHAR(1), 
	K050 CHAR(3), 
	K051 CHAR(2), 
	K060 CHAR(2), 
	K070 CHAR(5), 
	K072 CHAR(2), 
	K073 CHAR(1), 
	K074 CHAR(1), 
	K080 CHAR(2), 
	K081 CHAR(1), 
	K090 CHAR(5), 
	K110 CHAR(5), 
	K111 CHAR(2), 
	K112 CHAR(1)
   ) PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC  NOLOGGING 
  TABLESPACE BRSBIGD 
  PARTITION BY LIST (KF) 
 (PARTITION P_300465  VALUES (''300465'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_304665  VALUES (''304665'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_322669  VALUES (''322669'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_324805  VALUES (''324805'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_335106  VALUES (''335106'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_351823  VALUES (''351823'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSBIGD ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to NBUR_DM_CUSTOMERS ***
 exec bpa.alter_policies('NBUR_DM_CUSTOMERS');


COMMENT ON TABLE BARS.NBUR_DM_CUSTOMERS IS 'Клієнти АБС з параметрами';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.REPORT_DATE IS 'Звітна дата';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.KF IS 'Код фiлiалу (МФО)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CUST_ID IS 'Iдентифiкатор контрагента';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CUST_TYPE IS 'Тип клієнта (БАНК/ЮО/ФО)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CUST_CODE IS 'Код клієнта';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CUST_NAME IS 'Назва клієнта';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CUST_ADR IS 'Адреса клієнта';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.OPEN_DATE IS 'Дата реєстрації клієнта в АБС';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CLOSE_DATE IS 'Дата закриття клієнта';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.BRANCH IS 'Код вiддiлення';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.TAX_REG_ID IS 'Ід. регіональної податкової інспекції';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.TAX_DST_ID IS 'Ід. районної податкової інспекції';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CRISK IS 'Категорія ризику';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.CUST_PID IS 'РНК вищестоячого клієнта (RNKP)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.BC IS 'Ознака кліента/некліента банку';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K030 IS 'Резидентність (CODCAGENT)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K040 IS 'Код країни (COUNTRY)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K041 IS 'Група країн';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K050 IS 'Організаційно-правова форма господарювання';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K051 IS 'Коди організаційно-правових форм господарювання (SED)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K060 IS 'Код інсайдера (PRINSIDER)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K070 IS 'Інституційний сектор економіки (ISE)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K072 IS 'Сектор економіки';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K073 IS 'Сектор економіки 1-го рівня';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K074 IS 'Узагальнений сектор економіки (державний - недержавний) ';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K080 IS 'Форма власності (FS)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K081 IS 'Форма власності 1-го рівня';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K090 IS 'Галузь економiки (OE)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K110 IS 'Вид економічної діяльності (VED)';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K111 IS 'Розділ виду економічної діяльності';
COMMENT ON COLUMN BARS.NBUR_DM_CUSTOMERS.K112 IS 'Сектор виду економічної діяльності';




PROMPT *** Create  constraint CC_DMCUSTOMERS_REPORTDT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (REPORT_DATE CONSTRAINT CC_DMCUSTOMERS_REPORTDT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMCUSTOMERS_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (KF CONSTRAINT CC_DMCUSTOMERS_KF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMCUSTOMERS_CUSTID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (CUST_ID CONSTRAINT CC_DMCUSTOMERS_CUSTID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMCUSTOMERS_CUSTTP_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (CUST_TYPE CONSTRAINT CC_DMCUSTOMERS_CUSTTP_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMCUSTOMERS_OPENDT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (OPEN_DATE CONSTRAINT CC_DMCUSTOMERS_OPENDT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMCUSTOMERS_BRANCH_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (BRANCH CONSTRAINT CC_DMCUSTOMERS_BRANCH_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMCUSTOMERS_K040_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_CUSTOMERS MODIFY (K040 CONSTRAINT CC_DMCUSTOMERS_K040_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_DMCUSTOMERS ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_DMCUSTOMERS ON BARS.NBUR_DM_CUSTOMERS (KF, CUST_ID) 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSBIGI  LOCAL
 (PARTITION P_300465 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_302076 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_303398 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_304665 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_305482 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_311647 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_312356 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_313957 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_315784 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_322669 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_323475 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_324805 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_325796 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_326461 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_328845 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_331467 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_333368 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_335106 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_336503 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_337568 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_338545 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_351823 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_352457 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_353553 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_354507 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_356334 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI ) COMPRESS 1 ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/NBUR_DM_CUSTOMERS.sql =========*** End
PROMPT ===================================================================================== 
