

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/NBUR_DM_AGREEMENTS_ERRLOG.sql ========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to NBUR_DM_AGREEMENTS_ERRLOG ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''NBUR_DM_AGREEMENTS_ERRLOG'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table NBUR_DM_AGREEMENTS_ERRLOG ***
begin 
  execute immediate '
  CREATE TABLE BARS.NBUR_DM_AGREEMENTS_ERRLOG 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	REPORT_DATE VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	AGRM_ID VARCHAR2(4000), 
	AGRM_NUM VARCHAR2(4000), 
	AGRM_TP VARCHAR2(4000), 
	AGRM_STE VARCHAR2(4000), 
	BEG_DT VARCHAR2(4000), 
	END_DT VARCHAR2(4000), 
	INL_AMNT VARCHAR2(4000), 
	CRN_AMNT VARCHAR2(4000), 
	DBT_FRQ_TP VARCHAR2(4000), 
	DBT_INL_DT VARCHAR2(4000), 
	DBT_MAT_DAY VARCHAR2(4000), 
	INT_FRQ_TP VARCHAR2(4000), 
	INT_INL_DT VARCHAR2(4000), 
	INT_MAT_DAY VARCHAR2(4000), 
	PRTFL_TP VARCHAR2(4000), 
	CCY_ID VARCHAR2(4000), 
	CUST_ID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to NBUR_DM_AGREEMENTS_ERRLOG ***
 exec bpa.alter_policies('NBUR_DM_AGREEMENTS_ERRLOG');


COMMENT ON TABLE BARS.NBUR_DM_AGREEMENTS_ERRLOG IS 'DML Error Logging table for "NBUR_DM_AGREEMENTS"';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.REPORT_DATE IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.KF IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.AGRM_ID IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.AGRM_NUM IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.AGRM_TP IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.AGRM_STE IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.BEG_DT IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.END_DT IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.INL_AMNT IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.CRN_AMNT IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.DBT_FRQ_TP IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.DBT_INL_DT IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.DBT_MAT_DAY IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.INT_FRQ_TP IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.INT_INL_DT IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.INT_MAT_DAY IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.PRTFL_TP IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.CCY_ID IS '';
COMMENT ON COLUMN BARS.NBUR_DM_AGREEMENTS_ERRLOG.CUST_ID IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/NBUR_DM_AGREEMENTS_ERRLOG.sql ========
PROMPT ===================================================================================== 
