

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/NBUR_DM_ADL_DOC_RPT_DTL.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to NBUR_DM_ADL_DOC_RPT_DTL ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''NBUR_DM_ADL_DOC_RPT_DTL'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table NBUR_DM_ADL_DOC_RPT_DTL ***
begin 
  execute immediate '
  CREATE TABLE BARS.NBUR_DM_ADL_DOC_RPT_DTL 
   (	REPORT_DATE DATE, 
	KF CHAR(6), 
	REF NUMBER(38,0), 
	D1#70 VARCHAR2(64), 
	D2#70 VARCHAR2(64), 
	D3#70 VARCHAR2(64), 
	D4#70 VARCHAR2(64), 
	D5#70 VARCHAR2(64), 
	D6#70 VARCHAR2(64), 
	D7#70 VARCHAR2(64), 
	D8#70 VARCHAR2(64), 
	D9#70 VARCHAR2(64), 
	DA#70 VARCHAR2(64), 
	DB#70 VARCHAR2(64), 
	DD#70 VARCHAR2(64), 
	D1#E2 VARCHAR2(64), 
	D6#E2 VARCHAR2(64), 
	D7#E2 VARCHAR2(64), 
	D8#E2 VARCHAR2(64), 
	D1#E9 VARCHAR2(64), 
	D1#C9 VARCHAR2(64), 
	D6#C9 VARCHAR2(64), 
	DE#C9 VARCHAR2(64), 
	D1#D3 VARCHAR2(64), 
	D1#F1 VARCHAR2(64), 
	D1#27 VARCHAR2(64), 
	D1#39 VARCHAR2(64), 
	D1#44 VARCHAR2(64), 
	D1#73 VARCHAR2(64), 
	D2#73 VARCHAR2(64), 
	D020 VARCHAR2(64), 
	BM__C VARCHAR2(64), 
	KURS VARCHAR2(64), 
	D1#2D VARCHAR2(64), 
	KOD_B VARCHAR2(64), 
	KOD_G VARCHAR2(64), 
	KOD_N VARCHAR2(64), 
	TRF_R VARCHAR2(64), 
	TRF_D VARCHAR2(64), 
	DOC_T VARCHAR2(64), 
	DOC_A VARCHAR2(64), 
	DOC_S VARCHAR2(64), 
	DOC_N VARCHAR2(64), 
	DOC_D VARCHAR2(64), 
	REZID VARCHAR2(64), 
	NATIO VARCHAR2(64), 
	OKPO VARCHAR2(64), 
	POKPO VARCHAR2(64), 
	OOKPO VARCHAR2(64)
   ) PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC  NOLOGGING 
  TABLESPACE BRSMDLD 
  PARTITION BY LIST (KF) 
 (PARTITION P_300465  VALUES (''300465'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_304665  VALUES (''304665'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_322669  VALUES (''322669'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_324805  VALUES (''324805'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_335106  VALUES (''335106'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_351823  VALUES (''351823'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD , 
 PARTITION P_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC NOLOGGING 
  TABLESPACE BRSMDLD ) 
  PARALLEL 8 ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to NBUR_DM_ADL_DOC_RPT_DTL ***
 exec bpa.alter_policies('NBUR_DM_ADL_DOC_RPT_DTL');


COMMENT ON TABLE BARS.NBUR_DM_ADL_DOC_RPT_DTL IS 'Додаткові звітні параметри документів';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.REF IS 'ідентифікатор документа';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D2#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D3#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D4#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D5#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D6#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D7#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D8#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D9#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DA#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DB#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DD#70 IS 'Дод. параметр (показник для файлу #70)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#E2 IS 'Дод. параметр (показник для файлу #E2)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D6#E2 IS 'Дод. параметр (показник для файлу #E2)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D7#E2 IS 'Дод. параметр (показник для файлу #E2)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D8#E2 IS 'Дод. параметр (показник для файлу #E2)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#E9 IS 'Код країни отримувача/відправника (KL_K040.K040)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#C9 IS 'Дод. параметр (показник для файлу #C9)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D6#C9 IS 'Дод. параметр (показник для файлу #C9)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DE#C9 IS 'Дод. параметр (показник для файлу #C9)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#D3 IS 'Дод. параметр (показник для файлу #D3)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#F1 IS 'Дод. параметр (показник для файлу #F1)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#27 IS 'Дод. параметр D#27 (показник для файлу #27)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#39 IS 'Дод. параметр D#39 (показник для файлу #39)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#44 IS 'Дод. параметр D#44 (показник для файлу #44)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#73 IS 'Дод. параметр D#73 (показник для файлу #73)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D2#73 IS 'Дод. параметр 73%  (показник для файлу #73)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D020 IS 'Параметр розподілу суми оборотів';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.BM__C IS 'Дод. параметр (по банківських металах)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.KURS IS 'Курс купівлі-продажу валюти';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.D1#2D IS 'Код мети переказу для (#2D)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.KOD_B IS 'Код БАНКУ (1-ПБ)                                 [BOPBANK.REGNUM]';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.KOD_G IS 'Код країни Платника/Отримувача (TAG="KOD_G","n") [BOPCOUNT.KODC]';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.KOD_N IS 'Код призначення платежу (1-ПБ) (TAG="KOD_N","N") [BOPCODE.TRANSCODE]';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.TRF_R IS 'Референс документу відправки переказу';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.TRF_D IS 'Дата документу відправки переказу';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DOC_T IS 'Тип документу';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DOC_A IS 'Орган, який видав документ (issuing authority)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DOC_S IS 'Серiя документу';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DOC_N IS 'Номер документу';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.DOC_D IS 'Дата видачі документу';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.REZID IS 'резидент/нерезидент (K030)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.NATIO IS 'Громадянство';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.OKPO IS 'Ідентифікаційний код';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.POKPO IS 'Код платника';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.OOKPO IS 'Код отримувача';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.KF IS 'Код філіалу (МФО)';
COMMENT ON COLUMN BARS.NBUR_DM_ADL_DOC_RPT_DTL.REPORT_DATE IS 'Звітна дата';




PROMPT *** Create  constraint CC_DMADLDOCRPTDTL_REPORTDT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_ADL_DOC_RPT_DTL MODIFY (REPORT_DATE CONSTRAINT CC_DMADLDOCRPTDTL_REPORTDT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMADLDOCRPTDTL_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_ADL_DOC_RPT_DTL MODIFY (KF CONSTRAINT CC_DMADLDOCRPTDTL_KF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_DMADLDOCRPTDTL_REF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.NBUR_DM_ADL_DOC_RPT_DTL MODIFY (REF CONSTRAINT CC_DMADLDOCRPTDTL_REF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_DMADLDOCRPTDTL ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_DMADLDOCRPTDTL ON BARS.NBUR_DM_ADL_DOC_RPT_DTL (KF, REF) 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSBIGI  LOCAL
 (PARTITION P_300465 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_302076 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_303398 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_304665 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_305482 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_311647 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_312356 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_313957 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_315784 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_322669 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_323475 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_324805 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_325796 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_326461 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_328845 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_331467 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_333368 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_335106 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_336503 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_337568 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_338545 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_351823 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_352457 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_353553 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_354507 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI , 
 PARTITION P_356334 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSBIGI ) COMPRESS 1 ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  NBUR_DM_ADL_DOC_RPT_DTL ***
grant SELECT                                                                 on NBUR_DM_ADL_DOC_RPT_DTL to BARSREADER_ROLE;
grant SELECT                                                                 on NBUR_DM_ADL_DOC_RPT_DTL to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on NBUR_DM_ADL_DOC_RPT_DTL to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/NBUR_DM_ADL_DOC_RPT_DTL.sql =========*
PROMPT ===================================================================================== 
