begin
  execute immediate 'begin bpa.alter_policy_info(''ow_inst_sub_p'', ''WHOLE'',  null, ''E'', ''E'', ''E''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/
 begin
  execute immediate 'begin bpa.alter_policy_info(''ow_inst_sub_p'', ''FILIAL'', ''M'', ''M'', ''M'' , ''M''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/ 
begin
  execute immediate 'begin bpa.alter_policy_info(''ow_inst_sub_p'', ''CENTER'', null, ''E'', ''E'' , ''E''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/
BEGIN
execute immediate 'create table ow_inst_sub_p (
chain_idt number,
idp number,
type varchar2(30),
code varchar2(30),
status varchar2(30),
total_amount number,
amount_to_pay number,
written_off_amount number,
overdue_amount number,
KF varchar2(6 BYTE) default sys_context(''bars_context'',''user_mfo'') CONSTRAINT CC_OW_INST_SUB_P_KF_NN NOT NULL) 
tablespace BRSMDLD
PARTITION BY LIST (KF) 
 (PARTITION P_01_300465  VALUES (''300465'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_02_324805  VALUES (''324805'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_03_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_04_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_05_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_06_335106  VALUES (''335106'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_07_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_08_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_09_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_10_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_11_322669  VALUES (''322669'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_12_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_13_304665  VALUES (''304665'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_14_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_15_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_16_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_17_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_18_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_19_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_20_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_21_351823  VALUES (''351823'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_22_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_23_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_24_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_25_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_26_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD )';
  exception when others then
  if sqlcode = -955 then null;
  else raise;
  end if;
 END;
/
COMMENT ON TABLE BARS.OW_INST_SUB_P IS 'Графік сплати Інстолмент в розрізі складових порції';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.CHAIN_IDT IS 'ІД графіка';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.IDP IS 'ІД порції';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.TYPE IS 'Тип боргу: 
PRINCIPAL - основний борг
FEE - винагорода';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.CODE IS 'Тип боргу: 
PRINCIPAL - основний борг
FEE - комісія
INT - проценти';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.STATUS IS 'Сдатус порції: 
Waiting-статус до відкриття
Open - відкрито
Paid - погашено
Partially Paid - частково погашено
Overdue - прострочено
Closed - відмінено
Revised - реструктеризовано';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.TOTAL_AMOUNT IS 'Загальна сума складової порції';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.AMOUNT_TO_PAY IS 'Сума до сплати';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.WRITTEN_OFF_AMOUNT IS 'Сума списання';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.OVERDUE_AMOUNT IS 'Сума прострочки';

COMMENT ON COLUMN BARS.OW_INST_SUB_P.KF IS 'МФО';
/
begin
  execute immediate 'begin BARS_POLICY_ADM.ALTER_POLICIES(''ow_inst_sub_p''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/
begin   
 execute immediate 'ALTER TABLE BARS.OW_INST_SUB_P ADD 
CONSTRAINT OW_INST_SUB_P_PK
 PRIMARY KEY (CHAIN_IDT, IDP, CODE)
 ENABLE
 VALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/
begin   
 execute immediate ' 
ALTER TABLE BARS.OW_INST_SUB_P ADD 
CONSTRAINT OW_INST_SUB_P_FK
 FOREIGN KEY (CHAIN_IDT, IDP)
 REFERENCES BARS.OW_INST_PORTIONS (CHAIN_IDT, SEQ_NUMBER)
 ENABLE
 VALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/
grant all on ow_inst_sub_p to bars_access_defrole;
/
grant all on ow_inst_sub_p to bars;
/