

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/OW_OIC_ATRANSFERS_HIST.sql =========**
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to OW_OIC_ATRANSFERS_HIST ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''OW_OIC_ATRANSFERS_HIST'', ''CENTER'' , null, ''E'', ''E'', ''E'');
               bpa.alter_policy_info(''OW_OIC_ATRANSFERS_HIST'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''OW_OIC_ATRANSFERS_HIST'', ''WHOLE'' , null, ''E'', ''E'', ''E'');
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table OW_OIC_ATRANSFERS_HIST ***
begin 
  execute immediate '
  CREATE TABLE BARS.OW_OIC_ATRANSFERS_HIST 
   ( ID                 NUMBER(22),
     IDN                NUMBER(22),
     ANL_SYNTHCODE      VARCHAR2(100 BYTE),
     ANL_TRNDESCR       VARCHAR2(254 BYTE),
     ANL_ANALYTICREFN   VARCHAR2(100 BYTE),
     CREDIT_ANLACCOUNT  VARCHAR2(30 BYTE),
     CREDIT_AMOUNT      NUMBER(20,2),
     CREDIT_CURRENCY    NUMBER(3),
     DEBIT_ANLACCOUNT   VARCHAR2(30 BYTE),
     DEBIT_AMOUNT       NUMBER(20,2),
     DEBIT_CURRENCY     NUMBER(3),
     ANL_POSTINGDATE    DATE,
     DOC_DRN            NUMBER(18),
     DOC_LOCALDATE      DATE,
     DOC_DESCR          VARCHAR2(160 BYTE),
     DOC_AMOUNT         NUMBER(20,2),
     DOC_CURRENCY       NUMBER(3),
     REF                NUMBER(22),
     DOC_ORN            NUMBER(22),
     KF                 VARCHAR2(6 BYTE)           DEFAULT sys_context(''bars_context'',''user_mfo''),
     TRANS_INFO         VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  TABLESPACE BRSMDLD
PARTITION BY LIST (KF)
  (PARTITION "OW_AHIST_300465" VALUES (''300465'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_324805" VALUES (''324805'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_302076" VALUES (''302076'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_303398" VALUES (''303398'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_305482" VALUES (''305482'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_335106" VALUES (''335106'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_311647" VALUES (''311647'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_312356" VALUES (''312356'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_313957" VALUES (''313957'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_336503" VALUES (''336503'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_322669" VALUES (''322669'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_323475" VALUES (''323475'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_304665" VALUES (''304665'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_325796" VALUES (''325796'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_326461" VALUES (''326461'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_328845" VALUES (''328845'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_331467" VALUES (''331467'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_333368" VALUES (''333368'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_337568" VALUES (''337568'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_338545" VALUES (''338545'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_351823" VALUES (''351823'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_352457" VALUES (''352457'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_315784" VALUES (''315784'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_354507" VALUES (''354507'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_356334" VALUES (''356334'') TABLESPACE BRSMDLD,
   PARTITION "OW_AHIST_353553" VALUES (''353553'') TABLESPACE BRSMDLD
  )';
exception when others then
  if sqlcode=-955 then null; else raise; end if;
end; 
/




PROMPT *** ALTER_POLICIES to OW_OIC_ATRANSFERS_HIST ***
 exec bpa.alter_policies('OW_OIC_ATRANSFERS_HIST');


COMMENT ON TABLE BARS.OW_OIC_ATRANSFERS_HIST IS 'OpenWay. Імпортовані файли atransfers';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.KF IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.TRANS_INFO IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.ID IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.IDN IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.ANL_SYNTHCODE IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.ANL_TRNDESCR IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.ANL_ANALYTICREFN IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.CREDIT_ANLACCOUNT IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.CREDIT_AMOUNT IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.CREDIT_CURRENCY IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DEBIT_ANLACCOUNT IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DEBIT_AMOUNT IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DEBIT_CURRENCY IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.ANL_POSTINGDATE IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DOC_DRN IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DOC_LOCALDATE IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DOC_DESCR IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DOC_AMOUNT IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DOC_CURRENCY IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.REF IS '';
COMMENT ON COLUMN BARS.OW_OIC_ATRANSFERS_HIST.DOC_ORN IS '';




PROMPT *** Create  constraint PK_OWOICATRANSFERSHIST ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_OIC_ATRANSFERS_HIST ADD CONSTRAINT PK_OWOICATRANSFERSHIST PRIMARY KEY (ID, IDN, KF)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI  ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/


PROMPT *** Create  constraint CC_OWOICATRANSFERSHIST_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_OIC_ATRANSFERS_HIST MODIFY (KF CONSTRAINT CC_OWOICATRANSFERSHIST_KF_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/

PROMPT *** Create  constraint CC_OWOICATRANSFERSHIST_ID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_OIC_ATRANSFERS_HIST MODIFY (ID CONSTRAINT CC_OWOICATRANSFERSHIST_ID_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/

PROMPT *** Create  constraint CC_OWOICATRANSFERSHIST_IDN_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_OIC_ATRANSFERS_HIST MODIFY (IDN CONSTRAINT CC_OWOICATRANSFERSHIST_IDN_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/

PROMPT *** Create  constraint FK_OWOICATRANSFERSHIST_KF ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_OIC_ATRANSFERS_HIST ADD CONSTRAINT FK_OWOICATRANSFERSHIST_KF FOREIGN KEY (KF) REFERENCES BARS.BANKS$BASE (MFO) ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/

PROMPT *** Create  constraint FK_OWOICATRNHIST_OWFILES ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_OIC_ATRANSFERS_HIST ADD CONSTRAINT FK_OWOICATRNHIST_OWFILES  FOREIGN KEY (ID) REFERENCES BARS.OW_FILES (ID)    ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/



PROMPT *** Create  index PK_OWOICATRANSFERSHIST ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_OWOICATRANSFERSHIST ON BARS.OW_OIC_ATRANSFERS_HIST (ID, IDN, KF) LOCAL
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/


PROMPT *** Create  index I_OWOICATRANSFERSHIST_DOCORN ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OWOICATRANSFERSHIST_DOCORN ON BARS.OW_OIC_ATRANSFERS_HIST (DOC_ORN) LOCAL
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/

PROMPT *** Create  index I_OWOICATRANSFERSHIST_DOCDRN ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OWOICATRANSFERSHIST_DOCDRN ON BARS.OW_OIC_ATRANSFERS_HIST (DOC_DRN) LOCAL
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/

PROMPT *** Create  index I_OWOICATRANSFERSHIST_REF ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OWOICATRANSFERSHIST_REF ON BARS.OW_OIC_ATRANSFERS_HIST (REF) LOCAL
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/


PROMPT *** Create  grants  OW_OIC_ATRANSFERS_HIST ***
grant SELECT                                                                 on OW_OIC_ATRANSFERS_HIST to BARSREADER_ROLE;
grant SELECT,UPDATE                                                          on OW_OIC_ATRANSFERS_HIST to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on OW_OIC_ATRANSFERS_HIST to BARS_DM;
grant SELECT,UPDATE                                                          on OW_OIC_ATRANSFERS_HIST to OW;
grant SELECT                                                                 on OW_OIC_ATRANSFERS_HIST to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/OW_OIC_ATRANSFERS_HIST.sql =========**
PROMPT ===================================================================================== 
