begin
BARS_POLICY_ADM.ALTER_POLICY_INFO('SW_OPER_QUEUE', 'WHOLE', null, null, null, null);
BARS_POLICY_ADM.ALTER_POLICY_INFO('SW_OPER_QUEUE', 'FILIAL', null, null, null, null);
end;
/
commit
/
Prompt Table SW_OPER_QUEUE;
--
-- SW_OPER_QUEUE  (Table) 
--
BEGIN
execute immediate 'CREATE TABLE BARS.SW_OPER_QUEUE
(
  REF         NUMBER(38) ,
  SWREF       NUMBER(38) ,
  KF          VARCHAR2(6 BYTE)                  DEFAULT sys_context(''bars_context'',''user_mfo''),
  SWRNUM      NUMBER(10),
  SEND_MT199  NUMBER,
  SWREF_199   NUMBER,
  STATUS      NUMBER(2)        , 
  CONSTRAINT CC_SWOPER_QUE_REF_NN
  CHECK ("REF" IS NOT NULL)
  ENABLE VALIDATE, 
  CONSTRAINT CC_SWOPER_QUE_SWREF_NN
  CHECK ("SWREF" IS NOT NULL)
  ENABLE VALIDATE, 
  CONSTRAINT PK_SWOPER_QUEUE
  PRIMARY KEY
  (REF, SWREF,STATUS)
  ENABLE VALIDATE
)
TABLESPACE BRSMDLD
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOPARALLEL
NOMONITORING';
exception when others then if(sqlcode=-955) then null; else raise; end if;
end;
/

COMMENT ON TABLE BARS.SW_OPER_QUEUE IS 'SWT. Связь сообщений и документов'
/

COMMENT ON COLUMN BARS.SW_OPER_QUEUE.REF IS 'Референс документа'
/

COMMENT ON COLUMN BARS.SW_OPER_QUEUE.SWREF IS 'Референс сообщения'
/

Prompt Index I_SWREF_SWOPERQUE;
--
-- I_SWREF_SWOPERQUE  (Index) 
--
BEGIN
execute immediate 'CREATE INDEX BARS.I_SWREF_SWOPERQUE ON BARS.SW_OPER_QUEUE
(SWREF)
LOGGING
TABLESPACE BRSMDLI
NOPARALLEL';
exception when others then if(sqlcode=-955) then null; else raise; end if;
end;
/


Prompt Synonym SW_OPER_QUEUE;
--
-- SW_OPER_QUEUE  (Synonym) 
--
CREATE OR REPLACE PUBLIC SYNONYM SW_OPER_QUEUE FOR BARS.SW_OPER_QUEUE
/


Prompt Grants on TABLE SW_OPER_QUEUE TO BARSREADER_ROLE to BARSREADER_ROLE;
GRANT SELECT ON BARS.SW_OPER_QUEUE TO BARSREADER_ROLE
/

Prompt Grants on TABLE SW_OPER_QUEUE TO BARS_ACCESS_DEFROLE to BARS_ACCESS_DEFROLE;
GRANT INSERT, SELECT, UPDATE ON BARS.SW_OPER_QUEUE TO BARS_ACCESS_DEFROLE
/

Prompt Grants on TABLE SW_OPER_QUEUE TO START1 to START1;
GRANT SELECT ON BARS.SW_OPER_QUEUE TO START1
/

Prompt Grants on TABLE SW_OPER_QUEUE TO SWTOSS to SWTOSS;
GRANT SELECT ON BARS.SW_OPER_QUEUE TO SWTOSS
/

Prompt Grants on TABLE SW_OPER_QUEUE TO WR_ALL_RIGHTS to WR_ALL_RIGHTS;
GRANT DELETE, INSERT, SELECT, UPDATE, FLASHBACK ON BARS.SW_OPER_QUEUE TO WR_ALL_RIGHTS
/
