

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/T_W4_OTCH_PF.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to T_W4_OTCH_PF ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''T_W4_OTCH_PF'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''T_W4_OTCH_PF'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table T_W4_OTCH_PF ***
begin 
  execute immediate '
  CREATE TABLE BARS.T_W4_OTCH_PF 
   (	BRANCH VARCHAR2(30), 
	NLS VARCHAR2(15), 
	RNK NUMBER(38,0), 
	OKPO VARCHAR2(14), 
	NMK VARCHAR2(70), 
	BDAY DATE, 
	PASS_SER VARCHAR2(10), 
	PASS_NUM VARCHAR2(20), 
	INDX1 VARCHAR2(20), 
	NP1 VARCHAR2(30), 
	ADR1 VARCHAR2(100), 
	INDX2 VARCHAR2(20), 
	NP2 VARCHAR2(30), 
	ADR2 VARCHAR2(100), 
	CARD_CODE VARCHAR2(32), 
	CODE VARCHAR2(32), 
	PR VARCHAR2(3), 
	ZAR_365 NUMBER, 
	ZAR_N_365 NUMBER, 
	DMIN_ZAR DATE, 
	DMAX_ZAR DATE, 
	SPI_365 NUMBER, 
	SPI_365_DW NUMBER, 
	DMAX_SPI DATE, 
	OST_2625 NUMBER, 
	KF VARCHAR2(6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSDYND 
  PARTITION BY LIST (KF) 
 (PARTITION T_W4_300465  VALUES (''300465'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_304665  VALUES (''304665'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_322669  VALUES (''322669'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_324805  VALUES (''324805'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_335106  VALUES (''335106'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_351823  VALUES (''351823'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION T_W4_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to T_W4_OTCH_PF ***
 exec bpa.alter_policies('T_W4_OTCH_PF');


COMMENT ON TABLE BARS.T_W4_OTCH_PF IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.BRANCH IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.NLS IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.RNK IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.OKPO IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.NMK IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.BDAY IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.PASS_SER IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.PASS_NUM IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.INDX1 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.NP1 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.ADR1 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.INDX2 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.NP2 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.ADR2 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.CARD_CODE IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.CODE IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.PR IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.ZAR_365 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.ZAR_N_365 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.DMIN_ZAR IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.DMAX_ZAR IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.SPI_365 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.SPI_365_DW IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.DMAX_SPI IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.OST_2625 IS '';
COMMENT ON COLUMN BARS.T_W4_OTCH_PF.KF IS '';



PROMPT *** Create  grants  T_W4_OTCH_PF ***
grant SELECT                                                                 on T_W4_OTCH_PF    to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on T_W4_OTCH_PF    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/T_W4_OTCH_PF.sql =========*** End *** 
PROMPT ===================================================================================== 
