

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TEMP_KAS_OB.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TEMP_KAS_OB ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TEMP_KAS_OB'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''TEMP_KAS_OB'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''TEMP_KAS_OB'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TEMP_KAS_OB ***
begin 
  execute immediate '
  CREATE TABLE BARS.TEMP_KAS_OB 
   (	D1 NUMBER(*,0), 
	K1 NUMBER(*,0), 
	D2 NUMBER(*,0), 
	K2 NUMBER(*,0), 
	D3 NUMBER(*,0), 
	K3 NUMBER(*,0), 
	D4 NUMBER(*,0), 
	K4 NUMBER(*,0), 
	D5 NUMBER(*,0), 
	K5 NUMBER(*,0), 
	D6 NUMBER(*,0), 
	K6 NUMBER(*,0), 
	D7 NUMBER(*,0), 
	K7 NUMBER(*,0), 
	D8 NUMBER(*,0), 
	K8 NUMBER(*,0), 
	D9 NUMBER(*,0), 
	K9 NUMBER(*,0), 
	D10 NUMBER(*,0), 
	K10 NUMBER(*,0), 
	D11 NUMBER(*,0), 
	K11 NUMBER(*,0), 
	D12 NUMBER(*,0), 
	K12 NUMBER(*,0), 
	D13 NUMBER(*,0), 
	K13 NUMBER(*,0), 
	D14 NUMBER(*,0), 
	K14 NUMBER(*,0), 
	D15 NUMBER(*,0), 
	K15 NUMBER(*,0), 
	D16 NUMBER(*,0), 
	K16 NUMBER(*,0), 
	D17 NUMBER(*,0), 
	K17 NUMBER(*,0), 
	D18 NUMBER(*,0), 
	K18 NUMBER(*,0), 
	D19 NUMBER(*,0), 
	K19 NUMBER(*,0), 
	D20 NUMBER(*,0), 
	K20 NUMBER(*,0), 
	D21 NUMBER(*,0), 
	K21 NUMBER(*,0), 
	D22 NUMBER(*,0), 
	K22 NUMBER(*,0), 
	D23 NUMBER(*,0), 
	K23 NUMBER(*,0), 
	D24 NUMBER(*,0), 
	K24 NUMBER(*,0), 
	D25 NUMBER(*,0), 
	K25 NUMBER(*,0), 
	D26 NUMBER, 
	K26 NUMBER, 
	D27 NUMBER(*,0), 
	K27 NUMBER(*,0), 
	D28 NUMBER, 
	K28 NUMBER, 
	D29 NUMBER, 
	K29 NUMBER, 
	D30 NUMBER, 
	K30 NUMBER, 
	D31 NUMBER, 
	K31 NUMBER, 
	D32 NUMBER, 
	K32 NUMBER, 
	D33 NUMBER, 
	K33 NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TEMP_KAS_OB ***
 exec bpa.alter_policies('TEMP_KAS_OB');


COMMENT ON TABLE BARS.TEMP_KAS_OB IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D1 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K1 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D2 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K2 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D3 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K3 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D4 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K4 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D5 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K5 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D6 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K6 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D7 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K7 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D8 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K8 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D9 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K9 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D10 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K10 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D11 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K11 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D12 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K12 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D13 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K13 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D14 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K14 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D15 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K15 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D16 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K16 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D17 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K17 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D18 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K18 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D19 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K19 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D20 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K20 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D21 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K21 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D22 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K22 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D23 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K23 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D24 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K24 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D25 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K25 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D26 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K26 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D27 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K27 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D28 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K28 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D29 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K29 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D30 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K30 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D31 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K31 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D32 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K32 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.D33 IS '';
COMMENT ON COLUMN BARS.TEMP_KAS_OB.K33 IS '';



PROMPT *** Create  grants  TEMP_KAS_OB ***
grant SELECT                                                                 on TEMP_KAS_OB     to BARSREADER_ROLE;
grant SELECT                                                                 on TEMP_KAS_OB     to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on TEMP_KAS_OB     to BARS_DM;
grant SELECT                                                                 on TEMP_KAS_OB     to START1;
grant SELECT                                                                 on TEMP_KAS_OB     to UPLD;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on TEMP_KAS_OB     to WR_ALL_RIGHTS;



PROMPT *** Create SYNONYM  to TEMP_KAS_OB ***

  CREATE OR REPLACE PUBLIC SYNONYM TEMP_KAS_OB FOR BARS.TEMP_KAS_OB;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TEMP_KAS_OB.sql =========*** End *** =
PROMPT ===================================================================================== 
