

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_LICCORPC_KFILE.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_LICCORPC_KFILE ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TMP_LICCORPC_KFILE'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_LICCORPC_KFILE'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''TMP_LICCORPC_KFILE'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_LICCORPC_KFILE ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_LICCORPC_KFILE 
   (	ROWTYPE NUMBER, 
	OURMFO VARCHAR2(6), 
	NLS VARCHAR2(14), 
	KV NUMBER, 
	OKPO VARCHAR2(14), 
	OBDB NUMBER, 
	OBDBQ NUMBER, 
	OBKR NUMBER, 
	OBKRQ NUMBER, 
	OST NUMBER, 
	OSTQ NUMBER, 
	KOD_CORP NUMBER, 
	KOD_USTAN NUMBER, 
	KOD_ANALYT VARCHAR2(4), 
	DAPP DATE, 
	POSTDAT DATE, 
	DOCDAT DATE, 
	VALDAT DATE, 
	ND VARCHAR2(10), 
	VOB NUMBER, 
	DK NUMBER, 
	MFOA VARCHAR2(6), 
	NLSA VARCHAR2(14), 
	KVA NUMBER, 
	NAMA VARCHAR2(70), 
	OKPOA VARCHAR2(14), 
	MFOB VARCHAR2(6), 
	NLSB VARCHAR2(14), 
	KVB NUMBER, 
	NAMB VARCHAR2(70), 
	OKPOB VARCHAR2(14), 
	S NUMBER, 
	DOCKV NUMBER, 
	SQ NUMBER, 
	NAZN VARCHAR2(160), 
	DOCTYPE NUMBER, 
	POSTTIME DATE, 
	NAMK VARCHAR2(70), 
	NMS VARCHAR2(70), 
	TT VARCHAR2(3), 
	KF VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_LICCORPC_KFILE ***
 exec bpa.alter_policies('TMP_LICCORPC_KFILE');


COMMENT ON TABLE BARS.TMP_LICCORPC_KFILE IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.ROWTYPE IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OURMFO IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NLS IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KV IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OBDB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OBDBQ IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OBKR IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OBKRQ IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OST IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OSTQ IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KOD_CORP IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KOD_USTAN IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KOD_ANALYT IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.DAPP IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.POSTDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.DOCDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.VALDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.ND IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.VOB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.DK IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.MFOA IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NLSA IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KVA IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NAMA IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OKPOA IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.MFOB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NLSB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KVB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NAMB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.OKPOB IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.S IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.DOCKV IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.SQ IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NAZN IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.DOCTYPE IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.POSTTIME IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NAMK IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.NMS IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.TT IS '';
COMMENT ON COLUMN BARS.TMP_LICCORPC_KFILE.KF IS '';



PROMPT *** Create  grants  TMP_LICCORPC_KFILE ***
grant SELECT                                                                 on TMP_LICCORPC_KFILE to BARSREADER_ROLE;
grant ALTER,DEBUG,DELETE,FLASHBACK,INSERT,ON COMMIT REFRESH,QUERY REWRITE,SELECT,UPDATE on TMP_LICCORPC_KFILE to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on TMP_LICCORPC_KFILE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_LICCORPC_KFILE.sql =========*** En
PROMPT ===================================================================================== 
