

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_DYNAMIC_LAYOUT_DETAIL.sql ========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_DYNAMIC_LAYOUT_DETAIL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_DYNAMIC_LAYOUT_DETAIL ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_DYNAMIC_LAYOUT_DETAIL 
   (	ID NUMBER(38,0), 
	DK NUMBER(1,0), 
	ND VARCHAR2(10), 
	KV NUMBER(3,0), 
	BRANCH VARCHAR2(30), 
	BRANCH_NAME VARCHAR2(70), 
	NLS_A VARCHAR2(15), 
	NAMA VARCHAR2(256), 
	OKPOA VARCHAR2(14), 
	MFOB VARCHAR2(12), 
	MFOB_NAME VARCHAR2(256), 
	NLS_B VARCHAR2(15), 
	NAMB VARCHAR2(38), 
	OKPOB VARCHAR2(14), 
	PERCENT NUMBER(5,2), 
	SUMM_A NUMBER(38,0), 
	SUMM_B NUMBER(38,0), 
	DELTA NUMBER(38,0), 
	TT VARCHAR2(3), 
	VOB NUMBER, 
	NAZN VARCHAR2(256), 
	REF VARCHAR2(64), 
	NLS_COUNT NUMBER(38,0), 
	USERID NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSSMLD ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_DYNAMIC_LAYOUT_DETAIL ***
 exec bpa.alter_policies('TMP_DYNAMIC_LAYOUT_DETAIL');


COMMENT ON TABLE BARS.TMP_DYNAMIC_LAYOUT_DETAIL IS 'Деталі макету динамічних проводок';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.ID IS 'Ідентифікатор';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.DK IS 'Ознака 1 дебет, 2 - кредет';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.ND IS 'Номер документу(макету проводок)';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.KV IS 'Код валюти';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.BRANCH IS 'Код бранчу';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.BRANCH_NAME IS 'Назва бранчу';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.NLS_A IS 'Рахунок А';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.NAMA IS 'Найменування Рахуноку А';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.OKPOA IS 'ОКПО А';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.MFOB IS '';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.MFOB_NAME IS '';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.NLS_B IS 'Рахунок бранчу';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.NAMB IS 'МФО Б';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.OKPOB IS 'ОКПО Б';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.PERCENT IS 'відсоток від загальної суми';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.SUMM_A IS 'Сума проводки з рахунку А';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.SUMM_B IS 'Сума проводки в валюті Б';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.DELTA IS '+ или - константа к сумме';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.TT IS 'Тип операції';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.VOB IS 'Код ОП';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.NAZN IS '';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.REF IS '';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.NLS_COUNT IS 'Кількість рахунків Б';
COMMENT ON COLUMN BARS.TMP_DYNAMIC_LAYOUT_DETAIL.USERID IS '';



PROMPT *** Create  grants  TMP_DYNAMIC_LAYOUT_DETAIL ***
grant SELECT                                                                 on TMP_DYNAMIC_LAYOUT_DETAIL to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_DYNAMIC_LAYOUT_DETAIL to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on TMP_DYNAMIC_LAYOUT_DETAIL to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_DYNAMIC_LAYOUT_DETAIL.sql ========
PROMPT ===================================================================================== 
