

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_OPER_REVERT_DK.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_OPER_REVERT_DK ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_OPER_REVERT_DK ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_OPER_REVERT_DK 
   (	REF NUMBER(38,0), 
	DEAL_TAG NUMBER(38,0), 
	TT CHAR(3), 
	VOB NUMBER(38,0), 
	ND VARCHAR2(10), 
	PDAT DATE, 
	VDAT DATE, 
	KV NUMBER(*,0), 
	DK NUMBER(1,0), 
	S NUMBER(24,0), 
	SQ NUMBER(24,0), 
	SK NUMBER(2,0), 
	DATD DATE, 
	DATP DATE, 
	NAM_A VARCHAR2(38), 
	NLSA VARCHAR2(15), 
	MFOA VARCHAR2(12), 
	NAM_B VARCHAR2(38), 
	NLSB VARCHAR2(15), 
	MFOB VARCHAR2(12), 
	NAZN VARCHAR2(160), 
	D_REC VARCHAR2(60), 
	ID_A VARCHAR2(14), 
	ID_B VARCHAR2(14), 
	ID_O VARCHAR2(8), 
	SIGN RAW(2000), 
	SOS NUMBER(2,0), 
	VP NUMBER(1,0), 
	CHK CHAR(70), 
	S2 NUMBER(24,0), 
	KV2 NUMBER(38,0), 
	KVQ NUMBER(38,0), 
	REFL NUMBER(38,0), 
	PRTY NUMBER(1,0), 
	SQ2 NUMBER(24,0), 
	CURRVISAGRP VARCHAR2(4), 
	NEXTVISAGRP VARCHAR2(4), 
	REF_A VARCHAR2(9), 
	TOBO VARCHAR2(30), 
	OTM NUMBER(1,0), 
	SIGNED CHAR(1), 
	BRANCH VARCHAR2(30), 
	USERID NUMBER(38,0), 
	RESPID NUMBER, 
	KF VARCHAR2(6), 
	BIS NUMBER(38,0), 
	SOS_TRACKER NUMBER(38,0), 
	NEXT_VISA_BRANCHES VARCHAR2(128), 
	SOS_CHANGE_TIME DATE, 
	ODAT DATE, 
	BDAT DATE, 
	NEW_REF NUMBER(32,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_OPER_REVERT_DK ***
 exec bpa.alter_policies('TMP_OPER_REVERT_DK');


COMMENT ON TABLE BARS.TMP_OPER_REVERT_DK IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.REF IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.DEAL_TAG IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.TT IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.VOB IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.ND IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.PDAT IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.VDAT IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.KV IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.DK IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.S IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SQ IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SK IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.DATD IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.DATP IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NAM_A IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NLSA IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.MFOA IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NAM_B IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NLSB IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.MFOB IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NAZN IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.D_REC IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.ID_A IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.ID_B IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.ID_O IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SIGN IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SOS IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.VP IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.CHK IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.S2 IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.KV2 IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.KVQ IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.REFL IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.PRTY IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SQ2 IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.CURRVISAGRP IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NEXTVISAGRP IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.REF_A IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.TOBO IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.OTM IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SIGNED IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.USERID IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.RESPID IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.KF IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.BIS IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SOS_TRACKER IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NEXT_VISA_BRANCHES IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.SOS_CHANGE_TIME IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.ODAT IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.BDAT IS '';
COMMENT ON COLUMN BARS.TMP_OPER_REVERT_DK.NEW_REF IS '';



PROMPT *** Create  grants  TMP_OPER_REVERT_DK ***
grant SELECT                                                                 on TMP_OPER_REVERT_DK to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_OPER_REVERT_DK.sql =========*** En
PROMPT ===================================================================================== 
