

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CCK5.sql =========*** Run *** ====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CCK5 ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CCK5 ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARS.TMP_CCK5 
   (	BRANCH VARCHAR2(22), 
	SPOK VARCHAR2(7), 
	KV NUMBER(38,0), 
	SEGM VARCHAR2(7), 
	B1 DATE, 
	E1 DATE, 
	S11 NUMBER(18,2), 
	S12 NUMBER(18,2), 
	S13 NUMBER(18,2), 
	S14 NUMBER(18,2), 
	S15 NUMBER(18,2), 
	S16 NUMBER(18,2), 
	S17 NUMBER(18,2), 
	B2 DATE, 
	E2 DATE, 
	S21 NUMBER(18,2), 
	S22 NUMBER(18,2), 
	S23 NUMBER(18,2), 
	S24 NUMBER(18,2), 
	S25 NUMBER(18,2), 
	S26 NUMBER(18,2), 
	S27 NUMBER(18,2), 
	B3 DATE, 
	E3 DATE, 
	S31 NUMBER(18,2), 
	S32 NUMBER(18,2), 
	S33 NUMBER(18,2), 
	S34 NUMBER(18,2), 
	S35 NUMBER(18,2), 
	S36 NUMBER(18,2), 
	S37 NUMBER(18,2), 
	B4 DATE, 
	E4 DATE, 
	S41 NUMBER(18,2), 
	S42 NUMBER(18,2), 
	S43 NUMBER(18,2), 
	S44 NUMBER(18,2), 
	S45 NUMBER(18,2), 
	S46 NUMBER(18,2), 
	S47 NUMBER(18,2), 
	B5 DATE, 
	E5 DATE, 
	S51 NUMBER(18,2), 
	S52 NUMBER(18,2), 
	S53 NUMBER(18,2), 
	S54 NUMBER(18,2), 
	S55 NUMBER(18,2), 
	S56 NUMBER(18,2), 
	S57 NUMBER(18,2)
   ) ON COMMIT PRESERVE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CCK5 ***
 exec bpa.alter_policies('TMP_CCK5');


COMMENT ON TABLE BARS.TMP_CCK5 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S53 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S54 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S55 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S56 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S57 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.SPOK IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.KV IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.SEGM IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.B1 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.E1 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S11 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S12 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S13 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S14 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S15 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S16 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S17 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.B2 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.E2 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S21 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S22 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S23 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S24 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S25 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S26 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S27 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.B3 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.E3 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S31 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S32 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S33 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S34 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S35 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S36 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S37 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.B4 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.E4 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S41 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S42 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S43 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S44 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S45 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S46 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S47 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.B5 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.E5 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S51 IS '';
COMMENT ON COLUMN BARS.TMP_CCK5.S52 IS '';



PROMPT *** Create  grants  TMP_CCK5 ***
grant SELECT                                                                 on TMP_CCK5        to BARSREADER_ROLE;
grant SELECT                                                                 on TMP_CCK5        to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on TMP_CCK5        to RCC_DEAL;
grant SELECT                                                                 on TMP_CCK5        to SALGL;
grant SELECT                                                                 on TMP_CCK5        to UPLD;



PROMPT *** Create SYNONYM  to TMP_CCK5 ***

  CREATE OR REPLACE PUBLIC SYNONYM TMP0_CCK5 FOR BARS.TMP_CCK5;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CCK5.sql =========*** End *** ====
PROMPT ===================================================================================== 
