

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CP_OBU7.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CP_OBU7 ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CP_OBU7 ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_CP_OBU7 
   (	ID NUMBER(*,0), 
	ISIN VARCHAR2(20), 
	NBS_OLD NUMBER(4,0), 
	KV NUMBER(*,0), 
	REPO VARCHAR2(5), 
	D_K VARCHAR2(1), 
	PF_OLD NUMBER(*,0), 
	EMI VARCHAR2(50), 
	OKPO VARCHAR2(8), 
	AUKCION VARCHAR2(15), 
	DAT_K DATE, 
	NM_PROD VARCHAR2(50), 
	BV1 NUMBER, 
	CENA0 NUMBER, 
	KL1 NUMBER, 
	N1 NUMBER, 
	R1 NUMBER, 
	D1 NUMBER, 
	P1 NUMBER, 
	Z1 NUMBER, 
	S1 NUMBER, 
	CF007_019 NUMBER(1,0), 
	N2 NUMBER, 
	KL2 NUMBER, 
	KL_K2 NUMBER, 
	CENA_K2 NUMBER, 
	CF007_023 VARCHAR2(1), 
	DAT_K2 DATE, 
	NM_PROD2 VARCHAR2(50), 
	N2_P NUMBER, 
	KL2_P NUMBER, 
	CF007_028 VARCHAR2(1), 
	DAT_P2 DATE, 
	NM_POK VARCHAR2(50), 
	CENA_P2 NUMBER, 
	R2 NUMBER, 
	S2 NUMBER, 
	TR1_31 NUMBER, 
	KL31 NUMBER, 
	N31 NUMBER, 
	R31 NUMBER, 
	D31 NUMBER, 
	P31 NUMBER, 
	S31 NUMBER, 
	Z31 NUMBER, 
	IR31 NUMBER, 
	DAT_PG DATE, 
	CF007_042 DATE, 
	DAT_IR DATE, 
	KOT31 NUMBER, 
	CF007_045 VARCHAR2(30), 
	DAT_KOT DATE, 
	DAT_P4 DATE, 
	SUMB4 NUMBER, 
	NM_POK4 VARCHAR2(50), 
	KL_P4 NUMBER, 
	CENA_P4 NUMBER, 
	N4 NUMBER, 
	BV31 NUMBER, 
	PV31 NUMBER, 
	CF007_055 VARCHAR2(5), 
	CF007_056 NUMBER(1,0), 
	CF007_057 NUMBER, 
	CF007_058 NUMBER, 
	CF007_059 VARCHAR2(3), 
	CF007_060 NUMBER, 
	CF007_061 VARCHAR2(3), 
	CF007_062 VARCHAR2(20), 
	CF007_063 NUMBER(1,0), 
	DNK DATE, 
	CF007_065 VARCHAR2(14), 
	CF007_066 VARCHAR2(50), 
	DAT_R DATE, 
	NLS VARCHAR2(15), 
	NMS VARCHAR2(38), 
	REF NUMBER(*,0), 
	REF2 NUMBER(*,0), 
	VID_R CHAR(2), 
	CENA_START NUMBER, 
	IR NUMBER, 
	OST_V NUMBER, 
	FL NUMBER(*,0), 
	USERID NUMBER(*,0), 
	NLS_S VARCHAR2(15), 
	D2 NUMBER, 
	P2 NUMBER, 
	S_D NUMBER, 
	S_C NUMBER, 
	NLS_P VARCHAR2(15), 
	S_DP NUMBER, 
	S_CP NUMBER, 
	OST_I NUMBER, 
	S_DK NUMBER, 
	S_CK NUMBER, 
	OST_P NUMBER, 
	NLS_P1 VARCHAR2(15), 
	DAT_P DATE, 
	S_DP_NEW NUMBER, 
	S_CP_NEW NUMBER, 
	PAP NUMBER(*,0), 
	S_DK_NEW NUMBER, 
	S_CK_NEW NUMBER, 
	OST_PQ NUMBER, 
	OST_VQ NUMBER, 
	S_DQ NUMBER, 
	S_CQ NUMBER, 
	S_DKQ NUMBER, 
	S_CKQ NUMBER, 
	S_DPQ NUMBER, 
	S_CPQ NUMBER, 
	S_DPQ_NEW NUMBER, 
	S_CPQ_NEW NUMBER, 
	S_DKQ_NEW NUMBER, 
	S_CKQ_NEW NUMBER, 
	NBS_NEW NUMBER(4,0), 
	PF_NEW NUMBER(*,0), 
	OST_VT NUMBER, 
	OST_V31 NUMBER, 
	CENA NUMBER, 
	CENA4 NUMBER, 
	N0 NUMBER, 
	D0 NUMBER, 
	P0 NUMBER, 
	R0 NUMBER, 
	S0 NUMBER, 
	D4 NUMBER, 
	P4 NUMBER, 
	R4 NUMBER, 
	S4 NUMBER, 
	Z4 NUMBER, 
	KL0 NUMBER, 
	KL4 NUMBER, 
	DAT_4 DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CP_OBU7 ***
 exec bpa.alter_policies('TMP_CP_OBU7');


COMMENT ON TABLE BARS.TMP_CP_OBU7 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_045 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_KOT IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.SUMB4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NM_POK4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL_P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA_P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.N4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.BV31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.PV31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_055 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_056 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_057 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_058 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_059 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_060 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_061 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_062 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_063 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DNK IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_065 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_066 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_R IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NLS IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NMS IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.REF IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.REF2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.VID_R IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA_START IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.IR IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_V IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.FL IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.USERID IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NLS_S IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.D2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.P2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_D IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_C IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NLS_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DP IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CP IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_I IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DK IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CK IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NLS_P1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DP_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CP_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.PAP IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DK_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CK_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_PQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_VQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DKQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CKQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DPQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CPQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DPQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CPQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_DKQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S_CKQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NBS_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.PF_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_VT IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OST_V31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.N0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.D0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.P0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.R0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.D4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.R4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.Z4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.ID IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.ISIN IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NBS_OLD IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KV IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.REPO IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.D_K IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.PF_OLD IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.EMI IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.AUKCION IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_K IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NM_PROD IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.BV1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.N1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.R1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.D1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.P1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.Z1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_019 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.N2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL_K2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA_K2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_023 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_K2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NM_PROD2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.N2_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL2_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_028 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_P2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.NM_POK IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CENA_P2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.R2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.TR1_31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KL31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.N31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.R31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.D31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.P31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.S31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.Z31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.IR31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_PG IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.CF007_042 IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.DAT_IR IS '';
COMMENT ON COLUMN BARS.TMP_CP_OBU7.KOT31 IS '';



PROMPT *** Create  grants  TMP_CP_OBU7 ***
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_CP_OBU7     to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on TMP_CP_OBU7     to BARS_DM;
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_CP_OBU7     to START1;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CP_OBU7.sql =========*** End *** =
PROMPT ===================================================================================== 
