

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_NBU23_K11.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_NBU23_K11 ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_NBU23_K11 ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_NBU23_K11 
   (	FDAT DATE, 
	ID VARCHAR2(50), 
	RNK NUMBER, 
	NBS CHAR(4), 
	KV NUMBER, 
	ND NUMBER, 
	CC_ID VARCHAR2(50), 
	ACC NUMBER, 
	NLS VARCHAR2(20), 
	BRANCH VARCHAR2(30), 
	FIN NUMBER, 
	OBS NUMBER, 
	KAT NUMBER, 
	K NUMBER, 
	IRR NUMBER, 
	ZAL NUMBER, 
	BV NUMBER, 
	PV NUMBER, 
	REZ NUMBER, 
	REZQ NUMBER, 
	DD CHAR(1), 
	DDD CHAR(3), 
	BVQ NUMBER, 
	CUSTTYPE NUMBER, 
	IDR NUMBER, 
	WDATE DATE, 
	OKPO NUMBER, 
	NMK VARCHAR2(35), 
	RZ NUMBER, 
	PAWN NUMBER, 
	ISTVAL NUMBER, 
	R013 CHAR(1), 
	REZN NUMBER, 
	REZNQ NUMBER, 
	ARJK NUMBER, 
	PVZ NUMBER, 
	PVZQ NUMBER, 
	ZALQ NUMBER, 
	ZPR NUMBER, 
	ZPRQ NUMBER, 
	PVQ NUMBER, 
	RU VARCHAR2(70), 
	INN VARCHAR2(20), 
	NRC VARCHAR2(70), 
	SDATE DATE, 
	IR NUMBER, 
	S031 VARCHAR2(2), 
	K040 VARCHAR2(3), 
	PROD VARCHAR2(50), 
	K110 VARCHAR2(5), 
	K070 VARCHAR2(5), 
	K051 VARCHAR2(2), 
	S260 VARCHAR2(2), 
	R011 VARCHAR2(1), 
	R012 VARCHAR2(1), 
	S240 VARCHAR2(1), 
	S180 VARCHAR2(1), 
	S580 VARCHAR2(1), 
	NLS_REZ VARCHAR2(15), 
	NLS_REZN VARCHAR2(15), 
	S250 CHAR(1), 
	ACC_REZ NUMBER, 
	FIN_R NUMBER(*,0), 
	DISKONT NUMBER, 
	ISP NUMBER(*,0), 
	OB22 CHAR(2), 
	TIP CHAR(3), 
	SPEC CHAR(1), 
	ZAL_BL NUMBER, 
	S280_290 CHAR(1), 
	ZAL_BLQ NUMBER, 
	REZD NUMBER, 
	ACC_REZN NUMBER, 
	OB22_REZ CHAR(2), 
	OB22_REZN CHAR(2), 
	IR0 NUMBER, 
	IRR0 NUMBER, 
	ND_CP VARCHAR2(40), 
	SUM_IMP NUMBER, 
	SUMQ_IMP NUMBER, 
	PV_ZAL NUMBER, 
	VKR VARCHAR2(10), 
	S_L NUMBER, 
	SQ_L NUMBER, 
	ZAL_SV NUMBER, 
	ZAL_SVQ NUMBER, 
	GRP NUMBER(*,0), 
	KOL_SP NUMBER(*,0), 
	PVP NUMBER, 
	BV_30 NUMBER, 
	BVQ_30 NUMBER, 
	REZ_30 NUMBER, 
	REZQ_30 NUMBER, 
	NLS_REZ_30 VARCHAR2(15), 
	ACC_REZ_30 NUMBER, 
	BV_0 NUMBER, 
	BVQ_0 NUMBER, 
	REZ_0 NUMBER, 
	REZQ_0 NUMBER, 
	NLS_REZ_0 VARCHAR2(15), 
	ACC_REZ_0 NUMBER, 
	REZ39 NUMBER, 
	S250_23 VARCHAR2(1), 
	KAT39 NUMBER, 
	REZQ39 NUMBER, 
	S250_39 VARCHAR2(1), 
	REZ23 NUMBER, 
	REZQ23 NUMBER, 
	KAT23 NUMBER, 
	DAT_MI DATE, 
	OB22_REZ_30 CHAR(2), 
	OB22_REZ_0 CHAR(2), 
	TIPA NUMBER(*,0), 
	BVUQ NUMBER, 
	BVU NUMBER, 
	KF VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_NBU23_K11 ***
 exec bpa.alter_policies('TMP_NBU23_K11');


COMMENT ON TABLE BARS.TMP_NBU23_K11 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S250_23 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.KAT39 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZQ39 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S250_39 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZ23 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZQ23 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.KAT23 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.DAT_MI IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OB22_REZ_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OB22_REZ_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.TIPA IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BVUQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BVU IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.KF IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.FDAT IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ID IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.RNK IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NBS IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.KV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ND IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.CC_ID IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ACC IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NLS IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.FIN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OBS IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.KAT IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.K IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.IRR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZAL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.DD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.DDD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BVQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.IDR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.WDATE IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NMK IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.RZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PAWN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ISTVAL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.R013 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZNQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ARJK IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PVZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PVZQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZALQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZPR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZPRQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PVQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.RU IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.INN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NRC IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.SDATE IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.IR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S031 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.K040 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PROD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.K110 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.K070 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.K051 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S260 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.R011 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.R012 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S240 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S180 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S580 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NLS_REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NLS_REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S250 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ACC_REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.FIN_R IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.DISKONT IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ISP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OB22 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.TIP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.SPEC IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZAL_BL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S280_290 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZAL_BLQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ACC_REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OB22_REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.OB22_REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.IR0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.IRR0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ND_CP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.SUM_IMP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.SUMQ_IMP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PV_ZAL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.VKR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.S_L IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.SQ_L IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZAL_SV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ZAL_SVQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.GRP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.KOL_SP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.PVP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BV_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BVQ_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZ_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZQ_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NLS_REZ_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ACC_REZ_30 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BV_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.BVQ_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZ_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZQ_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.NLS_REZ_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.ACC_REZ_0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_K11.REZ39 IS '';




PROMPT *** Create  constraint SYS_C0031762 ***
begin   
 execute immediate '
  ALTER TABLE BARS.TMP_NBU23_K11 MODIFY (KF NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_NBU23_K11.sql =========*** End ***
PROMPT ===================================================================================== 
