

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_LICN.sql =========*** Run *** ====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_LICN ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_LICN ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARS.TMP_LICN 
   (	FDAT DATE, 
	TIP CHAR(3), 
	ACC NUMBER, 
	S NUMBER(24,0), 
	SQ NUMBER(24,0), 
	ND VARCHAR2(10), 
	MFO VARCHAR2(12), 
	NAZN VARCHAR2(230), 
	VDAT DATE, 
	NLSK VARCHAR2(15), 
	NAMK VARCHAR2(70), 
	USERID NUMBER, 
	REF NUMBER, 
	TT CHAR(3), 
	SK NUMBER, 
	DAPP DATE, 
	OSTF NUMBER(24,0), 
	OSTFQ NUMBER(24,0), 
	OSTFR NUMBER(24,0), 
	ISP NUMBER(38,0), 
	KV NUMBER(38,0), 
	NLS VARCHAR2(15), 
	NMS VARCHAR2(70), 
	OKPO VARCHAR2(14), 
	NB VARCHAR2(38), 
	VOB NUMBER, 
	BIS NUMBER, 
	DATP DATE, 
	DOS NUMBER(24,0), 
	KOS NUMBER(24,0), 
	DOSQ NUMBER(24,0), 
	KOSQ NUMBER(24,0), 
	DOSR NUMBER(24,0), 
	KOSR NUMBER(24,0), 
	CURS NUMBER(10,3), 
	DK NUMBER, 
	MFO2 VARCHAR2(6), 
	NAMK2 VARCHAR2(70), 
	OKPO2 VARCHAR2(14), 
	SRT CHAR(1), 
	PDAT DATE, 
	GRPLST VARCHAR2(70)
   ) ON COMMIT PRESERVE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_LICN ***
 exec bpa.alter_policies('TMP_LICN');


COMMENT ON TABLE BARS.TMP_LICN IS '';
COMMENT ON COLUMN BARS.TMP_LICN.FDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICN.TIP IS '';
COMMENT ON COLUMN BARS.TMP_LICN.ACC IS '';
COMMENT ON COLUMN BARS.TMP_LICN.S IS '';
COMMENT ON COLUMN BARS.TMP_LICN.SQ IS '';
COMMENT ON COLUMN BARS.TMP_LICN.ND IS '';
COMMENT ON COLUMN BARS.TMP_LICN.MFO IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NAZN IS '';
COMMENT ON COLUMN BARS.TMP_LICN.VDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NLSK IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NAMK IS '';
COMMENT ON COLUMN BARS.TMP_LICN.USERID IS '';
COMMENT ON COLUMN BARS.TMP_LICN.REF IS '';
COMMENT ON COLUMN BARS.TMP_LICN.TT IS '';
COMMENT ON COLUMN BARS.TMP_LICN.SK IS '';
COMMENT ON COLUMN BARS.TMP_LICN.DAPP IS '';
COMMENT ON COLUMN BARS.TMP_LICN.OSTF IS '';
COMMENT ON COLUMN BARS.TMP_LICN.OSTFQ IS '';
COMMENT ON COLUMN BARS.TMP_LICN.OSTFR IS '';
COMMENT ON COLUMN BARS.TMP_LICN.ISP IS '';
COMMENT ON COLUMN BARS.TMP_LICN.KV IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NLS IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NMS IS '';
COMMENT ON COLUMN BARS.TMP_LICN.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NB IS '';
COMMENT ON COLUMN BARS.TMP_LICN.VOB IS '';
COMMENT ON COLUMN BARS.TMP_LICN.BIS IS '';
COMMENT ON COLUMN BARS.TMP_LICN.DATP IS '';
COMMENT ON COLUMN BARS.TMP_LICN.DOS IS '';
COMMENT ON COLUMN BARS.TMP_LICN.KOS IS '';
COMMENT ON COLUMN BARS.TMP_LICN.DOSQ IS '';
COMMENT ON COLUMN BARS.TMP_LICN.KOSQ IS '';
COMMENT ON COLUMN BARS.TMP_LICN.DOSR IS '';
COMMENT ON COLUMN BARS.TMP_LICN.KOSR IS '';
COMMENT ON COLUMN BARS.TMP_LICN.CURS IS '';
COMMENT ON COLUMN BARS.TMP_LICN.DK IS '';
COMMENT ON COLUMN BARS.TMP_LICN.MFO2 IS '';
COMMENT ON COLUMN BARS.TMP_LICN.NAMK2 IS '';
COMMENT ON COLUMN BARS.TMP_LICN.OKPO2 IS '';
COMMENT ON COLUMN BARS.TMP_LICN.SRT IS '';
COMMENT ON COLUMN BARS.TMP_LICN.PDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICN.GRPLST IS '';



PROMPT *** Create  grants  TMP_LICN ***
grant ALTER,DELETE,INSERT,SELECT,UPDATE                                      on TMP_LICN        to BARS_ACCESS_DEFROLE;
grant ALTER,DELETE,INSERT,SELECT,UPDATE                                      on TMP_LICN        to RPBN001;
grant SELECT                                                                 on TMP_LICN        to TEST;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on TMP_LICN        to WR_ALL_RIGHTS;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_LICN.sql =========*** End *** ====
PROMPT ===================================================================================== 
