

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CIG_CUST_INDIVIDUAL.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CIG_CUST_INDIVIDUAL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CIG_CUST_INDIVIDUAL ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_CIG_CUST_INDIVIDUAL 
   (	CUST_ID NUMBER(38,0), 
	ROLE_ID NUMBER(4,0), 
	FIRST_NAME VARCHAR2(38), 
	SURNAME VARCHAR2(38), 
	FATHERS_NAME VARCHAR2(38), 
	GENDER NUMBER(1,0), 
	CLASSIFICATION NUMBER(4,0), 
	BIRTH_SURNAME VARCHAR2(38), 
	DATE_BIRTH DATE, 
	PLACE_BIRTH VARCHAR2(70), 
	RESIDENCY NUMBER(4,0), 
	CITIZENSHIP CHAR(2), 
	NEG_STATUS NUMBER(4,0), 
	EDUCATION NUMBER(4,0), 
	MARITAL_STATUS NUMBER(4,0), 
	POSITION NUMBER(4,0), 
	CUST_KEY VARCHAR2(70), 
	PASSP_SER VARCHAR2(10), 
	PASSP_NUM VARCHAR2(20), 
	PASSP_ISS_DATE DATE, 
	PASSP_EXP_DATE DATE, 
	PASSP_ORGAN VARCHAR2(70), 
	PHONE_OFFICE VARCHAR2(20), 
	PHONE_MOBILE VARCHAR2(20), 
	PHONE_FAX VARCHAR2(20), 
	EMAIL VARCHAR2(38), 
	WEBSITE VARCHAR2(38), 
	FACT_TERRITORY_ID NUMBER(38,0), 
	FACT_STREET_BUILDNUM VARCHAR2(250), 
	FACT_POST_INDEX VARCHAR2(20), 
	REG_TERRITORY_ID NUMBER(38,0), 
	REG_STREET_BUILDNUM VARCHAR2(250), 
	REG_POST_INDEX VARCHAR2(20), 
	BRANCH VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CIG_CUST_INDIVIDUAL ***
 exec bpa.alter_policies('TMP_CIG_CUST_INDIVIDUAL');


COMMENT ON TABLE BARS.TMP_CIG_CUST_INDIVIDUAL IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.CUST_ID IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.ROLE_ID IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.FIRST_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.SURNAME IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.FATHERS_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.GENDER IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.CLASSIFICATION IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.BIRTH_SURNAME IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.DATE_BIRTH IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PLACE_BIRTH IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.RESIDENCY IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.CITIZENSHIP IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.NEG_STATUS IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.EDUCATION IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.MARITAL_STATUS IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.POSITION IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.CUST_KEY IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PASSP_SER IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PASSP_NUM IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PASSP_ISS_DATE IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PASSP_EXP_DATE IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PASSP_ORGAN IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PHONE_OFFICE IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PHONE_MOBILE IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.PHONE_FAX IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.EMAIL IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.WEBSITE IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.FACT_TERRITORY_ID IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.FACT_STREET_BUILDNUM IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.FACT_POST_INDEX IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.REG_TERRITORY_ID IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.REG_STREET_BUILDNUM IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.REG_POST_INDEX IS '';
COMMENT ON COLUMN BARS.TMP_CIG_CUST_INDIVIDUAL.BRANCH IS '';



PROMPT *** Create  grants  TMP_CIG_CUST_INDIVIDUAL ***
grant SELECT                                                                 on TMP_CIG_CUST_INDIVIDUAL to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CIG_CUST_INDIVIDUAL.sql =========*
PROMPT ===================================================================================== 
