Prompt drop TABLE TMP_EKP_2_01;
DROP TABLE BARS.TMP_EKP_2_01 CASCADE CONSTRAINTS;

Prompt Table TMP_EKP_2_01;
CREATE TABLE BARS.TMP_EKP_2_01
(
  A010       VARCHAR2(2 BYTE),
  KUDA       VARCHAR2(10 BYTE),
  EK_POK     VARCHAR2(16 BYTE),
  TXT        VARCHAR2(2000 BYTE),
  PRM1       VARCHAR2(250 BYTE),
  PRM2       VARCHAR2(250 BYTE),
  PRM3       VARCHAR2(250 BYTE),
  PRM4       VARCHAR2(250 BYTE),
  PRM5       VARCHAR2(250 BYTE),
  PRM6       VARCHAR2(250 BYTE),
  PRM7       VARCHAR2(250 BYTE),
  FILT_REP2  VARCHAR2(250 BYTE),
  PREM       VARCHAR2(250 BYTE),
  DATA_O     DATE,
  DATA_M     DATE,
  DATA_C     DATE,
  PRM8       VARCHAR2(250 BYTE)
)
TABLESPACE BRSDYND
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
