--ALTER TABLE BARS.W4_ACC_INST DROP PRIMARY KEY CASCADE;
--DROP TABLE BARS.W4_ACC_INST CASCADE CONSTRAINTS;

PROMPT ===================================================================================== 
PROMPT *** Run *** ===== Scripts /Sql/BARSUPL/Table/W4_ACC_INST_UPDATE.sql ====*** Run *
PROMPT ===================================================================================== 

--PROMPT *** ADD  W4_ACC_INST_UPDATE into POLICY_TABLE ***
begin
  execute immediate 'begin bars.bpa.alter_policy_info( ''BARS'', ''W4_ACC_INST_UPDATE'', ''CENTER'',  null, ''E'', ''E'', ''E'' ); end;';
  execute immediate 'begin bars.bpa.alter_policy_info( ''BARS'', ''W4_ACC_INST_UPDATE'', ''WHOLE'',   null, ''E'', ''E'', ''E'' ); end;';
  execute immediate 'begin bars.bpa.alter_policy_info( ''BARS'', ''W4_ACC_INST_UPDATE'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'' ); end;'; 
  commit;
end;
/

PROMPT *** Create  table W4_ACC_INST_UPDATE ***
begin
  execute immediate '
CREATE TABLE BARS.W4_ACC_INST_UPDATE
( IDUPD       NUMBER,
  CHGACTION   CHAR(1),
  EFFECTDATE  DATE,
  GLOBALBD    DATE,
  CHGDATE     DATE,
  DONEBY      NUMBER,
  ND          NUMBER               constraint CC_W4INSTUPD_ND_NN NOT NULL,
  ACC_PK      NUMBER,
  CHAIN_IDT   NUMBER,
  TRANS_MASK  VARCHAR2(15 BYTE),
  ACC         NUMBER               constraint CC_W4INSTUPD_ACC_NN NOT NULL,
  CRT_BD      DATE,
  KF          VARCHAR2(6 BYTE)     constraint CC_W4INSTUPD_KF_NN NOT NULL
)
TABLESPACE BRSMDLD
PARTITION BY LIST (KF)
  (PARTITION "P_W4INSTUPD_300465" VALUES (''300465'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_324805" VALUES (''324805'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_302076" VALUES (''302076'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_303398" VALUES (''303398'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_305482" VALUES (''305482'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_335106" VALUES (''335106'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_311647" VALUES (''311647'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_312356" VALUES (''312356'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_313957" VALUES (''313957'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_336503" VALUES (''336503'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_322669" VALUES (''322669'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_323475" VALUES (''323475'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_304665" VALUES (''304665'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_325796" VALUES (''325796'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_326461" VALUES (''326461'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_328845" VALUES (''328845'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_331467" VALUES (''331467'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_333368" VALUES (''333368'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_337568" VALUES (''337568'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_338545" VALUES (''338545'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_351823" VALUES (''351823'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_352457" VALUES (''352457'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_315784" VALUES (''315784'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_354507" VALUES (''354507'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_356334" VALUES (''356334'') TABLESPACE BRSMDLD,
   PARTITION "P_W4INSTUPD_353553" VALUES (''353553'') TABLESPACE BRSMDLD
  )';

exception when others then
  if sqlcode=-955 then null; else raise; end if;
end;
/

COMMENT ON TABLE  BARS.W4_ACC_INST_UPDATE            IS 'Рахунки угоди';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.IDUPD      IS 'Идентификатор изменения';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.CHGACTION  IS 'Тип изменения';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.EFFECTDATE IS 'банковская дата изменения';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.GLOBALBD   IS 'Глобальна банківська дата';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.CHGDATE    IS 'Дата/время изменения';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.DONEBY     IS 'ID пользователя, выполнившего изменения';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.ND         IS 'Договор БПК';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.ACC_PK     IS 'Поточний картковий рахунок';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.CHAIN_IDT  IS '';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.TRANS_MASK IS '';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.ACC        IS 'Идентификатор счета';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.CRT_BD     IS '';
COMMENT ON COLUMN BARS.W4_ACC_INST_UPDATE.KF         IS 'МФО региона';


PROMPT *** ALTER  POLICIES  W4_ACC_INST_UPDATE***
 exec bars.bpa.alter_policies( 'BARS', 'W4_ACC_INST_UPDATE');


PROMPT *** Create  constraint PK_CPACCUPD ***
begin   
 execute immediate '
  ALTER TABLE BARS.W4_ACC_INST_UPDATE ADD CONSTRAINT PK_W4_ACC_INST_UPD PRIMARY KEY (IDUPD)
  USING INDEX COMPUTE STATISTICS TABLESPACE BRSDYND  ENABLE VALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/

PROMPT *** Create  index IDX_W4ACCINSTUPD_PK_ID ***
begin   
 execute immediate '
  CREATE INDEX BARS.IDX_W4ACCINSTUPD_PK_ID  ON BARS.W4_ACC_INST_UPDATE (KF, ACC_PK, CHAIN_IDT, TRANS_MASK, IDUPD) LOCAL
  COMPUTE STATISTICS TABLESPACE BRSDYND COMPRESS 2';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/

PROMPT *** Create  index IDX_W4ACCINSTUPD__EF_GL ***
begin   
 execute immediate '
  CREATE INDEX BARS.IDX_W4ACCINSTUPD__EF_GL ON BARS.W4_ACC_INST_UPDATE (EFFECTDATE, GLOBALBD) LOCAL
  COMPUTE STATISTICS TABLESPACE BRSDYND COMPRESS 2';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/





