

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/WCS_BID_STATES_BACKUP.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to WCS_BID_STATES_BACKUP ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''WCS_BID_STATES_BACKUP'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_BID_STATES_BACKUP'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_BID_STATES_BACKUP'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table WCS_BID_STATES_BACKUP ***
begin 
  execute immediate '
  CREATE TABLE BARS.WCS_BID_STATES_BACKUP 
   (	BID_ID NUMBER, 
	STATE_ID VARCHAR2(100), 
	CHECKOUTED NUMBER DEFAULT 0, 
	CHECKOUT_DAT DATE, 
	CHECKOUT_USER_ID NUMBER, 
	USER_COMMENT VARCHAR2(4000), 
	BACKUP_DATE DATE, 
	 CONSTRAINT FK_BIDSTATESBU_BID_BIDS_ID FOREIGN KEY (BID_ID)
	  REFERENCES BARS.WCS_BIDS (ID) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  PARTITION BY REFERENCE (FK_BIDSTATESBU_BID_BIDS_ID) 
 (PARTITION WCSBIDS_Y2011_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q1 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q1 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q1 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to WCS_BID_STATES_BACKUP ***
 exec bpa.alter_policies('WCS_BID_STATES_BACKUP');


COMMENT ON TABLE BARS.WCS_BID_STATES_BACKUP IS 'Резервная копия состояния заявки';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.BID_ID IS 'Идентификатор заявки';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.STATE_ID IS 'Идентификатор состояния';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.CHECKOUTED IS 'Блокирована ли заявка (0/1)';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.CHECKOUT_DAT IS 'Дата блокировки заявки';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.CHECKOUT_USER_ID IS 'Пользователь заблокировавший заявку';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.USER_COMMENT IS 'Комментарий пользователя';
COMMENT ON COLUMN BARS.WCS_BID_STATES_BACKUP.BACKUP_DATE IS 'Дата резервного копирования';




PROMPT *** Create  constraint PK_BIDSTATESBU ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_BACKUP ADD CONSTRAINT PK_BIDSTATESBU PRIMARY KEY (BID_ID, STATE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_BIDSTATESBU_CHECKOUTED ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_BACKUP ADD CONSTRAINT CC_BIDSTATESBU_CHECKOUTED CHECK (checkouted in (0, 1)) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_BIDSTATESBU_BIDID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_BACKUP MODIFY (BID_ID CONSTRAINT CC_BIDSTATESBU_BIDID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_BIDSTATESBU_BID_BIDS_ID ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_BACKUP ADD CONSTRAINT FK_BIDSTATESBU_BID_BIDS_ID FOREIGN KEY (BID_ID)
	  REFERENCES BARS.WCS_BIDS (ID) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_BIDSTATESBU ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_BIDSTATESBU ON BARS.WCS_BID_STATES_BACKUP (BID_ID, STATE_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  WCS_BID_STATES_BACKUP ***
grant DELETE,INSERT,SELECT,UPDATE                                            on WCS_BID_STATES_BACKUP to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on WCS_BID_STATES_BACKUP to START1;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/WCS_BID_STATES_BACKUP.sql =========***
PROMPT ===================================================================================== 
