

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/WCS_BID_STATES_HISTORY.sql =========**
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to WCS_BID_STATES_HISTORY ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''WCS_BID_STATES_HISTORY'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_BID_STATES_HISTORY'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_BID_STATES_HISTORY'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table WCS_BID_STATES_HISTORY ***
begin 
  execute immediate '
  CREATE TABLE BARS.WCS_BID_STATES_HISTORY 
   (	ID NUMBER, 
	BID_ID NUMBER, 
	STATE_ID VARCHAR2(100), 
	CHECKOUTED NUMBER DEFAULT 0, 
	CHECKOUT_DAT DATE, 
	CHECKOUT_USER_ID NUMBER, 
	USER_COMMENT VARCHAR2(4000), 
	CHANGE_ACTION VARCHAR2(100), 
	CHANGE_DAT DATE, 
	LAST_DATE DATE, 
	 CONSTRAINT FK_BIDSTATESHIST_BID_BIDS_ID FOREIGN KEY (BID_ID)
	  REFERENCES BARS.WCS_BIDS (ID) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  PARTITION BY REFERENCE (FK_BIDSTATESHIST_BID_BIDS_ID) 
 (PARTITION WCSBIDS_Y2011_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2017_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2017_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2017_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2017_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2018_Q1 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2018_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2018_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2018_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to WCS_BID_STATES_HISTORY ***
 exec bpa.alter_policies('WCS_BID_STATES_HISTORY');


COMMENT ON TABLE BARS.WCS_BID_STATES_HISTORY IS 'История состояний заявки';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.ID IS 'Идентификатор записи';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.BID_ID IS 'Идентификатор заявки';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.STATE_ID IS 'Идентификатор состояния';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.CHECKOUTED IS 'Блокирована ли заявка (0/1)';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.CHECKOUT_DAT IS 'Дата блокировки заявки';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.CHECKOUT_USER_ID IS 'Пользователь заблокировавший заявку';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.USER_COMMENT IS 'Комментарий пользователя';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.CHANGE_ACTION IS 'Действие';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.CHANGE_DAT IS 'Дата действия';
COMMENT ON COLUMN BARS.WCS_BID_STATES_HISTORY.LAST_DATE IS 'Дата последнего изменения (используется при захвате изменений)';




PROMPT *** Create  constraint CC_BIDSTATESHISTORY_BIDID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY MODIFY (BID_ID CONSTRAINT CC_BIDSTATESHISTORY_BIDID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_BIDSTATESHISTORY_STATEID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY MODIFY (STATE_ID CONSTRAINT CC_BIDSTATESHISTORY_STATEID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_BIDSTATESHIST_CHGACT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY MODIFY (CHANGE_ACTION CONSTRAINT CC_BIDSTATESHIST_CHGACT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_BIDSTATESHIST_CHGDAT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY MODIFY (CHANGE_DAT CONSTRAINT CC_BIDSTATESHIST_CHGDAT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_BIDSTATESHIST ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY ADD CONSTRAINT PK_BIDSTATESHIST PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint UK_BIDSTATESHIST ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY ADD CONSTRAINT UK_BIDSTATESHIST UNIQUE (BID_ID, STATE_ID, CHANGE_ACTION, CHANGE_DAT)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI  ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_BIDSTATESHIST_CHECKOUTED ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BID_STATES_HISTORY ADD CONSTRAINT CC_BIDSTATESHIST_CHECKOUTED CHECK (checkouted in (0, 1)) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_BIDSTATESHIST_LDATE ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_BIDSTATESHIST_LDATE ON BARS.WCS_BID_STATES_HISTORY (LAST_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_BIDSTATESHIST ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_BIDSTATESHIST ON BARS.WCS_BID_STATES_HISTORY (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_BIDSTATESHIST ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_BIDSTATESHIST ON BARS.WCS_BID_STATES_HISTORY (BID_ID, STATE_ID, CHANGE_ACTION, CHANGE_DAT) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  WCS_BID_STATES_HISTORY ***
grant SELECT                                                                 on WCS_BID_STATES_HISTORY to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on WCS_BID_STATES_HISTORY to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on WCS_BID_STATES_HISTORY to START1;
grant SELECT                                                                 on WCS_BID_STATES_HISTORY to UPLD;
grant SELECT                                                                 on WCS_BID_STATES_HISTORY to WCS_SYNC_USER;



PROMPT *** Create SYNONYM  to WCS_BID_STATES_HISTORY ***

  CREATE OR REPLACE PUBLIC SYNONYM WCS_BID_STATES_HISTORY FOR BARS.WCS_BID_STATES_HISTORY;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/WCS_BID_STATES_HISTORY.sql =========**
PROMPT ===================================================================================== 
