

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ZAYAVKA_RU.sql =========*** Run *** ==
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ZAYAVKA_RU ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''ZAYAVKA_RU'', ''CENTER'' , null, ''E'', ''E'', ''E'');
               bpa.alter_policy_info(''ZAYAVKA_RU'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''ZAYAVKA_RU'', ''WHOLE'' , null, ''E'', ''E'', ''E'');
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ZAYAVKA_RU ***
begin 
  execute immediate '
  CREATE TABLE BARS.ZAYAVKA_RU 
   (	ID NUMBER(22,0), 
	MFO VARCHAR2(6), 
	REQ_ID NUMBER(22,0), 
	DK NUMBER(1,0), 
	OBZ NUMBER(1,0), 
	ND VARCHAR2(10), 
	FDAT DATE, 
	DATT DATE, 
	RNK NUMBER(22,0), 
	NMK VARCHAR2(70), 
	ND_RNK VARCHAR2(38), 
	KV_CONV NUMBER(3,0), 
	LCV_CONV CHAR(3), 
	KV2 NUMBER(3,0), 
	LCV CHAR(3), 
	DIG NUMBER(10,0), 
	S2 NUMBER(22,0), 
	S2S NUMBER(22,0), 
	S3 NUMBER(22,0), 
	KOM NUMBER(10,4), 
	SKOM NUMBER(10,2), 
	KURS_Z NUMBER(16,8), 
	KURS_F NUMBER(16,8), 
	VDATE DATE, 
	DATZ DATE, 
	ACC0 NUMBER(22,0), 
	NLS_ACC0 VARCHAR2(15), 
	MFO0 VARCHAR2(12), 
	NLS0 VARCHAR2(15), 
	OKPO0 VARCHAR2(14), 
	OSTC0 NUMBER(24,0), 
	ACC1 NUMBER(22,0), 
	OSTC NUMBER(24,0), 
	NLS VARCHAR2(15), 
	SOS NUMBER(2,1), 
	REF NUMBER(22,0), 
	VIZA NUMBER(10,0), 
	PRIORITY NUMBER(10,0), 
	PRIORNAME VARCHAR2(50), 
	PRIORVERIFY NUMBER(1,0), 
	IDBACK NUMBER(10,0), 
	FL_PF NUMBER(1,0), 
	MFOP VARCHAR2(12), 
	NLSP VARCHAR2(15), 
	OKPOP VARCHAR2(10), 
	RNK_PF VARCHAR2(20), 
	PID NUMBER(22,0), 
	CONTRACT VARCHAR2(50), 
	DAT2_VMD DATE, 
	META NUMBER(2,0), 
	AIM_NAME VARCHAR2(50), 
	BASIS VARCHAR2(512), 
	PRODUCT_GROUP CHAR(2), 
	PRODUCT_GROUP_NAME VARCHAR2(102), 
	NUM_VMD VARCHAR2(35), 
	DAT_VMD DATE, 
	DAT5_VMD VARCHAR2(240), 
	COUNTRY NUMBER(3,0), 
	BENEFCOUNTRY NUMBER(3,0), 
	BANK_CODE VARCHAR2(10), 
	BANK_NAME VARCHAR2(60), 
	USERID NUMBER(22,0), 
	BRANCH VARCHAR2(30), 
	FL_KURSZ NUMBER(1,0), 
	IDENTKB VARCHAR2(16), 
	COMM VARCHAR2(250), 
	CUST_BRANCH VARCHAR2(30), 
	KURS_KL VARCHAR2(30), 
	CONTACT_FIO VARCHAR2(70), 
	CONTACT_TEL VARCHAR2(32), 
	VERIFY_OPT NUMBER(1,0), 
	CLOSE_TYPE NUMBER(1,0), 
	CLOSE_TYPE_NAME VARCHAR2(100), 
	AIMS_CODE NUMBER(2,0), 
	S_PF NUMBER(22,0), 
	REF_PF NUMBER(22,0), 
	REF_SPS NUMBER(22,0), 
	START_TIME DATE, 
	STATE VARCHAR2(100), 
	OPERID_NOKK VARCHAR2(30), 
	REQ_TYPE NUMBER(10,0), 
	REF_SPS_CHECK NUMBER(22,0), 
	VDATE_PLAN DATE, 
	CUSTTYPE NUMBER(1,0), 
	REASON_COMM VARCHAR2(254)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSMDLD ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ZAYAVKA_RU ***
 exec bpa.alter_policies('ZAYAVKA_RU');


COMMENT ON TABLE BARS.ZAYAVKA_RU IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.BENEFCOUNTRY IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.BANK_CODE IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.BANK_NAME IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.USERID IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.BRANCH IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.FL_KURSZ IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.IDENTKB IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.COMM IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CUST_BRANCH IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.KURS_KL IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CONTACT_FIO IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CONTACT_TEL IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.VERIFY_OPT IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CLOSE_TYPE IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CLOSE_TYPE_NAME IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.AIMS_CODE IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.S_PF IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REF_PF IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REF_SPS IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.START_TIME IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.STATE IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.OPERID_NOKK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REQ_TYPE IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REF_SPS_CHECK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.VDATE_PLAN IS 'Плановая дата валютирования';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CUSTTYPE IS 'Тип клиента';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REASON_COMM IS 'Причина возврата заявки';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.ID IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.MFO IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REQ_ID IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.OBZ IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.ND IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.FDAT IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DATT IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.RNK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.NMK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.ND_RNK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.KV_CONV IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.LCV_CONV IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.KV2 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.LCV IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DIG IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.S2 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.S2S IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.S3 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.KOM IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.SKOM IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.KURS_Z IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.KURS_F IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.VDATE IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DATZ IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.ACC0 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.NLS_ACC0 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.MFO0 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.NLS0 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.OKPO0 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.OSTC0 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.ACC1 IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.OSTC IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.NLS IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.SOS IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.REF IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.VIZA IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.PRIORITY IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.PRIORNAME IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.PRIORVERIFY IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.IDBACK IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.FL_PF IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.MFOP IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.NLSP IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.OKPOP IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.RNK_PF IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.PID IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.CONTRACT IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DAT2_VMD IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.META IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.AIM_NAME IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.BASIS IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.PRODUCT_GROUP IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.PRODUCT_GROUP_NAME IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.NUM_VMD IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DAT_VMD IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.DAT5_VMD IS '';
COMMENT ON COLUMN BARS.ZAYAVKA_RU.COUNTRY IS '';




PROMPT *** Create  constraint PK_ZAYAVKARU ***
begin   
 execute immediate '
  ALTER TABLE BARS.ZAYAVKA_RU ADD CONSTRAINT PK_ZAYAVKARU PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSMDLD  ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint UK_ZAYAVKARU ***
begin   
 execute immediate '
  ALTER TABLE BARS.ZAYAVKA_RU ADD CONSTRAINT UK_ZAYAVKARU UNIQUE (MFO, REQ_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSMDLI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_ZAYAVKARU ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_ZAYAVKARU ON BARS.ZAYAVKA_RU (MFO, REQ_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSMDLI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_ZAYAVKARU ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_ZAYAVKARU ON BARS.ZAYAVKA_RU (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSMDLD ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  ZAYAVKA_RU ***
grant SELECT                                                                 on ZAYAVKA_RU      to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on ZAYAVKA_RU      to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on ZAYAVKA_RU      to BARS_DM;
grant DELETE,INSERT,SELECT,UPDATE                                            on ZAYAVKA_RU      to START1;
grant SELECT                                                                 on ZAYAVKA_RU      to UPLD;
grant DELETE,INSERT,SELECT,UPDATE                                            on ZAYAVKA_RU      to ZAY;



PROMPT *** Create SYNONYM  to ZAYAVKA_RU ***

  CREATE OR REPLACE PUBLIC SYNONYM ZAYAVKA_RU FOR BARS.ZAYAVKA_RU;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ZAYAVKA_RU.sql =========*** End *** ==
PROMPT ===================================================================================== 
