begin
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29001801902', 'Вінниця');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29000801903', 'Волинь');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29009801904', 'Дніпро');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29008801905', 'Донецьк');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29007801906', 'Житомир');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29006801907', 'Закарпаття');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29005801908', 'Запоріжжя');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29004801909', 'І-Франківськ');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29003801911', 'Кіровоград');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29002801912', 'Луганськ');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29001801913', 'Львів');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29000801914', 'Миколаїв');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29009801915', 'Одеса');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29008801916', 'Полтава');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29007801917', 'Рівне');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29006801918', 'Сумське');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29005801919', 'Тернопіль');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29005801920', 'Харків');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29004801921', 'Херсон');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29003801922', 'Хмельницьк');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29002801923', 'Черкаси');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29001801924', 'Чернівці');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29000801925', 'Чернігів');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29009801926', 'Киев');
Insert into ZAY_ACC_RU
   (ACC, RU)
 Values
   ('29002801901', 'Крим');
 exception when dup_val_on_index then null;
end;
/
COMMIT;
/

