/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace cim
{
    public partial class VCimBoundVmd
    {
        public List<VCimBoundVmdRecord> SelectPrimaryBoundVMD(Decimal? CONTR_ID, String SortExpression, int maximumRows, int startRowIndex)
        {
            if (CONTR_ID.HasValue)
                this.Filter.CONTR_ID.Equal(CONTR_ID);
            return this.Select((String.IsNullOrEmpty(SortExpression) ? "DOC_DATE desc NULLS FIRST" : SortExpression), maximumRows, startRowIndex);
        }

        public List<VCimBoundVmdRecord> SelectSecondBoundVMD(Decimal? CONTR_ID, String SortExpression, int maximumRows, int startRowIndex)
        {
            if (CONTR_ID.HasValue)
                this.Filter.CONTR_ID.Equal(CONTR_ID);
            return this.Select((String.IsNullOrEmpty(SortExpression) ? "DOC_DATE desc NULLS FIRST" : SortExpression), maximumRows, startRowIndex);
        }
        public List<VCimBoundVmdRecord> SelectLinkedDecl(Decimal? CONTR_ID, Decimal? BOUND_ID, String SortExpression, int maximumRows, int startRowIndex)
        {
            if (CONTR_ID.HasValue)
                this.Filter.CONTR_ID.Equal(CONTR_ID);
            //if (BOUND_ID.HasValue)
            //    this.Filter.BOUND_ID.Equal(BOUND_ID);
            return this.Select((String.IsNullOrEmpty(SortExpression) ? "DOC_DATE desc NULLS FIRST" : SortExpression), maximumRows, startRowIndex);
        }
    }
}