

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARSAQ/Table/AQ$_TR_QT_P.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** Create  table AQ$_TR_QT_P ***
begin 
  execute immediate '
  CREATE TABLE BARSAQ.AQ$_TR_QT_P 
   (	Q_NAME VARCHAR2(30), 
	MSGID RAW(16), 
	CORRID VARCHAR2(128), 
	PRIORITY NUMBER, 
	STATE NUMBER, 
	DELAY TIMESTAMP (6), 
	EXPIRATION NUMBER, 
	TIME_MANAGER_INFO TIMESTAMP (6), 
	LOCAL_ORDER_NO NUMBER, 
	CHAIN_NO NUMBER, 
	CSCN NUMBER, 
	DSCN NUMBER, 
	ENQ_TIME TIMESTAMP (6), 
	ENQ_UID VARCHAR2(30), 
	ENQ_TID VARCHAR2(30), 
	DEQ_TIME TIMESTAMP (6), 
	DEQ_UID VARCHAR2(30), 
	DEQ_TID VARCHAR2(30), 
	RETRY_COUNT NUMBER, 
	EXCEPTION_QSCHEMA VARCHAR2(30), 
	EXCEPTION_QUEUE VARCHAR2(30), 
	STEP_NO NUMBER, 
	RECIPIENT_KEY NUMBER, 
	DEQUEUE_MSGID RAW(16), 
	SENDER_NAME VARCHAR2(30), 
	SENDER_ADDRESS VARCHAR2(1024), 
	SENDER_PROTOCOL NUMBER, 
	USER_DATA SYS.ANYDATA , 
	USER_PROP SYS.ANYDATA 
   ) USAGE QUEUE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE AQTS 
 OPAQUE TYPE USER_DATA STORE AS BASICFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) 
 OPAQUE TYPE USER_PROP STORE AS BASICFILE LOB (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE BARSAQ.AQ$_TR_QT_P IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.Q_NAME IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.MSGID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.CORRID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.PRIORITY IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.STATE IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.DELAY IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.EXPIRATION IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.TIME_MANAGER_INFO IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.LOCAL_ORDER_NO IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.CHAIN_NO IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.CSCN IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.DSCN IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.ENQ_TIME IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.ENQ_UID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.ENQ_TID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.DEQ_TIME IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.DEQ_UID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.DEQ_TID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.RETRY_COUNT IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.EXCEPTION_QSCHEMA IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.EXCEPTION_QUEUE IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.STEP_NO IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.RECIPIENT_KEY IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.DEQUEUE_MSGID IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.SENDER_NAME IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.SENDER_ADDRESS IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.SENDER_PROTOCOL IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.USER_DATA IS '';
COMMENT ON COLUMN BARSAQ.AQ$_TR_QT_P.USER_PROP IS '';




PROMPT *** Create  constraint SYS_C00118680 ***
begin   
 execute immediate '
  ALTER TABLE BARSAQ.AQ$_TR_QT_P ADD PRIMARY KEY (Q_NAME, MSGID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE AQTS  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index SYS_C00118680 ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARSAQ.SYS_C00118680 ON BARSAQ.AQ$_TR_QT_P (Q_NAME, MSGID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE AQTS ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  AQ$_TR_QT_P ***
grant SELECT                                                                 on AQ$_TR_QT_P     to BARSREADER_ROLE;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARSAQ/Table/AQ$_TR_QT_P.sql =========*** End ***
PROMPT ===================================================================================== 
