

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARSAQ/Table/TMP_REFSYNC_XML_DOCPAYED.sql =======
PROMPT ===================================================================================== 


PROMPT *** Create  table TMP_REFSYNC_XML_DOCPAYED ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARSAQ.TMP_REFSYNC_XML_DOCPAYED 
   (	REF NUMBER(38,0), 
	TT CHAR(3), 
	DK NUMBER(1,0), 
	ACC NUMBER(38,0), 
	FDAT DATE, 
	S NUMBER(24,0), 
	SQ NUMBER(24,0), 
	TXT VARCHAR2(70), 
	STMT NUMBER(38,0), 
	SOS NUMBER(1,0), 
	ID NUMBER(38,0), 
	KF VARCHAR2(6), 
	OTM NUMBER(38,0), 
	ACTION CHAR(1), 
	CHANGE_DATE DATE, 
	CHANGE_NUMBER NUMBER, 
	SYSTEM_CHANGE_NUMBER NUMBER
   ) ON COMMIT DELETE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE BARSAQ.TMP_REFSYNC_XML_DOCPAYED IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.REF IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.TT IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.DK IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.ACC IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.FDAT IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.S IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.SQ IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.TXT IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.STMT IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.SOS IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.ID IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.KF IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.OTM IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.ACTION IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.CHANGE_DATE IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.CHANGE_NUMBER IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_XML_DOCPAYED.SYSTEM_CHANGE_NUMBER IS '';



PROMPT *** Create  grants  TMP_REFSYNC_XML_DOCPAYED ***
grant DELETE,INSERT,SELECT                                                   on TMP_REFSYNC_XML_DOCPAYED to BARS;
grant DELETE,INSERT,SELECT                                                   on TMP_REFSYNC_XML_DOCPAYED to KLBX;
grant SELECT                                                                 on TMP_REFSYNC_XML_DOCPAYED to REFSYNC_USR;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARSAQ/Table/TMP_REFSYNC_XML_DOCPAYED.sql =======
PROMPT ===================================================================================== 
