declare
max_id number;
begin
select max(id)+1 into max_id from attribute_kind where id<>1234;  

insert into attribute_kind (ID, ATTRIBUTE_CODE, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, OBJECT_TYPE_ID, VALUE_TYPE_ID, VALUE_TABLE_OWNER, VALUE_TABLE_NAME, KEY_COLUMN_NAME, VALUE_COLUMN_NAME, REGULAR_EXPRESSION, LIST_TYPE_ID, SMALL_VALUE_FLAG, VALUE_BY_DATE_FLAG, MULTI_VALUES_FLAG, SAVE_HISTORY_FLAG, GET_VALUE_FUNCTION, SET_VALUE_PROCEDURES, STATE_ID)
values (max_id, 'CUSTOMER_PRDCT_AMNT_CARD_CREDIT_PRIME', 'БПК преміальний', 3, 41, 1, null, null,null, null, null, null, 'N', 'N', 'N', 'N', null, null, 2);

insert into attribute_kind (ID, ATTRIBUTE_CODE, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, OBJECT_TYPE_ID, VALUE_TYPE_ID, VALUE_TABLE_OWNER, VALUE_TABLE_NAME, KEY_COLUMN_NAME, VALUE_COLUMN_NAME, REGULAR_EXPRESSION, LIST_TYPE_ID, SMALL_VALUE_FLAG, VALUE_BY_DATE_FLAG, MULTI_VALUES_FLAG, SAVE_HISTORY_FLAG, GET_VALUE_FUNCTION, SET_VALUE_PROCEDURES, STATE_ID)
values (max_id+1, 'MOBILE_SAVING', 'Мобільні заощадження', 3, 41, 1, null, null,null, null, null, null, 'N', 'N', 'N', 'N', null, null, 2);

insert into attribute_kind (ID, ATTRIBUTE_CODE, ATTRIBUTE_NAME, ATTRIBUTE_TYPE_ID, OBJECT_TYPE_ID, VALUE_TYPE_ID, VALUE_TABLE_OWNER, VALUE_TABLE_NAME, KEY_COLUMN_NAME, VALUE_COLUMN_NAME, REGULAR_EXPRESSION, LIST_TYPE_ID, SMALL_VALUE_FLAG, VALUE_BY_DATE_FLAG, MULTI_VALUES_FLAG, SAVE_HISTORY_FLAG, GET_VALUE_FUNCTION, SET_VALUE_PROCEDURES, STATE_ID)
values (max_id+2, 'OSHAD_ACTIVE', 'Ощад 24/7 (інформац.активний)', 3, 41, 1, null, null,  null, null, null, null, 'N', 'N', 'N', 'N', null, null, 2);
commit;
end;
/