UPDATE BARS.CCK_NDG_TIP
   SET TIPS_NDG = 'CR9,SK0,SK9,SG ,SN8,ISG,S36,ODB,'
 WHERE ID_PAR = 1;

COMMIT;

BEGIN
   INSERT INTO BARS.VIDD_TIP (VIDD, TIP, FORCE_OPEN)
        VALUES (2, 'ODB', '0');
EXCEPTION
   WHEN DUP_VAL_ON_INDEX
   THEN
      NULL;
END;
/

BEGIN
   INSERT INTO BARS.VIDD_TIP (VIDD, TIP, FORCE_OPEN)
        VALUES (3, 'ODB', '0');
EXCEPTION
   WHEN DUP_VAL_ON_INDEX
   THEN
      NULL;
END;
/

COMMIT;