ALTER TABLE BARS.ADR_HOUSES DROP CONSTRAINT PK_HOUSENUMS;
ALTER TABLE BARS.ADR_HOUSES DROP CONSTRAINT FK_HOUSENUMS_CITYDISTRICTS ;
ALTER TABLE BARS.ADR_HOUSES DROP CONSTRAINT FK_HOUSENUMS_STREETS ;
DROP INDEX I_ADRHOUSES_STREETID;


ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT PK_STREETS;
ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT FK_STREETS_SETTLEMENTS;
ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT FK_STREETS_STREETTYPES;
DROP INDEX I_ADRSTREETS_SETTLEMENTID;
DROP INDEX I_ADRSTREETS_UNAME;
DROP INDEX I_ADRSTREETS_UNAMERU;


ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT FK_SETTLEMENTS_AREAS;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT FK_SETTLEMENTS_PHONECODES;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT FK_SETTLEMENTS_REGIONS;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT FK_SETTLEMENTS_SETTLEMENTTYPES;
DROP INDEX I_ADRSETTLEMENTS_NAME;
DROP INDEX I_ADRSETTLEMENTS_UNAME;
DROP INDEX I_ADRSETTLEMENTS_UNAMERU;


ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_AREACENTERF;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_AREACENTERF_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_EFFDT_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_ID_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_NAME_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_POSTCODEMAX_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_POSTCODEMIN_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_REGIONCENTERF;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_REGNCENTERF_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_SETTLEMENTPID;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_SPIUSETLID_NN;
ALTER TABLE BARS.ADR_SETTLEMENTS DROP CONSTRAINT CC_SETTLEMENTS_TYPEID_NN;

ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT CC_STREETS_EFFDT_NN;
ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT CC_STREETS_SETTLEMENTID_NN;
ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT CC_STREETS_STREETID_NN;
ALTER TABLE BARS.ADR_STREETS DROP CONSTRAINT CC_STREETS_STREETNAME_NN;


