SET DEFINE OFF;
MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  30 as FUNCID,
  'КП: Події ' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '86' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=CC_SOB_WU[ACCESSCODE=>1][PROC=>PUL_DAT(:B,:E)][PAR=>:B(SEM=З,TYPE=S),:E(SEM=По,TYPE=S)][DESCR=>Події в КП][EXEC=>BEFORE]' as WEB_FORM_NAME,
  86 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  31 as FUNCID,
  'КП ЮО: 1.Нарахування Відсотків,  Комісії, Пені' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_INTEREST_CCK[NSIFUNCTION][ACCESSCODE=>2][PROC=>p_interest_cck1(1,:E)][PAR=>:E(SEM=Дата по,TYPE=D)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  32 as FUNCID,
  'КП ЮО: 2 Нарахування Відсотків,  Комісії, Пені  для КД з залиш.на SG ' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_INTEREST_CCK[NSIFUNCTION][ACCESSCODE=>2][PROC=>p_interest_cck1(2,:E)][PAR=>:E(SEM=Дата по,TYPE=D)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  33 as FUNCID,
  'КП ЮО: 3 Нарахування Відсотків,  Комісії, Пені для КД з платіж.датами' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_INTEREST_CCK[NSIFUNCTION][ACCESSCODE=>2][PROC=>p_interest_cck1(3,null)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  34 as FUNCID,
  'КП ЮО: 4 Нарахування Відсотків,  Комісії, Пені для КД, що прострочені ' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_INTEREST_CCK[NSIFUNCTION][ACCESSCODE=>2][PROC=>p_interest_cck1(4,null)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  35 as FUNCID,
  'КП ЮО: 5 Нарахування Відсотків,  Комісії, Пені для ОДНОГО  КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_INTEREST_CCK_ND[NSIFUNCTION][ACCESSCODE=>2][PROC=>p_interest_cck1( - :R,:E)][PAR=>:E(SEM=Дата по,TYPE=D), :R(SEM=Реф_КД,TYPE=N)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  36 as FUNCID,
  'КП ЮО: 5 Нарахування Відсотків,  Комісії, Пені для  ВИДІЛЕНОГО  КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'EACH' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  NULL as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_INTEREST_CCK_ND[NSIFUNCTION][ACCESSCODE=>2][PROC=>PUL.PUT(''ND'',:ND);p_interest_cck1( - 999,:E)][PAR=>:E(SEM=Дата по,TYPE=D)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  97 as FUNCID,
  'Погноз суми погашення КП за період' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '90' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_SUMPOG_1[NSIFUNCTION][ACCESSCODE=>1][PROC=>p_cc_sum_pog_web(:D1,:D2,2)][PAR=>:D1(SEM=З_дати>,TYPE=D),:D2(SEM=По_дату>,TYPE=D)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  90 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  98 as FUNCID,
  'Доп.параметри по Договору (для СПЕЦ.звітів)' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '112' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=CC_DOPW_MOS[NSIFUNCTION][ACCESSCODE=>2][PROC=>PUL.Set_Mas_Ini(''ND'',:ND, ''X'' )][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  112 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  99 as FUNCID,
  'КП: Архів закритих КД ' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '75' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=V_CCK_ZU[ACCESSCODE=>1][DESCR=>КП: Архів закритих КД]' as WEB_FORM_NAME,
  75 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  19 as FUNCID,
  'КД: Забезпечення існуючі/нові' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'EACH' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '65' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/CreditUi/provide/Index/?id=:ND' as WEB_FORM_NAME,
  65 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  5 as FUNCID,
  'КД: Рахунки та операції по КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'EACH' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '106' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/CreditUi/accounts/Index/?id=:ND' as WEB_FORM_NAME,
  106 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  4 as FUNCID,
  'КД: Перегляд параметрів КД ' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  NULL as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '80' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/CreditUi/NewCredit/?custtype=2&nd=:ND&sos=:SOS' as WEB_FORM_NAME,
  80 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  8 as FUNCID,
  'КД: Архів подій по обраному КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '93' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=CC_SOB[ACCESSCODE=>5][PROC=>PUL.Set_Mas_Ini(''ND'',:ND,''X'')][EXEC=>BEFORE][showDialogWindow=>false][CONDITIONS=> nd=:ND]' as WEB_FORM_NAME,
  93 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  9 as FUNCID,
  'КД: Доппараметри КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '55' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/CreditUi/NewCredit/?custtype=2&nd=:ND&tagOnly=true' as WEB_FORM_NAME,
  55 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  10 as FUNCID,
  'КД: Картка клієнта' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '155' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/clientregister/registration.aspx?readonly=1&rnk=:RNK' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  11 as FUNCID,
  'КД: Таблична форма рахунків по КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '111' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/customerlist/custacc.aspx?type=3&nd=:ND' as WEB_FORM_NAME,
  111 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  14 as FUNCID,
  'КД: Побудова ГПК для обраного КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '83' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=CC_W_LIM1_EXT[NSIFUNCTION][ACCESSCODE=>0][PROC=>PUL.PUT(''ND'',:ND);PUL.PUT(''ACC8'',:ACC8)][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  83 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  15 as FUNCID,
  'КД: Графік лімітів кредитування' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '79' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/CreditUi/glk/Index/?id=:ND' as WEB_FORM_NAME,
  79 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  16 as FUNCID,
  'КД: Графік погашення траншів' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '154' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=CC_W_TRANSH[NSIFUNCTION][ACCESSCODE=>2][PROC=>PUL.Set_Mas_Ini(''ND'',:ND, ''X'' )][EXEC=>BEFORE][showDialogWindow=>false]' as WEB_FORM_NAME,
  NULL as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  18 as FUNCID,
  'КД: Дані про реструктуризацію КД' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  'ONCE' as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '51' as FORM_NAME,
  NULL as CHECK_FUNC,
  'sPar=CCK_RESTR[NSIFUNCTION][CONDITIONS=>ND=:ND][ACCESSCODE=>2][showDialogWindow=>false]' as WEB_FORM_NAME,
  51 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

MERGE INTO BARS.META_NSIFUNCTION A USING
 (SELECT
  1011623 as TABID,
  24 as FUNCID,
  'КД: Інтергрований показник фінстану позичальника' as DESCR,
  NULL as PROC_NAME,
  NULL as PROC_PAR,
  NULL as PROC_EXEC,
  NULL as QST,
  NULL as MSG,
  '105' as FORM_NAME,
  NULL as CHECK_FUNC,
  '/barsroot/barsweb/dynform.aspx?form=frm_fin2_kart_kl_fl&rnk=:RNK' as WEB_FORM_NAME,
  105 as ICON_ID
  FROM DUAL) B
ON (A.TABID = B.TABID and A.FUNCID = B.FUNCID)
WHEN NOT MATCHED THEN 
INSERT (
  TABID, FUNCID, DESCR, PROC_NAME, PROC_PAR, 
  PROC_EXEC, QST, MSG, FORM_NAME, CHECK_FUNC, 
  WEB_FORM_NAME, ICON_ID)
VALUES (
  B.TABID, B.FUNCID, B.DESCR, B.PROC_NAME, B.PROC_PAR, 
  B.PROC_EXEC, B.QST, B.MSG, B.FORM_NAME, B.CHECK_FUNC, 
  B.WEB_FORM_NAME, B.ICON_ID)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCR = B.DESCR,
  A.PROC_NAME = B.PROC_NAME,
  A.PROC_PAR = B.PROC_PAR,
  A.PROC_EXEC = B.PROC_EXEC,
  A.QST = B.QST,
  A.MSG = B.MSG,
  A.FORM_NAME = B.FORM_NAME,
  A.CHECK_FUNC = B.CHECK_FUNC,
  A.WEB_FORM_NAME = B.WEB_FORM_NAME,
  A.ICON_ID = B.ICON_ID;

COMMIT;
