begin
umu.remove_report_from_arm(132, '$RM_VALB', 1 );
umu.remove_report_from_arm(214, '$RM_VALB', 1 );
umu.remove_report_from_arm(54, '$RM_VALB', 1 );
umu.add_report2arm(132, '$RM_VALB', 1 );
umu.remove_report_from_arm(136, '$RM_VALB', 1 );
umu.add_report2arm(147, '$RM_VALB', 1 );
umu.remove_report_from_arm(202, '$RM_VALB', 1 );
umu.remove_report_from_arm(214, '$RM_VALB', 1 );
umu.add_report2arm(253, '$RM_VALB', 1 );
umu.add_report2arm(254, '$RM_VALB', 1 );
umu.remove_report_from_arm(282, '$RM_VALB', 1 );
umu.remove_report_from_arm(283, '$RM_VALB', 1 );
umu.remove_report_from_arm(287, '$RM_VALB', 1 );
umu.remove_report_from_arm(336, '$RM_VALB', 1 );
umu.remove_report_from_arm(345, '$RM_VALB', 1 );
umu.remove_report_from_arm(346, '$RM_VALB', 1 );
umu.remove_report_from_arm(347, '$RM_VALB', 1 );
umu.remove_report_from_arm(348, '$RM_VALB', 1 );
umu.remove_report_from_arm(349, '$RM_VALB', 1 );
umu.remove_report_from_arm(440, '$RM_VALB', 1 );
umu.remove_report_from_arm(441, '$RM_VALB', 1 );
umu.add_report2arm(456, '$RM_VALB', 1 );
umu.add_report2arm(457, '$RM_VALB', 1 );
umu.add_report2arm(566, '$RM_VALB', 1 );
umu.remove_report_from_arm(588, '$RM_VALB', 1 );
umu.remove_report_from_arm(591, '$RM_VALB', 1 );
umu.add_report2arm(16, '$RM_VALB', 1 );
umu.add_report2arm(261, '$RM_VALB', 1 );
umu.add_report2arm(262, '$RM_VALB', 1 );
umu.add_report2arm(375, '$RM_VALB', 1 );
umu.remove_report_from_arm(1010, '$RM_VALB', 1 );
umu.add_report2arm(7, '$RM_VALB', 1 );
umu.add_report2arm(107, '$RM_BUHG', 1 );
umu.add_report2arm(764, '$RM_VALB', 1 );
umu.add_report2arm(767, '$RM_VALB', 1 );
umu.add_report2arm(35, '$RM_VALB', 1 );
umu.add_report2arm(273, '$RM_VALB', 1 );
--umu.add_report2arm(766, '$RM_VALB', 1 );
--umu.add_report2arm(100260, '$RM_VALB', 1 );
end;
/
commit;