SET DEFINE OFF;
MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  1 as STR_TP_ID,
  'алея' as STR_TP_NM,
  'аллея' as STR_TP_NM_RU,
  'parkway' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  2 as STR_TP_ID,
  'бул.' as STR_TP_NM,
  'бул.' as STR_TP_NM_RU,
  'boulevard' as STR_TP_NM_ENG,
  'Blvd' as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  3 as STR_TP_ID,
  'в’їзд' as STR_TP_NM,
  'въезд' as STR_TP_NM_RU,
  'entrance
' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  4 as STR_TP_ID,
  'вул.' as STR_TP_NM,
  'ул.' as STR_TP_NM_RU,
  'street
' as STR_TP_NM_ENG,
  'Str' as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  5 as STR_TP_ID,
  'гай9' as STR_TP_NM,
  'роща' as STR_TP_NM_RU,
  'grove' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  6 as STR_TP_ID,
  'дорога' as STR_TP_NM,
  'дорога' as STR_TP_NM_RU,
  'road' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  7 as STR_TP_ID,
  'ж/м' as STR_TP_NM,
  'ж/м' as STR_TP_NM_RU,
  'housing estate' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  9 as STR_TP_ID,
  'кв.' as STR_TP_NM,
  'кв.' as STR_TP_NM_RU,
  'apartment' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  10 as STR_TP_ID,
  'лінія' as STR_TP_NM,
  'линия' as STR_TP_NM_RU,
  'line' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  11 as STR_TP_ID,
  'майд.' as STR_TP_NM,
  'пл.' as STR_TP_NM_RU,
  'square
' as STR_TP_NM_ENG,
  'sq.' as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  12 as STR_TP_ID,
  'мікр.' as STR_TP_NM,
  'микр.' as STR_TP_NM_RU,
  'microdistrict' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  13 as STR_TP_ID,
  'наб.' as STR_TP_NM,
  'наб.' as STR_TP_NM_RU,
  'embankment ' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  15 as STR_TP_ID,
  'остр.' as STR_TP_NM,
  'остр.' as STR_TP_NM_RU,
  'island
' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  16 as STR_TP_ID,
  'панс.' as STR_TP_NM,
  'панс.' as STR_TP_NM_RU,
  'pension' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  17 as STR_TP_ID,
  'парк' as STR_TP_NM,
  'парк' as STR_TP_NM_RU,
  'park' as STR_TP_NM_ENG,
  'pk.' as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  18 as STR_TP_ID,
  'пзз.' as STR_TP_NM,
  'пзз.' as STR_TP_NM_RU,
  NULL as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  19 as STR_TP_ID,
  'пл.' as STR_TP_NM,
  'пл.' as STR_TP_NM_RU,
  NULL as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  20 as STR_TP_ID,
  'пров.' as STR_TP_NM,
  'пер.' as STR_TP_NM_RU,
  'bystreet
' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  21 as STR_TP_ID,
  'проїзд' as STR_TP_NM,
  'проезд' as STR_TP_NM_RU,
  'passage' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  22 as STR_TP_ID,
  'просп.' as STR_TP_NM,
  'просп.' as STR_TP_NM_RU,
  'avenue' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  23 as STR_TP_ID,
  'прохід' as STR_TP_NM,
  'проход' as STR_TP_NM_RU,
  'pass' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  24 as STR_TP_ID,
  'радг.' as STR_TP_NM,
  'совх.' as STR_TP_NM_RU,
  'state farm' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  25 as STR_TP_ID,
  'роз’їзд' as STR_TP_NM,
  'разъезд' as STR_TP_NM_RU,
  'crossroad' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  26 as STR_TP_ID,
  'розвилка' as STR_TP_NM,
  'развилка' as STR_TP_NM_RU,
  'road fork' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  27 as STR_TP_ID,
  'санат.' as STR_TP_NM,
  'санат.' as STR_TP_NM_RU,
  'sanatorium' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  28 as STR_TP_ID,
  'селище' as STR_TP_NM,
  'поселок' as STR_TP_NM_RU,
  'village' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  29 as STR_TP_ID,
  'сквер' as STR_TP_NM,
  'сквер' as STR_TP_NM_RU,
  'garden square' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  30 as STR_TP_ID,
  'ст.' as STR_TP_NM,
  'ст.' as STR_TP_NM_RU,
  NULL as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  32 as STR_TP_ID,
  'тракт' as STR_TP_NM,
  'тракт' as STR_TP_NM_RU,
  'highway' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  33 as STR_TP_ID,
  'траса' as STR_TP_NM,
  'трасса' as STR_TP_NM_RU,
  'track' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  34 as STR_TP_ID,
  'тупик' as STR_TP_NM,
  'тупик' as STR_TP_NM_RU,
  'dead end' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  35 as STR_TP_ID,
  'узвіз' as STR_TP_NM,
  'спуск' as STR_TP_NM_RU,
  'descent' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  36 as STR_TP_ID,
  'урочище' as STR_TP_NM,
  'урочище' as STR_TP_NM_RU,
  'area' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  37 as STR_TP_ID,
  'уч.' as STR_TP_NM,
  'уч.' as STR_TP_NM_RU,
  NULL as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  38 as STR_TP_ID,
  'хутір' as STR_TP_NM,
  'хутор' as STR_TP_NM_RU,
  'farm' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  39 as STR_TP_ID,
  'шахта' as STR_TP_NM,
  'шахта' as STR_TP_NM_RU,
  'mine' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  40 as STR_TP_ID,
  'шлях' as STR_TP_NM,
  'путь' as STR_TP_NM_RU,
  'road' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

MERGE INTO BARS.ADR_STREET_TYPES A USING
 (SELECT
  41 as STR_TP_ID,
  'шосе' as STR_TP_NM,
  'шоссе' as STR_TP_NM_RU,
  'motorway' as STR_TP_NM_ENG,
  NULL as STR_TP_CODE_ENG
  FROM DUAL) B
ON (A.STR_TP_ID = B.STR_TP_ID)
WHEN NOT MATCHED THEN 
INSERT (
  STR_TP_ID, STR_TP_NM, STR_TP_NM_RU, STR_TP_NM_ENG, STR_TP_CODE_ENG)
VALUES (
  B.STR_TP_ID, B.STR_TP_NM, B.STR_TP_NM_RU, B.STR_TP_NM_ENG, B.STR_TP_CODE_ENG)
WHEN MATCHED THEN
UPDATE SET 
  A.STR_TP_NM = B.STR_TP_NM,
  A.STR_TP_NM_RU = B.STR_TP_NM_RU,
  A.STR_TP_NM_ENG = B.STR_TP_NM_ENG,
  A.STR_TP_CODE_ENG = B.STR_TP_CODE_ENG;

COMMIT;
