

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARSAQ/Table/TMP_REFSYNC_CUSTOMER.sql =========**
PROMPT ===================================================================================== 


PROMPT *** Create  table TMP_REFSYNC_CUSTOMER ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARSAQ.TMP_REFSYNC_CUSTOMER 
   (	RNK NUMBER(38,0), 
	TGR NUMBER(1,0), 
	CUSTTYPE NUMBER(1,0), 
	COUNTRY NUMBER(3,0), 
	NMK VARCHAR2(70), 
	NMKV VARCHAR2(70), 
	NMKK VARCHAR2(38), 
	CODCAGENT NUMBER(1,0), 
	PRINSIDER NUMBER(38,0), 
	OKPO VARCHAR2(14), 
	ADR VARCHAR2(70), 
	SAB VARCHAR2(6), 
	C_REG NUMBER(2,0), 
	C_DST NUMBER(2,0), 
	RGTAX VARCHAR2(30), 
	DATET DATE, 
	ADM VARCHAR2(70), 
	DATEA DATE, 
	STMT NUMBER(5,0), 
	DATE_ON DATE, 
	DATE_OFF DATE, 
	NOTES VARCHAR2(140), 
	NOTESEC VARCHAR2(256), 
	CRISK NUMBER(38,0), 
	PINCODE VARCHAR2(10), 
	ND VARCHAR2(10), 
	RNKP NUMBER(38,0), 
	ISE CHAR(5), 
	FS CHAR(2), 
	OE CHAR(5), 
	VED CHAR(5), 
	SED CHAR(4), 
	LIM NUMBER(24,0), 
	MB CHAR(1), 
	RGADM VARCHAR2(30), 
	BC NUMBER(1,0), 
	BRANCH VARCHAR2(30), 
	TOBO VARCHAR2(30), 
	ISP NUMBER(38,0), 
	TAXF VARCHAR2(12), 
	NOMPDV VARCHAR2(9), 
	ACTION CHAR(1), 
	CHANGE_DATE DATE, 
	CHANGE_NUMBER NUMBER, 
	SYSTEM_CHANGE_NUMBER NUMBER
   ) ON COMMIT DELETE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE BARSAQ.TMP_REFSYNC_CUSTOMER IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.RNK IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.TGR IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.CUSTTYPE IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.COUNTRY IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.NMK IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.NMKV IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.NMKK IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.CODCAGENT IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.PRINSIDER IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.OKPO IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.ADR IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.SAB IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.C_REG IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.C_DST IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.RGTAX IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.DATET IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.ADM IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.DATEA IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.STMT IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.DATE_ON IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.DATE_OFF IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.NOTES IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.NOTESEC IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.CRISK IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.PINCODE IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.ND IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.RNKP IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.ISE IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.FS IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.OE IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.VED IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.SED IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.LIM IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.MB IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.RGADM IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.BC IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.BRANCH IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.TOBO IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.ISP IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.TAXF IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.NOMPDV IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.ACTION IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.CHANGE_DATE IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.CHANGE_NUMBER IS '';
COMMENT ON COLUMN BARSAQ.TMP_REFSYNC_CUSTOMER.SYSTEM_CHANGE_NUMBER IS '';




PROMPT *** Create  constraint SYS_C0010423 ***
begin   
 execute immediate '
  ALTER TABLE BARSAQ.TMP_REFSYNC_CUSTOMER MODIFY (RNK NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C0010424 ***
begin   
 execute immediate '
  ALTER TABLE BARSAQ.TMP_REFSYNC_CUSTOMER MODIFY (DATE_ON NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C0010425 ***
begin   
 execute immediate '
  ALTER TABLE BARSAQ.TMP_REFSYNC_CUSTOMER MODIFY (BRANCH NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C0010426 ***
begin   
 execute immediate '
  ALTER TABLE BARSAQ.TMP_REFSYNC_CUSTOMER MODIFY (TOBO NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  TMP_REFSYNC_CUSTOMER ***
grant DELETE,INSERT,SELECT                                                   on TMP_REFSYNC_CUSTOMER to BARS;
grant SELECT                                                                 on TMP_REFSYNC_CUSTOMER to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT                                                   on TMP_REFSYNC_CUSTOMER to KLBX;
grant SELECT                                                                 on TMP_REFSYNC_CUSTOMER to REFSYNC_USR;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARSAQ/Table/TMP_REFSYNC_CUSTOMER.sql =========**
PROMPT ===================================================================================== 
