

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARSAQ/Table/TOAD_PLAN_TABLE.sql =========*** Run
PROMPT ===================================================================================== 


PROMPT *** Create  table TOAD_PLAN_TABLE ***
begin 
  execute immediate '
  CREATE TABLE BARSAQ.TOAD_PLAN_TABLE 
   (	STATEMENT_ID VARCHAR2(30), 
	PLAN_ID NUMBER, 
	TIMESTAMP DATE, 
	REMARKS VARCHAR2(4000), 
	OPERATION VARCHAR2(30), 
	OPTIONS VARCHAR2(255), 
	OBJECT_NODE VARCHAR2(128), 
	OBJECT_OWNER VARCHAR2(30), 
	OBJECT_NAME VARCHAR2(30), 
	OBJECT_ALIAS VARCHAR2(65), 
	OBJECT_INSTANCE NUMBER(*,0), 
	OBJECT_TYPE VARCHAR2(30), 
	OPTIMIZER VARCHAR2(255), 
	SEARCH_COLUMNS NUMBER, 
	ID NUMBER(*,0), 
	PARENT_ID NUMBER(*,0), 
	DEPTH NUMBER(*,0), 
	POSITION NUMBER(*,0), 
	COST NUMBER(*,0), 
	CARDINALITY NUMBER(*,0), 
	BYTES NUMBER(*,0), 
	OTHER_TAG VARCHAR2(255), 
	PARTITION_START VARCHAR2(255), 
	PARTITION_STOP VARCHAR2(255), 
	PARTITION_ID NUMBER(*,0), 
	OTHER LONG, 
	DISTRIBUTION VARCHAR2(30), 
	CPU_COST NUMBER(*,0), 
	IO_COST NUMBER(*,0), 
	TEMP_SPACE NUMBER(*,0), 
	ACCESS_PREDICATES VARCHAR2(4000), 
	FILTER_PREDICATES VARCHAR2(4000), 
	PROJECTION VARCHAR2(4000), 
	TIME NUMBER(*,0), 
	QBLOCK_NAME VARCHAR2(30), 
	OTHER_XML CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE AQTS 
 LOB (OTHER_XML) STORE AS BASICFILE (
  TABLESPACE AQTS ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE BARSAQ.TOAD_PLAN_TABLE IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.STATEMENT_ID IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.PLAN_ID IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.TIMESTAMP IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.REMARKS IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OPERATION IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OPTIONS IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OBJECT_NODE IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OBJECT_OWNER IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OBJECT_NAME IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OBJECT_ALIAS IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OBJECT_INSTANCE IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OBJECT_TYPE IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OPTIMIZER IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.SEARCH_COLUMNS IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.ID IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.PARENT_ID IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.DEPTH IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.POSITION IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.COST IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.CARDINALITY IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.BYTES IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OTHER_TAG IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.PARTITION_START IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.PARTITION_STOP IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.PARTITION_ID IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OTHER IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.DISTRIBUTION IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.CPU_COST IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.IO_COST IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.TEMP_SPACE IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.ACCESS_PREDICATES IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.FILTER_PREDICATES IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.PROJECTION IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.TIME IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.QBLOCK_NAME IS '';
COMMENT ON COLUMN BARSAQ.TOAD_PLAN_TABLE.OTHER_XML IS '';



PROMPT *** Create  grants  TOAD_PLAN_TABLE ***
grant SELECT                                                                 on TOAD_PLAN_TABLE to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TOAD_PLAN_TABLE to PUBLIC;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARSAQ/Table/TOAD_PLAN_TABLE.sql =========*** End
PROMPT ===================================================================================== 
