/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.EAD
{
    public partial class VEadSyncQueue
    {
        public List<VEadSyncQueueRecord> SelectSyncQueue(DateTime From, DateTime To, List<String> Status, List<String> Type, List<String> ObjID, List<Decimal?> ErrCount, String ErrText, String SortExpression, int maximumRows, int startRowIndex)
        {
            // обязательная фильтрация по датам
            this.Filter.CRT_DATE.Between(From, To);

            // фильтрация по статусу
            if (0 < Status.Count && Status.Count < 8)
                this.Filter.STATUS_ID.In(Status);

            // фильтрация по типу
            if (0 < Type.Count && Type.Count < 5)
                this.Filter.TYPE_ID.In(Type);

            // фильтрация по перечню объектов
            if (0 < ObjID.Count)
            {
                if (1 == ObjID.Count) //пошук по одному об'єкту
                    this.Filter.OBJ_ID.LikeBoth(ObjID[0]);
                else //пошук по списку.
                    this.Filter.OBJ_ID.In(ObjID);

            }

            // фильтрация по перечню объектов
            if (0 < ErrCount.Count)
                this.Filter.ERR_COUNT.In(ErrCount);

            // фильтрация по тексту ошибки
            if (!String.IsNullOrEmpty(ErrText))
                this.Filter.ERR_TEXT.LikeBoth(ErrText);


            return Select(SortExpression, maximumRows, startRowIndex);
        }
    }
}