CREATE OR REPLACE FORCE VIEW "BARS"."V_ALT_CORPS" ("ID", "CORPORATION_NAME") AS 
  select t.ID, t.CORPORATION_NAME from OB_CORPORATION t where t.PARENT_ID is null and t.STATE_ID = 1 and t.CORPORATION_CODE is null
;
/
GRANT SELECT ON "BARS"."V_ALT_CORPS" TO "BARS_ACCESS_DEFROLE";
/
GRANT SELECT ON "BARS"."V_ALT_CORPS" TO "CORP_CLIENT";
/
