CREATE OR REPLACE FORCE VIEW V_MBM_CUSTOMERS_SEARCH
AS SELECT
    TO_CHAR(C."RNK") AS "RNK",
    C."OKPO",
    C."CUSTTYPE",
    DECODE(C.CUSTTYPE, 2, 'L', 'F') || C.OKPO AS "CL_OKPO"
    FROM CUSTOMER C
    WHERE CUSTTYPE IN (2,3);

COMMENT ON TABLE BARS.V_MBM_CUSTOMERS_SEARCH IS 'Представляення для пошуку клієнтів за ЕДРПО';

GRANT SELECT ON BARS.V_MBM_CUSTOMERS_SEARCH TO BARS_ACCESS_DEFROLE;

