/* Formatted on 12/23/2015 11:16:44 AM (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW V_MBM_LOAN_SCHEDULE_PLAN
AS
   SELECT 
		CC.ND as LOAN_ID
		,CC.FDAT AS PLAN_DATE
		,CC.SUMO AS PAYMENT
		,CC.SUMG AS PAYMENT_BODY
		,CC.SUMO - CC.SUMG AS PAYMENT_PERCENT
		,CC.LIM2 AS REST
		,CC.SUMK AS COMMISSION
   FROM CC_LIM CC ORDER BY CC.FDAT ASC;


GRANT SELECT ON V_MBM_LOAN_SCHEDULE_PLAN TO BARS_ACCESS_DEFROLE;
