CREATE OR REPLACE FORCE VIEW V_MBM_ACCOUNTS
AS
   SELECT a."ACC",
          a."KF",
          a."NLS",
          a."KV",
          a."BRANCH",
          a."NLSALT",
          a."NBS",
          a."NBS2",
          a."DAOS",
          a."DAPP",
          a."ISP",
          a."NMS",
          a."LIM",
          a."OSTB",
          a."OSTC",
          a."OSTF",
          a."OSTQ",
          a."DOS",
          a."KOS",
          a."DOSQ",
          a."KOSQ",
          a."PAP",
          a."TIP",
          a."VID",
          a."TRCN",
          a."MDATE",
          a."DAZS",
          a."SEC",
          a."ACCC",
          a."BLKD",
          a."BLKK",
          a."POS",
          a."SECI",
          a."SECO",
          a."GRP",
          a."OSTX",
          a."RNK",
          a."NOTIFIER_REF",
          a."TOBO",
          a."BDATE",
          a."OPT",
          a."OB22",
          a."DAPPQ",
          a."SEND_SMS",
          c.OKPO,
          t.lcv
     FROM accounts a, customer c, tabval$global t
    WHERE a.kv = t.kv
        and a.RNK = c.RNK;
    
grant select on v_mbm_accounts to bars_access_defrole;        

