CREATE OR REPLACE FORCE VIEW "BARS"."V_ROOT_CORPORATION" ("ID", "EXTERNAL_ID", "CORPORATION_NAME") AS 
  select t.ID, t.EXTERNAL_ID, t.CORPORATION_NAME from OB_CORPORATION t where t.PARENT_ID is null and t.STATE_ID=1
;
/
GRANT SELECT ON "BARS"."V_ROOT_CORPORATION" TO "CORP_CLIENT";
/
GRANT SELECT ON "BARS"."V_ROOT_CORPORATION" TO "BARS_ACCESS_DEFROLE";
/
