--view по відправленим і не оплаченим смс по клієнтах поза рахунками

CREATE OR REPLACE FORCE VIEW BARS.V_SMS_CLIENT_SEND
(  kf,
   NMK,
   PHONE,
   CNT
)
AS   
SELECT t4.kf, t4.nmk, t5.phone, t5.cnt
  FROM CUSTOMERW T3,
       CUSTOMER T4,
       (  SELECT COUNT (T1.MSG_ID) cnt, T1.PHONE
            FROM MSG_SUBMIT_DATA t1
                 LEFT OUTER JOIN acc_msg t2 ON T1.MSG_ID = T2.MSG_ID
           WHERE T2.MSG_ID IS NULL AND T1.PAYEDREF IS NULL
        GROUP BY T1.PHONE) t5
 WHERE     T3.RNK = T4.RNK
       AND T4.DATE_OFF IS NULL
       AND T3.TAG = 'MPNO '
       AND T3.VALUE = t5.phone

/


PROMPT Privs on VIEW V_SMS_CLIENT_SEND TO BARS_ACCESS_DEFROLE to BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_SMS_CLIENT_SEND TO BARS_ACCESS_DEFROLE
/

PROMPT Privs on VIEW V_SMS_CLIENT_SEND TO DPT_ADMIN to DPT_ADMIN;
GRANT SELECT ON BARS.V_SMS_CLIENT_SEND TO DPT_ADMIN
/

PROMPT Privs on VIEW V_SMS_CLIENT_SEND TO DPT_ROLE to DPT_ROLE;
GRANT SELECT ON BARS.V_SMS_CLIENT_SEND TO DPT_ROLE
/