

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/CM_CLIENT_QUE.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to CM_CLIENT_QUE ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''CM_CLIENT_QUE'', ''CENTER'' , null, ''E'', ''E'', ''E'');
               bpa.alter_policy_info(''CM_CLIENT_QUE'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''CM_CLIENT_QUE'', ''WHOLE'' , null, ''E'', ''E'', ''E'');
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table CM_CLIENT_QUE ***
begin 
  execute immediate '
  CREATE TABLE BARS.CM_CLIENT_QUE 
   (	ID NUMBER(*,0), 
	DATEIN DATE, 
	DATEMOD DATE, 
	OPER_TYPE NUMBER(*,0), 
	OPER_STATUS NUMBER(*,0), 
	RESP_TXT VARCHAR2(1000), 
	BRANCH VARCHAR2(30), 
	OPENDATE DATE, 
	CLIENTTYPE NUMBER(*,0), 
	TAXPAYERIDENTIFIER VARCHAR2(10), 
	SHORTNAME VARCHAR2(105), 
	FIRSTNAME VARCHAR2(105), 
	LASTNAME VARCHAR2(105), 
	MIDDLENAME VARCHAR2(105), 
	ENGFIRSTNAME VARCHAR2(64), 
	ENGLASTNAME VARCHAR2(64), 
	COUNTRY VARCHAR2(3), 
	RESIDENT NUMBER(*,0), 
	WORK VARCHAR2(254), 
	OFFICE VARCHAR2(32), 
	DATE_W DATE, 
	ISVIP VARCHAR2(1), 
	K060 VARCHAR2(2), 
	COMPANYNAME VARCHAR2(200), 
	SHORTCOMPANYNAME VARCHAR2(32), 
	PERSONALISATIONNAME VARCHAR2(32), 
	KLAS_CLIENT_ID NUMBER(*,0), 
	CONTACTPERSON VARCHAR2(105), 
	BIRTHDATE DATE, 
	BIRTHPLACE VARCHAR2(1024), 
	GENDER VARCHAR2(1), 
	ADDR1_CITYNAME VARCHAR2(100), 
	ADDR1_PCODE VARCHAR2(10), 
	ADDR1_DOMAIN VARCHAR2(48), 
	ADDR1_REGION VARCHAR2(48), 
	ADDR1_STREET VARCHAR2(100), 
	ADDR2_CITYNAME VARCHAR2(100), 
	ADDR2_PCODE VARCHAR2(10), 
	ADDR2_DOMAIN VARCHAR2(48), 
	ADDR2_REGION VARCHAR2(48), 
	ADDR2_STREET VARCHAR2(100), 
	EMAIL VARCHAR2(32), 
	PHONENUMBER VARCHAR2(12), 
	PHONENUMBER_MOB VARCHAR2(12), 
	PHONENUMBER_DOD VARCHAR2(12), 
	FAX VARCHAR2(12), 
	TYPEDOC NUMBER(*,0), 
	PASPNUM VARCHAR2(16), 
	PASPSERIES VARCHAR2(16), 
	PASPDATE DATE, 
	PASPISSUER VARCHAR2(128), 
	FOREIGNPASPNUM VARCHAR2(16), 
	FOREIGNPASPSERIES VARCHAR2(16), 
	FOREIGNPASPDATE DATE, 
	FOREIGNPASPENDDATE DATE, 
	FOREIGNPASPISSUER VARCHAR2(128), 
	CONTRACTNUMBER VARCHAR2(19), 
	PRODUCTCODE VARCHAR2(32), 
	CARD_TYPE VARCHAR2(36), 
	CNTM NUMBER(*,0), 
	PIND VARCHAR2(32), 
	OKPO_SYSORG VARCHAR2(10), 
	KOD_SYSORG NUMBER(*,0), 
	REGNUMBERCLIENT VARCHAR2(32), 
	REGNUMBEROWNER VARCHAR2(32), 
	ACC NUMBER(22,0), 
	CL_RNK VARCHAR2(32), 
	CL_DT_ISS DATE, 
	CARD_BR_ISS VARCHAR2(30), 
	CARD_ADDR_ISS VARCHAR2(100), 
	DELIVERY_BR VARCHAR2(30), 
	RNK NUMBER(22,0), 
	KK_SECRET_WORD VARCHAR2(32), 
	KK_FLAG NUMBER(1,0), 
	KK_REGTYPE NUMBER(1,0), 
	KK_CITYAREAID NUMBER(10,0), 
	KK_STREETTYPEID NUMBER(10,0), 
	KK_STREETNAME VARCHAR2(64), 
	KK_APARTMENT VARCHAR2(32), 
	KK_POSTCODE VARCHAR2(5), 
	ADD_INFO VARCHAR2(500), 
	IDCARDENDDATE DATE, 
	EDDR_ID VARCHAR2(20), 
	KF VARCHAR2(6) DEFAULT sys_context(''bars_context'',''user_mfo''), 
	SHORTNAMEOWNER VARCHAR2(105)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSSMLD ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to CM_CLIENT_QUE ***
 exec bpa.alter_policies('CM_CLIENT_QUE');


COMMENT ON TABLE BARS.CM_CLIENT_QUE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.RNK IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_SECRET_WORD IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_FLAG IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_REGTYPE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_CITYAREAID IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_STREETTYPEID IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_STREETNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_APARTMENT IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KK_POSTCODE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADD_INFO IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.IDCARDENDDATE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.EDDR_ID IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KF IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.SHORTNAMEOWNER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ID IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.DATEIN IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.DATEMOD IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.OPER_TYPE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.OPER_STATUS IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.RESP_TXT IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.BRANCH IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.OPENDATE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CLIENTTYPE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.TAXPAYERIDENTIFIER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.SHORTNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FIRSTNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.LASTNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.MIDDLENAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ENGFIRSTNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ENGLASTNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.COUNTRY IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.RESIDENT IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.WORK IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.OFFICE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.DATE_W IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ISVIP IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.K060 IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.COMPANYNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.SHORTCOMPANYNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PERSONALISATIONNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KLAS_CLIENT_ID IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CONTACTPERSON IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.BIRTHDATE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.BIRTHPLACE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.GENDER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR1_CITYNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR1_PCODE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR1_DOMAIN IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR1_REGION IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR1_STREET IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR2_CITYNAME IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR2_PCODE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR2_DOMAIN IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR2_REGION IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ADDR2_STREET IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.EMAIL IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PHONENUMBER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PHONENUMBER_MOB IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PHONENUMBER_DOD IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FAX IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.TYPEDOC IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PASPNUM IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PASPSERIES IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PASPDATE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PASPISSUER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FOREIGNPASPNUM IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FOREIGNPASPSERIES IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FOREIGNPASPDATE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FOREIGNPASPENDDATE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.FOREIGNPASPISSUER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CONTRACTNUMBER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PRODUCTCODE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CARD_TYPE IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CNTM IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.PIND IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.OKPO_SYSORG IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.KOD_SYSORG IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.REGNUMBERCLIENT IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.REGNUMBEROWNER IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.ACC IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CL_RNK IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CL_DT_ISS IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CARD_BR_ISS IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.CARD_ADDR_ISS IS '';
COMMENT ON COLUMN BARS.CM_CLIENT_QUE.DELIVERY_BR IS '';




PROMPT *** Create  constraint PK_CMCLIENTQUE ***
begin   
 execute immediate '
  ALTER TABLE BARS.CM_CLIENT_QUE ADD CONSTRAINT PK_CMCLIENTQUE PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSSMLI  ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_CMCLIENTQUE_OPERSTATUS ***
begin   
 execute immediate '
  ALTER TABLE BARS.CM_CLIENT_QUE ADD CONSTRAINT CC_CMCLIENTQUE_OPERSTATUS CHECK (oper_status in (1,2,3,10,99)) ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_CMCLIENTQUE_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.CM_CLIENT_QUE MODIFY (KF CONSTRAINT CC_CMCLIENTQUE_KF_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_CMCLIENTQUE_ID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.CM_CLIENT_QUE MODIFY (ID CONSTRAINT CC_CMCLIENTQUE_ID_NN NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index I3_CMCLIENTQUE ***
begin   
 execute immediate '
  CREATE INDEX BARS.I3_CMCLIENTQUE ON BARS.CM_CLIENT_QUE (DATEIN) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index I2_CMCLIENTQUE ***
begin   
 execute immediate '
  CREATE INDEX BARS.I2_CMCLIENTQUE ON BARS.CM_CLIENT_QUE (RNK) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_CMCLIENTQUE ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_CMCLIENTQUE ON BARS.CM_CLIENT_QUE (ACC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_CMCLIENTQUE ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_CMCLIENTQUE ON BARS.CM_CLIENT_QUE (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSSMLI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  CM_CLIENT_QUE ***
grant SELECT                                                                 on CM_CLIENT_QUE   to BARSREADER_ROLE;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on CM_CLIENT_QUE   to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on CM_CLIENT_QUE   to BARS_DM;
grant DELETE,INSERT,SELECT,UPDATE                                            on CM_CLIENT_QUE   to OW;
grant UPDATE                                                                 on CM_CLIENT_QUE   to SEROVVV;
grant SELECT                                                                 on CM_CLIENT_QUE   to UPLD;
grant FLASHBACK,SELECT                                                       on CM_CLIENT_QUE   to WR_REFREAD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/CM_CLIENT_QUE.sql =========*** End ***
PROMPT ===================================================================================== 
