

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/CRSOUR_DEALS.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to CRSOUR_DEALS ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''CRSOUR_DEALS'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''CRSOUR_DEALS'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''CRSOUR_DEALS'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table CRSOUR_DEALS ***
begin 
  execute immediate '
  CREATE TABLE BARS.CRSOUR_DEALS 
   (	ID NUMBER(10,0), 
	KF VARCHAR2(6 CHAR), 
	ND NUMBER(10,0), 
	CC_ID VARCHAR2(50 CHAR), 
	VIDD NUMBER(5,0), 
	START_DATE DATE, 
	EXPIRY_DATE DATE, 
	DEAL_AMOUNT NUMBER(24,4), 
	DEAL_CURRENCY NUMBER(3,0), 
	MAIN_ACCOUNT_ID NUMBER(38,0), 
	MAIN_ACCOUNT_NUMBER VARCHAR2(15 CHAR), 
	PLAN_REST NUMBER, 
	CURRENT_REST NUMBER, 
	INTEREST_ACCOUNT_ID NUMBER(38,0), 
	INTEREST_ACCOUNT_NUMBER VARCHAR2(15 CHAR), 
	ACCRUED_INTEREST_PLAN_REST NUMBER, 
	ACCRUED_INTEREST_CURRENT_REST NUMBER, 
	INTEREST_CALENDAR NUMBER(*,0), 
	PARTY_MAIN_ACCOUNT VARCHAR2(15 CHAR), 
	PARTY_INTEREST_ACCOUNT VARCHAR2(15 CHAR), 
	PARTY_MFO VARCHAR2(6 CHAR), 
	TRANSIT_ACCOUNT_NUMBER VARCHAR2(15 CHAR), 
	CENTER_ND NUMBER(10,0), 
	CENTER_CC_ID VARCHAR2(50 CHAR), 
	CENTER_START_DATE DATE, 
	CENTER_EXPIRY_DATE DATE, 
	CENTER_DEAL_AMOUNT NUMBER(24,4), 
	CENTER_DEAL_CURRENCY NUMBER(3,0), 
	CENTER_MAIN_ACCOUNT_ID NUMBER(38,0), 
	CENTER_MAIN_ACCOUNT_NUMBER VARCHAR2(15 CHAR), 
	CENTER_PLAN_REST NUMBER, 
	CENTER_CURRENT_REST NUMBER, 
	CENTER_INT_ACCOUNT_ID NUMBER(38,0), 
	CENTER_INT_ACCOUNT_NUMBER VARCHAR2(15 CHAR), 
	CENTER_ACCR_INT_PLAN_REST NUMBER, 
	CENTER_ACCR_INT_CURRENT_REST NUMBER, 
	CENTER_INTEREST_CALENDAR NUMBER(*,0), 
	CENTER_PARTY_MAIN_ACCOUNT VARCHAR2(15 CHAR), 
	CENTER_PARTY_INTEREST_ACCOUNT VARCHAR2(15 CHAR), 
	CENTER_PARTY_MFO VARCHAR2(6 CHAR), 
	CENTER_TRANSIT_ACCOUNT_NUMBER VARCHAR2(15 CHAR), 
	STATE NUMBER(5,0), 
	STATE_MESSAGE VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to CRSOUR_DEALS ***
 exec bpa.alter_policies('CRSOUR_DEALS');


COMMENT ON TABLE BARS.CRSOUR_DEALS IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.KF IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.ND IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CC_ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.VIDD IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.START_DATE IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.EXPIRY_DATE IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.DEAL_AMOUNT IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.DEAL_CURRENCY IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.MAIN_ACCOUNT_ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.MAIN_ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.PLAN_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CURRENT_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.INTEREST_ACCOUNT_ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.INTEREST_ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.ACCRUED_INTEREST_PLAN_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.ACCRUED_INTEREST_CURRENT_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.INTEREST_CALENDAR IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.PARTY_MAIN_ACCOUNT IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.PARTY_INTEREST_ACCOUNT IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.PARTY_MFO IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.TRANSIT_ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_ND IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_CC_ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_START_DATE IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_EXPIRY_DATE IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_DEAL_AMOUNT IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_DEAL_CURRENCY IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_MAIN_ACCOUNT_ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_MAIN_ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_PLAN_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_CURRENT_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_INT_ACCOUNT_ID IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_INT_ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_ACCR_INT_PLAN_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_ACCR_INT_CURRENT_REST IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_INTEREST_CALENDAR IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_PARTY_MAIN_ACCOUNT IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_PARTY_INTEREST_ACCOUNT IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_PARTY_MFO IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.CENTER_TRANSIT_ACCOUNT_NUMBER IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.STATE IS '';
COMMENT ON COLUMN BARS.CRSOUR_DEALS.STATE_MESSAGE IS '';




PROMPT *** Create  constraint SYS_C0012839 ***
begin   
 execute immediate '
  ALTER TABLE BARS.CRSOUR_DEALS ADD PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index CRSOUR_DEAL_IDX ***
begin   
 execute immediate '
  CREATE INDEX BARS.CRSOUR_DEAL_IDX ON BARS.CRSOUR_DEALS (CC_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index SYS_C0012839 ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.SYS_C0012839 ON BARS.CRSOUR_DEALS (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  CRSOUR_DEALS ***
grant SELECT                                                                 on CRSOUR_DEALS    to BARS_DM;
grant ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE on CRSOUR_DEALS    to CDB;



PROMPT *** Create SYNONYM  to CRSOUR_DEALS ***

  CREATE OR REPLACE SYNONYM CDB.BARS_CRSOUR_DEALS FOR BARS.CRSOUR_DEALS;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/CRSOUR_DEALS.sql =========*** End *** 
PROMPT ===================================================================================== 
