

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SKRYNKA_ND.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SKRYNKA_ND ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SKRYNKA_ND ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SKRYNKA_ND 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ND VARCHAR2(4000), 
	N_SK VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	FIO VARCHAR2(4000), 
	DOKUM VARCHAR2(4000), 
	ISSUED VARCHAR2(4000), 
	ADRES VARCHAR2(4000), 
	DAT_BEGIN VARCHAR2(4000), 
	DAT_END VARCHAR2(4000), 
	TEL VARCHAR2(4000), 
	DOVER VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	DOV_DAT1 VARCHAR2(4000), 
	DOV_DAT2 VARCHAR2(4000), 
	DOV_PASP VARCHAR2(4000), 
	MFOK VARCHAR2(4000), 
	NLSK VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	O_SK VARCHAR2(4000), 
	ISP_DOV VARCHAR2(4000), 
	NDOV VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	NDOC VARCHAR2(4000), 
	DOCDATE VARCHAR2(4000), 
	SDOC VARCHAR2(4000), 
	TARIFF VARCHAR2(4000), 
	FIO2 VARCHAR2(4000), 
	ISSUED2 VARCHAR2(4000), 
	ADRES2 VARCHAR2(4000), 
	PASP2 VARCHAR2(4000), 
	OKPO1 VARCHAR2(4000), 
	OKPO2 VARCHAR2(4000), 
	S_ARENDA VARCHAR2(4000), 
	S_NDS VARCHAR2(4000), 
	SD VARCHAR2(4000), 
	KEYCOUNT VARCHAR2(4000), 
	PRSKIDKA VARCHAR2(4000), 
	PENY VARCHAR2(4000), 
	DATR2 VARCHAR2(4000), 
	MR2 VARCHAR2(4000), 
	MR VARCHAR2(4000), 
	DATR VARCHAR2(4000), 
	ADDND VARCHAR2(4000), 
	AMORT_DATE VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	DEAL_CREATED VARCHAR2(4000), 
	IMPORTED VARCHAR2(4000), 
	DAT_CLOSE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SKRYNKA_ND ***
 exec bpa.alter_policies('ERR$_SKRYNKA_ND');


COMMENT ON TABLE BARS.ERR$_SKRYNKA_ND IS 'DML Error Logging table for "SKRYNKA_ND"';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ND IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.N_SK IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.FIO IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DOKUM IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ISSUED IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ADRES IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DAT_BEGIN IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.TEL IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DOVER IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DOV_DAT1 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DOV_DAT2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DOV_PASP IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.MFOK IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.NLSK IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.O_SK IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ISP_DOV IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.NDOV IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.NDOC IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DOCDATE IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.SDOC IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.TARIFF IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.FIO2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ISSUED2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ADRES2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.PASP2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.OKPO1 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.OKPO2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.S_ARENDA IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.S_NDS IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.SD IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.KEYCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.PRSKIDKA IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.PENY IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DATR2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.MR2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.MR IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DATR IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.ADDND IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.AMORT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.KF IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DEAL_CREATED IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.IMPORTED IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_ND.DAT_CLOSE IS '';



PROMPT *** Create  grants  ERR$_SKRYNKA_ND ***
grant SELECT                                                                 on ERR$_SKRYNKA_ND to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_SKRYNKA_ND to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SKRYNKA_ND.sql =========*** End *
PROMPT ===================================================================================== 
