

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ZAYAVKA.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ZAYAVKA ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ZAYAVKA ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ZAYAVKA 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	RNK VARCHAR2(4000), 
	DK VARCHAR2(4000), 
	ACC0 VARCHAR2(4000), 
	ACC1 VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	S2 VARCHAR2(4000), 
	KURS_Z VARCHAR2(4000), 
	KURS_F VARCHAR2(4000), 
	MFOP VARCHAR2(4000), 
	NLSP VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	KV2 VARCHAR2(4000), 
	KOM VARCHAR2(4000), 
	SKOM VARCHAR2(4000), 
	VDATE VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	MFO0 VARCHAR2(4000), 
	NLS0 VARCHAR2(4000), 
	OKPOP VARCHAR2(4000), 
	OKPO0 VARCHAR2(4000), 
	CONTRACT VARCHAR2(4000), 
	DAT_VMD VARCHAR2(4000), 
	DAT2_VMD VARCHAR2(4000), 
	VIZA VARCHAR2(4000), 
	META VARCHAR2(4000), 
	DAT5_VMD VARCHAR2(4000), 
	RNK_PF VARCHAR2(4000), 
	PRIORITY VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	BASIS VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	FNAMEKB VARCHAR2(4000), 
	IDENTKB VARCHAR2(4000), 
	IDBACK VARCHAR2(4000), 
	PID VARCHAR2(4000), 
	TIPKB VARCHAR2(4000), 
	DATEDOKKB VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	DATT VARCHAR2(4000), 
	OBZ VARCHAR2(4000), 
	DATZ VARCHAR2(4000), 
	FL_PF VARCHAR2(4000), 
	FL_KURSZ VARCHAR2(4000), 
	BENEFCOUNTRY VARCHAR2(4000), 
	BANK_CODE VARCHAR2(4000), 
	BANK_NAME VARCHAR2(4000), 
	S3 VARCHAR2(4000), 
	LIM VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	PRODUCT_GROUP VARCHAR2(4000), 
	NUM_VMD VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	DETAILS VARCHAR2(4000), 
	KURS_KL VARCHAR2(4000), 
	COMM VARCHAR2(4000), 
	CONTACT_FIO VARCHAR2(4000), 
	CONTACT_TEL VARCHAR2(4000), 
	CLOSE_TYPE VARCHAR2(4000), 
	VERIFY_OPT VARCHAR2(4000), 
	AIMS_CODE VARCHAR2(4000), 
	KV_CONV VARCHAR2(4000), 
	OPERID_NOKK VARCHAR2(4000), 
	SOPER VARCHAR2(4000), 
	REF_SPS VARCHAR2(4000), 
	S_PF VARCHAR2(4000), 
	REF_PF VARCHAR2(4000), 
	ID_PREV VARCHAR2(4000), 
	REQ_TYPE VARCHAR2(4000), 
	VDATE_PLAN VARCHAR2(4000), 
	REASON_COMM VARCHAR2(4000), 
	REFOPER VARCHAR2(4000), 
	CODE_2C VARCHAR2(4000), 
	P12_2C VARCHAR2(4000), 
	SUPPORT_DOCUMENT VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ZAYAVKA ***
 exec bpa.alter_policies('ERR$_ZAYAVKA');


COMMENT ON TABLE BARS.ERR$_ZAYAVKA IS 'DML Error Logging table for "ZAYAVKA"';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ACC0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ACC1 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.S2 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KURS_Z IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KURS_F IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.MFOP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.NLSP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KV2 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KOM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.SKOM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.VDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.REF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.MFO0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.NLS0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.OKPOP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.OKPO0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.CONTRACT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DAT_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DAT2_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.VIZA IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.META IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DAT5_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.RNK_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.PRIORITY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.BASIS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ID IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.FNAMEKB IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.IDENTKB IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.IDBACK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.PID IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.TIPKB IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DATEDOKKB IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ND IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DATT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.OBZ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DATZ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.FL_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.FL_KURSZ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.BENEFCOUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.BANK_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.BANK_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.S3 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.LIM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.PRODUCT_GROUP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.NUM_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.DETAILS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KURS_KL IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.COMM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.CONTACT_FIO IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.CONTACT_TEL IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.CLOSE_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.VERIFY_OPT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.AIMS_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.KV_CONV IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.OPERID_NOKK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.SOPER IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.REF_SPS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.S_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.REF_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ID_PREV IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.REQ_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.VDATE_PLAN IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.REASON_COMM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.REFOPER IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.CODE_2C IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.P12_2C IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.SUPPORT_DOCUMENT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA.ORA_ERR_TAG$ IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ZAYAVKA.sql =========*** End *** 
PROMPT ===================================================================================== 
