

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ZAYAVKA_RU.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ZAYAVKA_RU ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ZAYAVKA_RU ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ZAYAVKA_RU 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	REQ_ID VARCHAR2(4000), 
	DK VARCHAR2(4000), 
	OBZ VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	DATT VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	ND_RNK VARCHAR2(4000), 
	KV_CONV VARCHAR2(4000), 
	LCV_CONV VARCHAR2(4000), 
	KV2 VARCHAR2(4000), 
	LCV VARCHAR2(4000), 
	DIG VARCHAR2(4000), 
	S2 VARCHAR2(4000), 
	S2S VARCHAR2(4000), 
	S3 VARCHAR2(4000), 
	KOM VARCHAR2(4000), 
	SKOM VARCHAR2(4000), 
	KURS_Z VARCHAR2(4000), 
	KURS_F VARCHAR2(4000), 
	VDATE VARCHAR2(4000), 
	DATZ VARCHAR2(4000), 
	ACC0 VARCHAR2(4000), 
	NLS_ACC0 VARCHAR2(4000), 
	MFO0 VARCHAR2(4000), 
	NLS0 VARCHAR2(4000), 
	OKPO0 VARCHAR2(4000), 
	OSTC0 VARCHAR2(4000), 
	ACC1 VARCHAR2(4000), 
	OSTC VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	VIZA VARCHAR2(4000), 
	PRIORITY VARCHAR2(4000), 
	PRIORNAME VARCHAR2(4000), 
	PRIORVERIFY VARCHAR2(4000), 
	IDBACK VARCHAR2(4000), 
	FL_PF VARCHAR2(4000), 
	MFOP VARCHAR2(4000), 
	NLSP VARCHAR2(4000), 
	OKPOP VARCHAR2(4000), 
	RNK_PF VARCHAR2(4000), 
	PID VARCHAR2(4000), 
	CONTRACT VARCHAR2(4000), 
	DAT2_VMD VARCHAR2(4000), 
	META VARCHAR2(4000), 
	AIM_NAME VARCHAR2(4000), 
	BASIS VARCHAR2(4000), 
	PRODUCT_GROUP VARCHAR2(4000), 
	PRODUCT_GROUP_NAME VARCHAR2(4000), 
	NUM_VMD VARCHAR2(4000), 
	DAT_VMD VARCHAR2(4000), 
	DAT5_VMD VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	BENEFCOUNTRY VARCHAR2(4000), 
	BANK_CODE VARCHAR2(4000), 
	BANK_NAME VARCHAR2(4000), 
	USERID VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	FL_KURSZ VARCHAR2(4000), 
	IDENTKB VARCHAR2(4000), 
	COMM VARCHAR2(4000), 
	CUST_BRANCH VARCHAR2(4000), 
	KURS_KL VARCHAR2(4000), 
	CONTACT_FIO VARCHAR2(4000), 
	CONTACT_TEL VARCHAR2(4000), 
	VERIFY_OPT VARCHAR2(4000), 
	CLOSE_TYPE VARCHAR2(4000), 
	CLOSE_TYPE_NAME VARCHAR2(4000), 
	AIMS_CODE VARCHAR2(4000), 
	S_PF VARCHAR2(4000), 
	REF_PF VARCHAR2(4000), 
	REF_SPS VARCHAR2(4000), 
	START_TIME VARCHAR2(4000), 
	STATE VARCHAR2(4000), 
	OPERID_NOKK VARCHAR2(4000), 
	REQ_TYPE VARCHAR2(4000), 
	REF_SPS_CHECK VARCHAR2(4000), 
	VDATE_PLAN VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	REASON_COMM VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ZAYAVKA_RU ***
 exec bpa.alter_policies('ERR$_ZAYAVKA_RU');


COMMENT ON TABLE BARS.ERR$_ZAYAVKA_RU IS 'DML Error Logging table for "ZAYAVKA_RU"';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ID IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REQ_ID IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.OBZ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ND IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DATT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ND_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.KV_CONV IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.LCV_CONV IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.KV2 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.LCV IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DIG IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.S2 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.S2S IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.S3 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.KOM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.SKOM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.KURS_Z IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.KURS_F IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.VDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DATZ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ACC0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.NLS_ACC0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.MFO0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.NLS0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.OKPO0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.OSTC0 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.ACC1 IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.OSTC IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.VIZA IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.PRIORITY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.PRIORNAME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.PRIORVERIFY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.IDBACK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.FL_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.MFOP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.NLSP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.OKPOP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.RNK_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.PID IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CONTRACT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DAT2_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.META IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.AIM_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.BASIS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.PRODUCT_GROUP IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.PRODUCT_GROUP_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.NUM_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DAT_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.DAT5_VMD IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.BENEFCOUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.BANK_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.BANK_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.FL_KURSZ IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.IDENTKB IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.COMM IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CUST_BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.KURS_KL IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CONTACT_FIO IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CONTACT_TEL IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.VERIFY_OPT IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CLOSE_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CLOSE_TYPE_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.AIMS_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.S_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REF_PF IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REF_SPS IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.START_TIME IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.STATE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.OPERID_NOKK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REQ_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REF_SPS_CHECK IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.VDATE_PLAN IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_ZAYAVKA_RU.REASON_COMM IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ZAYAVKA_RU.sql =========*** End *
PROMPT ===================================================================================== 
