

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CC_SOB_UPDATE.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CC_SOB_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CC_SOB_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CC_SOB_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ND VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	TXT VARCHAR2(4000), 
	OTM VARCHAR2(4000), 
	FREQ VARCHAR2(4000), 
	PSYS VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	IDUPD VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	FACT_DATE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CC_SOB_UPDATE ***
 exec bpa.alter_policies('ERR$_CC_SOB_UPDATE');


COMMENT ON TABLE BARS.ERR$_CC_SOB_UPDATE IS 'DML Error Logging table for "CC_SOB_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.TXT IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.OTM IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.FREQ IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.PSYS IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_CC_SOB_UPDATE.FACT_DATE IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CC_SOB_UPDATE.sql =========*** En
PROMPT ===================================================================================== 
