

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ALEGRO.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ALEGRO ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ALEGRO ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ALEGRO 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ZKPO VARCHAR2(4000), 
	NAME VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	NUM VARCHAR2(4000), 
	ACCOUNTMVPS VARCHAR2(4000), 
	PARENTID VARCHAR2(4000), 
	POSTALINDEX VARCHAR2(4000), 
	ADDRESS VARCHAR2(4000), 
	KOATUU VARCHAR2(4000), 
	MANAGERPHONE VARCHAR2(4000), 
	PHONE VARCHAR2(4000), 
	BUHGALTERPHONE VARCHAR2(4000), 
	EMAIL VARCHAR2(4000), 
	FOSSMAIL VARCHAR2(4000), 
	NBUMAIL VARCHAR2(4000), 
	FAX VARCHAR2(4000), 
	OPENDATE VARCHAR2(4000), 
	CLOSEDATE VARCHAR2(4000), 
	TERMINALNAME VARCHAR2(4000), 
	ORDERPUNKTNUMBER VARCHAR2(4000), 
	ACCOUNT1 VARCHAR2(4000), 
	ACCOUNT2 VARCHAR2(4000), 
	ACCOUNT3 VARCHAR2(4000), 
	ACCOUNT4 VARCHAR2(4000), 
	QUATERSAREA VARCHAR2(4000), 
	EMPLOYNUMBER VARCHAR2(4000), 
	PRIVACYFORM VARCHAR2(4000), 
	CITYCODE VARCHAR2(4000), 
	EMITSERVICE VARCHAR2(4000), 
	PAYMENTPOS VARCHAR2(4000), 
	PAYMENTIMP VARCHAR2(4000), 
	PAYMENTATM VARCHAR2(4000), 
	ACCOUNT24 VARCHAR2(4000), 
	ACCOUNT09 VARCHAR2(4000), 
	GEOGRAFICALCODE VARCHAR2(4000), 
	RANGE VARCHAR2(4000), 
	OPERWINDOWSACTIVE VARCHAR2(4000), 
	CUREXCHANGEPOINTS VARCHAR2(4000), 
	CUREXCHANGECONTRACTS VARCHAR2(4000), 
	RESPONSIBLEPHONE VARCHAR2(4000), 
	MANAGER VARCHAR2(4000), 
	GLAVBUHGALTER VARCHAR2(4000), 
	RESPONSIBLEPERSON VARCHAR2(4000), 
	REGCODE VARCHAR2(4000), 
	ACTUALITY VARCHAR2(4000), 
	REPORTBRANCH VARCHAR2(4000), 
	NAMEUKRR VARCHAR2(4000), 
	NAMERUSR VARCHAR2(4000), 
	NAMEENGR VARCHAR2(4000), 
	NAMEUKRB VARCHAR2(4000), 
	NAMERUSB VARCHAR2(4000), 
	NAMEENGB VARCHAR2(4000), 
	REGBICCODE VARCHAR2(4000), 
	CITYNAME VARCHAR2(4000), 
	CITYNAMERUS VARCHAR2(4000), 
	CITYNAMEENG VARCHAR2(4000), 
	ADDRESSRUS VARCHAR2(4000), 
	ADDRESSENG VARCHAR2(4000), 
	VAL VARCHAR2(4000), 
	NLS_CHK VARCHAR2(4000), 
	NLS_CHD VARCHAR2(4000), 
	NLS6_GOU_CH VARCHAR2(4000), 
	NLS_CHK0 VARCHAR2(4000), 
	NLS_CHK1 VARCHAR2(4000), 
	NLS_GTD VARCHAR2(4000), 
	NLS6_GOU_GT VARCHAR2(4000), 
	NLS7_GOU_KOB VARCHAR2(4000), 
	NLS6_MFO_KOB VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ALEGRO ***
 exec bpa.alter_policies('ERR$_ALEGRO');


COMMENT ON TABLE BARS.ERR$_ALEGRO IS 'DML Error Logging table for "ALEGRO"';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.PAYMENTATM IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNT24 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNT09 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.GEOGRAFICALCODE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.RANGE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.OPERWINDOWSACTIVE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CUREXCHANGEPOINTS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CUREXCHANGECONTRACTS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.RESPONSIBLEPHONE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.MANAGER IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.GLAVBUHGALTER IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.RESPONSIBLEPERSON IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.REGCODE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACTUALITY IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.REPORTBRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAMEUKRR IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAMERUSR IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAMEENGR IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAMEUKRB IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAMERUSB IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAMEENGB IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.REGBICCODE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CITYNAME IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CITYNAMERUS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CITYNAMEENG IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ADDRESSRUS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ADDRESSENG IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.VAL IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS_CHK IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS_CHD IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS6_GOU_CH IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS_CHK0 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS_CHK1 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS_GTD IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS6_GOU_GT IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS7_GOU_KOB IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NLS6_MFO_KOB IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ZKPO IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NUM IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNTMVPS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.PARENTID IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.POSTALINDEX IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ADDRESS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.KOATUU IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.MANAGERPHONE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.PHONE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.BUHGALTERPHONE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.EMAIL IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.FOSSMAIL IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.NBUMAIL IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.FAX IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.OPENDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CLOSEDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.TERMINALNAME IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ORDERPUNKTNUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNT1 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNT2 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNT3 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.ACCOUNT4 IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.QUATERSAREA IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.EMPLOYNUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.PRIVACYFORM IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.CITYCODE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.EMITSERVICE IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.PAYMENTPOS IS '';
COMMENT ON COLUMN BARS.ERR$_ALEGRO.PAYMENTIMP IS '';



PROMPT *** Create  grants  ERR$_ALEGRO ***
grant SELECT                                                                 on ERR$_ALEGRO     to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_ALEGRO     to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ALEGRO.sql =========*** End *** =
PROMPT ===================================================================================== 
