

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_FINMON_QUE.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_FINMON_QUE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_FINMON_QUE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_FINMON_QUE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	REC VARCHAR2(4000), 
	STATUS VARCHAR2(4000), 
	OPR_VID1 VARCHAR2(4000), 
	OPR_VID2 VARCHAR2(4000), 
	COMM_VID2 VARCHAR2(4000), 
	OPR_VID3 VARCHAR2(4000), 
	COMM_VID3 VARCHAR2(4000), 
	AGENT_ID VARCHAR2(4000), 
	IN_DATE VARCHAR2(4000), 
	MONITOR_MODE VARCHAR2(4000), 
	RNK_A VARCHAR2(4000), 
	RNK_B VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	DAT_I VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_FINMON_QUE ***
 exec bpa.alter_policies('ERR$_FINMON_QUE');


COMMENT ON TABLE BARS.ERR$_FINMON_QUE IS 'DML Error Logging table for "FINMON_QUE"';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.REF IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.REC IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.STATUS IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.OPR_VID1 IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.OPR_VID2 IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.COMM_VID2 IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.OPR_VID3 IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.COMM_VID3 IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.AGENT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.IN_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.MONITOR_MODE IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.RNK_A IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.RNK_B IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.COMMENTS IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.DAT_I IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_FINMON_QUE.ORA_ERR_OPTYP$ IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_FINMON_QUE.sql =========*** End *
PROMPT ===================================================================================== 
