

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CCK_RESTR_UPDATE.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CCK_RESTR_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CCK_RESTR_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CCK_RESTR_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	RESTR_ID VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	VID_RESTR VARCHAR2(4000), 
	TXT VARCHAR2(4000), 
	SUMR VARCHAR2(4000), 
	FDAT_END VARCHAR2(4000), 
	PR_NO VARCHAR2(4000), 
	S_RESTR VARCHAR2(4000), 
	N_DODATOK VARCHAR2(4000), 
	QTY_PAY VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CCK_RESTR_UPDATE ***
 exec bpa.alter_policies('ERR$_CCK_RESTR_UPDATE');


COMMENT ON TABLE BARS.ERR$_CCK_RESTR_UPDATE IS 'DML Error Logging table for "CCK_RESTR_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.RESTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.VID_RESTR IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.TXT IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.SUMR IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.FDAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.PR_NO IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.S_RESTR IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.N_DODATOK IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.QTY_PAY IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR_UPDATE.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CCK_RESTR_UPDATE.sql =========***
PROMPT ===================================================================================== 
