

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_DPU_AGREEMENTS.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_DPU_AGREEMENTS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_DPU_AGREEMENTS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_DPU_AGREEMENTS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	KF VARCHAR2(4000), 
	AGRMNT_ID VARCHAR2(4000), 
	AGRMNT_TYPE VARCHAR2(4000), 
	AGRMNT_NUM VARCHAR2(4000), 
	AGRMNT_BDATE VARCHAR2(4000), 
	AGRMNT_CRDATE VARCHAR2(4000), 
	AGRMNT_CRUSER VARCHAR2(4000), 
	AGRMNT_PRCDATE VARCHAR2(4000), 
	AGRMNT_PRCUSER VARCHAR2(4000), 
	AGRMNT_STATE VARCHAR2(4000), 
	DPU_ID VARCHAR2(4000), 
	DUE_DATE VARCHAR2(4000), 
	UNDO_ID VARCHAR2(4000), 
	AMOUNT VARCHAR2(4000), 
	RATE VARCHAR2(4000), 
	FREQ VARCHAR2(4000), 
	BEGIN_DATE VARCHAR2(4000), 
	END_DATE VARCHAR2(4000), 
	STOP_ID VARCHAR2(4000), 
	PAYMENT_DETAILS VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_DPU_AGREEMENTS ***
 exec bpa.alter_policies('ERR$_DPU_AGREEMENTS');


COMMENT ON TABLE BARS.ERR$_DPU_AGREEMENTS IS 'DML Error Logging table for "DPU_AGREEMENTS"';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.KF IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_BDATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_CRDATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_CRUSER IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_PRCDATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_PRCUSER IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AGRMNT_STATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.DPU_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.DUE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.UNDO_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.RATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.FREQ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.BEGIN_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.STOP_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.PAYMENT_DETAILS IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_AGREEMENTS.COMMENTS IS '';



PROMPT *** Create  grants  ERR$_DPU_AGREEMENTS ***
grant SELECT                                                                 on ERR$_DPU_AGREEMENTS to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_DPU_AGREEMENTS to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_DPU_AGREEMENTS.sql =========*** E
PROMPT ===================================================================================== 
