

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_INT_ACCN_UPDATE.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_INT_ACCN_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_INT_ACCN_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_INT_ACCN_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	METR VARCHAR2(4000), 
	BASEM VARCHAR2(4000), 
	BASEY VARCHAR2(4000), 
	FREQ VARCHAR2(4000), 
	STP_DAT VARCHAR2(4000), 
	ACR_DAT VARCHAR2(4000), 
	APL_DAT VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	ACRA VARCHAR2(4000), 
	ACRB VARCHAR2(4000), 
	S VARCHAR2(4000), 
	TTB VARCHAR2(4000), 
	KVB VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	MFOB VARCHAR2(4000), 
	NAMB VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	IO VARCHAR2(4000), 
	IDU VARCHAR2(4000), 
	IDR VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	GLOBAL_BDATE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_INT_ACCN_UPDATE ***
 exec bpa.alter_policies('ERR$_INT_ACCN_UPDATE');


COMMENT ON TABLE BARS.ERR$_INT_ACCN_UPDATE IS 'DML Error Logging table for "INT_ACCN_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.METR IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.BASEM IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.BASEY IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.FREQ IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.STP_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ACR_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.APL_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.TT IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ACRA IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.ACRB IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.S IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.TTB IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.KVB IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.MFOB IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.NAMB IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.IO IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.IDU IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.IDR IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_INT_ACCN_UPDATE.GLOBAL_BDATE IS '';



PROMPT *** Create  grants  ERR$_INT_ACCN_UPDATE ***
grant SELECT                                                                 on ERR$_INT_ACCN_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_INT_ACCN_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_INT_ACCN_UPDATE.sql =========*** 
PROMPT ===================================================================================== 
