

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OTCN_F08_DEBZ.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OTCN_F08_DEBZ ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OTCN_F08_DEBZ ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OTCN_F08_DEBZ 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	REF VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	ACCD VARCHAR2(4000), 
	NLSD VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	ACCK VARCHAR2(4000), 
	NLSK VARCHAR2(4000), 
	K072 VARCHAR2(4000), 
	S VARCHAR2(4000), 
	SQ VARCHAR2(4000), 
	OSTP VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	DATD VARCHAR2(4000), 
	RECID VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OTCN_F08_DEBZ ***
 exec bpa.alter_policies('ERR$_OTCN_F08_DEBZ');


COMMENT ON TABLE BARS.ERR$_OTCN_F08_DEBZ IS 'DML Error Logging table for "OTCN_F08_DEBZ"';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.REF IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.TT IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ACCD IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.NLSD IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.KV IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ACCK IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.NLSK IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.K072 IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.S IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.SQ IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.OSTP IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.ND IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.DATD IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.RECID IS '';
COMMENT ON COLUMN BARS.ERR$_OTCN_F08_DEBZ.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OTCN_F08_DEBZ.sql =========*** En
PROMPT ===================================================================================== 
