

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONTRACTS_APE.sql =========**
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_CONTRACTS_APE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_CONTRACTS_APE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_CONTRACTS_APE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	APE_ID VARCHAR2(4000), 
	CONTR_ID VARCHAR2(4000), 
	NUM VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	S VARCHAR2(4000), 
	RATE VARCHAR2(4000), 
	S_VK VARCHAR2(4000), 
	BEGIN_DATE VARCHAR2(4000), 
	END_DATE VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000), 
	DELETE_DATE VARCHAR2(4000), 
	DELETE_UID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_CONTRACTS_APE ***
 exec bpa.alter_policies('ERR$_CIM_CONTRACTS_APE');


COMMENT ON TABLE BARS.ERR$_CIM_CONTRACTS_APE IS 'DML Error Logging table for "CIM_CONTRACTS_APE"';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.APE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.CONTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.NUM IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.KV IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.S IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.RATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.S_VK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.BEGIN_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.COMMENTS IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.DELETE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS_APE.DELETE_UID IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONTRACTS_APE.sql =========**
PROMPT ===================================================================================== 
