

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CUST_REQUESTS.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CUST_REQUESTS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CUST_REQUESTS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CUST_REQUESTS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	REQ_ID VARCHAR2(4000), 
	REQ_TYPE VARCHAR2(4000), 
	TRUSTEE_TYPE VARCHAR2(4000), 
	TRUSTEE_RNK VARCHAR2(4000), 
	CERTIF_NUM VARCHAR2(4000), 
	CERTIF_DATE VARCHAR2(4000), 
	DATE_START VARCHAR2(4000), 
	DATE_FINISH VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000), 
	REQ_BDATE VARCHAR2(4000), 
	REQ_CRDATE VARCHAR2(4000), 
	REQ_CRUSER VARCHAR2(4000), 
	REQ_PRCDATE VARCHAR2(4000), 
	REQ_PRCUSER VARCHAR2(4000), 
	REQ_STATE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CUST_REQUESTS ***
 exec bpa.alter_policies('ERR$_CUST_REQUESTS');


COMMENT ON TABLE BARS.ERR$_CUST_REQUESTS IS 'DML Error Logging table for "CUST_REQUESTS"';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.TRUSTEE_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.TRUSTEE_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.CERTIF_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.CERTIF_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.DATE_START IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.DATE_FINISH IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.COMMENTS IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_BDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_CRDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_CRUSER IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_PRCDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_PRCUSER IS '';
COMMENT ON COLUMN BARS.ERR$_CUST_REQUESTS.REQ_STATE IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CUST_REQUESTS.sql =========*** En
PROMPT ===================================================================================== 
