

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SKRYNKA_MENU.sql =========*** Run
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SKRYNKA_MENU ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SKRYNKA_MENU ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SKRYNKA_MENU 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ITEM VARCHAR2(4000), 
	NAME VARCHAR2(4000), 
	TYPE VARCHAR2(4000), 
	DATENAME1 VARCHAR2(4000), 
	DATENAME2 VARCHAR2(4000), 
	TT VARCHAR2(4000), 
	SK VARCHAR2(4000), 
	TT2 VARCHAR2(4000), 
	TT3 VARCHAR2(4000), 
	VOB VARCHAR2(4000), 
	VOB2 VARCHAR2(4000), 
	VOB3 VARCHAR2(4000), 
	NUMPARNAME VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SKRYNKA_MENU ***
 exec bpa.alter_policies('ERR$_SKRYNKA_MENU');


COMMENT ON TABLE BARS.ERR$_SKRYNKA_MENU IS 'DML Error Logging table for "SKRYNKA_MENU"';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.ITEM IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.NAME IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.DATENAME1 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.DATENAME2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.TT IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.SK IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.TT2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.TT3 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.VOB IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.VOB2 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.VOB3 IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.NUMPARNAME IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_SKRYNKA_MENU.KF IS '';



PROMPT *** Create  grants  ERR$_SKRYNKA_MENU ***
grant SELECT                                                                 on ERR$_SKRYNKA_MENU to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_SKRYNKA_MENU to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SKRYNKA_MENU.sql =========*** End
PROMPT ===================================================================================== 
