

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIG_DOG_GENERAL.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIG_DOG_GENERAL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIG_DOG_GENERAL ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIG_DOG_GENERAL 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	CUST_ID VARCHAR2(4000), 
	PHASE_ID VARCHAR2(4000), 
	PAY_METHOD_ID VARCHAR2(4000), 
	PAY_PERIOD_ID VARCHAR2(4000), 
	OPERATION VARCHAR2(4000), 
	CONTRACT_TYPE VARCHAR2(4000), 
	CONTRACT_CODE VARCHAR2(4000), 
	CONTRACT_DATE VARCHAR2(4000), 
	CONTRACT_START_DATE VARCHAR2(4000), 
	CURRENCY_ID VARCHAR2(4000), 
	CREDIT_PURPOSE VARCHAR2(4000), 
	NEGATIVE_STATUS VARCHAR2(4000), 
	APPLICATION_DATE VARCHAR2(4000), 
	EXP_END_DATE VARCHAR2(4000), 
	FACT_END_DATE VARCHAR2(4000), 
	UPD_DATE VARCHAR2(4000), 
	SYNC_DATE VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	BRANCH_DOG VARCHAR2(4000), 
	SEND_DATE VARCHAR2(4000), 
	SEND_ID VARCHAR2(4000), 
	BATCH_ID VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIG_DOG_GENERAL ***
 exec bpa.alter_policies('ERR$_CIG_DOG_GENERAL');


COMMENT ON TABLE BARS.ERR$_CIG_DOG_GENERAL IS 'DML Error Logging table for "CIG_DOG_GENERAL"';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.PAY_PERIOD_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.OPERATION IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CONTRACT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CONTRACT_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CONTRACT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CONTRACT_START_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CURRENCY_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CREDIT_PURPOSE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.NEGATIVE_STATUS IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.APPLICATION_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.EXP_END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.FACT_END_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.UPD_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.SYNC_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.BRANCH_DOG IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.SEND_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.SEND_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.BATCH_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.CUST_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.PHASE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIG_DOG_GENERAL.PAY_METHOD_ID IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIG_DOG_GENERAL.sql =========*** 
PROMPT ===================================================================================== 
