

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTBANK_UPDATE.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CUSTBANK_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CUSTBANK_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CUSTBANK_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	ALT_BIC VARCHAR2(4000), 
	BIC VARCHAR2(4000), 
	RATING VARCHAR2(4000), 
	KOD_B VARCHAR2(4000), 
	DAT_ND VARCHAR2(4000), 
	RUK VARCHAR2(4000), 
	TELR VARCHAR2(4000), 
	BUH VARCHAR2(4000), 
	TELB VARCHAR2(4000), 
	NUM_ND VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CUSTBANK_UPDATE ***
 exec bpa.alter_policies('ERR$_CUSTBANK_UPDATE');


COMMENT ON TABLE BARS.ERR$_CUSTBANK_UPDATE IS 'DML Error Logging table for "CUSTBANK_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.ALT_BIC IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.BIC IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.RATING IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.KOD_B IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.DAT_ND IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.RUK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.TELR IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.BUH IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.TELB IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTBANK_UPDATE.NUM_ND IS '';



PROMPT *** Create  grants  ERR$_CUSTBANK_UPDATE ***
grant SELECT                                                                 on ERR$_CUSTBANK_UPDATE to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTBANK_UPDATE.sql =========*** 
PROMPT ===================================================================================== 
