

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_INHERITORS.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_DPT_INHERITORS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_DPT_INHERITORS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_DPT_INHERITORS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	DPT_ID VARCHAR2(4000), 
	INHERIT_CUSTID VARCHAR2(4000), 
	INHERIT_SHARE VARCHAR2(4000), 
	INHERIT_DATE VARCHAR2(4000), 
	CERTIF_NUM VARCHAR2(4000), 
	CERTIF_DATE VARCHAR2(4000), 
	BANKDATE VARCHAR2(4000), 
	INHERIT_STATE VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	ATTR_INCOME VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_DPT_INHERITORS ***
 exec bpa.alter_policies('ERR$_DPT_INHERITORS');


COMMENT ON TABLE BARS.ERR$_DPT_INHERITORS IS 'DML Error Logging table for "DPT_INHERITORS"';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.DPT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.INHERIT_CUSTID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.INHERIT_SHARE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.INHERIT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.CERTIF_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.CERTIF_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.BANKDATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.INHERIT_STATE IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.KF IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_INHERITORS.ATTR_INCOME IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_INHERITORS.sql =========*** E
PROMPT ===================================================================================== 
