

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CUSTOMER ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CUSTOMER ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CUSTOMER 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	RNK VARCHAR2(4000), 
	TGR VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	NMKV VARCHAR2(4000), 
	NMKK VARCHAR2(4000), 
	CODCAGENT VARCHAR2(4000), 
	PRINSIDER VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	ADR VARCHAR2(4000), 
	SAB VARCHAR2(4000), 
	C_REG VARCHAR2(4000), 
	C_DST VARCHAR2(4000), 
	RGTAX VARCHAR2(4000), 
	DATET VARCHAR2(4000), 
	ADM VARCHAR2(4000), 
	DATEA VARCHAR2(4000), 
	STMT VARCHAR2(4000), 
	DATE_ON VARCHAR2(4000), 
	DATE_OFF VARCHAR2(4000), 
	NOTES VARCHAR2(4000), 
	NOTESEC VARCHAR2(4000), 
	CRISK VARCHAR2(4000), 
	PINCODE VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	RNKP VARCHAR2(4000), 
	ISE VARCHAR2(4000), 
	FS VARCHAR2(4000), 
	OE VARCHAR2(4000), 
	VED VARCHAR2(4000), 
	SED VARCHAR2(4000), 
	LIM VARCHAR2(4000), 
	MB VARCHAR2(4000), 
	RGADM VARCHAR2(4000), 
	BC VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	TAXF VARCHAR2(4000), 
	NOMPDV VARCHAR2(4000), 
	K050 VARCHAR2(4000), 
	NREZID_CODE VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CUSTOMER ***
 exec bpa.alter_policies('ERR$_CUSTOMER');


COMMENT ON TABLE BARS.ERR$_CUSTOMER IS 'DML Error Logging table for "CUSTOMER"';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.TGR IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NMKV IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NMKK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.CODCAGENT IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.PRINSIDER IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ADR IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.SAB IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.C_REG IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.C_DST IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.RGTAX IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.DATET IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ADM IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.DATEA IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.STMT IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.DATE_ON IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.DATE_OFF IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NOTES IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NOTESEC IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.CRISK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.PINCODE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.RNKP IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ISE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.FS IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.OE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.VED IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.SED IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.LIM IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.MB IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.RGADM IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.BC IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.TAXF IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NOMPDV IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.K050 IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER.NREZID_CODE IS '';



PROMPT *** Create  grants  ERR$_CUSTOMER ***
grant SELECT                                                                 on ERR$_CUSTOMER   to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CUSTOMER   to BARS_DM;
grant SELECT                                                                 on ERR$_CUSTOMER   to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER.sql =========*** End ***
PROMPT ===================================================================================== 
