

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_DEPOSIT.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_DPT_DEPOSIT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_DPT_DEPOSIT ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_DPT_DEPOSIT 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	DEPOSIT_ID VARCHAR2(4000), 
	VIDD VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	DAT_BEGIN VARCHAR2(4000), 
	DAT_END VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000), 
	MFO_P VARCHAR2(4000), 
	NLS_P VARCHAR2(4000), 
	LIMIT VARCHAR2(4000), 
	DEPOSIT_COD VARCHAR2(4000), 
	NAME_P VARCHAR2(4000), 
	DATZ VARCHAR2(4000), 
	OKPO_P VARCHAR2(4000), 
	DAT_EXT_INT VARCHAR2(4000), 
	CNT_DUBL VARCHAR2(4000), 
	CNT_EXT_INT VARCHAR2(4000), 
	FREQ VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	STATUS VARCHAR2(4000), 
	DPT_D VARCHAR2(4000), 
	ACC_D VARCHAR2(4000), 
	MFO_D VARCHAR2(4000), 
	NLS_D VARCHAR2(4000), 
	NMS_D VARCHAR2(4000), 
	OKPO_D VARCHAR2(4000), 
	DAT_END_ALT VARCHAR2(4000), 
	STOP_ID VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	USERID VARCHAR2(4000), 
	ARCHDOC_ID VARCHAR2(4000), 
	FORBID_EXTENSION VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_DPT_DEPOSIT ***
 exec bpa.alter_policies('ERR$_DPT_DEPOSIT');


COMMENT ON TABLE BARS.ERR$_DPT_DEPOSIT IS 'DML Error Logging table for "DPT_DEPOSIT"';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DEPOSIT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.VIDD IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.KV IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DAT_BEGIN IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.COMMENTS IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.MFO_P IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.NLS_P IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.LIMIT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DEPOSIT_COD IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.NAME_P IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DATZ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.OKPO_P IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DAT_EXT_INT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.CNT_DUBL IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.CNT_EXT_INT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.FREQ IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ND IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.STATUS IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DPT_D IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ACC_D IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.MFO_D IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.NLS_D IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.NMS_D IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.OKPO_D IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.DAT_END_ALT IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.STOP_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.KF IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.ARCHDOC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPT_DEPOSIT.FORBID_EXTENSION IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_DPT_DEPOSIT.sql =========*** End 
PROMPT ===================================================================================== 
