

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OTC_FF6_HISTORY_ACC.sql =========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OTC_FF6_HISTORY_ACC ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OTC_FF6_HISTORY_ACC ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OTC_FF6_HISTORY_ACC 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	DATF VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	ACCC VARCHAR2(4000), 
	NBS VARCHAR2(4000), 
	SGN VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	KV_DOG VARCHAR2(4000), 
	NMS VARCHAR2(4000), 
	DAOS VARCHAR2(4000), 
	DAZS VARCHAR2(4000), 
	OST VARCHAR2(4000), 
	OSTQ VARCHAR2(4000), 
	DOSQ VARCHAR2(4000), 
	KOSQ VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	NKD VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	STAFF VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	S260 VARCHAR2(4000), 
	K110 VARCHAR2(4000), 
	K111 VARCHAR2(4000), 
	S031 VARCHAR2(4000), 
	S032 VARCHAR2(4000), 
	CC VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	OSTQ_KD VARCHAR2(4000), 
	R_DOS VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	S280 VARCHAR2(4000), 
	S290 VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OTC_FF6_HISTORY_ACC ***
 exec bpa.alter_policies('ERR$_OTC_FF6_HISTORY_ACC');


COMMENT ON TABLE BARS.ERR$_OTC_FF6_HISTORY_ACC IS 'DML Error Logging table for "OTC_FF6_HISTORY_ACC"';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.DATF IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ACCC IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.NBS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.SGN IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.KV IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.KV_DOG IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.NMS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.DAOS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.DAZS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.OST IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.OSTQ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.DOSQ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.KOSQ IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.ND IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.NKD IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.STAFF IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.S260 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.K110 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.K111 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.S031 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.S032 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.CC IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.OSTQ_KD IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.R_DOS IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.S280 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.S290 IS '';
COMMENT ON COLUMN BARS.ERR$_OTC_FF6_HISTORY_ACC.KF IS '';



PROMPT *** Create  grants  ERR$_OTC_FF6_HISTORY_ACC ***
grant SELECT                                                                 on ERR$_OTC_FF6_HISTORY_ACC to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_OTC_FF6_HISTORY_ACC to BARS_DM;
grant SELECT                                                                 on ERR$_OTC_FF6_HISTORY_ACC to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OTC_FF6_HISTORY_ACC.sql =========
PROMPT ===================================================================================== 
