

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONTRACTS.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_CONTRACTS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_CONTRACTS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_CONTRACTS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	CONTR_ID VARCHAR2(4000), 
	CONTR_TYPE VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	NUM VARCHAR2(4000), 
	OPEN_DATE VARCHAR2(4000), 
	CLOSE_DATE VARCHAR2(4000), 
	S VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	BENEF_ID VARCHAR2(4000), 
	STATUS_ID VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000), 
	SUBNUM VARCHAR2(4000), 
	OWNER_UID VARCHAR2(4000), 
	BIC VARCHAR2(4000), 
	B010 VARCHAR2(4000), 
	SERVICE_BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_CONTRACTS ***
 exec bpa.alter_policies('ERR$_CIM_CONTRACTS');


COMMENT ON TABLE BARS.ERR$_CIM_CONTRACTS IS 'DML Error Logging table for "CIM_CONTRACTS"';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.CONTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.CONTR_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.NUM IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.OPEN_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.CLOSE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.S IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.KV IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.BENEF_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.STATUS_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.COMMENTS IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.SUBNUM IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.OWNER_UID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.BIC IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.B010 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.SERVICE_BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_CONTRACTS.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_CONTRACTS.sql =========*** En
PROMPT ===================================================================================== 
