

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_F98.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_F98 ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_F98 ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_F98 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	NP VARCHAR2(4000), 
	DT VARCHAR2(4000), 
	EK_POK VARCHAR2(4000), 
	KO VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	NKB VARCHAR2(4000), 
	KU VARCHAR2(4000), 
	PRB VARCHAR2(4000), 
	K030 VARCHAR2(4000), 
	V_SANK VARCHAR2(4000), 
	KO_1 VARCHAR2(4000), 
	R1_1 VARCHAR2(4000), 
	R2_1 VARCHAR2(4000), 
	K020 VARCHAR2(4000), 
	DATAPOD VARCHAR2(4000), 
	NOMPOD VARCHAR2(4000), 
	DJERPOD VARCHAR2(4000), 
	NAKAZ VARCHAR2(4000), 
	DATANAK VARCHAR2(4000), 
	NOMNAK VARCHAR2(4000), 
	DATPODSK VARCHAR2(4000), 
	NOMPODSK VARCHAR2(4000), 
	DJERPODS VARCHAR2(4000), 
	DATNAKSK VARCHAR2(4000), 
	NOMNAKSK VARCHAR2(4000), 
	SANKSIA1 VARCHAR2(4000), 
	SRSANK11 VARCHAR2(4000), 
	SRSANK12 VARCHAR2(4000), 
	R4 VARCHAR2(4000), 
	R030 VARCHAR2(4000), 
	T071 VARCHAR2(4000), 
	K040 VARCHAR2(4000), 
	BANKIN VARCHAR2(4000), 
	ADRIN VARCHAR2(4000), 
	DATA_M VARCHAR2(4000), 
	LINE_HASH RAW(2000), 
	MODIFY_DATE VARCHAR2(4000), 
	DELETE_DATE VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_F98 ***
 exec bpa.alter_policies('ERR$_CIM_F98');


COMMENT ON TABLE BARS.ERR$_CIM_F98 IS 'DML Error Logging table for "CIM_F98"';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DJERPODS IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DATNAKSK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NOMNAKSK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.SANKSIA1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.SRSANK11 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.SRSANK12 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.R4 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.R030 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.T071 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.K040 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.BANKIN IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.ADRIN IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DATA_M IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.LINE_HASH IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.MODIFY_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DELETE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NP IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DT IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.EK_POK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.KO IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NKB IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.KU IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.PRB IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.K030 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.V_SANK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.KO_1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.R1_1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.R2_1 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.K020 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DATAPOD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NOMPOD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DJERPOD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NAKAZ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DATANAK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NOMNAK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.DATPODSK IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F98.NOMPODSK IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_F98.sql =========*** End *** 
PROMPT ===================================================================================== 
