

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_SPECPARAM_INT.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_SPECPARAM_INT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_SPECPARAM_INT ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_SPECPARAM_INT 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACC VARCHAR2(4000), 
	P080 VARCHAR2(4000), 
	OB22 VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	R020_FA VARCHAR2(4000), 
	KOR VARCHAR2(4000), 
	DEB01 VARCHAR2(4000), 
	DEB02 VARCHAR2(4000), 
	DEB03 VARCHAR2(4000), 
	DEB04 VARCHAR2(4000), 
	DEB05 VARCHAR2(4000), 
	DEB06 VARCHAR2(4000), 
	DEB07 VARCHAR2(4000), 
	F_11 VARCHAR2(4000), 
	OB88 VARCHAR2(4000), 
	DD VARCHAR2(4000), 
	RR VARCHAR2(4000), 
	PRIOCOM_IDCONTRACT VARCHAR2(4000), 
	PRIOCOM_CR_SUPPLYCODE VARCHAR2(4000), 
	PRIOCOM_KL_KPR VARCHAR2(4000), 
	PRIOCOM_KOD_BIZN VARCHAR2(4000), 
	PRIOCOM_NDOG_Z VARCHAR2(4000), 
	PRIOCOM_CURRENCY_Z VARCHAR2(4000), 
	PRIOCOM_S040_Z VARCHAR2(4000), 
	PRIOCOM_S050_Z VARCHAR2(4000), 
	PRIOCOM_LSUMM VARCHAR2(4000), 
	TYPNLS VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	DEMAND_BRN VARCHAR2(4000), 
	DEMAND_COND_SET VARCHAR2(4000), 
	DEMAND_KK VARCHAR2(4000), 
	KREDIT_ZARPLATA VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_SPECPARAM_INT ***
 exec bpa.alter_policies('ERR$_SPECPARAM_INT');


COMMENT ON TABLE BARS.ERR$_SPECPARAM_INT IS 'DML Error Logging table for "SPECPARAM_INT"';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.P080 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.OB22 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.R020_FA IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.KOR IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB01 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB02 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB03 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB04 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB05 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB06 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEB07 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.F_11 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.OB88 IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DD IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.RR IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_IDCONTRACT IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_CR_SUPPLYCODE IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_KL_KPR IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_KOD_BIZN IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_NDOG_Z IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_CURRENCY_Z IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_S040_Z IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_S050_Z IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.PRIOCOM_LSUMM IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.TYPNLS IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.KF IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEMAND_BRN IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEMAND_COND_SET IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.DEMAND_KK IS '';
COMMENT ON COLUMN BARS.ERR$_SPECPARAM_INT.KREDIT_ZARPLATA IS '';



PROMPT *** Create  grants  ERR$_SPECPARAM_INT ***
grant SELECT                                                                 on ERR$_SPECPARAM_INT to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_SPECPARAM_INT.sql =========*** En
PROMPT ===================================================================================== 
