

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER_ADDRESS_UPDATE.sql =====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CUSTOMER_ADDRESS_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CUSTOMER_ADDRESS_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CUSTOMER_ADDRESS_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	TYPE_ID VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	ZIP VARCHAR2(4000), 
	DOMAIN VARCHAR2(4000), 
	REGION VARCHAR2(4000), 
	LOCALITY VARCHAR2(4000), 
	ADDRESS VARCHAR2(4000), 
	TERRITORY_ID VARCHAR2(4000), 
	LOCALITY_TYPE VARCHAR2(4000), 
	STREET_TYPE VARCHAR2(4000), 
	STREET VARCHAR2(4000), 
	HOME_TYPE VARCHAR2(4000), 
	HOME VARCHAR2(4000), 
	HOMEPART_TYPE VARCHAR2(4000), 
	HOMEPART VARCHAR2(4000), 
	ROOM_TYPE VARCHAR2(4000), 
	ROOM VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CUSTOMER_ADDRESS_UPDATE ***
 exec bpa.alter_policies('ERR$_CUSTOMER_ADDRESS_UPDATE');


COMMENT ON TABLE BARS.ERR$_CUSTOMER_ADDRESS_UPDATE IS 'DML Error Logging table for "CUSTOMER_ADDRESS_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ZIP IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.DOMAIN IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.REGION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.LOCALITY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ADDRESS IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.TERRITORY_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.LOCALITY_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.STREET_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.STREET IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.HOME_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.HOME IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.HOMEPART_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.HOMEPART IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ROOM_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS_UPDATE.ROOM IS '';



PROMPT *** Create  grants  ERR$_CUSTOMER_ADDRESS_UPDATE ***
grant SELECT                                                                 on ERR$_CUSTOMER_ADDRESS_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CUSTOMER_ADDRESS_UPDATE to BARS_DM;
grant SELECT                                                                 on ERR$_CUSTOMER_ADDRESS_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER_ADDRESS_UPDATE.sql =====
PROMPT ===================================================================================== 
