

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_DPU_DEAL_SWTAGS.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_DPU_DEAL_SWTAGS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_DPU_DEAL_SWTAGS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_DPU_DEAL_SWTAGS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	DPU_ID VARCHAR2(4000), 
	TAG56_NAME VARCHAR2(4000), 
	TAG56_ADR VARCHAR2(4000), 
	TAG56_CODE VARCHAR2(4000), 
	TAG57_NAME VARCHAR2(4000), 
	TAG57_ADR VARCHAR2(4000), 
	TAG57_CODE VARCHAR2(4000), 
	TAG57_ACC VARCHAR2(4000), 
	TAG59_NAME VARCHAR2(4000), 
	TAG59_ADR VARCHAR2(4000), 
	TAG59_ACC VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_DPU_DEAL_SWTAGS ***
 exec bpa.alter_policies('ERR$_DPU_DEAL_SWTAGS');


COMMENT ON TABLE BARS.ERR$_DPU_DEAL_SWTAGS IS 'DML Error Logging table for "DPU_DEAL_SWTAGS"';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.DPU_ID IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG56_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG56_ADR IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG56_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG57_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG57_ADR IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG57_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG57_ACC IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG59_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG59_ADR IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.TAG59_ACC IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_DPU_DEAL_SWTAGS.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_DPU_DEAL_SWTAGS.sql =========*** 
PROMPT ===================================================================================== 
