

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CCK_RESTR.sql =========*** Run **
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CCK_RESTR ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CCK_RESTR ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CCK_RESTR 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ND VARCHAR2(4000), 
	FDAT VARCHAR2(4000), 
	VID_RESTR VARCHAR2(4000), 
	TXT VARCHAR2(4000), 
	SUMR VARCHAR2(4000), 
	FDAT_END VARCHAR2(4000), 
	PR_NO VARCHAR2(4000), 
	RESTR_ID VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	S_RESTR VARCHAR2(4000), 
	N_DODATOK VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	QTY_PAY VARCHAR2(4000), 
	DEL_PV VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CCK_RESTR ***
 exec bpa.alter_policies('ERR$_CCK_RESTR');


COMMENT ON TABLE BARS.ERR$_CCK_RESTR IS 'DML Error Logging table for "CCK_RESTR"';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.ND IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.VID_RESTR IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.TXT IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.SUMR IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.FDAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.PR_NO IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.RESTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.S_RESTR IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.N_DODATOK IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.QTY_PAY IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.DEL_PV IS '';
COMMENT ON COLUMN BARS.ERR$_CCK_RESTR.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CCK_RESTR.sql =========*** End **
PROMPT ===================================================================================== 
