

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_FANTOMS_BOUND.sql =========**
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_FANTOMS_BOUND ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_FANTOMS_BOUND ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_FANTOMS_BOUND 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	BOUND_ID VARCHAR2(4000), 
	DIRECT VARCHAR2(4000), 
	FANTOM_ID VARCHAR2(4000), 
	CONTR_ID VARCHAR2(4000), 
	PAY_FLAG VARCHAR2(4000), 
	S VARCHAR2(4000), 
	S_CV VARCHAR2(4000), 
	RATE VARCHAR2(4000), 
	COMISS VARCHAR2(4000), 
	COMMENTS VARCHAR2(4000), 
	JOURNAL_ID VARCHAR2(4000), 
	JOURNAL_NUM VARCHAR2(4000), 
	CREATE_DATE VARCHAR2(4000), 
	MODIFY_DATE VARCHAR2(4000), 
	DELETE_DATE VARCHAR2(4000), 
	UID_DEL_BOUND VARCHAR2(4000), 
	UID_DEL_JOURNAL VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	BORG_REASON VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_FANTOMS_BOUND ***
 exec bpa.alter_policies('ERR$_CIM_FANTOMS_BOUND');


COMMENT ON TABLE BARS.ERR$_CIM_FANTOMS_BOUND IS 'DML Error Logging table for "CIM_FANTOMS_BOUND"';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.BOUND_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.DIRECT IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.FANTOM_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.CONTR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.PAY_FLAG IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.S IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.S_CV IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.RATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.COMISS IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.COMMENTS IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.JOURNAL_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.JOURNAL_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.CREATE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.MODIFY_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.DELETE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.UID_DEL_BOUND IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.UID_DEL_JOURNAL IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_FANTOMS_BOUND.BORG_REASON IS '';



PROMPT *** Create  grants  ERR$_CIM_FANTOMS_BOUND ***
grant SELECT                                                                 on ERR$_CIM_FANTOMS_BOUND to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CIM_FANTOMS_BOUND to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_FANTOMS_BOUND.sql =========**
PROMPT ===================================================================================== 
