

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_REZ_CR.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_REZ_CR ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_REZ_CR ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_REZ_CR 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	FDAT VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	NBS VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	VIDD VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	FINP VARCHAR2(4000), 
	FINV VARCHAR2(4000), 
	VKR VARCHAR2(4000), 
	BV VARCHAR2(4000), 
	BVQ VARCHAR2(4000), 
	BV02 VARCHAR2(4000), 
	BV02Q VARCHAR2(4000), 
	EAD VARCHAR2(4000), 
	EADQ VARCHAR2(4000), 
	IDF VARCHAR2(4000), 
	PD VARCHAR2(4000), 
	CR VARCHAR2(4000), 
	CRQ VARCHAR2(4000), 
	CR_LGD VARCHAR2(4000), 
	KOL VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	CCF VARCHAR2(4000), 
	PAWN VARCHAR2(4000), 
	TIP_ZAL VARCHAR2(4000), 
	KPZ VARCHAR2(4000), 
	KL_351 VARCHAR2(4000), 
	ZAL VARCHAR2(4000), 
	ZALQ VARCHAR2(4000), 
	ZAL_BV VARCHAR2(4000), 
	ZAL_BVQ VARCHAR2(4000), 
	LGD VARCHAR2(4000), 
	RZ VARCHAR2(4000), 
	TEXT VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	PRINSIDER VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	ISE VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	DATE_V VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	ISTVAL VARCHAR2(4000), 
	RC VARCHAR2(4000), 
	RCQ VARCHAR2(4000), 
	FAKTOR VARCHAR2(4000), 
	K_FAKTOR VARCHAR2(4000), 
	K_DEFOLT VARCHAR2(4000), 
	DV VARCHAR2(4000), 
	FIN_KOR VARCHAR2(4000), 
	TIPA VARCHAR2(4000), 
	OVKR VARCHAR2(4000), 
	P_DEF VARCHAR2(4000), 
	OVD VARCHAR2(4000), 
	OPD VARCHAR2(4000), 
	KOL23 VARCHAR2(4000), 
	KOL24 VARCHAR2(4000), 
	KOL25 VARCHAR2(4000), 
	KOL26 VARCHAR2(4000), 
	KOL27 VARCHAR2(4000), 
	KOL28 VARCHAR2(4000), 
	KOL29 VARCHAR2(4000), 
	FIN_Z VARCHAR2(4000), 
	PD_0 VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	KOL17 VARCHAR2(4000), 
	KOL31 VARCHAR2(4000), 
	S180 VARCHAR2(4000), 
	T4 VARCHAR2(4000), 
	RPB VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	OB22 VARCHAR2(4000), 
	KOL30 VARCHAR2(4000), 
	S080 VARCHAR2(4000), 
	S080_Z VARCHAR2(4000), 
	TIP_FIN VARCHAR2(4000), 
	DDD_6B VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_REZ_CR ***
 exec bpa.alter_policies('ERR$_REZ_CR');


COMMENT ON TABLE BARS.ERR$_REZ_CR IS 'DML Error Logging table for "REZ_CR"';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KV IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.NBS IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ND IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.VIDD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FINP IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FINV IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.VKR IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.BV IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.BVQ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.BV02 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.BV02Q IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.EAD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.EADQ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.IDF IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.PD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.CR IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.CRQ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.CR_LGD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.CCF IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.PAWN IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.TIP_ZAL IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KPZ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KL_351 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ZAL IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ZALQ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ZAL_BV IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ZAL_BVQ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.LGD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.RZ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.TEXT IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.PRINSIDER IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ISE IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.DATE_V IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ISTVAL IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.RC IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.RCQ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FAKTOR IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.K_FAKTOR IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.K_DEFOLT IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.DV IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FIN_KOR IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.TIPA IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.OVKR IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.P_DEF IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.OVD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.OPD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL23 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL24 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL25 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL26 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL27 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL28 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL29 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.FIN_Z IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.PD_0 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL17 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL31 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.S180 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.T4 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.RPB IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.OB22 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KOL30 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.S080 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.S080_Z IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.TIP_FIN IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.DDD_6B IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.KF IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_CR.ORA_ERR_TAG$ IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_REZ_CR.sql =========*** End *** =
PROMPT ===================================================================================== 
