

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_E_DEAL$BASE_UPDATE.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_E_DEAL$BASE_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_E_DEAL$BASE_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_E_DEAL$BASE_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	USER_ID VARCHAR2(4000), 
	SA VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	ACC26 VARCHAR2(4000), 
	ACC36 VARCHAR2(4000), 
	ACCD VARCHAR2(4000), 
	ACCP VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_E_DEAL$BASE_UPDATE ***
 exec bpa.alter_policies('ERR$_E_DEAL$BASE_UPDATE');


COMMENT ON TABLE BARS.ERR$_E_DEAL$BASE_UPDATE IS 'DML Error Logging table for "E_DEAL$BASE_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ND IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.USER_ID IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.SA IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ACC26 IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ACC36 IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ACCD IS '';
COMMENT ON COLUMN BARS.ERR$_E_DEAL$BASE_UPDATE.ACCP IS '';



PROMPT *** Create  grants  ERR$_E_DEAL$BASE_UPDATE ***
grant SELECT                                                                 on ERR$_E_DEAL$BASE_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_E_DEAL$BASE_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_E_DEAL$BASE_UPDATE.sql =========*
PROMPT ===================================================================================== 
