

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_W4_ACC_UPDATE.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_W4_ACC_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_W4_ACC_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_W4_ACC_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	IDUPD VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	ACC_PK VARCHAR2(4000), 
	ACC_OVR VARCHAR2(4000), 
	ACC_9129 VARCHAR2(4000), 
	ACC_3570 VARCHAR2(4000), 
	ACC_2208 VARCHAR2(4000), 
	ACC_2627 VARCHAR2(4000), 
	ACC_2207 VARCHAR2(4000), 
	ACC_3579 VARCHAR2(4000), 
	ACC_2209 VARCHAR2(4000), 
	CARD_CODE VARCHAR2(4000), 
	ACC_2625X VARCHAR2(4000), 
	ACC_2627X VARCHAR2(4000), 
	ACC_2625D VARCHAR2(4000), 
	ACC_2628 VARCHAR2(4000), 
	ACC_2203 VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	FIN23 VARCHAR2(4000), 
	OBS23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	K23 VARCHAR2(4000), 
	DAT_BEGIN VARCHAR2(4000), 
	DAT_END VARCHAR2(4000), 
	DAT_CLOSE VARCHAR2(4000), 
	PASS_DATE VARCHAR2(4000), 
	PASS_STATE VARCHAR2(4000), 
	KOL_SP VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	GLOBAL_BDATE VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_W4_ACC_UPDATE ***
 exec bpa.alter_policies('ERR$_W4_ACC_UPDATE');


COMMENT ON TABLE BARS.ERR$_W4_ACC_UPDATE IS 'DML Error Logging table for "W4_ACC_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.KOL_SP IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.GLOBAL_BDATE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ND IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_PK IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_OVR IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_9129 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_3570 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2208 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2627 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2207 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_3579 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2209 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.CARD_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2625X IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2627X IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2625D IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2628 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.ACC_2203 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.FIN23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.OBS23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.K23 IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.DAT_BEGIN IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.DAT_END IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.DAT_CLOSE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.PASS_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_W4_ACC_UPDATE.PASS_STATE IS '';



PROMPT *** Create  grants  ERR$_W4_ACC_UPDATE ***
grant SELECT                                                                 on ERR$_W4_ACC_UPDATE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_W4_ACC_UPDATE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_W4_ACC_UPDATE.sql =========*** En
PROMPT ===================================================================================== 
