

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_REZ_DOC_MAKET.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_REZ_DOC_MAKET ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_REZ_DOC_MAKET ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_REZ_DOC_MAKET 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	TT VARCHAR2(4000), 
	VOB VARCHAR2(4000), 
	PDAT VARCHAR2(4000), 
	VDAT VARCHAR2(4000), 
	DATD VARCHAR2(4000), 
	DATP VARCHAR2(4000), 
	NAM_A VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	MFOA VARCHAR2(4000), 
	ID_A VARCHAR2(4000), 
	NAM_B VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	MFOB VARCHAR2(4000), 
	ID_B VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	S VARCHAR2(4000), 
	S2 VARCHAR2(4000), 
	KV2 VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	USERID VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	DK VARCHAR2(4000), 
	BRANCH_A VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_REZ_DOC_MAKET ***
 exec bpa.alter_policies('ERR$_REZ_DOC_MAKET');


COMMENT ON TABLE BARS.ERR$_REZ_DOC_MAKET IS 'DML Error Logging table for "REZ_DOC_MAKET"';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.TT IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.VOB IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.PDAT IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.VDAT IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.DATD IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.DATP IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.NAM_A IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.MFOA IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ID_A IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.NAM_B IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.MFOB IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.ID_B IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.KV IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.S IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.S2 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.KV2 IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.USERID IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.DK IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.BRANCH_A IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.REF IS '';
COMMENT ON COLUMN BARS.ERR$_REZ_DOC_MAKET.KF IS '';



PROMPT *** Create  grants  ERR$_REZ_DOC_MAKET ***
grant SELECT                                                                 on ERR$_REZ_DOC_MAKET to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_REZ_DOC_MAKET to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_REZ_DOC_MAKET.sql =========*** En
PROMPT ===================================================================================== 
