

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER_ADDRESS.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CUSTOMER_ADDRESS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CUSTOMER_ADDRESS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CUSTOMER_ADDRESS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	RNK VARCHAR2(4000), 
	TYPE_ID VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	ZIP VARCHAR2(4000), 
	DOMAIN VARCHAR2(4000), 
	REGION VARCHAR2(4000), 
	LOCALITY VARCHAR2(4000), 
	ADDRESS VARCHAR2(4000), 
	TERRITORY_ID VARCHAR2(4000), 
	LOCALITY_TYPE VARCHAR2(4000), 
	STREET_TYPE VARCHAR2(4000), 
	STREET VARCHAR2(4000), 
	HOME_TYPE VARCHAR2(4000), 
	HOME VARCHAR2(4000), 
	HOMEPART_TYPE VARCHAR2(4000), 
	HOMEPART VARCHAR2(4000), 
	ROOM_TYPE VARCHAR2(4000), 
	ROOM VARCHAR2(4000), 
	COMM VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CUSTOMER_ADDRESS ***
 exec bpa.alter_policies('ERR$_CUSTOMER_ADDRESS');


COMMENT ON TABLE BARS.ERR$_CUSTOMER_ADDRESS IS 'DML Error Logging table for "CUSTOMER_ADDRESS"';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ZIP IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.DOMAIN IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.REGION IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.LOCALITY IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ADDRESS IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.TERRITORY_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.LOCALITY_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.STREET_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.STREET IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.HOME_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.HOME IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.HOMEPART_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.HOMEPART IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ROOM_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.ROOM IS '';
COMMENT ON COLUMN BARS.ERR$_CUSTOMER_ADDRESS.COMM IS '';



PROMPT *** Create  grants  ERR$_CUSTOMER_ADDRESS ***
grant SELECT                                                                 on ERR$_CUSTOMER_ADDRESS to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CUSTOMER_ADDRESS.sql =========***
PROMPT ===================================================================================== 
