

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_PRVN_FLOW_DEALS_CONST.sql =======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_PRVN_FLOW_DEALS_CONST ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_PRVN_FLOW_DEALS_CONST ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_PRVN_FLOW_DEALS_CONST 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	DAT_ADD VARCHAR2(4000), 
	VIDD VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	DAOS VARCHAR2(4000), 
	I_CR9 VARCHAR2(4000), 
	PR_TR VARCHAR2(4000), 
	KV8 VARCHAR2(4000), 
	ACC8 VARCHAR2(4000), 
	FL2 VARCHAR2(4000), 
	DAZS VARCHAR2(4000), 
	DATE_CLOSE VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_PRVN_FLOW_DEALS_CONST ***
 exec bpa.alter_policies('ERR$_PRVN_FLOW_DEALS_CONST');


COMMENT ON TABLE BARS.ERR$_PRVN_FLOW_DEALS_CONST IS 'DML Error Logging table for "PRVN_FLOW_DEALS_CONST"';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ID IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ND IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.KV IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.DAT_ADD IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.VIDD IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.DAOS IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.I_CR9 IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.PR_TR IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.KV8 IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.ACC8 IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.FL2 IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.DAZS IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.DATE_CLOSE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_FLOW_DEALS_CONST.KF IS '';



PROMPT *** Create  grants  ERR$_PRVN_FLOW_DEALS_CONST ***
grant SELECT                                                                 on ERR$_PRVN_FLOW_DEALS_CONST to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_PRVN_FLOW_DEALS_CONST to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_PRVN_FLOW_DEALS_CONST.sql =======
PROMPT ===================================================================================== 
