

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_F36.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CIM_F36 ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CIM_F36 ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CIM_F36 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	B041 VARCHAR2(4000), 
	K020 VARCHAR2(4000), 
	P17 VARCHAR2(4000), 
	P16 VARCHAR2(4000), 
	DOC_DATE VARCHAR2(4000), 
	P21 VARCHAR2(4000), 
	P14 VARCHAR2(4000), 
	P01 VARCHAR2(4000), 
	P22 VARCHAR2(4000), 
	P02 VARCHAR2(4000), 
	P02_OLD VARCHAR2(4000), 
	P06 VARCHAR2(4000), 
	P06_OLD VARCHAR2(4000), 
	P07 VARCHAR2(4000), 
	P07_OLD VARCHAR2(4000), 
	P08 VARCHAR2(4000), 
	P08_OLD VARCHAR2(4000), 
	P09 VARCHAR2(4000), 
	P13 VARCHAR2(4000), 
	P15 VARCHAR2(4000), 
	P18 VARCHAR2(4000), 
	P19 VARCHAR2(4000), 
	P20 VARCHAR2(4000), 
	P23 VARCHAR2(4000), 
	P24 VARCHAR2(4000), 
	P25 VARCHAR2(4000), 
	CREATE_DATE VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CIM_F36 ***
 exec bpa.alter_policies('ERR$_CIM_F36');


COMMENT ON TABLE BARS.ERR$_CIM_F36 IS 'DML Error Logging table for "CIM_F36"';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.B041 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.K020 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P17 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P16 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.DOC_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P21 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P14 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P01 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P22 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P02 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P02_OLD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P06 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P06_OLD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P07 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P07_OLD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P08 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P08_OLD IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P09 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P13 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P15 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P18 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P19 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P20 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P23 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P24 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.P25 IS '';
COMMENT ON COLUMN BARS.ERR$_CIM_F36.CREATE_DATE IS '';



PROMPT *** Create  grants  ERR$_CIM_F36 ***
grant SELECT                                                                 on ERR$_CIM_F36    to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CIM_F36    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CIM_F36.sql =========*** End *** 
PROMPT ===================================================================================== 
