

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_LINES_F.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_LINES_F ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_LINES_F ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_LINES_F 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	FN VARCHAR2(4000), 
	DAT VARCHAR2(4000), 
	N VARCHAR2(4000), 
	MFO VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	RTYPE VARCHAR2(4000), 
	OTYPE VARCHAR2(4000), 
	ODATE VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	NLSM VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	RESID VARCHAR2(4000), 
	NMKK VARCHAR2(4000), 
	C_REG VARCHAR2(4000), 
	NTAX VARCHAR2(4000), 
	ID_O VARCHAR2(4000), 
	SIGN RAW(2000), 
	ERR VARCHAR2(4000), 
	DAT_IN_DPA VARCHAR2(4000), 
	DAT_ACC_DPA VARCHAR2(4000), 
	ID_PR VARCHAR2(4000), 
	ID_DPA VARCHAR2(4000), 
	ID_DPS VARCHAR2(4000), 
	ID_REC VARCHAR2(4000), 
	FN_R VARCHAR2(4000), 
	DATE_R VARCHAR2(4000), 
	N_R VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	ADR VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_LINES_F ***
 exec bpa.alter_policies('ERR$_LINES_F');


COMMENT ON TABLE BARS.ERR$_LINES_F IS 'DML Error Logging table for "LINES_F"';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.FN IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.DAT IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.N IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.MFO IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.RTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.OTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ODATE IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.NLSM IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.KV IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.RESID IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.NMKK IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.C_REG IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.NTAX IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ID_O IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.SIGN IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ERR IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.DAT_IN_DPA IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.DAT_ACC_DPA IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ID_PR IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ID_DPA IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ID_DPS IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ID_REC IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.FN_R IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.DATE_R IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.N_R IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.KF IS '';
COMMENT ON COLUMN BARS.ERR$_LINES_F.ADR IS '';



PROMPT *** Create  grants  ERR$_LINES_F ***
grant SELECT                                                                 on ERR$_LINES_F    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_LINES_F.sql =========*** End *** 
PROMPT ===================================================================================== 
