

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OW_CRVFILES_DATA.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OW_CRVFILES_DATA ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OW_CRVFILES_DATA ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OW_CRVFILES_DATA 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	IDN VARCHAR2(4000), 
	B040 VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	FIRST_NAME VARCHAR2(4000), 
	LAST_NAME VARCHAR2(4000), 
	MDL_NAME VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	ADR_PCODE VARCHAR2(4000), 
	ADR_DOMAIN VARCHAR2(4000), 
	ADR_REGION VARCHAR2(4000), 
	ADR_CITY VARCHAR2(4000), 
	ADR_STREET VARCHAR2(4000), 
	PHONE1 VARCHAR2(4000), 
	PHONE2 VARCHAR2(4000), 
	PHONE3 VARCHAR2(4000), 
	PASSP_SER VARCHAR2(4000), 
	PASSP_NUM VARCHAR2(4000), 
	PASSP_ORG VARCHAR2(4000), 
	PASSP_DATE VARCHAR2(4000), 
	BDAY VARCHAR2(4000), 
	BPLACE VARCHAR2(4000), 
	SEX VARCHAR2(4000), 
	WORD VARCHAR2(4000), 
	CRV_RNK VARCHAR2(4000), 
	CRV_DBCODE VARCHAR2(4000), 
	STR_ERR VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	CARD_ISSUE_BRANCH VARCHAR2(4000), 
	CARD_ISSUE_BRANCH_ADR VARCHAR2(4000), 
	CARD_ISSUE_DATE VARCHAR2(4000), 
	ERR_CODE VARCHAR2(4000), 
	CARD_ISSUE_BRANCH_ABS VARCHAR2(4000), 
	PASSP_DOCTYPE VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OW_CRVFILES_DATA ***
 exec bpa.alter_policies('ERR$_OW_CRVFILES_DATA');


COMMENT ON TABLE BARS.ERR$_OW_CRVFILES_DATA IS 'DML Error Logging table for "OW_CRVFILES_DATA"';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.CRV_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.CRV_DBCODE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.STR_ERR IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ND IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.CARD_ISSUE_BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.CARD_ISSUE_BRANCH_ADR IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.CARD_ISSUE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ERR_CODE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.CARD_ISSUE_BRANCH_ABS IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PASSP_DOCTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.KF IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ID IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.IDN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.B040 IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.FIRST_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.LAST_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.MDL_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ADR_PCODE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ADR_DOMAIN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ADR_REGION IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ADR_CITY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.ADR_STREET IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PHONE1 IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PHONE2 IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PHONE3 IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PASSP_SER IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PASSP_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PASSP_ORG IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.PASSP_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.BDAY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.BPLACE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.SEX IS '';
COMMENT ON COLUMN BARS.ERR$_OW_CRVFILES_DATA.WORD IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OW_CRVFILES_DATA.sql =========***
PROMPT ===================================================================================== 
