

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_CM_CLIENT_QUE.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_CM_CLIENT_QUE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_CM_CLIENT_QUE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_CM_CLIENT_QUE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	DATEIN VARCHAR2(4000), 
	DATEMOD VARCHAR2(4000), 
	OPER_TYPE VARCHAR2(4000), 
	OPER_STATUS VARCHAR2(4000), 
	RESP_TXT VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	OPENDATE VARCHAR2(4000), 
	CLIENTTYPE VARCHAR2(4000), 
	TAXPAYERIDENTIFIER VARCHAR2(4000), 
	SHORTNAME VARCHAR2(4000), 
	FIRSTNAME VARCHAR2(4000), 
	LASTNAME VARCHAR2(4000), 
	MIDDLENAME VARCHAR2(4000), 
	ENGFIRSTNAME VARCHAR2(4000), 
	ENGLASTNAME VARCHAR2(4000), 
	COUNTRY VARCHAR2(4000), 
	RESIDENT VARCHAR2(4000), 
	WORK VARCHAR2(4000), 
	OFFICE VARCHAR2(4000), 
	DATE_W VARCHAR2(4000), 
	ISVIP VARCHAR2(4000), 
	K060 VARCHAR2(4000), 
	COMPANYNAME VARCHAR2(4000), 
	SHORTCOMPANYNAME VARCHAR2(4000), 
	PERSONALISATIONNAME VARCHAR2(4000), 
	KLAS_CLIENT_ID VARCHAR2(4000), 
	CONTACTPERSON VARCHAR2(4000), 
	BIRTHDATE VARCHAR2(4000), 
	BIRTHPLACE VARCHAR2(4000), 
	GENDER VARCHAR2(4000), 
	ADDR1_CITYNAME VARCHAR2(4000), 
	ADDR1_PCODE VARCHAR2(4000), 
	ADDR1_DOMAIN VARCHAR2(4000), 
	ADDR1_REGION VARCHAR2(4000), 
	ADDR1_STREET VARCHAR2(4000), 
	ADDR2_CITYNAME VARCHAR2(4000), 
	ADDR2_PCODE VARCHAR2(4000), 
	ADDR2_DOMAIN VARCHAR2(4000), 
	ADDR2_REGION VARCHAR2(4000), 
	ADDR2_STREET VARCHAR2(4000), 
	EMAIL VARCHAR2(4000), 
	PHONENUMBER VARCHAR2(4000), 
	PHONENUMBER_MOB VARCHAR2(4000), 
	PHONENUMBER_DOD VARCHAR2(4000), 
	FAX VARCHAR2(4000), 
	TYPEDOC VARCHAR2(4000), 
	PASPNUM VARCHAR2(4000), 
	PASPSERIES VARCHAR2(4000), 
	PASPDATE VARCHAR2(4000), 
	PASPISSUER VARCHAR2(4000), 
	FOREIGNPASPNUM VARCHAR2(4000), 
	FOREIGNPASPSERIES VARCHAR2(4000), 
	FOREIGNPASPDATE VARCHAR2(4000), 
	FOREIGNPASPENDDATE VARCHAR2(4000), 
	FOREIGNPASPISSUER VARCHAR2(4000), 
	CONTRACTNUMBER VARCHAR2(4000), 
	PRODUCTCODE VARCHAR2(4000), 
	CARD_TYPE VARCHAR2(4000), 
	CNTM VARCHAR2(4000), 
	PIND VARCHAR2(4000), 
	OKPO_SYSORG VARCHAR2(4000), 
	KOD_SYSORG VARCHAR2(4000), 
	REGNUMBERCLIENT VARCHAR2(4000), 
	REGNUMBEROWNER VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	CL_RNK VARCHAR2(4000), 
	CL_DT_ISS VARCHAR2(4000), 
	CARD_BR_ISS VARCHAR2(4000), 
	CARD_ADDR_ISS VARCHAR2(4000), 
	DELIVERY_BR VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	KK_SECRET_WORD VARCHAR2(4000), 
	KK_FLAG VARCHAR2(4000), 
	KK_REGTYPE VARCHAR2(4000), 
	KK_CITYAREAID VARCHAR2(4000), 
	KK_STREETTYPEID VARCHAR2(4000), 
	KK_STREETNAME VARCHAR2(4000), 
	KK_APARTMENT VARCHAR2(4000), 
	KK_POSTCODE VARCHAR2(4000), 
	ADD_INFO VARCHAR2(4000), 
	IDCARDENDDATE VARCHAR2(4000), 
	EDDR_ID VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_CM_CLIENT_QUE ***
 exec bpa.alter_policies('ERR$_CM_CLIENT_QUE');


COMMENT ON TABLE BARS.ERR$_CM_CLIENT_QUE IS 'DML Error Logging table for "CM_CLIENT_QUE"';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR1_STREET IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR2_CITYNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR2_PCODE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR2_DOMAIN IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR2_REGION IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR2_STREET IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.EMAIL IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PHONENUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PHONENUMBER_MOB IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PHONENUMBER_DOD IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FAX IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.TYPEDOC IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PASPNUM IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PASPSERIES IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PASPDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PASPISSUER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FOREIGNPASPNUM IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FOREIGNPASPSERIES IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FOREIGNPASPDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FOREIGNPASPENDDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FOREIGNPASPISSUER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CONTRACTNUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PRODUCTCODE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CARD_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CNTM IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PIND IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.OKPO_SYSORG IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KOD_SYSORG IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.REGNUMBERCLIENT IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.REGNUMBEROWNER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CL_RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CL_DT_ISS IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CARD_BR_ISS IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CARD_ADDR_ISS IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.DELIVERY_BR IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_SECRET_WORD IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_FLAG IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_REGTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_CITYAREAID IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_STREETTYPEID IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_STREETNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_APARTMENT IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KK_POSTCODE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADD_INFO IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.IDCARDENDDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.EDDR_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ID IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.DATEIN IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.DATEMOD IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.OPER_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.OPER_STATUS IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.RESP_TXT IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.OPENDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CLIENTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.TAXPAYERIDENTIFIER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.SHORTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.FIRSTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.LASTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.MIDDLENAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ENGFIRSTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ENGLASTNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.COUNTRY IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.RESIDENT IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.WORK IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.OFFICE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.DATE_W IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ISVIP IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.K060 IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.COMPANYNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.SHORTCOMPANYNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.PERSONALISATIONNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.KLAS_CLIENT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.CONTACTPERSON IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.BIRTHDATE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.BIRTHPLACE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.GENDER IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR1_CITYNAME IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR1_PCODE IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR1_DOMAIN IS '';
COMMENT ON COLUMN BARS.ERR$_CM_CLIENT_QUE.ADDR1_REGION IS '';



PROMPT *** Create  grants  ERR$_CM_CLIENT_QUE ***
grant SELECT                                                                 on ERR$_CM_CLIENT_QUE to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_CM_CLIENT_QUE to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_CM_CLIENT_QUE.sql =========*** En
PROMPT ===================================================================================== 
