

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ACCOUNTS_UPDATE.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ACCOUNTS_UPDATE ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ACCOUNTS_UPDATE ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ACCOUNTS_UPDATE 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ACC VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	NLSALT VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	NBS VARCHAR2(4000), 
	NBS2 VARCHAR2(4000), 
	DAOS VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	NMS VARCHAR2(4000), 
	PAP VARCHAR2(4000), 
	VID VARCHAR2(4000), 
	DAZS VARCHAR2(4000), 
	BLKD VARCHAR2(4000), 
	BLKK VARCHAR2(4000), 
	CHGDATE VARCHAR2(4000), 
	CHGACTION VARCHAR2(4000), 
	POS VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	SECI VARCHAR2(4000), 
	SECO VARCHAR2(4000), 
	DONEBY VARCHAR2(4000), 
	IDUPD VARCHAR2(4000), 
	LIM VARCHAR2(4000), 
	ACCC VARCHAR2(4000), 
	TOBO VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	MDATE VARCHAR2(4000), 
	OSTX VARCHAR2(4000), 
	SEC RAW(2000), 
	RNK VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	EFFECTDATE VARCHAR2(4000), 
	SEND_SMS VARCHAR2(4000), 
	OB22 VARCHAR2(4000), 
	GLOBALBD VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ACCOUNTS_UPDATE ***
 exec bpa.alter_policies('ERR$_ACCOUNTS_UPDATE');


COMMENT ON TABLE BARS.ERR$_ACCOUNTS_UPDATE IS 'DML Error Logging table for "ACCOUNTS_UPDATE"';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.NLSALT IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.KV IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.NBS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.NBS2 IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.DAOS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.NMS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.PAP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.VID IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.DAZS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.BLKD IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.BLKK IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.CHGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.CHGACTION IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.POS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.SECI IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.SECO IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.DONEBY IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.IDUPD IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.LIM IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.ACCC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.TOBO IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.MDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.OSTX IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.SEC IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.KF IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.EFFECTDATE IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.SEND_SMS IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.OB22 IS '';
COMMENT ON COLUMN BARS.ERR$_ACCOUNTS_UPDATE.GLOBALBD IS '';



PROMPT *** Create  grants  ERR$_ACCOUNTS_UPDATE ***
grant SELECT                                                                 on ERR$_ACCOUNTS_UPDATE to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ACCOUNTS_UPDATE.sql =========*** 
PROMPT ===================================================================================== 
