

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_ESCR_REGISTER.sql =========*** Ru
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_ESCR_REGISTER ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_ESCR_REGISTER ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_ESCR_REGISTER 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	USER_ID VARCHAR2(4000), 
	STATUS_ID VARCHAR2(4000), 
	REG_UNION_FLAG VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	INNER_NUMBER VARCHAR2(4000), 
	OUTER_NUMBER VARCHAR2(4000), 
	CREATE_DATE VARCHAR2(4000), 
	DATE_FROM VARCHAR2(4000), 
	DATE_TO VARCHAR2(4000), 
	REG_TYPE_ID VARCHAR2(4000), 
	REG_KIND_ID VARCHAR2(4000), 
	REG_LEVEL VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	USER_NAME VARCHAR2(4000), 
	FILE_ID VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_ESCR_REGISTER ***
 exec bpa.alter_policies('ERR$_ESCR_REGISTER');


COMMENT ON TABLE BARS.ERR$_ESCR_REGISTER IS 'DML Error Logging table for "ESCR_REGISTER"';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.USER_ID IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.STATUS_ID IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.REG_UNION_FLAG IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.ID IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.INNER_NUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.OUTER_NUMBER IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.CREATE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.DATE_FROM IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.DATE_TO IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.REG_TYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.REG_KIND_ID IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.REG_LEVEL IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.USER_NAME IS '';
COMMENT ON COLUMN BARS.ERR$_ESCR_REGISTER.FILE_ID IS '';



PROMPT *** Create  grants  ERR$_ESCR_REGISTER ***
grant SELECT                                                                 on ERR$_ESCR_REGISTER to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_ESCR_REGISTER to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_ESCR_REGISTER.sql =========*** En
PROMPT ===================================================================================== 
