

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_FX_DEAL.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_FX_DEAL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_FX_DEAL ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_FX_DEAL 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	DEAL_TAG VARCHAR2(4000), 
	NTIK VARCHAR2(4000), 
	DAT VARCHAR2(4000), 
	KVA VARCHAR2(4000), 
	DAT_A VARCHAR2(4000), 
	SUMA VARCHAR2(4000), 
	KVB VARCHAR2(4000), 
	DAT_B VARCHAR2(4000), 
	SUMB VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	REFA VARCHAR2(4000), 
	REFB VARCHAR2(4000), 
	KODB VARCHAR2(4000), 
	REFB2 VARCHAR2(4000), 
	SWI_BIC VARCHAR2(4000), 
	SWI_ACC VARCHAR2(4000), 
	SWI_REF VARCHAR2(4000), 
	SWO_BIC VARCHAR2(4000), 
	SWO_ACC VARCHAR2(4000), 
	SWO_REF VARCHAR2(4000), 
	SWO_F57A VARCHAR2(4000), 
	SWI_F56A VARCHAR2(4000), 
	SWO_F56A VARCHAR2(4000), 
	AGRMNT_NUM VARCHAR2(4000), 
	AGRMNT_DATE VARCHAR2(4000), 
	BICB VARCHAR2(4000), 
	INTERM_B VARCHAR2(4000), 
	CURR_BASE VARCHAR2(4000), 
	ALT_PARTYB VARCHAR2(4000), 
	TELEXNUM VARCHAR2(4000), 
	REF1 VARCHAR2(4000), 
	SUMP VARCHAR2(4000), 
	SUMPB VARCHAR2(4000), 
	SUMPA VARCHAR2(4000), 
	REFB2_SPTOD VARCHAR2(4000), 
	REFB_SPTOD VARCHAR2(4000), 
	REFA_SPTOD VARCHAR2(4000), 
	NETA VARCHAR2(4000), 
	NETB VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	DETALI VARCHAR2(4000), 
	SWAP_TAG VARCHAR2(4000), 
	ACC9A VARCHAR2(4000), 
	ACC9B VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	B_PAYFLAG VARCHAR2(4000), 
	SUMC VARCHAR2(4000), 
	SUMB1 VARCHAR2(4000), 
	SUMB2 VARCHAR2(4000), 
	KOD_NA VARCHAR2(4000), 
	KOD_NB VARCHAR2(4000), 
	FIELD_58D VARCHAR2(4000), 
	VN_FLAG VARCHAR2(4000), 
	SOS VARCHAR2(4000), 
	NB VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_FX_DEAL ***
 exec bpa.alter_policies('ERR$_FX_DEAL');


COMMENT ON TABLE BARS.ERR$_FX_DEAL IS 'DML Error Logging table for "FX_DEAL"';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWO_F57A IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWI_F56A IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWO_F56A IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.AGRMNT_NUM IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.AGRMNT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.BICB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.INTERM_B IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.CURR_BASE IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ALT_PARTYB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.TELEXNUM IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REF1 IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMP IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMPB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMPA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REFB2_SPTOD IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REFB_SPTOD IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REFA_SPTOD IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.NETA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.NETB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.DETALI IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWAP_TAG IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ACC9A IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ACC9B IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.B_PAYFLAG IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMC IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMB1 IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMB2 IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.KOD_NA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.KOD_NB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.FIELD_58D IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.VN_FLAG IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SOS IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.NB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.DEAL_TAG IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.NTIK IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.DAT IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.KVA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.DAT_A IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.KVB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.DAT_B IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SUMB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REF IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REFA IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REFB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.KODB IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.REFB2 IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWI_BIC IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWI_ACC IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWI_REF IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWO_BIC IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWO_ACC IS '';
COMMENT ON COLUMN BARS.ERR$_FX_DEAL.SWO_REF IS '';



PROMPT *** Create  grants  ERR$_FX_DEAL ***
grant SELECT                                                                 on ERR$_FX_DEAL    to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_FX_DEAL    to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_FX_DEAL.sql =========*** End *** 
PROMPT ===================================================================================== 
