

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_OW_OIC_STRANSFERS_HIST.sql ======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_OW_OIC_STRANSFERS_HIST ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_OW_OIC_STRANSFERS_HIST ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_OW_OIC_STRANSFERS_HIST 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	ID VARCHAR2(4000), 
	IDN VARCHAR2(4000), 
	SYNTH_SYNTHREFN VARCHAR2(4000), 
	SYNTH_SYNTHCODE VARCHAR2(4000), 
	SYNTH_TRNDESCR VARCHAR2(4000), 
	CREDIT_SYNTACCOUNT VARCHAR2(4000), 
	CREDIT_AMOUNT VARCHAR2(4000), 
	CREDIT_LOCALAMOUNT VARCHAR2(4000), 
	CREDIT_CURRENCY VARCHAR2(4000), 
	DEBIT_SYNTACCOUNT VARCHAR2(4000), 
	DEBIT_AMOUNT VARCHAR2(4000), 
	DEBIT_LOCALAMOUNT VARCHAR2(4000), 
	DEBIT_CURRENCY VARCHAR2(4000), 
	SYNTH_POSTINGDATE VARCHAR2(4000), 
	NLSA VARCHAR2(4000), 
	NLSB VARCHAR2(4000), 
	NAZN VARCHAR2(4000), 
	ERR_TEXT VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_OW_OIC_STRANSFERS_HIST ***
 exec bpa.alter_policies('ERR$_OW_OIC_STRANSFERS_HIST');


COMMENT ON TABLE BARS.ERR$_OW_OIC_STRANSFERS_HIST IS 'DML Error Logging table for "OW_OIC_STRANSFERS_HIST"';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ID IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.IDN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.SYNTH_SYNTHREFN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.SYNTH_SYNTHCODE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.SYNTH_TRNDESCR IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.CREDIT_SYNTACCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.CREDIT_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.CREDIT_LOCALAMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.CREDIT_CURRENCY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.DEBIT_SYNTACCOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.DEBIT_AMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.DEBIT_LOCALAMOUNT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.DEBIT_CURRENCY IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.SYNTH_POSTINGDATE IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.NLSA IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.NLSB IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.NAZN IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.ERR_TEXT IS '';
COMMENT ON COLUMN BARS.ERR$_OW_OIC_STRANSFERS_HIST.KF IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_OW_OIC_STRANSFERS_HIST.sql ======
PROMPT ===================================================================================== 
