

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_PRVN_AUTOEVENT_ARC.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_PRVN_AUTOEVENT_ARC ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_PRVN_AUTOEVENT_ARC ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_PRVN_AUTOEVENT_ARC 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	REPORTING_DATE VARCHAR2(4000), 
	REF_AGR VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	EVENT_TYPE VARCHAR2(4000), 
	EVENT_DATE VARCHAR2(4000), 
	OBJECT_TYPE VARCHAR2(4000), 
	CREATE_DATE VARCHAR2(4000), 
	CREATE_USER VARCHAR2(4000), 
	RESTR_END_DAT VARCHAR2(4000), 
	ZO VARCHAR2(4000), 
	KF VARCHAR2(4000), 
	VIDD VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_PRVN_AUTOEVENT_ARC ***
 exec bpa.alter_policies('ERR$_PRVN_AUTOEVENT_ARC');


COMMENT ON TABLE BARS.ERR$_PRVN_AUTOEVENT_ARC IS 'DML Error Logging table for "PRVN_AUTOEVENT_ARC"';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.REPORTING_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.REF_AGR IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.EVENT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.EVENT_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.OBJECT_TYPE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.CREATE_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.CREATE_USER IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.RESTR_END_DAT IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.ZO IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.KF IS '';
COMMENT ON COLUMN BARS.ERR$_PRVN_AUTOEVENT_ARC.VIDD IS '';



PROMPT *** Create  grants  ERR$_PRVN_AUTOEVENT_ARC ***
grant SELECT                                                                 on ERR$_PRVN_AUTOEVENT_ARC to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_PRVN_AUTOEVENT_ARC to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_PRVN_AUTOEVENT_ARC.sql =========*
PROMPT ===================================================================================== 
