

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_NBU23_REZ_OTCN.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_NBU23_REZ_OTCN ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_NBU23_REZ_OTCN ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_NBU23_REZ_OTCN 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	FDAT VARCHAR2(4000), 
	ID VARCHAR2(4000), 
	RNK VARCHAR2(4000), 
	NBS VARCHAR2(4000), 
	KV VARCHAR2(4000), 
	ND VARCHAR2(4000), 
	CC_ID VARCHAR2(4000), 
	ACC VARCHAR2(4000), 
	NLS VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	FIN VARCHAR2(4000), 
	OBS VARCHAR2(4000), 
	KAT VARCHAR2(4000), 
	K VARCHAR2(4000), 
	IRR VARCHAR2(4000), 
	ZAL VARCHAR2(4000), 
	BV VARCHAR2(4000), 
	PV VARCHAR2(4000), 
	REZ VARCHAR2(4000), 
	REZQ VARCHAR2(4000), 
	DD VARCHAR2(4000), 
	DDD VARCHAR2(4000), 
	BVQ VARCHAR2(4000), 
	CUSTTYPE VARCHAR2(4000), 
	IDR VARCHAR2(4000), 
	WDATE VARCHAR2(4000), 
	OKPO VARCHAR2(4000), 
	NMK VARCHAR2(4000), 
	RZ VARCHAR2(4000), 
	PAWN VARCHAR2(4000), 
	ISTVAL VARCHAR2(4000), 
	R013 VARCHAR2(4000), 
	REZN VARCHAR2(4000), 
	REZNQ VARCHAR2(4000), 
	ARJK VARCHAR2(4000), 
	PVZ VARCHAR2(4000), 
	PVZQ VARCHAR2(4000), 
	ZALQ VARCHAR2(4000), 
	ZPR VARCHAR2(4000), 
	ZPRQ VARCHAR2(4000), 
	PVQ VARCHAR2(4000), 
	RU VARCHAR2(4000), 
	INN VARCHAR2(4000), 
	NRC VARCHAR2(4000), 
	SDATE VARCHAR2(4000), 
	IR VARCHAR2(4000), 
	S031 VARCHAR2(4000), 
	K040 VARCHAR2(4000), 
	PROD VARCHAR2(4000), 
	K110 VARCHAR2(4000), 
	K070 VARCHAR2(4000), 
	K051 VARCHAR2(4000), 
	S260 VARCHAR2(4000), 
	R011 VARCHAR2(4000), 
	R012 VARCHAR2(4000), 
	S240 VARCHAR2(4000), 
	S180 VARCHAR2(4000), 
	S580 VARCHAR2(4000), 
	NLS_REZ VARCHAR2(4000), 
	NLS_REZN VARCHAR2(4000), 
	S250 VARCHAR2(4000), 
	ACC_REZ VARCHAR2(4000), 
	FIN_R VARCHAR2(4000), 
	DISKONT VARCHAR2(4000), 
	ISP VARCHAR2(4000), 
	OB22 VARCHAR2(4000), 
	TIP VARCHAR2(4000), 
	SPEC VARCHAR2(4000), 
	ZAL_BL VARCHAR2(4000), 
	S280_290 VARCHAR2(4000), 
	ZAL_BLQ VARCHAR2(4000), 
	REZD VARCHAR2(4000), 
	ACC_REZN VARCHAR2(4000), 
	OB22_REZ VARCHAR2(4000), 
	OB22_REZN VARCHAR2(4000), 
	IR0 VARCHAR2(4000), 
	IRR0 VARCHAR2(4000), 
	ND_CP VARCHAR2(4000), 
	SUM_IMP VARCHAR2(4000), 
	SUMQ_IMP VARCHAR2(4000), 
	PV_ZAL VARCHAR2(4000), 
	VKR VARCHAR2(4000), 
	S_L VARCHAR2(4000), 
	SQ_L VARCHAR2(4000), 
	ZAL_SV VARCHAR2(4000), 
	ZAL_SVQ VARCHAR2(4000), 
	GRP VARCHAR2(4000), 
	KOL_SP VARCHAR2(4000), 
	REF VARCHAR2(4000), 
	PVP VARCHAR2(4000), 
	BV_30 VARCHAR2(4000), 
	BVQ_30 VARCHAR2(4000), 
	REZ_30 VARCHAR2(4000), 
	REZQ_30 VARCHAR2(4000), 
	NLS_REZ_30 VARCHAR2(4000), 
	ACC_REZ_30 VARCHAR2(4000), 
	OB22_REZ_30 VARCHAR2(4000), 
	BV_0 VARCHAR2(4000), 
	BVQ_0 VARCHAR2(4000), 
	REZ_0 VARCHAR2(4000), 
	REZQ_0 VARCHAR2(4000), 
	NLS_REZ_0 VARCHAR2(4000), 
	ACC_REZ_0 VARCHAR2(4000), 
	OB22_REZ_0 VARCHAR2(4000), 
	KAT39 VARCHAR2(4000), 
	REZ39 VARCHAR2(4000), 
	REZQ39 VARCHAR2(4000), 
	S250_39 VARCHAR2(4000), 
	REZ23 VARCHAR2(4000), 
	REZQ23 VARCHAR2(4000), 
	KAT23 VARCHAR2(4000), 
	S250_23 VARCHAR2(4000), 
	DAT_MI VARCHAR2(4000), 
	TIPA VARCHAR2(4000), 
	BVUQ VARCHAR2(4000), 
	BVU VARCHAR2(4000), 
	KF VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_NBU23_REZ_OTCN ***
 exec bpa.alter_policies('ERR$_NBU23_REZ_OTCN');


COMMENT ON TABLE BARS.ERR$_NBU23_REZ_OTCN IS 'DML Error Logging table for "NBU23_REZ_OTCN"';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZQ_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NLS_REZ_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ACC_REZ_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OB22_REZ_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BV_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BVQ_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZ_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZQ_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NLS_REZ_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ACC_REZ_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OB22_REZ_0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.KAT39 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZ39 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZQ39 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S250_39 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZ23 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZQ23 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.KAT23 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S250_23 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.DAT_MI IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.TIPA IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BVUQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BVU IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.KF IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OB22_REZN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.IR0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.IRR0 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ND_CP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.SUM_IMP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.SUMQ_IMP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PV_ZAL IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.VKR IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S_L IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.SQ_L IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZAL_SV IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZAL_SVQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.GRP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.KOL_SP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REF IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PVP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BV_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BVQ_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZ_30 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PVQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.RU IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.INN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NRC IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.SDATE IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.IR IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S031 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.K040 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PROD IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.K110 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.K070 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.K051 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S260 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.R011 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.R012 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S240 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S180 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S580 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NLS_REZ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NLS_REZN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S250 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ACC_REZ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.FIN_R IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.DISKONT IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ISP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OB22 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.TIP IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.SPEC IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZAL_BL IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.S280_290 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZAL_BLQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZD IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ACC_REZN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OB22_REZ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.DD IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.DDD IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BVQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.IDR IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.WDATE IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OKPO IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NMK IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.RZ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PAWN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ISTVAL IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.R013 IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZNQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ARJK IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PVZ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PVZQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZALQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZPR IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZPRQ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.FDAT IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ID IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.RNK IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NBS IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.KV IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ND IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.CC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ACC IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.NLS IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.FIN IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.OBS IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.KAT IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.K IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.IRR IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.ZAL IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.BV IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.PV IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZ IS '';
COMMENT ON COLUMN BARS.ERR$_NBU23_REZ_OTCN.REZQ IS '';



PROMPT *** Create  grants  ERR$_NBU23_REZ_OTCN ***
grant SELECT                                                                 on ERR$_NBU23_REZ_OTCN to BARSREADER_ROLE;
grant SELECT                                                                 on ERR$_NBU23_REZ_OTCN to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_NBU23_REZ_OTCN.sql =========*** E
PROMPT ===================================================================================== 
