

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/MWAY_LOG.sql =========*** Run *** ====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to MWAY_LOG ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''MWAY_LOG'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''MWAY_LOG'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''MWAY_LOG'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table MWAY_LOG ***
begin 
  execute immediate '
  CREATE TABLE BARS.MWAY_LOG 
   (	ID NUMBER(*,0), 
	LOG_DIR VARCHAR2(1), 
	LOG_DATE DATE, 
	LOG_DATA CLOB, 
	RESP_FOR NUMBER(*,0), 
	USERRNK NUMBER(*,0), 
	TRANSCODE VARCHAR2(400), 
	MSGID VARCHAR2(100)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  TABLESPACE BRSDYND 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
  PARTITION BY RANGE (LOG_DATE) 
 (PARTITION MWLOG_Y2015_Q1  VALUES LESS THAN (TO_DATE('' 2015-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2015_Q2  VALUES LESS THAN (TO_DATE('' 2015-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2015_Q3  VALUES LESS THAN (TO_DATE('' 2015-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2015_Q4  VALUES LESS THAN (TO_DATE('' 2016-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2016_Q1  VALUES LESS THAN (TO_DATE('' 2016-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2016_Q2  VALUES LESS THAN (TO_DATE('' 2016-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2016_Q3  VALUES LESS THAN (TO_DATE('' 2016-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2016_Q4  VALUES LESS THAN (TO_DATE('' 2017-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYNI ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2017_Q1  VALUES LESS THAN (TO_DATE('' 2017-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2017_Q2  VALUES LESS THAN (TO_DATE('' 2017-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2017_Q3  VALUES LESS THAN (TO_DATE('' 2017-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2017_Q4  VALUES LESS THAN (TO_DATE('' 2018-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYNI 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2018_Q1  VALUES LESS THAN (TO_DATE('' 2018-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2018_Q2  VALUES LESS THAN (TO_DATE('' 2018-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2018_Q3  VALUES LESS THAN (TO_DATE('' 2018-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION MWLOG_Y2018_Q4  VALUES LESS THAN (TO_DATE('' 2019-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND 
 LOB (LOG_DATA) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to MWAY_LOG ***
 exec bpa.alter_policies('MWAY_LOG');


COMMENT ON TABLE BARS.MWAY_LOG IS 'таблица истории обмена WAY4 с BARS';
COMMENT ON COLUMN BARS.MWAY_LOG.MSGID IS 'MsgId РІС…РѕРґСЏС‰РµРіРѕ СЃРѕРѕР±С‰РµРЅРёСЏ';
COMMENT ON COLUMN BARS.MWAY_LOG.ID IS 'уникальный идентификатор сообщения';
COMMENT ON COLUMN BARS.MWAY_LOG.LOG_DIR IS 'направление относительно АБС (I/O)';
COMMENT ON COLUMN BARS.MWAY_LOG.LOG_DATE IS 'дата/время обработки';
COMMENT ON COLUMN BARS.MWAY_LOG.LOG_DATA IS 'тело сообщения (clob)';
COMMENT ON COLUMN BARS.MWAY_LOG.RESP_FOR IS 'идентификатор предидущего сообщения';
COMMENT ON COLUMN BARS.MWAY_LOG.USERRNK IS 'рнк клієнта';
COMMENT ON COLUMN BARS.MWAY_LOG.TRANSCODE IS 'код транзакции(платежные сервисы)';




PROMPT *** Create  constraint SYS_C0035368 ***
begin   
 execute immediate '
  ALTER TABLE BARS.MWAY_LOG MODIFY (LOG_DATE NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint UQ_MWAY_LOG_MSGID ***
begin   
 execute immediate '
  ALTER TABLE BARS.MWAY_LOG ADD CONSTRAINT UQ_MWAY_LOG_MSGID UNIQUE (MSGID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index UQ_MWAY_LOG_MSGID ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UQ_MWAY_LOG_MSGID ON BARS.MWAY_LOG (MSGID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  MWAY_LOG ***
grant SELECT                                                                 on MWAY_LOG        to BARSREADER_ROLE;
grant ALTER,DELETE,INSERT,SELECT,UPDATE                                      on MWAY_LOG        to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on MWAY_LOG        to CIG_LOADER;
grant SELECT                                                                 on MWAY_LOG        to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/MWAY_LOG.sql =========*** End *** ====
PROMPT ===================================================================================== 
