

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/OB_CORP_DATA_DOC.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to OB_CORP_DATA_DOC ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''OB_CORP_DATA_DOC'', ''CENTER'' , null, null, ''E'', null);
               bpa.alter_policy_info(''OB_CORP_DATA_DOC'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''OB_CORP_DATA_DOC'', ''WHOLE'' , null, null, ''E'', null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table OB_CORP_DATA_DOC ***
begin 
  execute immediate '
  CREATE TABLE BARS.OB_CORP_DATA_DOC 
   (	SESS_ID NUMBER, 
	ACC NUMBER, 
	KF VARCHAR2(6), 
	REF NUMBER, 
	DK NUMBER, 
	POSTDAT DATE, 
	DOCDAT DATE, 
	VALDAT DATE, 
	ND VARCHAR2(10), 
	VOB NUMBER, 
	MFOA VARCHAR2(6), 
	NLSA VARCHAR2(14), 
	KVA NUMBER, 
	NAMA VARCHAR2(70), 
	OKPOA VARCHAR2(14), 
	MFOB VARCHAR2(6), 
	NLSB VARCHAR2(14), 
	KVB NUMBER, 
	NAMB VARCHAR2(70), 
	OKPOB VARCHAR2(14), 
	S NUMBER, 
	DOCKV NUMBER, 
	SQ NUMBER, 
	NAZN VARCHAR2(160), 
	TT VARCHAR2(3)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSBIGD 
  PARTITION BY LIST (KF) 
 (PARTITION P_01_300465  VALUES (''300465'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_02_324805  VALUES (''324805'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_03_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_04_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_05_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_06_335106  VALUES (''335106'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_07_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_08_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_09_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_10_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_11_322669  VALUES (''322669'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_12_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_13_304665  VALUES (''304665'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_14_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_15_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_16_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_17_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_18_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_19_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_20_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_21_351823  VALUES (''351823'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_22_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_23_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_24_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_25_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_26_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to OB_CORP_DATA_DOC ***
 exec bpa.alter_policies('OB_CORP_DATA_DOC');


COMMENT ON TABLE BARS.OB_CORP_DATA_DOC IS 'Дані К-файлів у розрізі документів';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.SESS_ID IS 'Ідентифікатор сесії завантаження даних з РУ';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.ACC IS 'ІД рахунку';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.KF IS 'МФО банку';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.REF IS 'Референс';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.DK IS 'Дебет/Кредит';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.POSTDAT IS 'Дата проведення в ОДБ (дата руху по рахунку для стрычки по рахунку)';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.DOCDAT IS 'Дата документу';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.VALDAT IS 'Дата валютування';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.ND IS 'Номер документу';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.VOB IS 'Вид документу';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.MFOA IS 'МФО банку платника';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.NLSA IS 'Особовий рахунок платника';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.KVA IS 'Валюта особового рахунку платника';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.NAMA IS 'Найменування клієнта платника';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.OKPOA IS 'Ідентифікатор клієнта платника';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.MFOB IS 'МФО банку отримувача';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.NLSB IS 'Особовий рахунок отримувача';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.KVB IS 'Валюта особового рахунку отримувача';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.NAMB IS 'Найменування клієнта отримувача';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.OKPOB IS 'Ідентифікатор клієнта отримувача';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.S IS 'Сума платежу в валюті';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.DOCKV IS 'Валюта платежу';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.SQ IS 'Сума платежу (еквівалент в національній валюті)';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.NAZN IS 'Призначення платежу';
COMMENT ON COLUMN BARS.OB_CORP_DATA_DOC.TT IS 'Код операции';




PROMPT *** Create  constraint PK_OB_CORP_DATA_DOC ***
begin   
 execute immediate '
  ALTER TABLE BARS.OB_CORP_DATA_DOC ADD CONSTRAINT PK_OB_CORP_DATA_DOC PRIMARY KEY (KF, SESS_ID, ACC, REF, DK)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_OB_CORP_DATA_DOC ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_OB_CORP_DATA_DOC ON BARS.OB_CORP_DATA_DOC (KF, SESS_ID, ACC, REF, DK) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  OB_CORP_DATA_DOC ***
grant DELETE,INSERT,SELECT,UPDATE                                            on OB_CORP_DATA_DOC to BARS_ACCESS_DEFROLE;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/OB_CORP_DATA_DOC.sql =========*** End 
PROMPT ===================================================================================== 

