begin
  execute immediate 'begin bpa.alter_policy_info(''OW_INST_TOTALS_HIST'', ''WHOLE'',  null, ''E'', ''E'', ''E''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/
 begin
  execute immediate 'begin bpa.alter_policy_info(''OW_INST_TOTALS_HIST'', ''FILIAL'', ''M'', ''M'', ''M'' , ''M''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/ 
begin
  execute immediate 'begin bpa.alter_policy_info(''OW_INST_TOTALS_HIST'', ''CENTER'', null, ''E'', ''E'' , ''E''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/ 
BEGIN
execute immediate 'create table ow_inst_totals_hist (
id number,
idn number,
nd number, 
contract number,
contract_idt varchar2(30),
scheme number,
plan_id number,
chain_idt number,
document_id number,
status varchar2(30),
total_amount number,
amount_to_pay number,
written_off_amount number,
overdue_amount number,
sub_int_rate number,
sub_fee_rate number,
eff_rate number,
tenor number,
posting_date date,
pay_b_date date,
end_date_p date,
end_date_f date,
ovd_90_days date,
plan_num number,
ins_bd date,
kf varchar2(6 BYTE) default sys_context(''bars_context'',''user_mfo'') CONSTRAINT CC_OW_INST_TOTALS_HIST_KF_NN NOT NULL)  
tablespace BRSMDLD
PARTITION BY LIST (KF) 
 (PARTITION P_01_300465  VALUES (''300465'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_02_324805  VALUES (''324805'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_03_302076  VALUES (''302076'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_04_303398  VALUES (''303398'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_05_305482  VALUES (''305482'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_06_335106  VALUES (''335106'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_07_311647  VALUES (''311647'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_08_312356  VALUES (''312356'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_09_313957  VALUES (''313957'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_10_336503  VALUES (''336503'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_11_322669  VALUES (''322669'') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_12_323475  VALUES (''323475'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_13_304665  VALUES (''304665'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_14_325796  VALUES (''325796'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_15_326461  VALUES (''326461'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_16_328845  VALUES (''328845'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_17_331467  VALUES (''331467'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_18_333368  VALUES (''333368'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_19_337568  VALUES (''337568'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_20_338545  VALUES (''338545'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_21_351823  VALUES (''351823'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_22_352457  VALUES (''352457'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_23_315784  VALUES (''315784'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_24_354507  VALUES (''354507'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_25_356334  VALUES (''356334'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION P_26_353553  VALUES (''353553'') SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD )';
  exception when others then
  if sqlcode = -955 then null;
  else raise;
  end if;
 END;
/
COMMENT ON TABLE BARS.OW_INST_TOTALS_HIST IS 'Графік сплати Інстолмент(Історична)';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.CONTRACT IS 'ІД договору';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.CONTRACT_IDT IS 'Рахунок 2625XX з АБС';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.SCHEME IS 'ІД затвердженої схеми';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.PLAN_ID IS 'ІД графіка';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.CHAIN_IDT IS 'ІД основного(першого) графіка';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.DOCUMENT_ID IS 'ІД документу';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.STATUS IS 'Статус графіка: 
Waiting-статус до відкриття
Open - відкрито
Paid - погашено
Partially Paid - частково погашено
Overdue - прострочено
Closed - відмінено
Revised - реструктеризовано';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.TOTAL_AMOUNT IS 'Загальна сума по графіку';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.AMOUNT_TO_PAY IS 'Сума до сплати';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.WRITTEN_OFF_AMOUNT IS 'Сума списання';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.OVERDUE_AMOUNT IS 'Сума прострочки';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.OVD_90_DAYS IS 'Дата визнання договору проблемним';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.PLAN_NUM IS 'Кількість графіків в історичних таблицях';

COMMENT ON COLUMN BARS.OW_INST_TOTALS_HIST.KF IS 'МФО';
/
begin
  execute immediate 'begin BARS_POLICY_ADM.ALTER_POLICIES(''OW_INST_TOTALS_HIST''); end;';
exception when others then
  if sqlcode = -06550 then null; else raise; end if;
end;
/
begin   
 execute immediate 'ALTER TABLE BARS.OW_INST_TOTALS_HIST ADD 
CONSTRAINT ow_inst_totals_hist_PK
 PRIMARY KEY (chain_idt, plan_num)
 ENABLE
 VALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/
begin   
 execute immediate ' 
ALTER TABLE BARS.OW_INST_TOTALS_HIST ADD 
CONSTRAINT FK_OW_INST_TOTALS_HIST
 FOREIGN KEY (CHAIN_IDT)
 REFERENCES BARS.OW_INST_TOTALS (CHAIN_IDT)
  ON DELETE CASCADE
 ENABLE
 VALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/

PROMPT *** Create  index IDX_OWINSTTOTALH_DT1 ***
begin   
 execute immediate '
  CREATE INDEX BARS.IDX_OWINSTTOTALH_DT1 ON 
  BARS.OW_INST_TOTALS_HIST (INS_BD, CHAIN_IDT, PLAN_NUM) 
  NOLOGGING LOCAL TABLESPACE BRSDYNI COMPUTE STATISTICS';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/

grant all on ow_inst_totals_hist to bars_access_defrole;
/
grant all on ow_inst_totals_hist to bars;
/