

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/OW_LOCPAY_MATCH.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to OW_LOCPAY_MATCH ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''OW_LOCPAY_MATCH'', ''CENTER'' , null, ''E'', ''E'', ''E'');
               bpa.alter_policy_info(''OW_LOCPAY_MATCH'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''OW_LOCPAY_MATCH'', ''WHOLE'' , null, ''E'', ''E'', ''E'');
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table OW_LOCPAY_MATCH ***
begin 
  execute immediate '
  CREATE TABLE BARS.OW_LOCPAY_MATCH 
   (	REF NUMBER(22,0), 
	STATE NUMBER DEFAULT 0, 
	DRN NUMBER(22,0), 
	RRN NUMBER(22,0), 
	REVFLAG NUMBER DEFAULT 0, 
	DOC_DATA CLOB, 
	REVFILE_NAME VARCHAR2(100), 
	REV_MESSAGE VARCHAR2(500), 
	REF_FEE NUMBER(22,0), 
	RESP_CLASS VARCHAR2(100), 
	RESP_CODE VARCHAR2(100), 
	RESP_TEXT VARCHAR2(254), 
	ACC NUMBER(38,0), 
	KF VARCHAR2(6) DEFAULT sys_context(''bars_context'',''user_mfo'')
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSDYND 
 LOB (DOC_DATA) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
  PARTITION BY LIST (REVFLAG) 
  SUBPARTITION BY LIST (STATE) 
  SUBPARTITION TEMPLATE ( 
    SUBPARTITION SP_STATE0 VALUES ( 0 )
  TABLESPACE BRSDYND , 
    SUBPARTITION SP_STATE1 VALUES ( 1 )
  TABLESPACE BRSDYND , 
    SUBPARTITION SP_STATE2 VALUES ( 2 )
  TABLESPACE BRSDYND , 
    SUBPARTITION SP_STATE3 VALUES ( 3 )
  TABLESPACE BRSDYND , 
    SUBPARTITION SP_STATE10 VALUES ( 10 )
  TABLESPACE BRSDYND , 
    SUBPARTITION SP_STATE11 VALUES ( 11 )
  TABLESPACE BRSDYND , 
    SUBPARTITION SP_STATEDEF VALUES ( default )
  TABLESPACE BRSDYND  ) 
 (PARTITION P_REVFLAG0  VALUES (0) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSDYND 
 LOB (DOC_DATA) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION P_REVFLAG1  VALUES (1) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSDYND 
 LOB (DOC_DATA) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION P_REVFLAGDEF  VALUES (default) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSDYND 
 LOB (DOC_DATA) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) )  ENABLE ROW MOVEMENT ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to OW_LOCPAY_MATCH ***
 exec bpa.alter_policies('OW_LOCPAY_MATCH');


COMMENT ON TABLE BARS.OW_LOCPAY_MATCH IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.RESP_CLASS IS 'Категория ответа';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.RESP_CODE IS 'Код ответа';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.RESP_TEXT IS 'Текст ответа';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.ACC IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.KF IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.REF IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.STATE IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.DRN IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.RRN IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.REVFLAG IS 'Флаг реверсала';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.DOC_DATA IS '';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.REVFILE_NAME IS 'Имя файла  LOCPAYREV';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.REV_MESSAGE IS 'Причина отмены платежа.';
COMMENT ON COLUMN BARS.OW_LOCPAY_MATCH.REF_FEE IS 'Референс документа комиссии';




PROMPT *** Create  constraint SYS_C004455 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_LOCPAY_MATCH MODIFY (REF NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_OWLOCPAYMATCH ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_LOCPAY_MATCH ADD CONSTRAINT PK_OWLOCPAYMATCH PRIMARY KEY (REF)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OWLOCPAYMATCH_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OW_LOCPAY_MATCH MODIFY (KF CONSTRAINT CC_OWLOCPAYMATCH_KF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_OWLOCPAYMATCH ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_OWLOCPAYMATCH ON BARS.OW_LOCPAY_MATCH (REF) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_OWLOCPAYMATCH_ACC ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OWLOCPAYMATCH_ACC ON BARS.OW_LOCPAY_MATCH (ACC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYNI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_OWLOCPAYMATCH_RRN ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OWLOCPAYMATCH_RRN ON BARS.OW_LOCPAY_MATCH (RRN) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI  LOCAL
 (PARTITION P_REVFLAG0 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI 
 ( SUBPARTITION P_REVFLAG0_SP_STATE0 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE1 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE2 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE3 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE10 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE11 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATEDEF 
  TABLESPACE BRSDYNI ) , 
 PARTITION P_REVFLAG1 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI 
 ( SUBPARTITION P_REVFLAG1_SP_STATE0 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE1 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE2 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE3 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE10 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE11 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATEDEF 
  TABLESPACE BRSDYNI ) , 
 PARTITION P_REVFLAGDEF 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI 
 ( SUBPARTITION P_REVFLAGDEF_SP_STATE0 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE1 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE2 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE3 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE10 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE11 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATEDEF 
  TABLESPACE BRSDYNI ) ) ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_OWLOCPAYMATCH_DRN ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_OWLOCPAYMATCH_DRN ON BARS.OW_LOCPAY_MATCH (DRN) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI  LOCAL
 (PARTITION P_REVFLAG0 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI 
 ( SUBPARTITION P_REVFLAG0_SP_STATE0 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE1 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE2 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE3 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE10 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATE11 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG0_SP_STATEDEF 
  TABLESPACE BRSDYNI ) , 
 PARTITION P_REVFLAG1 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI 
 ( SUBPARTITION P_REVFLAG1_SP_STATE0 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE1 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE2 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE3 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE10 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATE11 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAG1_SP_STATEDEF 
  TABLESPACE BRSDYNI ) , 
 PARTITION P_REVFLAGDEF 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSDYNI 
 ( SUBPARTITION P_REVFLAGDEF_SP_STATE0 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE1 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE2 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE3 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE10 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATE11 
  TABLESPACE BRSDYNI , 
  SUBPARTITION P_REVFLAGDEF_SP_STATEDEF 
  TABLESPACE BRSDYNI ) ) ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  OW_LOCPAY_MATCH ***
grant SELECT                                                                 on OW_LOCPAY_MATCH to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on OW_LOCPAY_MATCH to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on OW_LOCPAY_MATCH to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/OW_LOCPAY_MATCH.sql =========*** End *
PROMPT ===================================================================================== 
