

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/PFU_EPP_LINE_PROCESSING.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to PFU_EPP_LINE_PROCESSING ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''PFU_EPP_LINE_PROCESSING'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''PFU_EPP_LINE_PROCESSING'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table PFU_EPP_LINE_PROCESSING ***
begin 
  execute immediate '
  CREATE TABLE BARS.PFU_EPP_LINE_PROCESSING 
   (	ID NUMBER, 
	FILE_ID NUMBER, 
	EPP_NUMBER VARCHAR2(12), 
	PERSON_RECORD_NUMBER VARCHAR2(10), 
	LAST_NAME VARCHAR2(70), 
	FIRST_NAME VARCHAR2(50), 
	MIDDLE_NAME VARCHAR2(50), 
	GENDER NUMBER(1,0), 
	DATE_OF_BIRTH DATE, 
	PHONE_NUMBERS VARCHAR2(30), 
	EMBOSSING_NAME VARCHAR2(172), 
	TAX_REGISTRATION_NUMBER VARCHAR2(10), 
	DOCUMENT_TYPE NUMBER(1,0), 
	DOCUMENT_ID VARCHAR2(10), 
	DOCUMENT_ISSUE_DATE DATE, 
	DOCUMENT_ISSUER VARCHAR2(100), 
	DISPLACED_PERSON_FLAG NUMBER(1,0), 
	BANK_MFO VARCHAR2(6), 
	BANK_NUM VARCHAR2(30), 
	BANK_NAME VARCHAR2(100), 
	EPP_EXPIRY_DATE DATE, 
	LEGAL_COUNTRY VARCHAR2(50), 
	LEGAL_ZIP_CODE VARCHAR2(6), 
	LEGAL_REGION VARCHAR2(50), 
	LEGAL_DISTRICT VARCHAR2(100), 
	LEGAL_SETTLEMENT VARCHAR2(100), 
	LEGAL_STREET VARCHAR2(100), 
	LEGAL_HOUSE VARCHAR2(5), 
	LEGAL_HOUSE_PART VARCHAR2(2), 
	LEGAL_APARTMENT VARCHAR2(5), 
	ACTUAL_COUNTRY VARCHAR2(50), 
	ACTUAL_ZIP_CODE VARCHAR2(6), 
	ACTUAL_REGION VARCHAR2(50), 
	ACTUAL_DISTRICT VARCHAR2(100), 
	ACTUAL_SETTLEMENT VARCHAR2(100), 
	ACTUAL_STREET VARCHAR2(100), 
	ACTUAL_HOUSE VARCHAR2(5), 
	ACTUAL_HOUSE_PART VARCHAR2(2), 
	ACTUAL_APARTMENT VARCHAR2(5), 
	SIGN RAW(128), 
	STATE_ID NUMBER(5,0), 
	MESSAGE VARCHAR2(4000), 
	NLS VARCHAR2(15), 
	BRANCH VARCHAR2(30), 
	TYPE_PENS NUMBER(1,0), 
	REQID NUMBER(38,0), 
	DATE_BLK DATE, 
	IS_BLK NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSMDLD ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to PFU_EPP_LINE_PROCESSING ***
 exec bpa.alter_policies('PFU_EPP_LINE_PROCESSING');


COMMENT ON TABLE BARS.PFU_EPP_LINE_PROCESSING IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DATE_BLK IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.IS_BLK IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ID IS 'Ідентифікатор запису в файлі з ФА';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.FILE_ID IS 'Ідентифікатор файлу ЦА';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.EPP_NUMBER IS 'Ідентифікатор електронного пенсійного посвідчення';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.PERSON_RECORD_NUMBER IS 'Номер облікової картки застрахованої особи';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LAST_NAME IS 'Прізвище';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.FIRST_NAME IS 'Ім’я';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.MIDDLE_NAME IS 'По батькові';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.GENDER IS 'Стать';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DATE_OF_BIRTH IS 'Дата народження';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.PHONE_NUMBERS IS 'Контактний номер телефону';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.EMBOSSING_NAME IS 'Транслітерація ПІБ';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.TAX_REGISTRATION_NUMBER IS 'ІПН';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DOCUMENT_TYPE IS 'Тип документу';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DOCUMENT_ID IS 'Серія та номер документу';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DOCUMENT_ISSUE_DATE IS 'Дата видачі документу';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DOCUMENT_ISSUER IS 'Ким видано документ';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.DISPLACED_PERSON_FLAG IS 'Ознака «тимчасово переміщена особа»';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.BANK_MFO IS 'Код банку (МФО)';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.BANK_NUM IS 'Номер філії/ відділення банку де особа отримуватиме картку';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.BANK_NAME IS 'Найменування філії/відділення  банку де особа отримуватиме картку';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.EPP_EXPIRY_DATE IS 'Термін закінчення дії електронного пенсійного посвідчення';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_COUNTRY IS 'Країна';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_ZIP_CODE IS 'індекс';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_REGION IS 'область';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_DISTRICT IS 'район';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_SETTLEMENT IS 'населений пункт';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_STREET IS 'вулиця';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_HOUSE IS 'будинок';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_HOUSE_PART IS 'корпус';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.LEGAL_APARTMENT IS 'квартира';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_COUNTRY IS 'Країна';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_ZIP_CODE IS 'індекс';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_REGION IS 'область';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_DISTRICT IS 'район';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_SETTLEMENT IS 'населений пункт';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_STREET IS 'вулиця';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_HOUSE IS 'будинок';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_HOUSE_PART IS 'корпус';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.ACTUAL_APARTMENT IS 'квартира';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.SIGN IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.STATE_ID IS 'Статус обробки';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.MESSAGE IS 'Текс обробки';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.NLS IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.BRANCH IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.TYPE_PENS IS '';
COMMENT ON COLUMN BARS.PFU_EPP_LINE_PROCESSING.REQID IS 'ИД заявки на CM';




PROMPT *** Create  constraint SYS_C00109503 ***
begin   
 execute immediate '
  ALTER TABLE BARS.PFU_EPP_LINE_PROCESSING MODIFY (ID NOT NULL ENABLE NOVALIDATE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_PFU_EPP_LINE_PROCESSING ***
begin   
 execute immediate '
  ALTER TABLE BARS.PFU_EPP_LINE_PROCESSING ADD CONSTRAINT PK_PFU_EPP_LINE_PROCESSING PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint UK_PFU_EPP_LINE_PROCESSING ***
begin   
 execute immediate '
  ALTER TABLE BARS.PFU_EPP_LINE_PROCESSING ADD CONSTRAINT UK_PFU_EPP_LINE_PROCESSING UNIQUE (EPP_NUMBER)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_PFU_EPP_LINE_NLS ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_PFU_EPP_LINE_NLS ON BARS.PFU_EPP_LINE_PROCESSING (NLS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_PFU_EPP_LINE_PROCESSING ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_PFU_EPP_LINE_PROCESSING ON BARS.PFU_EPP_LINE_PROCESSING (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index UK_PFU_EPP_LINE_PROCESSING ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.UK_PFU_EPP_LINE_PROCESSING ON BARS.PFU_EPP_LINE_PROCESSING (EPP_NUMBER) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  PFU_EPP_LINE_PROCESSING ***
grant SELECT                                                                 on PFU_EPP_LINE_PROCESSING to BARSREADER_ROLE;
grant ALTER,DEBUG,DELETE,FLASHBACK,INSERT,ON COMMIT REFRESH,QUERY REWRITE,SELECT,UPDATE on PFU_EPP_LINE_PROCESSING to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on PFU_EPP_LINE_PROCESSING to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/PFU_EPP_LINE_PROCESSING.sql =========*
PROMPT ===================================================================================== 
