

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/REZ_XLS_GT.sql =========*** Run *** ==
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to REZ_XLS_GT ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''REZ_XLS_GT'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''REZ_XLS_GT'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table REZ_XLS_GT ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARS.REZ_XLS_GT 
   (	TIPA NUMBER(*,0), 
	ACC NUMBER(*,0), 
	NLS VARCHAR2(15), 
	KV NUMBER(3,0), 
	FIN NUMBER(*,0), 
	EAD NUMBER, 
	EADQ NUMBER, 
	BV NUMBER, 
	BVQ NUMBER, 
	ND NUMBER, 
	EAD_SN NUMBER, 
	EAD_SNQ NUMBER, 
	EAD_CCF NUMBER, 
	EAD_CCFQ NUMBER, 
	ZAL NUMBER, 
	ZALQ NUMBER, 
	RC NUMBER, 
	RCQ NUMBER, 
	CR NUMBER, 
	CRQ NUMBER, 
	REZ39 NUMBER, 
	REZQ39 NUMBER, 
	REZ23 NUMBER, 
	REZQ23 NUMBER, 
	ISTVAL NUMBER, 
	CCF NUMBER, 
	G6 NUMBER, 
	DEL NUMBER, 
	S250 NUMBER, 
	CUSTTYPE NUMBER, 
	DD CHAR(1), 
	DDD CHAR(3), 
	NBS CHAR(4), 
	RZ NUMBER, 
	PD_0 NUMBER, 
	RPB NUMBER, 
	X6 NUMBER, 
	X7 NUMBER, 
	X8 NUMBER, 
	X9 NUMBER, 
	X10 NUMBER, 
	X11 NUMBER
   ) ON COMMIT PRESERVE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to REZ_XLS_GT ***
 exec bpa.alter_policies('REZ_XLS_GT');


COMMENT ON TABLE BARS.REZ_XLS_GT IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.TIPA IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.ACC IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.NLS IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.KV IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.FIN IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.EAD IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.EADQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.BV IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.BVQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.ND IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.EAD_SN IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.EAD_SNQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.EAD_CCF IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.EAD_CCFQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.ZAL IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.ZALQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.RC IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.RCQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.CR IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.CRQ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.REZ39 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.REZQ39 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.REZ23 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.REZQ23 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.ISTVAL IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.CCF IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.G6 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.DEL IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.S250 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.DD IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.DDD IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.NBS IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.RZ IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.PD_0 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.RPB IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.X6 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.X7 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.X8 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.X9 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.X10 IS '';
COMMENT ON COLUMN BARS.REZ_XLS_GT.X11 IS '';



PROMPT *** Create  grants  REZ_XLS_GT ***
grant SELECT                                                                 on REZ_XLS_GT      to BARSREADER_ROLE;
grant SELECT                                                                 on REZ_XLS_GT      to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/REZ_XLS_GT.sql =========*** End *** ==
PROMPT ===================================================================================== 
