

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/REZERV_REPORT.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to REZERV_REPORT ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''REZERV_REPORT'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''REZERV_REPORT'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''REZERV_REPORT'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table REZERV_REPORT ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARS.REZERV_REPORT 
   (	BRANCH VARCHAR2(30), 
	BR_NAME VARCHAR2(70), 
	S1 NUMBER, 
	S2 NUMBER, 
	S3 NUMBER, 
	S4 NUMBER, 
	S5 NUMBER, 
	S6 NUMBER, 
	S7 NUMBER, 
	S8 NUMBER, 
	S9 NUMBER, 
	S10 NUMBER, 
	S11 NUMBER, 
	S12 NUMBER, 
	S13 NUMBER, 
	S14 NUMBER, 
	S15 NUMBER, 
	S16 NUMBER, 
	S17 NUMBER, 
	S18 NUMBER, 
	S19 NUMBER, 
	S20 NUMBER, 
	S21 NUMBER, 
	S22 NUMBER, 
	S23 NUMBER, 
	S24 NUMBER, 
	S25 NUMBER, 
	S26 NUMBER, 
	S27 NUMBER, 
	S28 NUMBER, 
	S29 NUMBER, 
	S30 NUMBER, 
	S31 NUMBER, 
	S32 NUMBER, 
	S33 NUMBER, 
	S34 NUMBER, 
	S35 NUMBER, 
	S36 NUMBER, 
	S37 NUMBER, 
	S38 NUMBER, 
	S39 NUMBER, 
	S40 NUMBER, 
	S41 NUMBER, 
	S42 NUMBER, 
	S43 NUMBER, 
	S44 NUMBER, 
	S45 NUMBER, 
	S46 NUMBER, 
	S47 NUMBER, 
	S48 NUMBER, 
	S49 NUMBER, 
	S50 NUMBER, 
	S51 NUMBER, 
	S52 NUMBER, 
	S54 NUMBER, 
	S55 NUMBER
   ) ON COMMIT PRESERVE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to REZERV_REPORT ***
 exec bpa.alter_policies('REZERV_REPORT');


COMMENT ON TABLE BARS.REZERV_REPORT IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.BRANCH IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.BR_NAME IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S1 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S2 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S3 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S4 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S5 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S6 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S7 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S8 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S9 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S10 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S11 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S12 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S13 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S14 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S15 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S16 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S17 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S18 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S19 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S20 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S21 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S22 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S23 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S24 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S25 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S26 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S27 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S28 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S29 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S30 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S31 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S32 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S33 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S34 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S35 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S36 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S37 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S38 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S39 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S40 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S41 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S42 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S43 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S44 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S45 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S46 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S47 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S48 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S49 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S50 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S51 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S52 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S54 IS '';
COMMENT ON COLUMN BARS.REZERV_REPORT.S55 IS '';



PROMPT *** Create  grants  REZERV_REPORT ***
grant SELECT                                                                 on REZERV_REPORT   to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on REZERV_REPORT   to RCC_DEAL;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on REZERV_REPORT   to WR_ALL_RIGHTS;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/REZERV_REPORT.sql =========*** End ***
PROMPT ===================================================================================== 
