

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TEMP_FIN_BUDGET.sql =========*** Run *
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TEMP_FIN_BUDGET ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TEMP_FIN_BUDGET'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''TEMP_FIN_BUDGET'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''TEMP_FIN_BUDGET'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TEMP_FIN_BUDGET ***
begin 
  execute immediate '
  CREATE TABLE BARS.TEMP_FIN_BUDGET 
   (	N600_601 NUMBER, 
	N602 NUMBER, 
	N603 NUMBER, 
	N604 NUMBER, 
	N605 NUMBER, 
	N608_708 NUMBER, 
	N609 NUMBER, 
	SUMA1 NUMBER, 
	A700_A701 NUMBER, 
	A702_P702 NUMBER, 
	A703 NUMBER, 
	S41_42 NUMBER, 
	A7040 NUMBER, 
	A_7041_P7041 NUMBER, 
	A705_P705 NUMBER, 
	A708_P608 NUMBER, 
	A709 NUMBER, 
	SUMA1_2 NUMBER, 
	SUMA2 NUMBER, 
	P610_611 NUMBER, 
	A710 NUMBER, 
	SUMA4_5 NUMBER, 
	SUMA7 NUMBER, 
	P6204_A6204 NUMBER, 
	P6203_A6203 NUMBER, 
	P6209_A6209 NUMBER, 
	P6394 NUMBER, 
	SUMA3_6_7_8 NUMBER, 
	SUMA10 NUMBER, 
	SUMA1_10 NUMBER, 
	A741 NUMBER, 
	A7420 NUMBER, 
	A7430 NUMBER, 
	A7431 NUMBER, 
	A7432 NUMBER, 
	A7433 NUMBER, 
	A744 NUMBER, 
	A7451 NUMBER, 
	A7452 NUMBER, 
	A7455 NUMBER, 
	A7423 NUMBER, 
	SUMA31_32 NUMBER, 
	A7421 NUMBER, 
	A7395 NUMBER, 
	SUMA41_42 NUMBER, 
	A7390 NUMBER, 
	A7450 NUMBER, 
	SUMA11 NUMBER, 
	A7400 NUMBER, 
	A7401 NUMBER, 
	A7403 NUMBER, 
	A7409 NUMBER, 
	SUMA13 NUMBER, 
	SUMA14 NUMBER, 
	A7702 NUMBER, 
	A7701 NUMBER, 
	A7704 NUMBER, 
	A7700 NUMBER, 
	A7717 NUMBER, 
	A7900 NUMBER, 
	P6809_A7809 NUMBER, 
	SUMA13_14_15_16 NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TEMP_FIN_BUDGET ***
 exec bpa.alter_policies('TEMP_FIN_BUDGET');


COMMENT ON TABLE BARS.TEMP_FIN_BUDGET IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N600_601 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N602 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N603 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N604 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N605 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N608_708 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.N609 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA1 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A700_A701 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A702_P702 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A703 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.S41_42 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7040 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A_7041_P7041 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A705_P705 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A708_P608 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A709 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA1_2 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA2 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.P610_611 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A710 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA4_5 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA7 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.P6204_A6204 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.P6203_A6203 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.P6209_A6209 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.P6394 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA3_6_7_8 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA10 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA1_10 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A741 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7420 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7430 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7431 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7432 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7433 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A744 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7451 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7452 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7455 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7423 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA31_32 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7421 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7395 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA41_42 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7390 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7450 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA11 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7400 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7401 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7403 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7409 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA13 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA14 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7702 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7701 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7704 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7700 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7717 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.A7900 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.P6809_A7809 IS '';
COMMENT ON COLUMN BARS.TEMP_FIN_BUDGET.SUMA13_14_15_16 IS '';



PROMPT *** Create  grants  TEMP_FIN_BUDGET ***
grant SELECT                                                                 on TEMP_FIN_BUDGET to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TEMP_FIN_BUDGET to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TEMP_FIN_BUDGET to START1;
grant SELECT                                                                 on TEMP_FIN_BUDGET to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TEMP_FIN_BUDGET.sql =========*** End *
PROMPT ===================================================================================== 
