

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_PRIOCOM_CLIENTS_JUR.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_PRIOCOM_CLIENTS_JUR ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TMP_PRIOCOM_CLIENTS_JUR'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_PRIOCOM_CLIENTS_JUR'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_PRIOCOM_CLIENTS_JUR'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_PRIOCOM_CLIENTS_JUR ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARS.TMP_PRIOCOM_CLIENTS_JUR 
   (	MFO VARCHAR2(6), 
	KOD_FIL NUMBER(*,0), 
	OKPO VARCHAR2(14), 
	SYSNAME VARCHAR2(70), 
	NAME VARCHAR2(70), 
	ISSTOCKHOLDER NUMBER(*,0), 
	ISVIP NUMBER(*,0), 
	REGDATE DATE, 
	CREATEDATE DATE, 
	ISBUDGETORG NUMBER(*,0), 
	ISRESIDENT NUMBER(*,0), 
	DEBTORCLASS NUMBER(*,0), 
	LEGALADDR_POSTIND VARCHAR2(10), 
	LEGALADDR VARCHAR2(70), 
	LEGALADDR_PHONE VARCHAR2(500), 
	LEGALADDR_FAX VARCHAR2(500), 
	LEGALADDR_EMAIL VARCHAR2(500), 
	ADDR_POSTIND VARCHAR2(10), 
	ADDR VARCHAR2(70), 
	FIODIRECTOR VARCHAR2(70), 
	OKPODIRECTOR VARCHAR2(14), 
	POSDIRECTOR VARCHAR2(500), 
	STATUT VARCHAR2(500), 
	SIGNDIRECTOR NUMBER(*,0), 
	DESCRIPTIONDIRECTOR VARCHAR2(500), 
	FIOSYN VARCHAR2(70), 
	OKPOSYN VARCHAR2(14), 
	POSSYN VARCHAR2(500), 
	SIGNSYN NUMBER(*,0), 
	DESCRIPTIONSYN VARCHAR2(500), 
	K050 VARCHAR2(3), 
	K060 VARCHAR2(2), 
	K070 VARCHAR2(5), 
	K080 VARCHAR2(2), 
	K090 VARCHAR2(5), 
	K110 VARCHAR2(5), 
	K120 VARCHAR2(5), 
	SMALLBIS NUMBER(*,0), 
	TAXADMINNUM NUMBER(*,0), 
	TAXREGIONNUM NUMBER(*,0), 
	GOVERMENTPART NUMBER, 
	SALESTAXCODE NUMBER(*,0), 
	TAXFORM NUMBER(*,0), 
	TAXDOLG NUMBER(*,0), 
	TAXORG VARCHAR2(128), 
	TAXNUM VARCHAR2(30), 
	TAXREGDATE DATE, 
	PUBADMINNUM VARCHAR2(30), 
	PUBADMINDATE DATE, 
	PUBADMINPLACE VARCHAR2(70), 
	FIOFOUNDER VARCHAR2(70), 
	OKPOFOUNDER VARCHAR2(14), 
	RELTYPE VARCHAR2(500), 
	DESCRIPTION VARCHAR2(500), 
	RESULT NUMBER(*,0), 
	MESSAGE VARCHAR2(4000), 
	CODE NUMBER(*,0)
   ) ON COMMIT PRESERVE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_PRIOCOM_CLIENTS_JUR ***
 exec bpa.alter_policies('TMP_PRIOCOM_CLIENTS_JUR');


COMMENT ON TABLE BARS.TMP_PRIOCOM_CLIENTS_JUR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.ISBUDGETORG IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.ISRESIDENT IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.DEBTORCLASS IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.LEGALADDR_POSTIND IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.LEGALADDR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.LEGALADDR_PHONE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.LEGALADDR_FAX IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.LEGALADDR_EMAIL IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.ADDR_POSTIND IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.ADDR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.FIODIRECTOR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.OKPODIRECTOR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.POSDIRECTOR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.STATUT IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.SIGNDIRECTOR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.DESCRIPTIONDIRECTOR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.FIOSYN IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.OKPOSYN IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.POSSYN IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.SIGNSYN IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.DESCRIPTIONSYN IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K050 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K060 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K070 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K080 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K090 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K110 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.K120 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.SMALLBIS IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXADMINNUM IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXREGIONNUM IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.GOVERMENTPART IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.SALESTAXCODE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXFORM IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXDOLG IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXORG IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXNUM IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.TAXREGDATE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.PUBADMINNUM IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.PUBADMINDATE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.PUBADMINPLACE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.FIOFOUNDER IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.OKPOFOUNDER IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.RELTYPE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.DESCRIPTION IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.RESULT IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.MESSAGE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.CODE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.MFO IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.KOD_FIL IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.SYSNAME IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.NAME IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.ISSTOCKHOLDER IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.ISVIP IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.REGDATE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_CLIENTS_JUR.CREATEDATE IS '';



PROMPT *** Create  grants  TMP_PRIOCOM_CLIENTS_JUR ***
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_PRIOCOM_CLIENTS_JUR to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_PRIOCOM_CLIENTS_JUR to START1;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_PRIOCOM_CLIENTS_JUR.sql =========*
PROMPT ===================================================================================== 
