Prompt drop TABLE TMP_TXT;
DROP TABLE BARS.TMP_TXT CASCADE CONSTRAINTS;

Prompt Table TMP_TXT;
CREATE TABLE BARS.TMP_TXT
(
  TXT  CLOB
)
LOB (TXT) STORE AS (
  TABLESPACE  BRSDYND
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE BRSDYND
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
