

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_LICS_ELPAY.sql =========*** Run **
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_LICS_ELPAY ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TMP_LICS_ELPAY'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_LICS_ELPAY'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_LICS_ELPAY'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_LICS_ELPAY ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_LICS_ELPAY 
   (	ID NUMBER(38,0), 
	DAOPL DATE, 
	ACC NUMBER(16,0), 
	S NUMBER(17,0), 
	ND VARCHAR2(10), 
	MFOB VARCHAR2(9), 
	NAZN VARCHAR2(160), 
	ISP NUMBER(38,0), 
	NLSA VARCHAR2(14), 
	MFOA VARCHAR2(9), 
	KV NUMBER, 
	NAMA VARCHAR2(38), 
	NLSB VARCHAR2(14), 
	NAMB VARCHAR2(38), 
	REF NUMBER(16,0), 
	TT CHAR(3), 
	IOST NUMBER(24,0), 
	DOS NUMBER(24,0), 
	KOS NUMBER(24,0), 
	VDAT DATE, 
	PDAT DATE, 
	SK NUMBER(38,0), 
	DAPP DATE, 
	OKPOA VARCHAR2(14), 
	OKPOB VARCHAR2(14), 
	DK NUMBER(38,0), 
	VOB NUMBER(38,0), 
	POND VARCHAR2(10), 
	NAMEFILEA VARCHAR2(12), 
	KODIROWKA NUMBER, 
	NAZNS VARCHAR2(2), 
	BIS NUMBER, 
	NAZNK VARCHAR2(3), 
	D_REC VARCHAR2(80), 
	FN_A VARCHAR2(12), 
	REC NUMBER, 
	DATD DATE, 
	NB_A VARCHAR2(38), 
	NB_B VARCHAR2(38), 
	SOS NUMBER, 
	OPLDOK_ID NUMBER, 
	RECORD_ID VARCHAR2(128), 
	PRWO VARCHAR2(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_LICS_ELPAY ***
 exec bpa.alter_policies('TMP_LICS_ELPAY');


COMMENT ON TABLE BARS.TMP_LICS_ELPAY IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.REC IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.DATD IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NB_A IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NB_B IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.SOS IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.OPLDOK_ID IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.RECORD_ID IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.PRWO IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.ID IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.DAOPL IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.ACC IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.S IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.ND IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.MFOB IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NAZN IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.ISP IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NLSA IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.MFOA IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.KV IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NAMA IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NLSB IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NAMB IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.REF IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.TT IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.IOST IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.DOS IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.KOS IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.VDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.PDAT IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.SK IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.DAPP IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.OKPOA IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.OKPOB IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.DK IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.VOB IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.POND IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NAMEFILEA IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.KODIROWKA IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NAZNS IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.BIS IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.NAZNK IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.D_REC IS '';
COMMENT ON COLUMN BARS.TMP_LICS_ELPAY.FN_A IS '';



PROMPT *** Create  grants  TMP_LICS_ELPAY ***
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_LICS_ELPAY  to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_LICS_ELPAY  to START1;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_LICS_ELPAY.sql =========*** End **
PROMPT ===================================================================================== 
