

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CP_ZV_OLD.sql =========*** Run ***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CP_ZV_OLD ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CP_ZV_OLD ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_CP_ZV_OLD 
   (	G001 VARCHAR2(4), 
	G002 VARCHAR2(3), 
	G003 VARCHAR2(1), 
	G004 VARCHAR2(4), 
	G005 VARCHAR2(1), 
	G006 VARCHAR2(50), 
	G007 VARCHAR2(50), 
	G008 VARCHAR2(50), 
	G009 VARCHAR2(3), 
	G010 VARCHAR2(50), 
	G011 VARCHAR2(50), 
	G012 VARCHAR2(20), 
	G013 DATE, 
	G014 VARCHAR2(50), 
	G015 NUMBER, 
	G016 NUMBER, 
	G017 NUMBER, 
	G018 NUMBER, 
	G019 NUMBER, 
	G020 NUMBER, 
	G021 NUMBER, 
	G022 NUMBER, 
	G023 NUMBER, 
	G024 NUMBER, 
	G025 NUMBER, 
	G026 NUMBER, 
	G027 NUMBER, 
	G028 NUMBER, 
	G029 NUMBER, 
	G030 NUMBER, 
	G031 NUMBER, 
	G032 NUMBER, 
	G033 NUMBER, 
	G034 VARCHAR2(1), 
	G035 DATE, 
	G036 VARCHAR2(50), 
	G037 NUMBER, 
	G038 NUMBER, 
	G039 NUMBER, 
	G040 NUMBER, 
	G041 VARCHAR2(1), 
	G042 DATE, 
	G043 VARCHAR2(50), 
	G044 VARCHAR2(50), 
	G045 VARCHAR2(50), 
	G046 VARCHAR2(50), 
	G047 VARCHAR2(50), 
	G048 DATE, 
	G049 DATE, 
	G050 DATE, 
	G051 NUMBER, 
	G052 NUMBER, 
	G053 NUMBER, 
	G054 NUMBER, 
	G055 NUMBER, 
	G056 NUMBER, 
	G057 NUMBER, 
	G058 NUMBER, 
	G059 NUMBER, 
	G060 NUMBER, 
	G061 NUMBER, 
	G062 NUMBER, 
	G063 NUMBER, 
	G064 NUMBER, 
	G065 NUMBER, 
	G066 NUMBER, 
	G067 NUMBER, 
	G068 NUMBER, 
	G069 NUMBER, 
	G070 NUMBER, 
	G071 VARCHAR2(50), 
	G072 DATE, 
	G073 VARCHAR2(3), 
	G074 VARCHAR2(50), 
	G075 VARCHAR2(50), 
	G076 VARCHAR2(50), 
	G077 DATE, 
	G078 VARCHAR2(50), 
	G079 VARCHAR2(50), 
	G080 VARCHAR2(14), 
	G081 DATE, 
	G082 NUMBER, 
	G083 VARCHAR2(50), 
	G084 NUMBER, 
	G085 NUMBER, 
	G086 VARCHAR2(1), 
	G087 NUMBER, 
	G088 NUMBER, 
	ID NUMBER(*,0), 
	ISIN VARCHAR2(20), 
	NBS_OLD NUMBER(4,0), 
	KV NUMBER(*,0), 
	REPO VARCHAR2(5), 
	D_K VARCHAR2(1), 
	PF_OLD NUMBER(*,0), 
	EMI VARCHAR2(50), 
	OKPO VARCHAR2(8), 
	AUKCION VARCHAR2(15), 
	DAT_K DATE, 
	NM_PROD VARCHAR2(50), 
	BV1 NUMBER, 
	CENA0 NUMBER, 
	KL1 NUMBER, 
	N1 NUMBER, 
	R1 NUMBER, 
	D1 NUMBER, 
	P1 NUMBER, 
	Z1 NUMBER, 
	S1 NUMBER, 
	CF008_019 NUMBER(1,0), 
	N2 NUMBER, 
	KL2 NUMBER, 
	KL_K2 NUMBER, 
	CENA_K2 NUMBER, 
	CF008_023 VARCHAR2(1), 
	DAT_K2 DATE, 
	NM_PROD2 VARCHAR2(50), 
	N2_P NUMBER, 
	KL2_P NUMBER, 
	CF008_028 VARCHAR2(1), 
	DAT_P2 DATE, 
	NM_POK VARCHAR2(50), 
	CENA_P2 NUMBER, 
	R2 NUMBER, 
	S2 NUMBER, 
	TR1_31 NUMBER, 
	KL31 NUMBER, 
	N31 NUMBER, 
	R31 NUMBER, 
	D31 NUMBER, 
	P31 NUMBER, 
	S31 NUMBER, 
	Z31 NUMBER, 
	IR31 NUMBER, 
	DAT_PG DATE, 
	CF008_042 DATE, 
	DAT_IR DATE, 
	KOT31 NUMBER, 
	CF008_045 VARCHAR2(30), 
	DAT_KOT DATE, 
	DAT_P4 DATE, 
	SUMB4 NUMBER, 
	NM_POK4 VARCHAR2(50), 
	KL_P4 NUMBER, 
	CENA_P4 NUMBER, 
	N4 NUMBER, 
	BV31 NUMBER, 
	PV31 NUMBER, 
	CF008_055 VARCHAR2(5), 
	CF008_056 NUMBER(1,0), 
	CF008_057 NUMBER, 
	CF008_058 NUMBER, 
	CF008_059 VARCHAR2(3), 
	CF008_060 NUMBER, 
	CF008_061 VARCHAR2(3), 
	CF008_062 VARCHAR2(20), 
	CF008_063 NUMBER(1,0), 
	DNK DATE, 
	CF008_065 VARCHAR2(14), 
	CF008_066 VARCHAR2(50), 
	DAT_R DATE, 
	NLS VARCHAR2(15), 
	NMS VARCHAR2(38), 
	REF NUMBER(*,0), 
	REF2 NUMBER(*,0), 
	VID_R CHAR(2), 
	CENA_START NUMBER, 
	IR NUMBER, 
	OST_V NUMBER, 
	FL NUMBER(*,0), 
	USERID NUMBER(*,0), 
	NLS_S VARCHAR2(15), 
	D2 NUMBER, 
	P2 NUMBER, 
	S_D NUMBER, 
	S_C NUMBER, 
	NLS_P VARCHAR2(15), 
	S_DP NUMBER, 
	S_CP NUMBER, 
	OST_I NUMBER, 
	S_DK NUMBER, 
	S_CK NUMBER, 
	OST_P NUMBER, 
	NLS_P1 VARCHAR2(15), 
	DAT_P DATE, 
	S_DP_NEW NUMBER, 
	S_CP_NEW NUMBER, 
	PAP NUMBER(*,0), 
	S_DK_NEW NUMBER, 
	S_CK_NEW NUMBER, 
	OST_PQ NUMBER, 
	OST_VQ NUMBER, 
	S_DQ NUMBER, 
	S_CQ NUMBER, 
	S_DKQ NUMBER, 
	S_CKQ NUMBER, 
	S_DPQ NUMBER, 
	S_CPQ NUMBER, 
	S_DPQ_NEW NUMBER, 
	S_CPQ_NEW NUMBER, 
	S_DKQ_NEW NUMBER, 
	S_CKQ_NEW NUMBER, 
	NBS_NEW NUMBER(4,0), 
	PF_NEW NUMBER(*,0), 
	OST_VT NUMBER, 
	OST_V31 NUMBER, 
	CENA NUMBER, 
	CENA4 NUMBER, 
	N0 NUMBER, 
	D0 NUMBER, 
	P0 NUMBER, 
	R0 NUMBER, 
	S0 NUMBER, 
	D4 NUMBER, 
	P4 NUMBER, 
	R4 NUMBER, 
	S4 NUMBER, 
	Z4 NUMBER, 
	KL0 NUMBER, 
	KL4 NUMBER, 
	DAT_4 DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CP_ZV_OLD ***
 exec bpa.alter_policies('TMP_CP_ZV_OLD');


COMMENT ON TABLE BARS.TMP_CP_ZV_OLD IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NLS_P1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DP_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CP_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.PAP IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DK_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CK_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_PQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_VQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DKQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CKQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DPQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CPQ IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DPQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CPQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DKQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CKQ_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NBS_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.PF_NEW IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_VT IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_V31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.N0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.D0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.P0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.R0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.D4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.R4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.Z4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G045 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G046 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G047 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G048 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G049 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G050 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G051 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G052 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G053 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G054 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G055 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G056 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G057 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G058 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G059 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G060 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G061 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G062 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G063 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G064 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G065 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G066 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G067 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G068 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G069 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G070 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G071 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G072 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G073 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G074 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G075 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G076 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G077 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G078 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G079 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G080 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G081 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G082 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G083 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G084 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G085 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G086 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G087 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G088 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.ID IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.ISIN IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NBS_OLD IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KV IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.REPO IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.D_K IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.PF_OLD IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.EMI IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.AUKCION IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_K IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NM_PROD IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.BV1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA0 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.N1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.R1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.D1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.P1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.Z1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S1 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_019 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.N2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL_K2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA_K2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_023 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_K2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NM_PROD2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.N2_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL2_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_028 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_P2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NM_POK IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA_P2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.R2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.TR1_31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.N31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.R31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.D31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.P31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.Z31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.IR31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_PG IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_042 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_IR IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KOT31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_045 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_KOT IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.SUMB4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NM_POK4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.KL_P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA_P4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.N4 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.BV31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.PV31 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_055 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_056 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_057 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_058 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_059 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_060 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_061 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_062 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_063 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DNK IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_065 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CF008_066 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.DAT_R IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NLS IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NMS IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.REF IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.REF2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.VID_R IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.CENA_START IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.IR IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_V IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.FL IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.USERID IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NLS_S IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.D2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.P2 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_D IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_C IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.NLS_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DP IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CP IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_I IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_DK IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.S_CK IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.OST_P IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G001 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G002 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G003 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G004 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G005 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G006 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G007 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G008 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G009 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G010 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G011 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G012 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G013 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G014 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G015 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G016 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G017 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G018 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G019 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G020 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G021 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G022 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G023 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G024 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G025 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G026 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G027 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G028 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G029 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G030 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G031 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G032 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G033 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G034 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G035 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G036 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G037 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G038 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G039 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G040 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G041 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G042 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G043 IS '';
COMMENT ON COLUMN BARS.TMP_CP_ZV_OLD.G044 IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CP_ZV_OLD.sql =========*** End ***
PROMPT ===================================================================================== 
