

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_PRIOCOM_ACCOUNTS.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_PRIOCOM_ACCOUNTS ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TMP_PRIOCOM_ACCOUNTS'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_PRIOCOM_ACCOUNTS'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''TMP_PRIOCOM_ACCOUNTS'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_PRIOCOM_ACCOUNTS ***
begin 
  execute immediate '
  CREATE GLOBAL TEMPORARY TABLE BARS.TMP_PRIOCOM_ACCOUNTS 
   (	INPUT_ID NUMBER(*,0), 
	MFO VARCHAR2(6), 
	KOD_FIL NUMBER(*,0), 
	OPENDATE DATE, 
	CODE NUMBER(*,0), 
	CL_TYPE NUMBER(*,0), 
	IDCONTRACT NUMBER(*,0), 
	R020 VARCHAR2(4), 
	CURRENCY NUMBER(*,0), 
	S040 DATE, 
	S050 DATE, 
	CREDITSUPPLYCODE VARCHAR2(64), 
	S080 VARCHAR2(1), 
	S180 VARCHAR2(1), 
	S182 VARCHAR2(1), 
	PROCENT NUMBER, 
	KL_KPR NUMBER(*,0), 
	KOD_BIZN NUMBER(*,0), 
	S190 VARCHAR2(1), 
	R011 VARCHAR2(1), 
	R013 VARCHAR2(1), 
	NDOG_Z VARCHAR2(64), 
	CURRENCY_Z NUMBER(*,0), 
	S040_Z DATE, 
	S050_Z DATE, 
	CFPLEDGE VARCHAR2(2), 
	S120 VARCHAR2(1), 
	S181 VARCHAR2(1), 
	NLSSH VARCHAR2(15), 
	OB22 VARCHAR2(2), 
	LSUMM NUMBER, 
	S200 VARCHAR2(1), 
	RESULT NUMBER(*,0), 
	MESSAGE VARCHAR2(4000), 
	ACCOUNT VARCHAR2(14)
   ) ON COMMIT PRESERVE ROWS ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_PRIOCOM_ACCOUNTS ***
 exec bpa.alter_policies('TMP_PRIOCOM_ACCOUNTS');


COMMENT ON TABLE BARS.TMP_PRIOCOM_ACCOUNTS IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.INPUT_ID IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.MFO IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.KOD_FIL IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.OPENDATE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.CODE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.CL_TYPE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.IDCONTRACT IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.R020 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.CURRENCY IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S040 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S050 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.CREDITSUPPLYCODE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S080 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S180 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S182 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.PROCENT IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.KL_KPR IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.KOD_BIZN IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S190 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.R011 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.R013 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.NDOG_Z IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.CURRENCY_Z IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S040_Z IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S050_Z IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.CFPLEDGE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S120 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S181 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.NLSSH IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.OB22 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.LSUMM IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.S200 IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.RESULT IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.MESSAGE IS '';
COMMENT ON COLUMN BARS.TMP_PRIOCOM_ACCOUNTS.ACCOUNT IS '';



PROMPT *** Create  grants  TMP_PRIOCOM_ACCOUNTS ***
grant SELECT                                                                 on TMP_PRIOCOM_ACCOUNTS to BARSREADER_ROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_PRIOCOM_ACCOUNTS to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on TMP_PRIOCOM_ACCOUNTS to START1;
grant SELECT                                                                 on TMP_PRIOCOM_ACCOUNTS to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_PRIOCOM_ACCOUNTS.sql =========*** 
PROMPT ===================================================================================== 
