

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CUSTOMER_REL.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CUSTOMER_REL ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CUSTOMER_REL ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_CUSTOMER_REL 
   (	RNK NUMBER(22,0), 
	REL_ID NUMBER(22,0), 
	REL_RNK NUMBER(22,0), 
	REL_INTEXT NUMBER(1,0), 
	VAGA1 NUMBER(8,4), 
	VAGA2 NUMBER(8,4), 
	TYPE_ID NUMBER(22,0), 
	POSITION VARCHAR2(100), 
	FIRST_NAME VARCHAR2(70), 
	MIDDLE_NAME VARCHAR2(70), 
	LAST_NAME VARCHAR2(70), 
	DOCUMENT_TYPE_ID NUMBER(22,0), 
	DOCUMENT VARCHAR2(70), 
	TRUST_REGNUM VARCHAR2(38), 
	TRUST_REGDAT DATE, 
	BDATE DATE, 
	EDATE DATE, 
	NOTARY_NAME VARCHAR2(70), 
	NOTARY_REGION VARCHAR2(70), 
	SIGN_PRIVS NUMBER(1,0), 
	SIGN_ID NUMBER(22,0), 
	NAME_R VARCHAR2(100), 
	POSITION_R VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CUSTOMER_REL ***
 exec bpa.alter_policies('TMP_CUSTOMER_REL');


COMMENT ON TABLE BARS.TMP_CUSTOMER_REL IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.VAGA1 IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.VAGA2 IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.TYPE_ID IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.POSITION IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.FIRST_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.MIDDLE_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.LAST_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.DOCUMENT_TYPE_ID IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.DOCUMENT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.TRUST_REGNUM IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.TRUST_REGDAT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.BDATE IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.EDATE IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.NOTARY_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.NOTARY_REGION IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.SIGN_PRIVS IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.SIGN_ID IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.NAME_R IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.POSITION_R IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.RNK IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.REL_ID IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.REL_RNK IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_REL.REL_INTEXT IS '';



PROMPT *** Create  grants  TMP_CUSTOMER_REL ***
grant SELECT                                                                 on TMP_CUSTOMER_REL to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CUSTOMER_REL.sql =========*** End 
PROMPT ===================================================================================== 
