

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CUSTOMER_SEGMENT_REPORT.sql ======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CUSTOMER_SEGMENT_REPORT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CUSTOMER_SEGMENT_REPORT ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_CUSTOMER_SEGMENT_REPORT 
   (	RECORD_LEVEL NUMBER(5,0), 
	BRANCH VARCHAR2(30 CHAR), 
	CLIENTS_COUNT NUMBER(10,0), 
	CLIENT_NAME VARCHAR2(300 CHAR), 
	ACTIVITY_SEGMENT NUMBER(5,0), 
	FINANCIAL_SEGMENT NUMBER(5,0), 
	BEHAVIOR_SEGMENT NUMBER(5,0), 
	SOCIAL_VIP_SEGMENT NUMBER(5,0), 
	TRANSACTOR_SUBSEGMENT NUMBER(10,0), 
	GENERAL_PROD_PRESSURE NUMBER(14,4), 
	DEPOSIT_FACTOR NUMBER(10,0), 
	SECURED_LOANS_FACTOR NUMBER(10,0), 
	CARD_LOANS_FACTOR NUMBER(10,0), 
	CARDLESS_LOANS_FACTOR NUMBER(10,0), 
	ENERGY_LOANS_FACTOR NUMBER(10,0), 
	DEBIT_CARDS_FACTOR NUMBER(10,0), 
	CURRENT_ACCOUNTS_FACTOR NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CUSTOMER_SEGMENT_REPORT ***
 exec bpa.alter_policies('TMP_CUSTOMER_SEGMENT_REPORT');


COMMENT ON TABLE BARS.TMP_CUSTOMER_SEGMENT_REPORT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.RECORD_LEVEL IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.CLIENTS_COUNT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.CLIENT_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.ACTIVITY_SEGMENT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.FINANCIAL_SEGMENT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.BEHAVIOR_SEGMENT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.SOCIAL_VIP_SEGMENT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.TRANSACTOR_SUBSEGMENT IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.GENERAL_PROD_PRESSURE IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.DEPOSIT_FACTOR IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.SECURED_LOANS_FACTOR IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.CARD_LOANS_FACTOR IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.CARDLESS_LOANS_FACTOR IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.ENERGY_LOANS_FACTOR IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.DEBIT_CARDS_FACTOR IS '';
COMMENT ON COLUMN BARS.TMP_CUSTOMER_SEGMENT_REPORT.CURRENT_ACCOUNTS_FACTOR IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CUSTOMER_SEGMENT_REPORT.sql ======
PROMPT ===================================================================================== 
