

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_SHOW_BALANCE_DATA.sql =========***
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_SHOW_BALANCE_DATA ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''TMP_SHOW_BALANCE_DATA'', ''CENTER'' , null, ''E'', ''E'', ''E'');
               bpa.alter_policy_info(''TMP_SHOW_BALANCE_DATA'', ''FILIAL'' , ''M'', null, null, null);
               bpa.alter_policy_info(''TMP_SHOW_BALANCE_DATA'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_SHOW_BALANCE_DATA ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_SHOW_BALANCE_DATA 
   (	SHOW_DATE DATE, 
	KF CHAR(6), 
	ROW_TYPE NUMBER(2,0), 
	BRANCH VARCHAR2(30), 
	NBS CHAR(4), 
	KV NUMBER(3,0), 
	DOS NUMBER(24,0), 
	DOSQ NUMBER(24,0), 
	KOS NUMBER(24,0), 
	KOSQ NUMBER(24,0), 
	OSTD NUMBER(24,0), 
	OSTDQ NUMBER(24,0), 
	OSTK NUMBER(24,0), 
	OSTKQ NUMBER(24,0), 
	KF_NAME VARCHAR2(200)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSBIGD 
  PARTITION BY RANGE (SHOW_DATE) INTERVAL (NUMTODSINTERVAL(1,''DAY'')) 
  SUBPARTITION BY LIST (KF) 
  SUBPARTITION TEMPLATE ( 
    SUBPARTITION SP_300465 VALUES ( ''300465'' ), 
    SUBPARTITION SP_302076 VALUES ( ''302076'' ), 
    SUBPARTITION SP_303398 VALUES ( ''303398'' ), 
    SUBPARTITION SP_304665 VALUES ( ''304665'' ), 
    SUBPARTITION SP_305482 VALUES ( ''305482'' ), 
    SUBPARTITION SP_311647 VALUES ( ''311647'' ), 
    SUBPARTITION SP_312356 VALUES ( ''312356'' ), 
    SUBPARTITION SP_313957 VALUES ( ''313957'' ), 
    SUBPARTITION SP_315784 VALUES ( ''315784'' ), 
    SUBPARTITION SP_322669 VALUES ( ''322669'' ), 
    SUBPARTITION SP_323475 VALUES ( ''323475'' ), 
    SUBPARTITION SP_324805 VALUES ( ''324805'' ), 
    SUBPARTITION SP_325796 VALUES ( ''325796'' ), 
    SUBPARTITION SP_326461 VALUES ( ''326461'' ), 
    SUBPARTITION SP_328845 VALUES ( ''328845'' ), 
    SUBPARTITION SP_331467 VALUES ( ''331467'' ), 
    SUBPARTITION SP_333368 VALUES ( ''333368'' ), 
    SUBPARTITION SP_335106 VALUES ( ''335106'' ), 
    SUBPARTITION SP_336503 VALUES ( ''336503'' ), 
    SUBPARTITION SP_337568 VALUES ( ''337568'' ), 
    SUBPARTITION SP_338545 VALUES ( ''338545'' ), 
    SUBPARTITION SP_351823 VALUES ( ''351823'' ), 
    SUBPARTITION SP_352457 VALUES ( ''352457'' ), 
    SUBPARTITION SP_353553 VALUES ( ''353553'' ), 
    SUBPARTITION SP_354507 VALUES ( ''354507'' ), 
    SUBPARTITION SP_356334 VALUES ( ''356334'' ), 
    SUBPARTITION SP_OTHERS VALUES ( DEFAULT ) ) 
 (PARTITION P_MINVALUE  VALUES LESS THAN (TO_DATE('' 2015-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSBIGD ) 
  PARALLEL ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_SHOW_BALANCE_DATA ***
 exec bpa.alter_policies('TMP_SHOW_BALANCE_DATA');


COMMENT ON TABLE BARS.TMP_SHOW_BALANCE_DATA IS 'временная по назначению таблица для сборки данных для отображения баланса для таб. формы в WEB';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.SHOW_DATE IS 'Дата балансу';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.KF IS 'Код філіалу (МФО)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.ROW_TYPE IS 'Ід. типу розрізу даних';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.BRANCH IS 'Код відділення (ТВБВ)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.NBS IS 'Нобер балансового рахунка (R020)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.KV IS 'Код валюти (R030)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.DOS IS 'Дт. обороти (номінал)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.DOSQ IS 'Дт. обороти (еквівалент)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.KOS IS 'Кт. обороти (номінал)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.KOSQ IS 'Кт. обороти (еквівалент)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.OSTD IS 'Дт. залишок (номінал)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.OSTDQ IS 'Дт. залишок (еквівалент)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.OSTK IS 'Кт. залишок (номінал)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.OSTKQ IS 'Кт. залишок (еквівалент)';
COMMENT ON COLUMN BARS.TMP_SHOW_BALANCE_DATA.KF_NAME IS 'Назва філіалу';




PROMPT *** Create  constraint SYS_C0030846 ***
begin   
 execute immediate '
  ALTER TABLE BARS.TMP_SHOW_BALANCE_DATA MODIFY (SHOW_DATE NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C0030848 ***
begin   
 execute immediate '
  ALTER TABLE BARS.TMP_SHOW_BALANCE_DATA MODIFY (ROW_TYPE NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint SYS_C0030847 ***
begin   
 execute immediate '
  ALTER TABLE BARS.TMP_SHOW_BALANCE_DATA MODIFY (KF NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index IDX_TMP_SHOW_BALANCE_DATA ***
begin   
 execute immediate '
  CREATE INDEX BARS.IDX_TMP_SHOW_BALANCE_DATA ON BARS.TMP_SHOW_BALANCE_DATA (SHOW_DATE, ROW_TYPE, KF, BRANCH, KV, NBS) 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSACCM  LOCAL
 (PARTITION P_MINVALUE 
PCTFREE 0 INITRANS 2 MAXTRANS 255 
  TABLESPACE BRSACCM 
 ( SUBPARTITION P_MINVALUE_SP_300465 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_302076 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_303398 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_304665 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_305482 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_311647 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_312356 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_313957 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_315784 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_322669 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_323475 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_324805 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_325796 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_326461 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_328845 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_331467 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_333368 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_335106 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_336503 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_337568 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_338545 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_351823 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_352457 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_353553 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_354507 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_356334 
  TABLESPACE BRSACCM , 
  SUBPARTITION P_MINVALUE_SP_OTHERS 
  TABLESPACE BRSACCM ) ) COMPRESS 3 ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  TMP_SHOW_BALANCE_DATA ***
grant SELECT                                                                 on TMP_SHOW_BALANCE_DATA to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on TMP_SHOW_BALANCE_DATA to BARS_DM;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_SHOW_BALANCE_DATA.sql =========***
PROMPT ===================================================================================== 
