

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_NBU23_REZ_03.sql =========*** Run 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_NBU23_REZ_03 ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_NBU23_REZ_03 ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_NBU23_REZ_03 
   (	FDAT DATE, 
	ID VARCHAR2(50), 
	RNK NUMBER, 
	NBS CHAR(4), 
	KV NUMBER, 
	ND NUMBER, 
	CC_ID VARCHAR2(50), 
	ACC NUMBER, 
	NLS VARCHAR2(20), 
	BRANCH VARCHAR2(30), 
	FIN NUMBER, 
	OBS NUMBER, 
	KAT NUMBER, 
	K NUMBER, 
	IRR NUMBER, 
	ZAL NUMBER, 
	BV NUMBER, 
	PV NUMBER, 
	REZ NUMBER, 
	REZQ NUMBER, 
	DD CHAR(1), 
	DDD CHAR(3), 
	BVQ NUMBER, 
	CUSTTYPE NUMBER, 
	IDR NUMBER, 
	WDATE DATE, 
	OKPO NUMBER, 
	NMK VARCHAR2(35), 
	RZ NUMBER, 
	PAWN NUMBER, 
	ISTVAL NUMBER, 
	R013 CHAR(1), 
	REZN NUMBER, 
	REZNQ NUMBER, 
	ARJK NUMBER, 
	PVZ NUMBER, 
	PVZQ NUMBER, 
	ZALQ NUMBER, 
	ZPR NUMBER, 
	ZPRQ NUMBER, 
	PVQ NUMBER, 
	RU VARCHAR2(70), 
	INN VARCHAR2(20), 
	NRC VARCHAR2(70), 
	SDATE DATE, 
	IR NUMBER, 
	S031 VARCHAR2(2), 
	K040 VARCHAR2(3), 
	PROD VARCHAR2(50), 
	K110 VARCHAR2(5), 
	K070 VARCHAR2(5), 
	K051 VARCHAR2(2), 
	S260 VARCHAR2(2), 
	R011 VARCHAR2(1), 
	R012 VARCHAR2(1), 
	S240 VARCHAR2(1), 
	S180 VARCHAR2(1), 
	S580 VARCHAR2(1), 
	NLS_REZ VARCHAR2(15), 
	NLS_REZN VARCHAR2(15), 
	S250 CHAR(1), 
	ACC_REZ NUMBER, 
	FIN_R NUMBER(*,0), 
	DISKONT NUMBER, 
	ISP NUMBER(*,0), 
	OB22 CHAR(2), 
	TIP CHAR(3), 
	SPEC CHAR(1), 
	ZAL_BL NUMBER, 
	S280_290 CHAR(1), 
	ZAL_BLQ NUMBER, 
	REZD NUMBER, 
	ACC_REZN NUMBER, 
	OB22_REZ CHAR(2), 
	OB22_REZN CHAR(2), 
	IR0 NUMBER, 
	IRR0 NUMBER, 
	ND_CP VARCHAR2(40), 
	SUM_IMP NUMBER, 
	SUMQ_IMP NUMBER, 
	PV_ZAL NUMBER, 
	VKR VARCHAR2(10), 
	S_L NUMBER, 
	SQ_L NUMBER, 
	ZAL_SV NUMBER, 
	ZAL_SVQ NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_NBU23_REZ_03 ***
 exec bpa.alter_policies('TMP_NBU23_REZ_03');


COMMENT ON TABLE BARS.TMP_NBU23_REZ_03 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.FDAT IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ID IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.RNK IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.NBS IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.KV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ND IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.CC_ID IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ACC IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.NLS IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.FIN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.OBS IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.KAT IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.K IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.IRR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZAL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.BV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.REZQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.DD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.DDD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.BVQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.CUSTTYPE IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.IDR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.WDATE IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.OKPO IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.NMK IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.RZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PAWN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ISTVAL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.R013 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.REZNQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ARJK IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PVZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PVZQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZALQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZPR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZPRQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PVQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.RU IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.INN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.NRC IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.SDATE IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.IR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S031 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.K040 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PROD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.K110 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.K070 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.K051 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S260 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.R011 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.R012 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S240 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S180 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S580 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.NLS_REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.NLS_REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S250 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ACC_REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.FIN_R IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.DISKONT IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ISP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.OB22 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.TIP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.SPEC IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZAL_BL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S280_290 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZAL_BLQ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.REZD IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ACC_REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.OB22_REZ IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.OB22_REZN IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.IR0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.IRR0 IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ND_CP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.SUM_IMP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.SUMQ_IMP IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.PV_ZAL IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.VKR IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.S_L IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.SQ_L IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZAL_SV IS '';
COMMENT ON COLUMN BARS.TMP_NBU23_REZ_03.ZAL_SVQ IS '';



PROMPT *** Create  grants  TMP_NBU23_REZ_03 ***
grant SELECT                                                                 on TMP_NBU23_REZ_03 to BARSREADER_ROLE;
grant SELECT                                                                 on TMP_NBU23_REZ_03 to BARS_DM;
grant SELECT                                                                 on TMP_NBU23_REZ_03 to UPLD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_NBU23_REZ_03.sql =========*** End 
PROMPT ===================================================================================== 
