

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/WCS_ANSWERS.sql =========*** Run *** =
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to WCS_ANSWERS ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''WCS_ANSWERS'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_ANSWERS'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_ANSWERS'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table WCS_ANSWERS ***
begin 
  execute immediate '
  CREATE TABLE BARS.WCS_ANSWERS 
   (	BID_ID NUMBER, 
	WS_ID VARCHAR2(100) DEFAULT ''MAIN'', 
	WS_NUMBER NUMBER DEFAULT 0, 
	QUESTION_ID VARCHAR2(100), 
	VAL_TEXT VARCHAR2(4000), 
	VAL_NUMB NUMBER, 
	VAL_DECIMAL NUMBER, 
	VAL_DATE DATE, 
	VAL_LIST NUMBER, 
	VAL_REFER VARCHAR2(4000), 
	VAL_FILE BLOB, 
	VAL_FILE_NAME VARCHAR2(255), 
	VAL_MATRIX NUMBER, 
	VAL_BOOL NUMBER(1,0), 
	VAL_XML CLOB, 
	LAST_DATE DATE, 
	 CONSTRAINT FK_ANSWERS_BID_BIDS_ID FOREIGN KEY (BID_ID)
	  REFERENCES BARS.WCS_BIDS (ID) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE WCSANSWERS_FILE(
  ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
  PARTITION BY REFERENCE (FK_ANSWERS_BID_BIDS_ID) 
 (PARTITION WCSBIDS_Y2011_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2011_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2011_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2011_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2012_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2012_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2012_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2012_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2013_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2013_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2013_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2013_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2015_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2015_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2015_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2015_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2016_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2016_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2016_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2016_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2017_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2017_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2017_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2017_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2018_Q1 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2018_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2018_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) , 
 PARTITION WCSBIDS_Y2018_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSLOBD 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING ) 
 LOB (VAL_XML) STORE AS BASICFILE (
  TABLESPACE BRSLOBD ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to WCS_ANSWERS ***
 exec bpa.alter_policies('WCS_ANSWERS');


COMMENT ON TABLE BARS.WCS_ANSWERS IS 'Ответы';
COMMENT ON COLUMN BARS.WCS_ANSWERS.BID_ID IS 'Идентификатор заявки';
COMMENT ON COLUMN BARS.WCS_ANSWERS.WS_ID IS 'Идентификатор рабочего пространства';
COMMENT ON COLUMN BARS.WCS_ANSWERS.WS_NUMBER IS 'Номер рабочего пространства';
COMMENT ON COLUMN BARS.WCS_ANSWERS.QUESTION_ID IS 'Идентификатор вопроса';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_TEXT IS 'Текстовый';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_NUMB IS 'Целочисленный';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_DECIMAL IS 'Дробное число';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_DATE IS 'Дата';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_LIST IS 'Список';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_REFER IS 'Справочник';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_FILE IS 'Файл';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_FILE_NAME IS 'Имя файла';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_MATRIX IS 'Матрица';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_BOOL IS 'Булевый';
COMMENT ON COLUMN BARS.WCS_ANSWERS.VAL_XML IS 'Xml';
COMMENT ON COLUMN BARS.WCS_ANSWERS.LAST_DATE IS 'Дата последнего изменения (используется при захвате изменений)';




PROMPT *** Create  constraint CC_WCSANSWERS_BIDID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS MODIFY (BID_ID CONSTRAINT CC_WCSANSWERS_BIDID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERS_WSID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS MODIFY (WS_ID CONSTRAINT CC_WCSANSWERS_WSID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERS_WSNUMBER_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS MODIFY (WS_NUMBER CONSTRAINT CC_WCSANSWERS_WSNUMBER_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERS_VALBOOL ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS ADD CONSTRAINT CC_WCSANSWERS_VALBOOL CHECK (val_bool in (0, 1) or val_bool is null) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_WCSANSWERS ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS ADD CONSTRAINT PK_WCSANSWERS PRIMARY KEY (BID_ID, WS_ID, WS_NUMBER, QUESTION_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_WCSANSWERS ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_WCSANSWERS ON BARS.WCS_ANSWERS (BID_ID, WS_ID, WS_NUMBER, QUESTION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_WCSANSWERS_LDATE ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_WCSANSWERS_LDATE ON BARS.WCS_ANSWERS (LAST_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  WCS_ANSWERS ***
grant SELECT                                                                 on WCS_ANSWERS     to BARSREADER_ROLE;
grant SELECT                                                                 on WCS_ANSWERS     to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on WCS_ANSWERS     to UPLD;
grant SELECT                                                                 on WCS_ANSWERS     to WCS_SYNC_USER;



PROMPT *** Create SYNONYM  to WCS_ANSWERS ***

  CREATE OR REPLACE PUBLIC SYNONYM WCS_ANSWERS FOR BARS.WCS_ANSWERS;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/WCS_ANSWERS.sql =========*** End *** =
PROMPT ===================================================================================== 
