

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/WCS_ANSWERS_HISTORY.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to WCS_ANSWERS_HISTORY ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''WCS_ANSWERS_HISTORY'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_ANSWERS_HISTORY'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_ANSWERS_HISTORY'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table WCS_ANSWERS_HISTORY ***
begin 
  execute immediate '
  CREATE TABLE BARS.WCS_ANSWERS_HISTORY 
   (	ID NUMBER, 
	BID_ID NUMBER, 
	WS_ID VARCHAR2(100) DEFAULT ''MAIN'', 
	WS_NUMBER NUMBER DEFAULT 0, 
	QUESTION_ID VARCHAR2(100), 
	VAL_OLD VARCHAR2(4000), 
	VAL_NEW VARCHAR2(4000), 
	ACTION_TYPE_ID VARCHAR2(100), 
	ACTION_DATE DATE, 
	ACTION_USER NUMBER, 
	 CONSTRAINT FK_ANSWERSHIST_BID_BIDS_ID FOREIGN KEY (BID_ID)
	  REFERENCES BARS.WCS_BIDS (ID) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  PARTITION BY REFERENCE (FK_ANSWERSHIST_BID_BIDS_ID) 
 (PARTITION WCSBIDS_Y2011_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q3 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q1 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q2 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q4 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q1 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q2 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q3 SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q4 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to WCS_ANSWERS_HISTORY ***
 exec bpa.alter_policies('WCS_ANSWERS_HISTORY');


COMMENT ON TABLE BARS.WCS_ANSWERS_HISTORY IS 'История изменения ответов';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.ID IS 'Идентификатор записи';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.BID_ID IS 'Идентификатор заявки';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.WS_ID IS 'Идентификатор рабочего пространства';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.WS_NUMBER IS 'Номер рабочего пространства';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.QUESTION_ID IS 'Идентификатор вопроса';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.VAL_OLD IS 'Старое значение';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.VAL_NEW IS 'Новое значение';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.ACTION_TYPE_ID IS 'Идентификатор типа изменения';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.ACTION_DATE IS 'Дата изменения';
COMMENT ON COLUMN BARS.WCS_ANSWERS_HISTORY.ACTION_USER IS 'Пользователь изменения';




PROMPT *** Create  constraint CC_WCSANSWERSHIST_WSNUMBER_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (WS_NUMBER CONSTRAINT CC_WCSANSWERSHIST_WSNUMBER_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERSHIST_WSID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (WS_ID CONSTRAINT CC_WCSANSWERSHIST_WSID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERSHIST_BIDID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (BID_ID CONSTRAINT CC_WCSANSWERSHIST_BIDID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERSHIST_QID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (QUESTION_ID CONSTRAINT CC_WCSANSWERSHIST_QID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_WCSANSWERSHIST ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY ADD CONSTRAINT PK_WCSANSWERSHIST PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERSHIST_ADATE_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (ACTION_DATE CONSTRAINT CC_WCSANSWERSHIST_ADATE_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERSHIST_AUSER_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (ACTION_USER CONSTRAINT CC_WCSANSWERSHIST_AUSER_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_ANSWERSHIST_BID_BIDS_ID ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY ADD CONSTRAINT FK_ANSWERSHIST_BID_BIDS_ID FOREIGN KEY (BID_ID)
	  REFERENCES BARS.WCS_BIDS (ID) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSANSWERSHIST_ATYPEID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_ANSWERS_HISTORY MODIFY (ACTION_TYPE_ID CONSTRAINT CC_WCSANSWERSHIST_ATYPEID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index I_ANSWERSHIST ***
begin   
 execute immediate '
  CREATE INDEX BARS.I_ANSWERSHIST ON BARS.WCS_ANSWERS_HISTORY (BID_ID, WS_ID, WS_NUMBER, QUESTION_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_WCSANSWERSHIST ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_WCSANSWERSHIST ON BARS.WCS_ANSWERS_HISTORY (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  WCS_ANSWERS_HISTORY ***
grant DELETE,INSERT,SELECT,UPDATE                                            on WCS_ANSWERS_HISTORY to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on WCS_ANSWERS_HISTORY to START1;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/WCS_ANSWERS_HISTORY.sql =========*** E
PROMPT ===================================================================================== 
