

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/WCS_BIDS.sql =========*** Run *** ====
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to WCS_BIDS ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''WCS_BIDS'', ''CENTER'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_BIDS'', ''FILIAL'' , null, null, null, null);
               bpa.alter_policy_info(''WCS_BIDS'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table WCS_BIDS ***
begin 
  execute immediate '
  CREATE TABLE BARS.WCS_BIDS 
   (	ID NUMBER, 
	SUBPRODUCT_ID VARCHAR2(100), 
	CRT_DATE DATE DEFAULT sysdate, 
	INN VARCHAR2(10), 
	RNK NUMBER, 
	MGR_ID NUMBER, 
	BRANCH VARCHAR2(30), 
	LAST_DATE DATE, 
	 CONSTRAINT PK_WCSBIDS PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE BRSBIGD 
  PARTITION BY RANGE (CRT_DATE) 
 (PARTITION WCSBIDS_Y2011_Q1  VALUES LESS THAN (TO_DATE('' 2011-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q2  VALUES LESS THAN (TO_DATE('' 2011-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q3  VALUES LESS THAN (TO_DATE('' 2011-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2011_Q4  VALUES LESS THAN (TO_DATE('' 2012-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q1  VALUES LESS THAN (TO_DATE('' 2012-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q2  VALUES LESS THAN (TO_DATE('' 2012-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q3  VALUES LESS THAN (TO_DATE('' 2012-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2012_Q4  VALUES LESS THAN (TO_DATE('' 2013-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q1  VALUES LESS THAN (TO_DATE('' 2013-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q2  VALUES LESS THAN (TO_DATE('' 2013-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q3  VALUES LESS THAN (TO_DATE('' 2013-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2013_Q4  VALUES LESS THAN (TO_DATE('' 2014-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q1  VALUES LESS THAN (TO_DATE('' 2015-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q2  VALUES LESS THAN (TO_DATE('' 2015-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q3  VALUES LESS THAN (TO_DATE('' 2015-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2015_Q4  VALUES LESS THAN (TO_DATE('' 2016-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q1  VALUES LESS THAN (TO_DATE('' 2016-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q2  VALUES LESS THAN (TO_DATE('' 2016-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q3  VALUES LESS THAN (TO_DATE('' 2016-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD , 
 PARTITION WCSBIDS_Y2016_Q4  VALUES LESS THAN (TO_DATE('' 2017-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSBIGD ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to WCS_BIDS ***
 exec bpa.alter_policies('WCS_BIDS');


COMMENT ON TABLE BARS.WCS_BIDS IS 'Заявки';
COMMENT ON COLUMN BARS.WCS_BIDS.ID IS 'Идентификатор';
COMMENT ON COLUMN BARS.WCS_BIDS.SUBPRODUCT_ID IS 'Идентификатор субпродукта';
COMMENT ON COLUMN BARS.WCS_BIDS.CRT_DATE IS 'Дата создания заявки';
COMMENT ON COLUMN BARS.WCS_BIDS.INN IS 'ИНН клиента';
COMMENT ON COLUMN BARS.WCS_BIDS.RNK IS 'РНК клиента';
COMMENT ON COLUMN BARS.WCS_BIDS.MGR_ID IS 'Ид менеджера заявки';
COMMENT ON COLUMN BARS.WCS_BIDS.BRANCH IS 'Код отделения заявки';
COMMENT ON COLUMN BARS.WCS_BIDS.LAST_DATE IS 'Дата последнего изменения (используется при захвате изменений)';




PROMPT *** Create  constraint FK_BIDS_SBPID_SBPS_ID ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS ADD CONSTRAINT FK_BIDS_SBPID_SBPS_ID FOREIGN KEY (SUBPRODUCT_ID)
	  REFERENCES BARS.WCS_SUBPRODUCTS (ID) ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_BIDS_MGRID_STAFF_ID ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS ADD CONSTRAINT FK_BIDS_MGRID_STAFF_ID FOREIGN KEY (MGR_ID)
	  REFERENCES BARS.STAFF$BASE (ID) ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_BIDS_B_BRANCH_B ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS ADD CONSTRAINT FK_BIDS_B_BRANCH_B FOREIGN KEY (BRANCH)
	  REFERENCES BARS.BRANCH (BRANCH) ENABLE NOVALIDATE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSBIDS_NAME_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS MODIFY (SUBPRODUCT_ID CONSTRAINT CC_WCSBIDS_NAME_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSBIDS_CRTDATE_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS MODIFY (CRT_DATE CONSTRAINT CC_WCSBIDS_CRTDATE_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSBIDS_MGRID_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS MODIFY (MGR_ID CONSTRAINT CC_WCSBIDS_MGRID_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_WCSBIDS_BRANCH_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS MODIFY (BRANCH CONSTRAINT CC_WCSBIDS_BRANCH_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_WCSBIDS ***
begin   
 execute immediate '
  ALTER TABLE BARS.WCS_BIDS ADD CONSTRAINT PK_WCSBIDS PRIMARY KEY (ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_WCSBIDS ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_WCSBIDS ON BARS.WCS_BIDS (ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_WCSBIDS_LDATE ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_WCSBIDS_LDATE ON BARS.WCS_BIDS (LAST_DATE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSBIGI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  WCS_BIDS ***
grant SELECT                                                                 on WCS_BIDS        to BARS_ACCESS_DEFROLE;
grant SELECT                                                                 on WCS_BIDS        to WCS_SYNC_USER;



PROMPT *** Create SYNONYM  to WCS_BIDS ***

  CREATE OR REPLACE PUBLIC SYNONYM WCS_BIDS FOR BARS.WCS_BIDS;


PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/WCS_BIDS.sql =========*** End *** ====
PROMPT ===================================================================================== 
