/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public sealed class VWcsScoringQsBoolRecord : BbRecord
    {
        public VWcsScoringQsBoolRecord(): base()
        {
            fillFields();
        }
        public VWcsScoringQsBoolRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VWcsScoringQsBoolRecord(BbDataSource Parent, OracleDecimal RowScn, String SCORING_ID, String QUESTION_ID, Decimal? SCORE_IF_0, Decimal? SCORE_IF_1)
            : this(Parent)
        {
            this.SCORING_ID = SCORING_ID;
            this.QUESTION_ID = QUESTION_ID;
            this.SCORE_IF_0 = SCORE_IF_0;
            this.SCORE_IF_1 = SCORE_IF_1;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("SCORING_ID", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_SCORING_QS_BOOL", ObjectTypes.View, "Вопрос карты скоринга (бальность по вопросам типа BOOL) (Представление)", "Идентификатор карты скоринга"));
            Fields.Add( new BbField("QUESTION_ID", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_SCORING_QS_BOOL", ObjectTypes.View, "Вопрос карты скоринга (бальность по вопросам типа BOOL) (Представление)", "Идентификатор вопроса"));
            Fields.Add( new BbField("SCORE_IF_0", OracleDbType.Decimal, false, false, false, false, false, "V_WCS_SCORING_QS_BOOL", ObjectTypes.View, "Вопрос карты скоринга (бальность по вопросам типа BOOL) (Представление)", "Баллы за ответ нет (0)"));
            Fields.Add( new BbField("SCORE_IF_1", OracleDbType.Decimal, false, false, false, false, false, "V_WCS_SCORING_QS_BOOL", ObjectTypes.View, "Вопрос карты скоринга (бальность по вопросам типа BOOL) (Представление)", "Баллы за ответ да (1)"));        
        }
        public String SCORING_ID { get { return (String)FindField("SCORING_ID").Value; } set {SetField("SCORING_ID", value);} }
        public String QUESTION_ID { get { return (String)FindField("QUESTION_ID").Value; } set {SetField("QUESTION_ID", value);} }
        public Decimal? SCORE_IF_0 { get { return (Decimal?)FindField("SCORE_IF_0").Value; } set {SetField("SCORE_IF_0", value);} }
        public Decimal? SCORE_IF_1 { get { return (Decimal?)FindField("SCORE_IF_1").Value; } set {SetField("SCORE_IF_1", value);} }
    }

    public sealed class VWcsScoringQsBoolFilters : BbFilters
    {
        public VWcsScoringQsBoolFilters(BbDataSource Parent) : base (Parent)
        {
            SCORING_ID = new BBVarchar2Filter(this, "SCORING_ID");
            QUESTION_ID = new BBVarchar2Filter(this, "QUESTION_ID");
            SCORE_IF_0 = new BBDecimalFilter(this, "SCORE_IF_0");
            SCORE_IF_1 = new BBDecimalFilter(this, "SCORE_IF_1");
        }
        public BBVarchar2Filter SCORING_ID;
        public BBVarchar2Filter QUESTION_ID;
        public BBDecimalFilter SCORE_IF_0;
        public BBDecimalFilter SCORE_IF_1;
    }

    public partial class VWcsScoringQsBool : BbTable<VWcsScoringQsBoolRecord, VWcsScoringQsBoolFilters>
    {
        public VWcsScoringQsBool() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VWcsScoringQsBool(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VWcsScoringQsBoolRecord> Select(VWcsScoringQsBoolRecord Item)
        {
            List<VWcsScoringQsBoolRecord> res = new List<VWcsScoringQsBoolRecord>();
                        OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VWcsScoringQsBoolRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (String)null : Convert.ToString(rdr[1]), 
                        rdr.IsDBNull(2) ?  (String)null : Convert.ToString(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]), 
                        rdr.IsDBNull(4) ?  (Decimal?)null : Convert.ToDecimal(rdr[4]))
                    );
                }
            }
                        finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}