//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Areas.AccountRestore.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccountRestoreModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AccountRestoreModel object using the connection string found in the 'AccountRestoreModel' section of the application configuration file.
        /// </summary>
        public AccountRestoreModel() : base("name=AccountRestoreModel", "AccountRestoreModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountRestoreModel object.
        /// </summary>
        public AccountRestoreModel(string connectionString) : base(connectionString, "AccountRestoreModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountRestoreModel object.
        /// </summary>
        public AccountRestoreModel(EntityConnection connection) : base(connection, "AccountRestoreModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

    
}
