
<input runat="server" type="hidden" id="Mes36" value='<%$ Resources:Deposit.GlobalResources, Mes36%>'/><!--"Не выбран клиент!" />-->
<input runat="server" type="hidden" id="Mes37" value='<%$ Resources:Deposit.GlobalResources, Mes37%>'/><!--"Данный клиент открыт!" />-->
<input runat="server" type="hidden" id="Mes38" value='<%$ Resources:Deposit.GlobalResources, Mes38%>'/><!--"Перерегистрировать клиента?" />-->
<input runat="server" type="hidden" id="Mes39" value='<%$ Resources:Deposit.GlobalResources, Mes39%>'/><!--"Данный клиент закрыт!" />-->
<input runat="server" type="hidden" id="Mes40" value='<%$ Resources:Deposit.GlobalResources, Mes40%>'/><!--"Для заведения депозита перерегистрируйте клиента." />-->
<input runat="server" type="hidden" id="Mes41" value='<%$ Resources:Deposit.GlobalResources, Mes41%>'/><!--"Не выбран депозит!" />-->

