/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.Ins
{
    public sealed class VInsPartnerTypeScansAdmRecord : BbRecord
    {
        public VInsPartnerTypeScansAdmRecord(): base()
        {
            fillFields();
        }
        public VInsPartnerTypeScansAdmRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VInsPartnerTypeScansAdmRecord(BbDataSource Parent, OracleDecimal RowScn, Decimal? ID, Decimal? PARTNER_ID, String PARTNER_NAME, Decimal? TYPE_ID, String TYPE_NAME, String SCAN_ID, String SCAN_NAME, Decimal? IS_REQUIRED)
            : this(Parent)
        {
            this.ID = ID;
            this.PARTNER_ID = PARTNER_ID;
            this.PARTNER_NAME = PARTNER_NAME;
            this.TYPE_ID = TYPE_ID;
            this.TYPE_NAME = TYPE_NAME;
            this.SCAN_ID = SCAN_ID;
            this.SCAN_NAME = SCAN_NAME;
            this.IS_REQUIRED = IS_REQUIRED;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("ID", OracleDbType.Decimal, false, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Ідентифікатор"));
            Fields.Add( new BbField("PARTNER_ID", OracleDbType.Decimal, true, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Ід. СК"));
            Fields.Add( new BbField("PARTNER_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Найм. СК"));
            Fields.Add( new BbField("TYPE_ID", OracleDbType.Decimal, true, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Ід. типу"));
            Fields.Add( new BbField("TYPE_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Найм. типу"));
            Fields.Add( new BbField("SCAN_ID", OracleDbType.Varchar2, false, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Ід. сканкопії"));
            Fields.Add( new BbField("SCAN_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Найм. сканкопії"));
            Fields.Add( new BbField("IS_REQUIRED", OracleDbType.Decimal, false, false, false, false, false, "V_INS_PARTNER_TYPE_SCANS_ADM", ObjectTypes.View, "Сканкопії СК та типів СД (Адміністрування)", "Обов`язковий"));        
        }
        public Decimal? ID { get { return (Decimal?)FindField("ID").Value; } set {SetField("ID", value);} }
        public Decimal? PARTNER_ID { get { return (Decimal?)FindField("PARTNER_ID").Value; } set {SetField("PARTNER_ID", value);} }
        public String PARTNER_NAME { get { return (String)FindField("PARTNER_NAME").Value; } set {SetField("PARTNER_NAME", value);} }
        public Decimal? TYPE_ID { get { return (Decimal?)FindField("TYPE_ID").Value; } set {SetField("TYPE_ID", value);} }
        public String TYPE_NAME { get { return (String)FindField("TYPE_NAME").Value; } set {SetField("TYPE_NAME", value);} }
        public String SCAN_ID { get { return (String)FindField("SCAN_ID").Value; } set {SetField("SCAN_ID", value);} }
        public String SCAN_NAME { get { return (String)FindField("SCAN_NAME").Value; } set {SetField("SCAN_NAME", value);} }
        public Decimal? IS_REQUIRED { get { return (Decimal?)FindField("IS_REQUIRED").Value; } set {SetField("IS_REQUIRED", value);} }
    }

    public sealed class VInsPartnerTypeScansAdmFilters : BbFilters
    {
        public VInsPartnerTypeScansAdmFilters(BbDataSource Parent) : base (Parent)
        {
            ID = new BBDecimalFilter(this, "ID");
            PARTNER_ID = new BBDecimalFilter(this, "PARTNER_ID");
            PARTNER_NAME = new BBVarchar2Filter(this, "PARTNER_NAME");
            TYPE_ID = new BBDecimalFilter(this, "TYPE_ID");
            TYPE_NAME = new BBVarchar2Filter(this, "TYPE_NAME");
            SCAN_ID = new BBVarchar2Filter(this, "SCAN_ID");
            SCAN_NAME = new BBVarchar2Filter(this, "SCAN_NAME");
            IS_REQUIRED = new BBDecimalFilter(this, "IS_REQUIRED");
        }
        public BBDecimalFilter ID;
        public BBDecimalFilter PARTNER_ID;
        public BBVarchar2Filter PARTNER_NAME;
        public BBDecimalFilter TYPE_ID;
        public BBVarchar2Filter TYPE_NAME;
        public BBVarchar2Filter SCAN_ID;
        public BBVarchar2Filter SCAN_NAME;
        public BBDecimalFilter IS_REQUIRED;
    }

    public partial class VInsPartnerTypeScansAdm : BbTable<VInsPartnerTypeScansAdmRecord, VInsPartnerTypeScansAdmFilters>
    {
        public VInsPartnerTypeScansAdm() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VInsPartnerTypeScansAdm(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VInsPartnerTypeScansAdmRecord> Select(VInsPartnerTypeScansAdmRecord Item)
        {
            List<VInsPartnerTypeScansAdmRecord> res = new List<VInsPartnerTypeScansAdmRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VInsPartnerTypeScansAdmRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (Decimal?)null : Convert.ToDecimal(rdr[1]), 
                        rdr.IsDBNull(2) ?  (Decimal?)null : Convert.ToDecimal(rdr[2]), 
                        rdr.IsDBNull(3) ?  (String)null : Convert.ToString(rdr[3]), 
                        rdr.IsDBNull(4) ?  (Decimal?)null : Convert.ToDecimal(rdr[4]), 
                        rdr.IsDBNull(5) ?  (String)null : Convert.ToString(rdr[5]), 
                        rdr.IsDBNull(6) ?  (String)null : Convert.ToString(rdr[6]), 
                        rdr.IsDBNull(7) ?  (String)null : Convert.ToString(rdr[7]), 
                        rdr.IsDBNull(8) ?  (Decimal?)null : Convert.ToDecimal(rdr[8]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}