/*
    AUTOGENERATED! Do not modify this code. 
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.UI.WebControls;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;

namespace ibank.objlayer
{
    public sealed class VDpztjobJobsRecord : BbRecord
    {
        public VDpztjobJobsRecord(BbDataSource Parent) : base (Parent)
        {
            Fields.Add( new BbField("JOB_CODE", OracleDbType.Varchar2, false, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Код завдання"));
            Fields.Add( new BbField("JOB_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Найменування завдання"));
            Fields.Add( new BbField("JOB_ACTIVITY", OracleDbType.Char, false, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Ознака активності"));
            Fields.Add( new BbField("JOB_INTERVAL", OracleDbType.Decimal, true, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Інтервал завдання"));
            Fields.Add( new BbField("JOB_BEGDATE", OracleDbType.Date, true, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Дата початку роботи"));
            Fields.Add( new BbField("JOB_ENDDATE", OracleDbType.Date, true, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Дата завершення роботи"));
            Fields.Add( new BbField("JOB_FAILED", OracleDbType.Decimal, false, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Кільк. помилок"));
            Fields.Add( new BbField("JOB_STATE", OracleDbType.Varchar2, true, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Поточний стан"));
            Fields.Add( new BbField("JOB_MESSAGE", OracleDbType.Varchar2, true, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Інформація про виконання"));
            Fields.Add( new BbField("JOB_ERRTEXT", OracleDbType.Varchar2, true, false, false, false, false, "V_DPZTJOB_JOBS", ObjectTypes.View, "Інтерфейс з ОДБ. Завдання інтерфейсу", "Текст помилки"));
        }
        public VDpztjobJobsRecord(BbDataSource Parent, OracleDecimal RowScn, OracleString JOB_CODE, OracleString JOB_NAME, OracleString JOB_ACTIVITY, OracleDecimal JOB_INTERVAL, OracleDate JOB_BEGDATE, OracleDate JOB_ENDDATE, OracleDecimal JOB_FAILED, OracleString JOB_STATE, OracleString JOB_MESSAGE, OracleString JOB_ERRTEXT)
            : this(Parent)
        {
            this.JOB_CODE = JOB_CODE;
            this.JOB_NAME = JOB_NAME;
            this.JOB_ACTIVITY = JOB_ACTIVITY;
            this.JOB_INTERVAL = JOB_INTERVAL;
            this.JOB_BEGDATE = JOB_BEGDATE;
            this.JOB_ENDDATE = JOB_ENDDATE;
            this.JOB_FAILED = JOB_FAILED;
            this.JOB_STATE = JOB_STATE;
            this.JOB_MESSAGE = JOB_MESSAGE;
            this.JOB_ERRTEXT = JOB_ERRTEXT;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        public OracleString JOB_CODE { get { return (OracleString)FindField("JOB_CODE").Value; } set {SetField("JOB_CODE", value);} }
        public OracleString JOB_NAME { get { return (OracleString)FindField("JOB_NAME").Value; } set {SetField("JOB_NAME", value);} }
        public OracleString JOB_ACTIVITY { get { return (OracleString)FindField("JOB_ACTIVITY").Value; } set {SetField("JOB_ACTIVITY", value);} }
        public OracleDecimal JOB_INTERVAL { get { return (OracleDecimal)FindField("JOB_INTERVAL").Value; } set {SetField("JOB_INTERVAL", value);} }
        public OracleDate JOB_BEGDATE { get { return (OracleDate)FindField("JOB_BEGDATE").Value; } set {SetField("JOB_BEGDATE", value);} }
        public OracleDate JOB_ENDDATE { get { return (OracleDate)FindField("JOB_ENDDATE").Value; } set {SetField("JOB_ENDDATE", value);} }
        public OracleDecimal JOB_FAILED { get { return (OracleDecimal)FindField("JOB_FAILED").Value; } set {SetField("JOB_FAILED", value);} }
        public OracleString JOB_STATE { get { return (OracleString)FindField("JOB_STATE").Value; } set {SetField("JOB_STATE", value);} }
        public OracleString JOB_MESSAGE { get { return (OracleString)FindField("JOB_MESSAGE").Value; } set {SetField("JOB_MESSAGE", value);} }
        public OracleString JOB_ERRTEXT { get { return (OracleString)FindField("JOB_ERRTEXT").Value; } set {SetField("JOB_ERRTEXT", value);} }
    }

    public sealed class VDpztjobJobsFilters : BbFilters
    {
        public VDpztjobJobsFilters(BbDataSource Parent) : base (Parent)
        {
            JOB_CODE = new BBVarchar2Filter(this, "JOB_CODE");
            JOB_NAME = new BBVarchar2Filter(this, "JOB_NAME");
            JOB_ACTIVITY = new BBCharFilter(this, "JOB_ACTIVITY");
            JOB_INTERVAL = new BBDecimalFilter(this, "JOB_INTERVAL");
            JOB_BEGDATE = new BBDateFilter(this, "JOB_BEGDATE");
            JOB_ENDDATE = new BBDateFilter(this, "JOB_ENDDATE");
            JOB_FAILED = new BBDecimalFilter(this, "JOB_FAILED");
            JOB_STATE = new BBVarchar2Filter(this, "JOB_STATE");
            JOB_MESSAGE = new BBVarchar2Filter(this, "JOB_MESSAGE");
            JOB_ERRTEXT = new BBVarchar2Filter(this, "JOB_ERRTEXT");
        }
        public BBVarchar2Filter JOB_CODE;
        public BBVarchar2Filter JOB_NAME;
        public BBCharFilter JOB_ACTIVITY;
        public BBDecimalFilter JOB_INTERVAL;
        public BBDateFilter JOB_BEGDATE;
        public BBDateFilter JOB_ENDDATE;
        public BBDecimalFilter JOB_FAILED;
        public BBVarchar2Filter JOB_STATE;
        public BBVarchar2Filter JOB_MESSAGE;
        public BBVarchar2Filter JOB_ERRTEXT;
    }

    public sealed class VDpztjobJobs : BbTable<VDpztjobJobsRecord, VDpztjobJobsFilters>
    {
        public VDpztjobJobs(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VDpztjobJobsRecord> Select(VDpztjobJobsRecord Item)
        {
            List<VDpztjobJobsRecord> res = new List<VDpztjobJobsRecord>();
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                OracleDataReader rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VDpztjobJobsRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.GetOracleString(1), 
                        rdr.GetOracleString(2), 
                        rdr.GetOracleString(3), 
                        rdr.GetOracleDecimal(4), 
                        rdr.GetOracleDate(5), 
                        rdr.GetOracleDate(6), 
                        rdr.GetOracleDecimal(7), 
                        rdr.GetOracleString(8), 
                        rdr.GetOracleString(9), 
                        rdr.GetOracleString(10))
                    );
                }
                rdr.Close();
                rdr.Dispose();
            }
            finally
            {
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}