

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Procedure/GRANT_REF_PRIVS.sql =========*** R
PROMPT ===================================================================================== 


PROMPT *** Create  procedure GRANT_REF_PRIVS ***

  CREATE OR REPLACE PROCEDURE BARS.GRANT_REF_PRIVS (CODEAPP_ CHAR DEFAULT NULL) IS
  --Процедура добавляют недостающие привилегии на справочники
  CURSOR REF_ROLES_ALL IS
  SELECT DISTINCT
    STAFF.LOGNAME USERNAME,REFERENCES.ROLE2EDIT ROLE_NAME
  FROM STAFF,APPLIST_STAFF,REFAPP,REFERENCES,DBA_ROLES
  WHERE
    STAFF.ID=APPLIST_STAFF.ID AND
	APPLIST_STAFF.CODEAPP=REFAPP.CODEAPP AND
	REFAPP.TABID=REFERENCES.TABID AND
	REFERENCES.ROLE2EDIT IS NOT NULL AND
	UPPER(REFERENCES.ROLE2EDIT) = DBA_ROLES.ROLE AND
	UPPER(REFERENCES.ROLE2EDIT) NOT IN (
	SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE=STAFF.LOGNAME)
  ORDER BY
    STAFF.LOGNAME, REFERENCES.ROLE2EDIT;
  CURSOR REF_ROLES_APP IS
  SELECT DISTINCT
    STAFF.LOGNAME USERNAME,REFERENCES.ROLE2EDIT ROLE_NAME
  FROM STAFF,APPLIST_STAFF,REFAPP,REFERENCES,DBA_ROLES
  WHERE
    STAFF.ID=APPLIST_STAFF.ID AND
	APPLIST_STAFF.CODEAPP=REFAPP.CODEAPP AND
	APPLIST_STAFF.CODEAPP=CODEAPP_ AND
	REFAPP.TABID=REFERENCES.TABID AND
	REFERENCES.ROLE2EDIT IS NOT NULL AND
	UPPER(REFERENCES.ROLE2EDIT) = DBA_ROLES.ROLE AND
	UPPER(REFERENCES.ROLE2EDIT) NOT IN (
	SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE=STAFF.LOGNAME)
  ORDER BY
    STAFF.LOGNAME, REFERENCES.ROLE2EDIT;
  CID			   INTEGER;
  GRANTS_STR	   VARCHAR2(300);
  HIT_COUNT		   INTEGER;
BEGIN
  CID := DBMS_SQL.OPEN_CURSOR;
  HIT_COUNT := 0;
  IF CODEAPP_ IS NULL THEN
    FOR C1 IN REF_ROLES_ALL LOOP
      IF LENGTH(C1.ROLE_NAME)>0 AND LENGTH(C1.USERNAME)>0 THEN
        GRANTS_STR := 'GRANT ' || C1.ROLE_NAME || ' TO ' || C1.USERNAME;
	    BEGIN
          DBMS_SQL.PARSE( CID, GRANTS_STR, DBMS_SQL.V7 );
	    EXCEPTION
	      WHEN OTHERS THEN NULL;
  	    END;
	    HIT_COUNT := HIT_COUNT + 1;
	  END IF;
    END LOOP;
  ELSE
    FOR C1 IN REF_ROLES_APP LOOP
      IF LENGTH(C1.ROLE_NAME)>0 AND LENGTH(C1.USERNAME)>0 THEN
        GRANTS_STR := 'GRANT ' || C1.ROLE_NAME || ' TO ' || C1.USERNAME;
	    BEGIN
          DBMS_SQL.PARSE( CID, GRANTS_STR, DBMS_SQL.V7 );
	    EXCEPTION
	      WHEN OTHERS THEN NULL;
  	    END;
	    HIT_COUNT := HIT_COUNT + 1;
	  END IF;
    END LOOP;
  END IF;
  DBMS_SQL.CLOSE_CURSOR( CID );
  DBMS_OUTPUT.PUT_LINE( HIT_COUNT || ' ролей дано на справочники.' );
END;
/
show err;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Procedure/GRANT_REF_PRIVS.sql =========*** E
PROMPT ===================================================================================== 
