/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public sealed class VWcsBidCuraccountsRecord : BbRecord
    {
        public VWcsBidCuraccountsRecord(): base()
        {
            fillFields();
        }
        public VWcsBidCuraccountsRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VWcsBidCuraccountsRecord(BbDataSource Parent, OracleDecimal RowScn, Decimal? BID_ID, Decimal? RNK, Decimal? ACC, String NLS, Decimal? KV, String NMS, String DESCR, Decimal? SELECTED)
            : this(Parent)
        {
            this.BID_ID = BID_ID;
            this.RNK = RNK;
            this.ACC = ACC;
            this.NLS = NLS;
            this.KV = KV;
            this.NMS = NMS;
            this.DESCR = DESCR;
            this.SELECTED = SELECTED;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("BID_ID", OracleDbType.Decimal, false, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Идентификатор заявки"));
            Fields.Add( new BbField("RNK", OracleDbType.Decimal, false, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "РНК"));
            Fields.Add( new BbField("ACC", OracleDbType.Decimal, false, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Идентификатор счета"));
            Fields.Add( new BbField("NLS", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Номер балансового счета"));
            Fields.Add( new BbField("KV", OracleDbType.Decimal, false, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Код валюты"));
            Fields.Add( new BbField("NMS", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Наименование счета"));
            Fields.Add( new BbField("DESCR", OracleDbType.Varchar2, true, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Расширеное описание счета"));
            Fields.Add( new BbField("SELECTED", OracleDbType.Decimal, true, false, false, false, false, "V_WCS_BID_CURACCOUNTS", ObjectTypes.View, "Текущие счета заявки (Представление)", "Счет выбран для обслуживания"));        
        }
        public Decimal? BID_ID { get { return (Decimal?)FindField("BID_ID").Value; } set {SetField("BID_ID", value);} }
        public Decimal? RNK { get { return (Decimal?)FindField("RNK").Value; } set {SetField("RNK", value);} }
        public Decimal? ACC { get { return (Decimal?)FindField("ACC").Value; } set {SetField("ACC", value);} }
        public String NLS { get { return (String)FindField("NLS").Value; } set {SetField("NLS", value);} }
        public Decimal? KV { get { return (Decimal?)FindField("KV").Value; } set {SetField("KV", value);} }
        public String NMS { get { return (String)FindField("NMS").Value; } set {SetField("NMS", value);} }
        public String DESCR { get { return (String)FindField("DESCR").Value; } set {SetField("DESCR", value);} }
        public Decimal? SELECTED { get { return (Decimal?)FindField("SELECTED").Value; } set {SetField("SELECTED", value);} }
    }

    public sealed class VWcsBidCuraccountsFilters : BbFilters
    {
        public VWcsBidCuraccountsFilters(BbDataSource Parent) : base (Parent)
        {
            BID_ID = new BBDecimalFilter(this, "BID_ID");
            RNK = new BBDecimalFilter(this, "RNK");
            ACC = new BBDecimalFilter(this, "ACC");
            NLS = new BBVarchar2Filter(this, "NLS");
            KV = new BBDecimalFilter(this, "KV");
            NMS = new BBVarchar2Filter(this, "NMS");
            DESCR = new BBVarchar2Filter(this, "DESCR");
            SELECTED = new BBDecimalFilter(this, "SELECTED");
        }
        public BBDecimalFilter BID_ID;
        public BBDecimalFilter RNK;
        public BBDecimalFilter ACC;
        public BBVarchar2Filter NLS;
        public BBDecimalFilter KV;
        public BBVarchar2Filter NMS;
        public BBVarchar2Filter DESCR;
        public BBDecimalFilter SELECTED;
    }

    public partial class VWcsBidCuraccounts : BbTable<VWcsBidCuraccountsRecord, VWcsBidCuraccountsFilters>
    {
        public VWcsBidCuraccounts() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VWcsBidCuraccounts(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VWcsBidCuraccountsRecord> Select(VWcsBidCuraccountsRecord Item)
        {
            List<VWcsBidCuraccountsRecord> res = new List<VWcsBidCuraccountsRecord>();
                        OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VWcsBidCuraccountsRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (Decimal?)null : Convert.ToDecimal(rdr[1]), 
                        rdr.IsDBNull(2) ?  (Decimal?)null : Convert.ToDecimal(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]), 
                        rdr.IsDBNull(4) ?  (String)null : Convert.ToString(rdr[4]), 
                        rdr.IsDBNull(5) ?  (Decimal?)null : Convert.ToDecimal(rdr[5]), 
                        rdr.IsDBNull(6) ?  (String)null : Convert.ToString(rdr[6]), 
                        rdr.IsDBNull(7) ?  (String)null : Convert.ToString(rdr[7]), 
                        rdr.IsDBNull(8) ?  (Decimal?)null : Convert.ToDecimal(rdr[8]))
                    );
                }
            }
                        finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}