

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_SURVEY_GROUP_QUEST.sql ======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_WCS_SURVEY_GROUP_QUEST ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_WCS_SURVEY_GROUP_QUEST ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_WCS_SURVEY_GROUP_QUEST 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	SURVEY_ID VARCHAR2(4000), 
	SGROUP_ID VARCHAR2(4000), 
	RECTYPE_ID VARCHAR2(4000), 
	QUESTION_ID VARCHAR2(4000), 
	DNSHOW_IF VARCHAR2(4000), 
	IS_READONLY VARCHAR2(4000), 
	IS_REWRITABLE VARCHAR2(4000), 
	IS_CHECKABLE VARCHAR2(4000), 
	CHECK_PROC VARCHAR2(4000), 
	ORD VARCHAR2(4000), 
	IS_REQUIRED VARCHAR2(4000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_WCS_SURVEY_GROUP_QUEST ***
 exec bpa.alter_policies('ERR$_WCS_SURVEY_GROUP_QUEST');


COMMENT ON TABLE BARS.ERR$_WCS_SURVEY_GROUP_QUEST IS 'DML Error Logging table for "WCS_SURVEY_GROUP_QUESTIONS"';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.SURVEY_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.SGROUP_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.RECTYPE_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.QUESTION_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.DNSHOW_IF IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.IS_READONLY IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.IS_REWRITABLE IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.IS_CHECKABLE IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.CHECK_PROC IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.ORD IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SURVEY_GROUP_QUEST.IS_REQUIRED IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_SURVEY_GROUP_QUEST.sql ======
PROMPT ===================================================================================== 
