

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_SUBPRODUCT_MACS.sql =========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to ERR$_WCS_SUBPRODUCT_MACS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table ERR$_WCS_SUBPRODUCT_MACS ***
begin 
  execute immediate '
  CREATE TABLE BARS.ERR$_WCS_SUBPRODUCT_MACS 
   (	ORA_ERR_NUMBER$ NUMBER, 
	ORA_ERR_MESG$ VARCHAR2(2000), 
	ORA_ERR_ROWID$ UROWID (4000), 
	ORA_ERR_OPTYP$ VARCHAR2(2), 
	ORA_ERR_TAG$ VARCHAR2(2000), 
	SUBPRODUCT_ID VARCHAR2(4000), 
	MAC_ID VARCHAR2(4000), 
	BRANCH VARCHAR2(4000), 
	VAL_TEXT VARCHAR2(4000), 
	VAL_NUMB VARCHAR2(4000), 
	VAL_DECIMAL VARCHAR2(4000), 
	VAL_DATE VARCHAR2(4000), 
	VAL_LIST VARCHAR2(4000), 
	VAL_REFER VARCHAR2(4000), 
	VAL_BOOL VARCHAR2(4000), 
	APPLY_DATE VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to ERR$_WCS_SUBPRODUCT_MACS ***
 exec bpa.alter_policies('ERR$_WCS_SUBPRODUCT_MACS');


COMMENT ON TABLE BARS.ERR$_WCS_SUBPRODUCT_MACS IS 'DML Error Logging table for "WCS_SUBPRODUCT_MACS"';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_NUMB IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_DECIMAL IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_LIST IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_REFER IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_BOOL IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.APPLY_DATE IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.ORA_ERR_NUMBER$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.ORA_ERR_MESG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.ORA_ERR_ROWID$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.ORA_ERR_OPTYP$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.ORA_ERR_TAG$ IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.SUBPRODUCT_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.MAC_ID IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.BRANCH IS '';
COMMENT ON COLUMN BARS.ERR$_WCS_SUBPRODUCT_MACS.VAL_TEXT IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/ERR$_WCS_SUBPRODUCT_MACS.sql =========
PROMPT ===================================================================================== 
