

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/F98.sql =========*** Run *** =========
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to F98 ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''F98'', ''FILIAL'' , null, ''E'', ''E'', ''E'');
               bpa.alter_policy_info(''F98'', ''WHOLE'' , null, null, null, null);
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table F98 ***
begin 
  execute immediate '
  CREATE TABLE BARS.F98 
   (	NP VARCHAR2(2), 
	DT DATE, 
	EK_POK VARCHAR2(5), 
	KO VARCHAR2(3), 
	MFO VARCHAR2(6), 
	NKB VARCHAR2(3), 
	KU VARCHAR2(3), 
	PRB VARCHAR2(1), 
	K030 VARCHAR2(1), 
	V_SANK VARCHAR2(1), 
	KO_1 VARCHAR2(3), 
	R1_1 VARCHAR2(100), 
	R2_1 VARCHAR2(100), 
	K020 VARCHAR2(10), 
	DATAPOD DATE, 
	NOMPOD VARCHAR2(16), 
	DJERPOD VARCHAR2(20), 
	NAKAZ VARCHAR2(20), 
	DATANAK DATE, 
	NOMNAK VARCHAR2(16), 
	DATPODSK DATE, 
	NOMPODSK VARCHAR2(16), 
	DJERPODS VARCHAR2(20), 
	DATNAKSK DATE, 
	NOMNAKSK VARCHAR2(50), 
	SANKSIA1 VARCHAR2(5), 
	SRSANK11 DATE, 
	SRSANK12 DATE, 
	R4 VARCHAR2(100), 
	R030 VARCHAR2(3), 
	T071 NUMBER(16,0), 
	K040 VARCHAR2(3), 
	BANKIN VARCHAR2(200), 
	ADRIN VARCHAR2(200), 
	DATA_M DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to F98 ***
 exec bpa.alter_policies('F98');


COMMENT ON TABLE BARS.F98 IS '';
COMMENT ON COLUMN BARS.F98.K020 IS '';
COMMENT ON COLUMN BARS.F98.DATAPOD IS '';
COMMENT ON COLUMN BARS.F98.NOMPOD IS '';
COMMENT ON COLUMN BARS.F98.DJERPOD IS '';
COMMENT ON COLUMN BARS.F98.NAKAZ IS '';
COMMENT ON COLUMN BARS.F98.DATANAK IS '';
COMMENT ON COLUMN BARS.F98.NOMNAK IS '';
COMMENT ON COLUMN BARS.F98.DATPODSK IS '';
COMMENT ON COLUMN BARS.F98.NOMPODSK IS '';
COMMENT ON COLUMN BARS.F98.DJERPODS IS '';
COMMENT ON COLUMN BARS.F98.DATNAKSK IS '';
COMMENT ON COLUMN BARS.F98.NOMNAKSK IS '';
COMMENT ON COLUMN BARS.F98.SANKSIA1 IS '';
COMMENT ON COLUMN BARS.F98.SRSANK11 IS '';
COMMENT ON COLUMN BARS.F98.SRSANK12 IS '';
COMMENT ON COLUMN BARS.F98.R4 IS '';
COMMENT ON COLUMN BARS.F98.R030 IS '';
COMMENT ON COLUMN BARS.F98.T071 IS '';
COMMENT ON COLUMN BARS.F98.K040 IS '';
COMMENT ON COLUMN BARS.F98.BANKIN IS '';
COMMENT ON COLUMN BARS.F98.ADRIN IS '';
COMMENT ON COLUMN BARS.F98.DATA_M IS '';
COMMENT ON COLUMN BARS.F98.NP IS '';
COMMENT ON COLUMN BARS.F98.DT IS '';
COMMENT ON COLUMN BARS.F98.EK_POK IS '';
COMMENT ON COLUMN BARS.F98.KO IS '';
COMMENT ON COLUMN BARS.F98.MFO IS '';
COMMENT ON COLUMN BARS.F98.NKB IS '';
COMMENT ON COLUMN BARS.F98.KU IS '';
COMMENT ON COLUMN BARS.F98.PRB IS '';
COMMENT ON COLUMN BARS.F98.K030 IS '';
COMMENT ON COLUMN BARS.F98.V_SANK IS '';
COMMENT ON COLUMN BARS.F98.KO_1 IS '';
COMMENT ON COLUMN BARS.F98.R1_1 IS '';
COMMENT ON COLUMN BARS.F98.R2_1 IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/F98.sql =========*** End *** =========
PROMPT ===================================================================================== 
