PROMPT Table KF_W4;

BEGIN
   bpa.alter_policy_info ('KF_W4', 'WHOLE', NULL, NULL, NULL, NULL);
   bpa.alter_policy_info ('KF_W4', 'FILIAL', NULL, NULL, NULL, NULL);
END;
/

BEGIN
   EXECUTE IMMEDIATE
   'CREATE TABLE KF_W4
    ( KF    INTEGER NOT NULL, 
      CodeW4  char(4) NOT NULL     
    ) TABLESPACE brssmld';
EXCEPTION
   WHEN OTHERS
   THEN
      IF (SQLCODE = -955)
      THEN NULL;
      ELSE RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PK_KF_W4 ON KF_W4
    (KF)
    LOGGING
    NOPARALLEL TABLESPACE brssmli';
EXCEPTION
   WHEN OTHERS
   THEN
      IF (SQLCODE = -955) or (SQLCODE = -02260)
      THEN NULL;
      ELSE RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE KF_W4 ADD PRIMARY KEY (KF)';
EXCEPTION
   WHEN OTHERS
   THEN
      IF (SQLCODE = -955) or (SQLCODE = -02260)
      THEN NULL;
      ELSE RAISE;
      END IF;
END;
/
COMMENT ON TABLE KF_W4 IS ' Ó‰Ë –” ‚ WAY4';
COMMENT ON COLUMN KF_W4.KF IS 'Ã‘Œ';
COMMENT ON COLUMN KF_W4.CodeW4 IS ' Ó‰ –” ‚ Way4';
/

GRANT ALL ON KF_W4 TO BARS_ACCESS_DEFROLE;
/
