

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/OPLDOK.sql =========*** Run *** ======
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to OPLDOK ***


BEGIN 
        execute immediate  
          'begin  
               bpa.alter_policy_info(''OPLDOK'', ''FILIAL'' , ''M'', ''M'', ''M'', ''M'');
               bpa.alter_policy_info(''OPLDOK'', ''WHOLE'' , null, ''E'', ''E'', ''E'');
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table OPLDOK ***
begin 
  execute immediate '
  CREATE TABLE BARS.OPLDOK 
   (	REF NUMBER(38,0), 
	TT CHAR(3), 
	DK NUMBER(1,0), 
	ACC NUMBER(38,0), 
	FDAT DATE, 
	S NUMBER(24,0), 
	SQ NUMBER(24,0), 
	TXT VARCHAR2(70), 
	STMT NUMBER(38,0), 
	SOS NUMBER(1,0), 
	KF VARCHAR2(6) DEFAULT sys_context(''bars_context'',''user_mfo''), 
	OTM NUMBER(*,0) DEFAULT null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255  LOGGING 
  TABLESPACE SYSTEM 
  PARTITION BY RANGE (FDAT) 
 (PARTITION OPLDOK_Y2009_Q1  VALUES LESS THAN (TO_DATE('' 2009-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2009D , 
 PARTITION OPLDOK_Y2009_Q2  VALUES LESS THAN (TO_DATE('' 2009-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2009D , 
 PARTITION OPLDOK_Y2009_Q3  VALUES LESS THAN (TO_DATE('' 2009-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2009D , 
 PARTITION OPLDOK_Y2009_Q4  VALUES LESS THAN (TO_DATE('' 2010-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2009D , 
 PARTITION OPLDOK_Y2010_Q1  VALUES LESS THAN (TO_DATE('' 2010-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2010D , 
 PARTITION OPLDOK_Y2010_Q2  VALUES LESS THAN (TO_DATE('' 2010-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2010D , 
 PARTITION OPLDOK_Y2010_Q3  VALUES LESS THAN (TO_DATE('' 2010-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2010D , 
 PARTITION OPLDOK_Y2010_Q4  VALUES LESS THAN (TO_DATE('' 2011-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2010D , 
 PARTITION OPLDOK_Y2011_Q1  VALUES LESS THAN (TO_DATE('' 2011-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2011D , 
 PARTITION OPLDOK_Y2011_Q2  VALUES LESS THAN (TO_DATE('' 2011-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2011D , 
 PARTITION OPLDOK_Y2011_Q3  VALUES LESS THAN (TO_DATE('' 2011-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2011D , 
 PARTITION OPLDOK_Y2011_Q4  VALUES LESS THAN (TO_DATE('' 2012-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2011D , 
 PARTITION OPLDOK_Y2012_Q1  VALUES LESS THAN (TO_DATE('' 2012-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2012D , 
 PARTITION OPLDOK_Y2012_Q2  VALUES LESS THAN (TO_DATE('' 2012-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2012D , 
 PARTITION OPLDOK_Y2012_Q3  VALUES LESS THAN (TO_DATE('' 2012-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2012D , 
 PARTITION OPLDOK_Y2012_Q4  VALUES LESS THAN (TO_DATE('' 2013-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2012D , 
 PARTITION OPLDOK_Y2013_Q1  VALUES LESS THAN (TO_DATE('' 2013-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2013D , 
 PARTITION OPLDOK_Y2013_Q2  VALUES LESS THAN (TO_DATE('' 2013-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2013D , 
 PARTITION OPLDOK_Y2013_Q3  VALUES LESS THAN (TO_DATE('' 2013-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2013D , 
 PARTITION OPLDOK_Y2013_Q4  VALUES LESS THAN (TO_DATE('' 2014-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2013D , 
 PARTITION OPLDOK_Y2014_Q1  VALUES LESS THAN (TO_DATE('' 2014-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2014D , 
 PARTITION OPLDOK_Y2014_Q2  VALUES LESS THAN (TO_DATE('' 2014-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2014D , 
 PARTITION OPLDOK_Y2014_Q3  VALUES LESS THAN (TO_DATE('' 2014-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2014D , 
 PARTITION OPLDOK_Y2014_Q4  VALUES LESS THAN (TO_DATE('' 2015-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2014D , 
 PARTITION OPLDOK_Y2015_Q1  VALUES LESS THAN (TO_DATE('' 2015-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2015D , 
 PARTITION OPLDOK_Y2015_Q2  VALUES LESS THAN (TO_DATE('' 2015-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2015D , 
 PARTITION OPLDOK_Y2015_Q3  VALUES LESS THAN (TO_DATE('' 2015-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2015D , 
 PARTITION OPLDOK_Y2015_Q4  VALUES LESS THAN (TO_DATE('' 2016-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2015D , 
 PARTITION OPLDOK_Y2016_Q1  VALUES LESS THAN (TO_DATE('' 2016-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2016D , 
 PARTITION OPLDOK_Y2016_Q2  VALUES LESS THAN (TO_DATE('' 2016-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2016D , 
 PARTITION OPLDOK_Y2016_Q3  VALUES LESS THAN (TO_DATE('' 2016-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2016D , 
 PARTITION OPLDOK_Y2016_Q4  VALUES LESS THAN (TO_DATE('' 2017-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2016D , 
 PARTITION OPLDOK_Y2017_Q1  VALUES LESS THAN (TO_DATE('' 2017-04-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2017D , 
 PARTITION OPLDOK_Y2017_Q2  VALUES LESS THAN (TO_DATE('' 2017-07-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2017D , 
 PARTITION OPLDOK_Y2017_Q3  VALUES LESS THAN (TO_DATE('' 2017-10-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2017D , 
 PARTITION OPLDOK_Y2017_Q4  VALUES LESS THAN (TO_DATE('' 2018-01-01 00:00:00'', ''SYYYY-MM-DD HH24:MI:SS'', ''NLS_CALENDAR=GREGORIAN'')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSOPLDOK2017D )  ENABLE ROW MOVEMENT ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to OPLDOK ***
 exec bpa.alter_policies('OPLDOK');


COMMENT ON TABLE BARS.OPLDOK IS 'Проводки';
COMMENT ON COLUMN BARS.OPLDOK.REF IS 'Внутренний номер документа';
COMMENT ON COLUMN BARS.OPLDOK.TT IS 'Тип транзакции';
COMMENT ON COLUMN BARS.OPLDOK.DK IS 'Признак дебет/кредит';
COMMENT ON COLUMN BARS.OPLDOK.ACC IS 'Внутренний номер счета';
COMMENT ON COLUMN BARS.OPLDOK.FDAT IS 'Фактическая дата оплаты документа';
COMMENT ON COLUMN BARS.OPLDOK.S IS 'Сумма транзакции';
COMMENT ON COLUMN BARS.OPLDOK.SQ IS 'Сумма транзакции в эквиваленте';
COMMENT ON COLUMN BARS.OPLDOK.TXT IS 'Назначения транзакции';
COMMENT ON COLUMN BARS.OPLDOK.STMT IS 'Идентификатор транзакции';
COMMENT ON COLUMN BARS.OPLDOK.SOS IS 'Признак оплаты
1 - booked ( по плановому остатку)
3 - forward
5 - cleared';
COMMENT ON COLUMN BARS.OPLDOK.KF IS '';
COMMENT ON COLUMN BARS.OPLDOK.OTM IS 'Признак оплаты для НУ ОБ';




PROMPT *** Create  constraint FK_OPLDOK_OPER2 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT FK_OPLDOK_OPER2 FOREIGN KEY (KF, REF)
	  REFERENCES BARS.OPER (KF, REF) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPLDOK_ACCOUNTS2 ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT FK_OPLDOK_ACCOUNTS2 FOREIGN KEY (KF, ACC)
	  REFERENCES BARS.ACCOUNTS (KF, ACC) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPLDOK_KF ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT FK_OPLDOK_KF FOREIGN KEY (KF)
	  REFERENCES BARS.BANKS$BASE (MFO) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPLDOK_TTS ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT FK_OPLDOK_TTS FOREIGN KEY (TT)
	  REFERENCES BARS.TTS (TT) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint FK_OPLDOK_SOS ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT FK_OPLDOK_SOS FOREIGN KEY (SOS)
	  REFERENCES BARS.SOS (SOS) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_FDAT ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT CC_OPLDOK_FDAT CHECK (fdat = trunc(fdat)) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_DK ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT CC_OPLDOK_DK CHECK (dk in (0, 1)) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_KF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (KF CONSTRAINT CC_OPLDOK_KF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_SOS_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (SOS CONSTRAINT CC_OPLDOK_SOS_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_STMT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (STMT CONSTRAINT CC_OPLDOK_STMT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_SQ_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (SQ CONSTRAINT CC_OPLDOK_SQ_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_S_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (S CONSTRAINT CC_OPLDOK_S_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_FDAT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (FDAT CONSTRAINT CC_OPLDOK_FDAT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_ACC_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (ACC CONSTRAINT CC_OPLDOK_ACC_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_DK_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (DK CONSTRAINT CC_OPLDOK_DK_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_TT_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (TT CONSTRAINT CC_OPLDOK_TT_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint CC_OPLDOK_REF_NN ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK MODIFY (REF CONSTRAINT CC_OPLDOK_REF_NN NOT NULL ENABLE)';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  constraint PK_OPLDOK ***
begin   
 execute immediate '
  ALTER TABLE BARS.OPLDOK ADD CONSTRAINT PK_OPLDOK PRIMARY KEY (REF, STMT, DK)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPLDOKI  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index XIE_FDAT_ACC_OPLDOK ***
begin   
 execute immediate '
  CREATE INDEX BARS.XIE_FDAT_ACC_OPLDOK ON BARS.OPLDOK (FDAT, ACC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255  LOGGING 
  TABLESPACE BRSOPLDOKI  LOCAL
 (PARTITION OPLDOK_Y2009_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOKI , 
 PARTITION OPLDOK_Y2009_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOKI , 
 PARTITION OPLDOK_Y2009_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOKI , 
 PARTITION OPLDOK_Y2009_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOKI , 
 PARTITION OPLDOK_Y2010_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2010I , 
 PARTITION OPLDOK_Y2010_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2010I , 
 PARTITION OPLDOK_Y2010_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2010I , 
 PARTITION OPLDOK_Y2010_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2010I , 
 PARTITION OPLDOK_Y2011_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2011I , 
 PARTITION OPLDOK_Y2011_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2011I , 
 PARTITION OPLDOK_Y2011_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2011I , 
 PARTITION OPLDOK_Y2011_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2011I , 
 PARTITION OPLDOK_Y2012_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2012I , 
 PARTITION OPLDOK_Y2012_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2012I , 
 PARTITION OPLDOK_Y2012_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2012I , 
 PARTITION OPLDOK_Y2012_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2012I , 
 PARTITION OPLDOK_Y2013_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2013I , 
 PARTITION OPLDOK_Y2013_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2013I , 
 PARTITION OPLDOK_Y2013_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2013I , 
 PARTITION OPLDOK_Y2013_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2013I , 
 PARTITION OPLDOK_Y2014_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2014I , 
 PARTITION OPLDOK_Y2014_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2014I , 
 PARTITION OPLDOK_Y2014_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2014I , 
 PARTITION OPLDOK_Y2014_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2014I , 
 PARTITION OPLDOK_Y2015_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2015I , 
 PARTITION OPLDOK_Y2015_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2015I , 
 PARTITION OPLDOK_Y2015_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2015I , 
 PARTITION OPLDOK_Y2015_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2015I , 
 PARTITION OPLDOK_Y2016_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2016I , 
 PARTITION OPLDOK_Y2016_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2016I , 
 PARTITION OPLDOK_Y2016_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2016I , 
 PARTITION OPLDOK_Y2016_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2016I , 
 PARTITION OPLDOK_Y2017_Q1 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2017I , 
 PARTITION OPLDOK_Y2017_Q2 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2017I , 
 PARTITION OPLDOK_Y2017_Q3 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2017I , 
 PARTITION OPLDOK_Y2017_Q4 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  TABLESPACE BRSOPLDOK2017I ) COMPRESS 1 ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/




PROMPT *** Create  index PK_OPLDOK ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.PK_OPLDOK ON BARS.OPLDOK (REF, STMT, DK) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSOPLDOKI ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  OPLDOK ***
grant DELETE,INSERT,SELECT,UPDATE                                            on OPLDOK          to ABS_ADMIN;
grant DELETE,UPDATE                                                          on OPLDOK          to BARS014;
grant FLASHBACK,REFERENCES,SELECT,UPDATE                                     on OPLDOK          to BARSAQ with grant option;
grant REFERENCES,SELECT,UPDATE                                               on OPLDOK          to BARSAQ_ADM with grant option;
grant SELECT                                                                 on OPLDOK          to BARSDWH_ACCESS_USER;
grant SELECT                                                                 on OPLDOK          to BARSUPL;
grant DELETE,INSERT,SELECT,UPDATE                                            on OPLDOK          to BARS_ACCESS_DEFROLE;
grant ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE on OPLDOK          to BARS_DM;
grant SELECT                                                                 on OPLDOK          to BARS_SUP;
grant SELECT                                                                 on OPLDOK          to FINMON01;
grant SELECT,SELECT                                                          on OPLDOK          to KLBX;
grant SELECT                                                                 on OPLDOK          to OBPC;
grant UPDATE                                                                 on OPLDOK          to PYOD001;
grant SELECT                                                                 on OPLDOK          to RPBN002;
grant SELECT                                                                 on OPLDOK          to START1;
grant SELECT,UPDATE                                                          on OPLDOK          to TEST;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on OPLDOK          to WR_ALL_RIGHTS;
grant SELECT                                                                 on OPLDOK          to WR_CUSTLIST;
grant SELECT                                                                 on OPLDOK          to WR_DEPOSIT_U;
grant SELECT                                                                 on OPLDOK          to WR_DOCVIEW;
grant SELECT                                                                 on OPLDOK          to WR_ND_ACCOUNTS;
grant SELECT                                                                 on OPLDOK          to WR_TOBO_ACCOUNTS_LIST;
grant SELECT                                                                 on OPLDOK          to WR_USER_ACCOUNTS_LIST;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/OPLDOK.sql =========*** End *** ======
PROMPT ===================================================================================== 
