

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/S6_S6_CONTRACTEVT.sql =========*** Run
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to S6_S6_CONTRACTEVT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table S6_S6_CONTRACTEVT ***
begin 
  execute immediate '
  CREATE TABLE BARS.S6_S6_CONTRACTEVT 
   (	ID NUMBER(11,0), 
	IDVID_CALE NUMBER(11,0), 
	BIC NUMBER(11,0), 
	IDCONTRACT VARCHAR2(40), 
	D_OPEN DATE, 
	D_PLAN DATE, 
	D_FACT DATE, 
	SUMMA NUMBER(18,2), 
	DA_OD DATE, 
	ID_OPER NUMBER(11,0), 
	ID_DOCUM NUMBER(11,0), 
	IDDOC NUMBER(11,0), 
	IDMETHOD NUMBER(11,0), 
	ISP_MODIFY NUMBER(11,0), 
	D_MODIFY DATE, 
	DESCRIPTIO VARCHAR2(240), 
	I_VA NUMBER(11,0), 
	ISP_EXEC NUMBER(11,0), 
	ISP_OWNER NUMBER(11,0), 
	ISP_VERIFY NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to S6_S6_CONTRACTEVT ***
 exec bpa.alter_policies('S6_S6_CONTRACTEVT');


COMMENT ON TABLE BARS.S6_S6_CONTRACTEVT IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ID IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.IDVID_CALE IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.BIC IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.IDCONTRACT IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.D_OPEN IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.D_PLAN IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.D_FACT IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.SUMMA IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.DA_OD IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ID_OPER IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ID_DOCUM IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.IDDOC IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.IDMETHOD IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ISP_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.D_MODIFY IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.DESCRIPTIO IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.I_VA IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ISP_EXEC IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ISP_OWNER IS '';
COMMENT ON COLUMN BARS.S6_S6_CONTRACTEVT.ISP_VERIFY IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/S6_S6_CONTRACTEVT.sql =========*** End
PROMPT ===================================================================================== 
