

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_WCS_SUBPRODUCT_MACS.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_WCS_SUBPRODUCT_MACS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_WCS_SUBPRODUCT_MACS ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_WCS_SUBPRODUCT_MACS 
   (	SUBPRODUCT_ID VARCHAR2(100), 
	MAC_ID VARCHAR2(100), 
	BRANCH VARCHAR2(30), 
	VAL_TEXT VARCHAR2(4000), 
	VAL_NUMB NUMBER, 
	VAL_DECIMAL NUMBER, 
	VAL_DATE DATE, 
	VAL_LIST NUMBER, 
	VAL_REFER VARCHAR2(4000), 
	VAL_FILE BLOB, 
	VAL_BOOL NUMBER(1,0), 
	APPLY_DATE DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND 
 LOB (VAL_FILE) STORE AS BASICFILE (
  TABLESPACE BRSDYND ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_WCS_SUBPRODUCT_MACS ***
 exec bpa.alter_policies('TMP_WCS_SUBPRODUCT_MACS');


COMMENT ON TABLE BARS.TMP_WCS_SUBPRODUCT_MACS IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.SUBPRODUCT_ID IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.MAC_ID IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_TEXT IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_NUMB IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_DECIMAL IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_DATE IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_LIST IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_REFER IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_FILE IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.VAL_BOOL IS '';
COMMENT ON COLUMN BARS.TMP_WCS_SUBPRODUCT_MACS.APPLY_DATE IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_WCS_SUBPRODUCT_MACS.sql =========*
PROMPT ===================================================================================== 
