

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_WCS_QUESTION_PARAMS.sql =========*
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_WCS_QUESTION_PARAMS ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_WCS_QUESTION_PARAMS ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_WCS_QUESTION_PARAMS 
   (	QUESTION_ID VARCHAR2(100), 
	TEXT_LENG_MIN VARCHAR2(4000), 
	TEXT_LENG_MAX VARCHAR2(4000), 
	TEXT_VAL_DEFAULT VARCHAR2(4000), 
	TEXT_WIDTH NUMBER, 
	TEXT_ROWS NUMBER, 
	NMBDEC_VAL_MIN VARCHAR2(4000), 
	NMBDEC_VAL_MAX VARCHAR2(4000), 
	NMBDEC_VAL_DEFAULT VARCHAR2(4000), 
	DAT_VAL_MIN VARCHAR2(4000), 
	DAT_VAL_MAX VARCHAR2(4000), 
	DAT_VAL_DEFAULT VARCHAR2(4000), 
	LIST_SID_DEFAULT VARCHAR2(4000), 
	REFER_SID_DEFAULT VARCHAR2(4000), 
	BOOL_VAL_DEFAULT VARCHAR2(4000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_WCS_QUESTION_PARAMS ***
 exec bpa.alter_policies('TMP_WCS_QUESTION_PARAMS');


COMMENT ON TABLE BARS.TMP_WCS_QUESTION_PARAMS IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.QUESTION_ID IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.TEXT_LENG_MIN IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.TEXT_LENG_MAX IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.TEXT_VAL_DEFAULT IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.TEXT_WIDTH IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.TEXT_ROWS IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.NMBDEC_VAL_MIN IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.NMBDEC_VAL_MAX IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.NMBDEC_VAL_DEFAULT IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.DAT_VAL_MIN IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.DAT_VAL_MAX IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.DAT_VAL_DEFAULT IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.LIST_SID_DEFAULT IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.REFER_SID_DEFAULT IS '';
COMMENT ON COLUMN BARS.TMP_WCS_QUESTION_PARAMS.BOOL_VAL_DEFAULT IS '';





PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_WCS_QUESTION_PARAMS.sql =========*
PROMPT ===================================================================================== 
