

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/Table/TMP_CRCA_DPT.sql =========*** Run *** 
PROMPT ===================================================================================== 


PROMPT *** ALTER_POLICY_INFO to TMP_CRCA_DPT ***


BEGIN 
        execute immediate  
          'begin  
               null;
           end; 
          '; 
END; 
/

PROMPT *** Create  table TMP_CRCA_DPT ***
begin 
  execute immediate '
  CREATE TABLE BARS.TMP_CRCA_DPT 
   (	NAME VARCHAR2(120), 
	F_NAME VARCHAR2(20), 
	L_NAME VARCHAR2(20), 
	ICOD VARCHAR2(10), 
	DBCOD VARCHAR2(14), 
	DATA_ID VARCHAR2(10), 
	DOCTYPE VARCHAR2(1), 
	S_PASPORT VARCHAR2(7), 
	N_PASPORT VARCHAR2(8), 
	D_PASPORT VARCHAR2(10), 
	PHONE VARCHAR2(16), 
	REGION VARCHAR2(2), 
	OTDEL VARCHAR2(5), 
	FILIAL VARCHAR2(5), 
	BRANCH VARCHAR2(30), 
	VKLAD VARCHAR2(40), 
	N_ANALIT VARCHAR2(19), 
	OB22 VARCHAR2(2), 
	CFID VARCHAR2(10), 
	NSC VARCHAR2(19), 
	DATO VARCHAR2(10), 
	DAZS VARCHAR2(10), 
	OST NUMBER(14,2), 
	NSC2 VARCHAR2(21), 
	GENDER VARCHAR2(1), 
	DATM VARCHAR2(10), 
	TIMEM VARCHAR2(8), 
	VSBRK VARCHAR2(12), 
	USER_NAME VARCHAR2(90), 
	NSC_ID VARCHAR2(38)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE BRSDYND ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/




PROMPT *** ALTER_POLICIES to TMP_CRCA_DPT ***
 exec bpa.alter_policies('TMP_CRCA_DPT');


COMMENT ON TABLE BARS.TMP_CRCA_DPT IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.NAME IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.F_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.L_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.ICOD IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.DBCOD IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.DATA_ID IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.DOCTYPE IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.S_PASPORT IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.N_PASPORT IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.D_PASPORT IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.PHONE IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.REGION IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.OTDEL IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.FILIAL IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.BRANCH IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.VKLAD IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.N_ANALIT IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.OB22 IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.CFID IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.NSC IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.DATO IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.DAZS IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.OST IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.NSC2 IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.GENDER IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.DATM IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.TIMEM IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.VSBRK IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.USER_NAME IS '';
COMMENT ON COLUMN BARS.TMP_CRCA_DPT.NSC_ID IS '';




PROMPT *** Create  constraint SYS_C003289914 ***
begin   
 execute immediate '
  ALTER TABLE BARS.TMP_CRCA_DPT ADD PRIMARY KEY (NSC_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND  ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/




PROMPT *** Create  index SYS_C003289914 ***
begin   
 execute immediate '
  CREATE UNIQUE INDEX BARS.SYS_C003289914 ON BARS.TMP_CRCA_DPT (NSC_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE BRSDYND ';
exception when others then
  if  sqlcode=-955  then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  TMP_CRCA_DPT ***
grant DELETE,INSERT,SELECT                                                   on TMP_CRCA_DPT    to WR_ALL_RIGHTS;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/Table/TMP_CRCA_DPT.sql =========*** End *** 
PROMPT ===================================================================================== 
