/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public sealed class VWcsSurveysRecord : BbRecord
    {
        public VWcsSurveysRecord(): base()
        {
            fillFields();
        }
        public VWcsSurveysRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VWcsSurveysRecord(BbDataSource Parent, OracleDecimal RowScn, String SURVEY_ID, String SURVEY_NAME, Decimal? GRP_CNT)
            : this(Parent)
        {
            this.SURVEY_ID = SURVEY_ID;
            this.SURVEY_NAME = SURVEY_NAME;
            this.GRP_CNT = GRP_CNT;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("SURVEY_ID", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_SURVEYS", ObjectTypes.View, "Анкеты (Представление)", "Идентификатор анкеты"));
            Fields.Add( new BbField("SURVEY_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_SURVEYS", ObjectTypes.View, "Анкеты (Представление)", "Наименование анкеты"));
            Fields.Add( new BbField("GRP_CNT", OracleDbType.Decimal, true, false, false, false, false, "V_WCS_SURVEYS", ObjectTypes.View, "Анкеты (Представление)", "Кол-во груп в акете"));        
        }
        public String SURVEY_ID { get { return (String)FindField("SURVEY_ID").Value; } set {SetField("SURVEY_ID", value);} }
        public String SURVEY_NAME { get { return (String)FindField("SURVEY_NAME").Value; } set {SetField("SURVEY_NAME", value);} }
        public Decimal? GRP_CNT { get { return (Decimal?)FindField("GRP_CNT").Value; } set {SetField("GRP_CNT", value);} }
    }

    public sealed class VWcsSurveysFilters : BbFilters
    {
        public VWcsSurveysFilters(BbDataSource Parent) : base (Parent)
        {
            SURVEY_ID = new BBVarchar2Filter(this, "SURVEY_ID");
            SURVEY_NAME = new BBVarchar2Filter(this, "SURVEY_NAME");
            GRP_CNT = new BBDecimalFilter(this, "GRP_CNT");
        }
        public BBVarchar2Filter SURVEY_ID;
        public BBVarchar2Filter SURVEY_NAME;
        public BBDecimalFilter GRP_CNT;
    }

    public partial class VWcsSurveys : BbTable<VWcsSurveysRecord, VWcsSurveysFilters>
    {
        public VWcsSurveys() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VWcsSurveys(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VWcsSurveysRecord> Select(VWcsSurveysRecord Item)
        {
            List<VWcsSurveysRecord> res = new List<VWcsSurveysRecord>();
                        OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VWcsSurveysRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (String)null : Convert.ToString(rdr[1]), 
                        rdr.IsDBNull(2) ?  (String)null : Convert.ToString(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]))
                    );
                }
            }
                        finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}