/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public sealed class VWcsScancopiesRecord : BbRecord
    {
        public VWcsScancopiesRecord(): base()
        {
            fillFields();
        }
        public VWcsScancopiesRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VWcsScancopiesRecord(BbDataSource Parent, OracleDecimal RowScn, String SCOPY_ID, String SCOPY_NAME, Decimal? QUEST_CNT)
            : this(Parent)
        {
            this.SCOPY_ID = SCOPY_ID;
            this.SCOPY_NAME = SCOPY_NAME;
            this.QUEST_CNT = QUEST_CNT;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("SCOPY_ID", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_SCANCOPIES", ObjectTypes.View, "Карты сканкопий (Представление)", "Идентификатор карты сканкопий"));
            Fields.Add( new BbField("SCOPY_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_WCS_SCANCOPIES", ObjectTypes.View, "Карты сканкопий (Представление)", "Наименование карты сканкопий"));
            Fields.Add( new BbField("QUEST_CNT", OracleDbType.Decimal, true, false, false, false, false, "V_WCS_SCANCOPIES", ObjectTypes.View, "Карты сканкопий (Представление)", "Кол-во сканкопий в карте"));        
        }
        public String SCOPY_ID { get { return (String)FindField("SCOPY_ID").Value; } set {SetField("SCOPY_ID", value);} }
        public String SCOPY_NAME { get { return (String)FindField("SCOPY_NAME").Value; } set {SetField("SCOPY_NAME", value);} }
        public Decimal? QUEST_CNT { get { return (Decimal?)FindField("QUEST_CNT").Value; } set {SetField("QUEST_CNT", value);} }
    }

    public sealed class VWcsScancopiesFilters : BbFilters
    {
        public VWcsScancopiesFilters(BbDataSource Parent) : base (Parent)
        {
            SCOPY_ID = new BBVarchar2Filter(this, "SCOPY_ID");
            SCOPY_NAME = new BBVarchar2Filter(this, "SCOPY_NAME");
            QUEST_CNT = new BBDecimalFilter(this, "QUEST_CNT");
        }
        public BBVarchar2Filter SCOPY_ID;
        public BBVarchar2Filter SCOPY_NAME;
        public BBDecimalFilter QUEST_CNT;
    }

    public partial class VWcsScancopies : BbTable<VWcsScancopiesRecord, VWcsScancopiesFilters>
    {
        public VWcsScancopies() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VWcsScancopies(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VWcsScancopiesRecord> Select(VWcsScancopiesRecord Item)
        {
            List<VWcsScancopiesRecord> res = new List<VWcsScancopiesRecord>();
                        OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VWcsScancopiesRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (String)null : Convert.ToString(rdr[1]), 
                        rdr.IsDBNull(2) ?  (String)null : Convert.ToString(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]))
                    );
                }
            }
                        finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}