
<input runat="server" type="hidden" id="Mes10" value='<%$ Resources:Deposit.GlobalResources, Mes10%>'/><!--"Неверный формат номера паспорта!"--> 
<input runat="server" type="hidden" id="Mes11" value='<%$ Resources:Deposit.GlobalResources, Mes11%>'/><!--"Неверный формат серии паспорта!" -->
<input runat="server" type="hidden" id="Mes12" value='<%$ Resources:Deposit.GlobalResources, Mes12%>'/><!--"Некорректное значение!" -->
<input runat="server" type="hidden" id="Mes13" value='<%$ Resources:Deposit.GlobalResources, Mes13%>'/><!--"Заполните поля для поиска!" -->
<input runat="server" type="hidden" id="Mes14" value='<%$ Resources:Deposit.GlobalResources, Mes14%>'/><!--"Идентификационный код меньше 10 знаков!" -->
<input runat="server" type="hidden" id="Mes15" value='<%$ Resources:Deposit.GlobalResources, Mes15%>'/><!--"Заменить нулями?" -->
<input runat="server" type="hidden" id="Mes16" value='<%$ Resources:Deposit.GlobalResources, Mes16%>'/><!--"Выберите доп.соглашение для заключения!" -->
<input runat="server" type="hidden" id="Mes17" value='<%$ Resources:Deposit.GlobalResources, Mes17%>'/><!--"Выберите довереное лицо!" -->
<input runat="server" type="hidden" id="Mes18" value='<%$ Resources:Deposit.GlobalResources, Mes18%>'/><!--"Выберите доп.соглашение для печати!" -->
<input runat="server" type="hidden" id="Mes19" value='<%$ Resources:Deposit.GlobalResources, Mes19%>'/><!--"Выберите доп.соглашение для отмены!" -->
<input runat="server" type="hidden" id="Mes20" value='<%$ Resources:Deposit.GlobalResources, Mes20%>'/><!--"Выберите активное доп. соглашение о правах бенефициара!" -->
<input runat="server" type="hidden" id="Mes21" value='<%$ Resources:Deposit.GlobalResources, Mes21%>'/><!--"Выберите шаблон!" -->
<input runat="server" type="hidden" id="Mes22" value='<%$ Resources:Deposit.GlobalResources, Mes22%>'/><!--"Выберите операцию!" -->
<input runat="server" type="hidden" id="Mes23" value='<%$ Resources:Deposit.GlobalResources, Mes23%>'/><!--"Выберите депозит!" -->
<input runat="server" type="hidden" id="Mes24" value='<%$ Resources:Deposit.GlobalResources, Mes24%>'/><!--"Выберите клиента!" -->
<input runat="server" type="hidden" id="Mes25" value='<%$ Resources:Deposit.GlobalResources, Mes25%>'/><!--"Выберите письмо для формирования!" -->
<input runat="server" type="hidden" id="Mes26" value='<%$ Resources:Deposit.GlobalResources, Mes26%>'/><!--"Ставка не поменялась!" -->
<input runat="server" type="hidden" id="Mes27" value='<%$ Resources:Deposit.GlobalResources, Mes27%>'/><!--"Необходимо заполнить!" -->
<input runat="server" type="hidden" id="Mes28" value='<%$ Resources:Deposit.GlobalResources, Mes28%>'/><!--"Выберите тип депозитного договора!" -->
<input runat="server" type="hidden" id="Mes29" value='<%$ Resources:Deposit.GlobalResources, Mes29%>'/><!--"Сумма меньше минимальной допустимой!" -->
<input runat="server" type="hidden" id="Mes43" value='<%$ Resources:Deposit.GlobalResources, Mes43%>'/><!--"Заповніть хоча б одне поле адреси крім населеного пункта!" />-->