CREATE OR REPLACE FORCE VIEW BARS.CC_POTR
(
   ID,
   NAME,
   S260
)
AS
   SELECT s.r020 || s.ob22, SUBSTR (s.txt, 1, 250), c.s260
     FROM sb_ob22 s, cck_ob22 c
    WHERE     s.d_close IS NULL
          AND s.r020 = c.nbs(+)
          AND s.ob22 = c.ob22(+)
          AND r020 = SUBSTR (pul.get_mas_ini_val ('NBS_AIM'), 1, 4);



GRANT DELETE, INSERT, SELECT, UPDATE, FLASHBACK ON BARS.CC_POTR TO BARS_ACCESS_DEFROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON BARS.CC_POTR TO RCC_DEAL;

GRANT DELETE, INSERT, SELECT, UPDATE, FLASHBACK ON BARS.CC_POTR TO WR_ALL_RIGHTS;
