 -- виртуальные  обороты  по Ѕал+об22 дл¤ @37)
CREATE OR REPLACE FORCE VIEW BARS.SALDO_V37 AS SELECT KF,FDAT,kv,NBS,ob22,POS,NBS1,OB22_1,SUM (DOS) dos, SUM (KOS) kos FROM SALDO_V GROUP BY KF, FDAT,  kv,   NBS,  ob22,  POS, NBS1, OB22_1;

GRANT SELECT ON BARS.SALDO_V37 TO BARS_ACCESS_DEFROLE;