

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS/View/V_CM_CLIENT.sql =========*** Run *** ==
PROMPT ===================================================================================== 


PROMPT *** Create  view V_CM_CLIENT ***

  CREATE OR REPLACE FORCE VIEW BARS.V_CM_CLIENT ("ARC", "ID", "DATEIN", "DATEMOD", "OPER_TYPE", "OPER_STATUS", "RESP_TXT", "BRANCH", "OPENDATE", "REGNUMBERCLIENT", "REGNUMBEROWNER", "CLIENTTYPE", "TAXPAYERIDENTIFIER", "SHORTNAME", "FIRSTNAME", "LASTNAME", "MIDDLENAME", "ENGFIRSTNAME", "ENGLASTNAME", "COUNTRY", "RESIDENT", "WORK", "OFFICE", "DATE_W", "ISVIP", "K060", "COMPANYNAME", "SHORTCOMPANYNAME", "PERSONALISATIONNAME", "KLAS_CLIENT_ID", "CONTACTPERSON", "BIRTHDATE", "BIRTHPLACE", "GENDER", "ADDR1_CITYNAME", "ADDR1_PCODE", "ADDR1_DOMAIN", "ADDR1_REGION", "ADDR1_STREET", "ADDR2_CITYNAME", "ADDR2_PCODE", "ADDR2_DOMAIN", "ADDR2_REGION", "ADDR2_STREET", "EMAIL", "PHONENUMBER", "PHONENUMBER_MOB", "PHONENUMBER_DOD", "FAX", "TYPEDOC", "PASPNUM", "PASPSERIES", "PASPDATE", "PASPISSUER", "FOREIGNPASPNUM", "FOREIGNPASPSERIES", "FOREIGNPASPDATE", "FOREIGNPASPENDDATE", "FOREIGNPASPISSUER", "CONTRACTNUMBER", "PRODUCTCODE", "CARD_TYPE", "CNTM", "PIND", "OKPO_SYSORG", "KOD_SYSORG", "CL_RNK", "CL_DT_ISS", "CARD_BR_ISS", "CARD_ADDR_ISS", "DELIVERY_BR", "RNK", "ACC") AS 
  select 0 arc, id,
       datein,
       datemod,
       oper_type,
       oper_status,
       resp_txt,
       branch,
       opendate,
       regnumberclient,
       regnumberowner,
       clienttype,
       taxpayeridentifier,
       shortname,
       firstname,
       lastname,
       middlename,
       engfirstname,
       englastname,
       country,
       resident,
       work,
       office,
       date_w,
       isvip,
       k060,
       companyname,
       shortcompanyname,
       personalisationname,
       klas_client_id,
       contactperson,
       birthdate,
       birthplace,
       gender,
       addr1_cityname,
       addr1_pcode,
       addr1_domain,
       addr1_region,
       addr1_street,
       addr2_cityname,
       addr2_pcode,
       addr2_domain,
       addr2_region,
       addr2_street,
       email,
       phonenumber,
       phonenumber_mob,
       phonenumber_dod,
       fax,
       typedoc,
       paspnum,
       paspseries,
       paspdate,
       paspissuer,
       foreignpaspnum,
       foreignpaspseries,
       foreignpaspdate,
       foreignpaspenddate,
       foreignpaspissuer,
       contractnumber,
       productcode,
       card_type,
       cntm,
       pind,
       okpo_sysorg,
       kod_sysorg,
       cl_rnk,
       cl_dt_iss,
       card_br_iss,
       card_addr_iss,
       delivery_br,
       rnk, acc
  from cm_client_que
union all
select 1 arc, id,
       datein,
       datemod,
       oper_type,
       oper_status,
       resp_txt,
       branch,
       opendate,
       regnumberclient,
       regnumberowner,
       clienttype,
       taxpayeridentifier,
       shortname,
       firstname,
       lastname,
       middlename,
       engfirstname,
       englastname,
       country,
       resident,
       work,
       office,
       date_w,
       isvip,
       k060,
       companyname,
       shortcompanyname,
       personalisationname,
       klas_client_id,
       contactperson,
       birthdate,
       birthplace,
       gender,
       addr1_cityname,
       addr1_pcode,
       addr1_domain,
       addr1_region,
       addr1_street,
       addr2_cityname,
       addr2_pcode,
       addr2_domain,
       addr2_region,
       addr2_street,
       email,
       phonenumber,
       phonenumber_mob,
       phonenumber_dod,
       fax,
       typedoc,
       paspnum,
       paspseries,
       paspdate,
       paspissuer,
       foreignpaspnum,
       foreignpaspseries,
       foreignpaspdate,
       foreignpaspenddate,
       foreignpaspissuer,
       contractnumber,
       productcode,
       card_type,
       cntm,
       pind,
       okpo_sysorg,
       kod_sysorg,
       cl_rnk,
       cl_dt_iss,
       card_br_iss,
       card_addr_iss,
       delivery_br,
       rnk, acc
  from cm_client_que_arc
 where chgaction = 3 or (chgaction = 2 and oper_status = 3);

PROMPT *** Create  grants  V_CM_CLIENT ***
grant SELECT                                                                 on V_CM_CLIENT     to BARSREADER_ROLE;
grant DELETE,FLASHBACK,INSERT,SELECT,UPDATE                                  on V_CM_CLIENT     to BARS_ACCESS_DEFROLE;
grant DELETE,INSERT,SELECT,UPDATE                                            on V_CM_CLIENT     to OW;
grant SELECT                                                                 on V_CM_CLIENT     to UPLD;
grant FLASHBACK,SELECT                                                       on V_CM_CLIENT     to WR_REFREAD;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS/View/V_CM_CLIENT.sql =========*** End *** ==
PROMPT ===================================================================================== 
