CREATE OR REPLACE FORCE VIEW BARS.V_MBDK_PRODUCT as 
SELECT M.vidd, m.vidd||'.'||M.name name , T.tipd,   
(CASE
WHEN t.vidd IN (2700,2701,3660,3661) THEN 1 ELSE 2 END) tipp  
FROM cc_vidd t, mbdk_OB22 M    
WHERE M.VIDD = T.VIDD ;

show err;

GRANT DELETE, INSERT, SELECT, UPDATE ON BARS.V_MBDK_PRODUCT TO BARS_ACCESS_DEFROLE;