/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public partial class WcsQuestionTypes : BbTable<WcsQuestionTypesRecord, WcsQuestionTypesFilters>
    {
        public List<WcsQuestionTypesRecord> SelectTypes(String TYPES)
        {
            String lTYPES = TYPES.Trim();
            lTYPES = (lTYPES.StartsWith(",") ? lTYPES.Substring(1) : lTYPES);
            lTYPES = (lTYPES.EndsWith(",") ? lTYPES.Substring(0, lTYPES.Length - 1) : lTYPES);

            string[] arTYPES = TYPES.Split(',');

            if (arTYPES.Length > 0)
            {
                List<String> Values = new List<String>();
                foreach (string TYPE in arTYPES)
                {
                    Values.Add(TYPE);
                }

                this.Filter.ID.In(Values);
            }

            return Select();
        }
    }
}