
<input runat="server" type="hidden" id="wgPageSizeText" meta:resourcekey="wgPageSizeText" value="Cтрок на странице:" />
<input runat="server" type="hidden" id="wgPrevPage" meta:resourcekey="wgPrevPage" value="Предыдущая страница" />
<input runat="server" type="hidden" id="wgNextPage" meta:resourcekey="wgNextPage" value="Следующая страница" />
<input runat="server" type="hidden" id="wgRowsInTable" meta:resourcekey="wgRowsInTable" value="Количество строк в таблице" />
<input runat="server" type="hidden" id="wgAscending" meta:resourcekey="wgAscending" value="По возрастанию" />
<input runat="server" type="hidden" id="wgDescending" meta:resourcekey="wgDescending" value="По убыванию" />
<input runat="server" type="hidden" id="wgSave" meta:resourcekey="wgSave" value="Сохранить" />
<input runat="server" type="hidden" id="wgCancel" meta:resourcekey="wgCancel" value="Отмена" />
<input runat="server" type="hidden" id="wgSetFilter" meta:resourcekey="wgSetFilter" value="Установить фильтр" />

<input type="hidden" id="wgFilter" value="Фильтр" />
<input type="hidden" id="wgAttribute" value="Атрибут" />
<input type="hidden" id="wgOperator" value="Оператор" />
<input type="hidden" id="wgLike" value="похож" />
<input type="hidden" id="wgNotLike" value="не похож" />
<input type="hidden" id="wgIsNull" value="пустой" />
<input type="hidden" id="wgIsNotNull" value="не пустой" />
<input type="hidden" id="wgOneOf" value="один из" />
<input type="hidden" id="wgNotOneOf" value="ни один из" />
<input type="hidden" id="wgValue" value="Значение" />
<input type="hidden" id="wgApply" value="Применить" />
<input type="hidden" id="wgFilterCancel" value="Отменить" />
<input type="hidden" id="wgCurrentFilter" value="Текущий фильтр:" />
<input type="hidden" id="wgDeleteRow" value="Удалить строку" />
<input type="hidden" id="wgDeleteAll" value="Удалить все" />

