prompt create tablespace BRSDMIMP

begin
	execute immediate q'[
		CREATE TABLESPACE BRSDMIMP DATAFILE 
		'+DATA1' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED,
		'+DATA1' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED,
		'+DATA1' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED,
		'+DATA1' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED,
		'+DATA1' SIZE 128M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
		NOLOGGING
		ONLINE
		EXTENT MANAGEMENT LOCAL AUTOALLOCATE
		SEGMENT SPACE MANAGEMENT AUTO]';
exception
	when others then
		if sqlcode = -1543 then null; else raise; end if;
end;
/