/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace Bars.Ins
{
    public sealed class VInsTariffsRecord : BbRecord
    {
        public VInsTariffsRecord(): base()
        {
            fillFields();
        }
        public VInsTariffsRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VInsTariffsRecord(BbDataSource Parent, OracleDecimal RowScn, String TARIFF_ID, String NAME, Decimal? MIN_VALUE, Decimal? MIN_PERC, Decimal? MAX_VALUE, Decimal? MAX_PERC, Decimal? AMORT, Decimal? PER_CNT)
            : this(Parent)
        {
            this.TARIFF_ID = TARIFF_ID;
            this.NAME = NAME;
            this.MIN_VALUE = MIN_VALUE;
            this.MIN_PERC = MIN_PERC;
            this.MAX_VALUE = MAX_VALUE;
            this.MAX_PERC = MAX_PERC;
            this.AMORT = AMORT;
            this.PER_CNT = PER_CNT;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("TARIFF_ID", OracleDbType.Varchar2, false, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Ідентифікатор"));
            Fields.Add( new BbField("NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Найменування"));
            Fields.Add( new BbField("MIN_VALUE", OracleDbType.Decimal, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Мінімальна сума"));
            Fields.Add( new BbField("MIN_PERC", OracleDbType.Decimal, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Мінімальний процент"));
            Fields.Add( new BbField("MAX_VALUE", OracleDbType.Decimal, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Максимальна сума"));
            Fields.Add( new BbField("MAX_PERC", OracleDbType.Decimal, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Максимальний процент"));
            Fields.Add( new BbField("AMORT", OracleDbType.Decimal, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Коефіцієнт амортизації"));
            Fields.Add( new BbField("PER_CNT", OracleDbType.Decimal, true, false, false, false, false, "V_INS_TARIFFS", ObjectTypes.View, "Страхові тарифи (Представлення)", "Кіл-ть періодів"));        
        }
        public String TARIFF_ID { get { return (String)FindField("TARIFF_ID").Value; } set {SetField("TARIFF_ID", value);} }
        public String NAME { get { return (String)FindField("NAME").Value; } set {SetField("NAME", value);} }
        public Decimal? MIN_VALUE { get { return (Decimal?)FindField("MIN_VALUE").Value; } set {SetField("MIN_VALUE", value);} }
        public Decimal? MIN_PERC { get { return (Decimal?)FindField("MIN_PERC").Value; } set {SetField("MIN_PERC", value);} }
        public Decimal? MAX_VALUE { get { return (Decimal?)FindField("MAX_VALUE").Value; } set {SetField("MAX_VALUE", value);} }
        public Decimal? MAX_PERC { get { return (Decimal?)FindField("MAX_PERC").Value; } set {SetField("MAX_PERC", value);} }
        public Decimal? AMORT { get { return (Decimal?)FindField("AMORT").Value; } set {SetField("AMORT", value);} }
        public Decimal? PER_CNT { get { return (Decimal?)FindField("PER_CNT").Value; } set {SetField("PER_CNT", value);} }
    }

    public sealed class VInsTariffsFilters : BbFilters
    {
        public VInsTariffsFilters(BbDataSource Parent) : base (Parent)
        {
            TARIFF_ID = new BBVarchar2Filter(this, "TARIFF_ID");
            NAME = new BBVarchar2Filter(this, "NAME");
            MIN_VALUE = new BBDecimalFilter(this, "MIN_VALUE");
            MIN_PERC = new BBDecimalFilter(this, "MIN_PERC");
            MAX_VALUE = new BBDecimalFilter(this, "MAX_VALUE");
            MAX_PERC = new BBDecimalFilter(this, "MAX_PERC");
            AMORT = new BBDecimalFilter(this, "AMORT");
            PER_CNT = new BBDecimalFilter(this, "PER_CNT");
        }
        public BBVarchar2Filter TARIFF_ID;
        public BBVarchar2Filter NAME;
        public BBDecimalFilter MIN_VALUE;
        public BBDecimalFilter MIN_PERC;
        public BBDecimalFilter MAX_VALUE;
        public BBDecimalFilter MAX_PERC;
        public BBDecimalFilter AMORT;
        public BBDecimalFilter PER_CNT;
    }

    public partial class VInsTariffs : BbTable<VInsTariffsRecord, VInsTariffsFilters>
    {
        public VInsTariffs() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VInsTariffs(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VInsTariffsRecord> Select(VInsTariffsRecord Item)
        {
            List<VInsTariffsRecord> res = new List<VInsTariffsRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VInsTariffsRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (String)null : Convert.ToString(rdr[1]), 
                        rdr.IsDBNull(2) ?  (String)null : Convert.ToString(rdr[2]), 
                        rdr.IsDBNull(3) ?  (Decimal?)null : Convert.ToDecimal(rdr[3]), 
                        rdr.IsDBNull(4) ?  (Decimal?)null : Convert.ToDecimal(rdr[4]), 
                        rdr.IsDBNull(5) ?  (Decimal?)null : Convert.ToDecimal(rdr[5]), 
                        rdr.IsDBNull(6) ?  (Decimal?)null : Convert.ToDecimal(rdr[6]), 
                        rdr.IsDBNull(7) ?  (Decimal?)null : Convert.ToDecimal(rdr[7]), 
                        rdr.IsDBNull(8) ?  (Decimal?)null : Convert.ToDecimal(rdr[8]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}