/*
    AUTOGENERATED! Do not modify this code.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Collections.Specialized;
using System.Data;
using System.Web.Configuration;
using Oracle.DataAccess.Client;
using Oracle.DataAccess.Types;
using ibank.core;
using Bars.Classes;

namespace credit
{
    public sealed class VCimCreditContractsRecord : BbRecord
    {
        public VCimCreditContractsRecord(): base()
        {
            fillFields();
        }
        public VCimCreditContractsRecord(BbDataSource Parent) : base (Parent)
        {
            fillFields();
        }
        public VCimCreditContractsRecord(BbDataSource Parent, OracleDecimal RowScn, Decimal? CONTR_ID, Decimal? CONTR_TYPE, String CONTR_TYPE_NAME, String NUM, String SUBNUM, Decimal? RNK, String OKPO, String NMK, String NMKK, String PASSPORT, Decimal? CUSTTYPE, String ND, String VED, String VED_NAME, DateTime? OPEN_DATE, DateTime? CLOSE_DATE, Decimal? KV, Decimal? S, Decimal? BENEF_ID, String BENEF_NAME, String BENEF_ADR, Decimal? COUNTRY_ID, String COUNTRY_NAME, Decimal? STATUS_ID, String STATUS_NAME, String COMMENTS, String BRANCH, String BRANCH_NAME, Decimal? OWNER, Decimal? OWNER_UID, String OWNER_NAME, String BIC, String B010, String BANK_NAME, String SERVICE_BRANCH, String EA_URL, Decimal? PERCENT_NBU, Decimal? S_LIMIT, Decimal? CREDITOR_TYPE, String CREDITOR_TYPE_NAME, Decimal? BORROWER_ID, Decimal? CREDIT_TYPE, String CREDIT_TYPE_NAME, Decimal? CREDIT_TERM, String CREDIT_TERM_NAME, Decimal? CREDIT_PREPAY, String CREDIT_PREPAY_NAME, String NAME, String ADD_AGREE, Decimal? PERCENT_NBU_TYPE, String PERCENT_NBU_NAME, String PERCENT_NBU_INFO, DateTime? R_AGREE_DATE, String R_AGREE_NO, Decimal? PREV_DDOC_KEY, String PREV_REESTR_ATTR, DateTime? ENDING_DATE_INDIV, String PARENT_CH_DATA, DateTime? ENDING_DATE, DateTime? DATE_TERM_CHANGE, Decimal? S_IN_PL, Decimal? S_OUT_PL, Decimal? S_V_PR, String Z_PR, String S_PR_NBU, Decimal? S_DOD_PL, Decimal? F503_REASON, Decimal? F503_STATE, String F503_NOTE, Decimal? F504_REASON, String F504_NOTE)
            : this(Parent)
        {
            this.CONTR_ID = CONTR_ID;
            this.CONTR_TYPE = CONTR_TYPE;
            this.CONTR_TYPE_NAME = CONTR_TYPE_NAME;
            this.NUM = NUM;
            this.SUBNUM = SUBNUM;
            this.RNK = RNK;
            this.OKPO = OKPO;
            this.NMK = NMK;
            this.NMKK = NMKK;
            this.PASSPORT = PASSPORT;
            this.CUSTTYPE = CUSTTYPE;
            this.ND = ND;
            this.VED = VED;
            this.VED_NAME = VED_NAME;
            this.OPEN_DATE = OPEN_DATE;
            this.CLOSE_DATE = CLOSE_DATE;
            this.KV = KV;
            this.S = S;
            this.BENEF_ID = BENEF_ID;
            this.BENEF_NAME = BENEF_NAME;
            this.BENEF_ADR = BENEF_ADR;
            this.COUNTRY_ID = COUNTRY_ID;
            this.COUNTRY_NAME = COUNTRY_NAME;
            this.STATUS_ID = STATUS_ID;
            this.STATUS_NAME = STATUS_NAME;
            this.COMMENTS = COMMENTS;
            this.BRANCH = BRANCH;
            this.BRANCH_NAME = BRANCH_NAME;
            this.OWNER = OWNER;
            this.OWNER_UID = OWNER_UID;
            this.OWNER_NAME = OWNER_NAME;
            this.BIC = BIC;
            this.B010 = B010;
            this.BANK_NAME = BANK_NAME;
            this.SERVICE_BRANCH = SERVICE_BRANCH;
            this.EA_URL = EA_URL;
            this.PERCENT_NBU = PERCENT_NBU;
            this.S_LIMIT = S_LIMIT;
            this.CREDITOR_TYPE = CREDITOR_TYPE;
            this.CREDITOR_TYPE_NAME = CREDITOR_TYPE_NAME;
            this.BORROWER_ID = BORROWER_ID;
            this.CREDIT_TYPE = CREDIT_TYPE;
            this.CREDIT_TYPE_NAME = CREDIT_TYPE_NAME;
            this.CREDIT_TERM = CREDIT_TERM;
            this.CREDIT_TERM_NAME = CREDIT_TERM_NAME;
            this.CREDIT_PREPAY = CREDIT_PREPAY;
            this.CREDIT_PREPAY_NAME = CREDIT_PREPAY_NAME;
            this.NAME = NAME;
            this.ADD_AGREE = ADD_AGREE;
            this.PERCENT_NBU_TYPE = PERCENT_NBU_TYPE;
            this.PERCENT_NBU_NAME = PERCENT_NBU_NAME;
            this.PERCENT_NBU_INFO = PERCENT_NBU_INFO;
            this.R_AGREE_DATE = R_AGREE_DATE;
            this.R_AGREE_NO = R_AGREE_NO;
            this.PREV_DDOC_KEY = PREV_DDOC_KEY;
            this.PREV_REESTR_ATTR = PREV_REESTR_ATTR;
            this.ENDING_DATE_INDIV = ENDING_DATE_INDIV;
            this.PARENT_CH_DATA = PARENT_CH_DATA;
            this.ENDING_DATE = ENDING_DATE;
            this.DATE_TERM_CHANGE = DATE_TERM_CHANGE;
            this.S_IN_PL = S_IN_PL;
            this.S_OUT_PL = S_OUT_PL;
            this.S_V_PR = S_V_PR;
            this.Z_PR = Z_PR;
            this.S_PR_NBU = S_PR_NBU;
            this.S_DOD_PL = S_DOD_PL;
            this.F503_REASON = F503_REASON;
            this.F503_STATE = F503_STATE;
            this.F503_NOTE = F503_NOTE;
            this.F504_REASON = F504_REASON;
            this.F504_NOTE = F504_NOTE;
            this.RowScn = RowScn;
            this.IsRowscnSupported = false;
            this.ClearChanges();
        }
        private void fillFields()
        {
            Fields.Add( new BbField("CONTR_ID", OracleDbType.Decimal, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Внутрішній код контракту"));
            Fields.Add( new BbField("CONTR_TYPE", OracleDbType.Decimal, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Тип контракту"));
            Fields.Add( new BbField("CONTR_TYPE_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Найменування типу контракту"));
            Fields.Add( new BbField("NUM", OracleDbType.Varchar2, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Символьний номер контракту"));
            Fields.Add( new BbField("SUBNUM", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Субномер контракту"));
            Fields.Add( new BbField("RNK", OracleDbType.Decimal, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Внутрішній номер (rnk) контрагента контракту"));
            Fields.Add( new BbField("OKPO", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "ОКПО контрагента контракту"));
            Fields.Add( new BbField("NMK", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Найменування контрагента"));
            Fields.Add( new BbField("NMKK", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Коротке найменування контрагента"));
            Fields.Add( new BbField("PASSPORT", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Серія та номер паспорта"));
            Fields.Add( new BbField("CUSTTYPE", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Тип контрагента (1 -банк, 2 - ЮО, 3-ФО)"));
            Fields.Add( new BbField("ND", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Номер договору контрагента"));
            Fields.Add( new BbField("VED", OracleDbType.Char, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Код виду економічної діяльності"));
            Fields.Add( new BbField("VED_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Вид економічної діяльності"));
            Fields.Add( new BbField("OPEN_DATE", OracleDbType.Date, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Дата відкриття"));
            Fields.Add( new BbField("CLOSE_DATE", OracleDbType.Date, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Дата закриття "));
            Fields.Add( new BbField("KV", OracleDbType.Decimal, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Валюта контракту"));
            Fields.Add( new BbField("S", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Сума контракту"));
            Fields.Add( new BbField("BENEF_ID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Код клієнта-нерезидента"));
            Fields.Add( new BbField("BENEF_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Найменування клієнта-нерезидента"));
            Fields.Add( new BbField("BENEF_ADR", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Адреса клієнта-нерезидента"));
            Fields.Add( new BbField("COUNTRY_ID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "id країни клієнта-нерезидента"));
            Fields.Add( new BbField("COUNTRY_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва країни клієнта-нерезидента"));
            Fields.Add( new BbField("STATUS_ID", OracleDbType.Decimal, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Код статусу контракту"));
            Fields.Add( new BbField("STATUS_NAME", OracleDbType.Varchar2, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Статус контракту"));
            Fields.Add( new BbField("COMMENTS", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Уточнення предмету контракту"));
            Fields.Add( new BbField("BRANCH", OracleDbType.Varchar2, false, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Код установи"));
            Fields.Add( new BbField("BRANCH_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва установи"));
            Fields.Add( new BbField("OWNER", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Установа - власник контракту (1 - так, 0 - ні)"));
            Fields.Add( new BbField("OWNER_UID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Id користувача, за яким закріплено контракт"));
            Fields.Add( new BbField("OWNER_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "ПІБ користувача, за яким закріплено контракт"));
            Fields.Add( new BbField("BIC", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "BIC-код банку-нерезидента"));
            Fields.Add( new BbField("B010", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Код B010 банку нерезидента"));
            Fields.Add( new BbField("BANK_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва банку нерезидента"));
            Fields.Add( new BbField("SERVICE_BRANCH", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Установа, відповідальна за прийом первинних документів"));
            Fields.Add( new BbField("EA_URL", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Адреса сервера електронного архіву ВК"));
            Fields.Add( new BbField("PERCENT_NBU", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Максимальна процентна ставка НБУ"));
            Fields.Add( new BbField("S_LIMIT", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Ліміт заборгованості"));
            Fields.Add( new BbField("CREDITOR_TYPE", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "ID типу кредитора"));
            Fields.Add( new BbField("CREDITOR_TYPE_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва типу кредитора"));
            Fields.Add( new BbField("BORROWER_ID", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "ID виду позичальника"));
            Fields.Add( new BbField("CREDIT_TYPE", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "id типу кредиту"));
            Fields.Add( new BbField("CREDIT_TYPE_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва типу кредиту"));
            Fields.Add( new BbField("CREDIT_TERM", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "id коду строковості кредиту"));
            Fields.Add( new BbField("CREDIT_TERM_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва коду строковості кредиту"));
            Fields.Add( new BbField("CREDIT_PREPAY", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Можливість дострокового погашення (id)"));
            Fields.Add( new BbField("CREDIT_PREPAY_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Можливість дострокового погашення (назва)"));
            Fields.Add( new BbField("NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва договору"));
            Fields.Add( new BbField("ADD_AGREE", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Додаткові угоди"));
            Fields.Add( new BbField("PERCENT_NBU_TYPE", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "id назви максимальної процентної ставки НБУ"));
            Fields.Add( new BbField("PERCENT_NBU_NAME", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Назва максимальної процентної ставки НБУ"));
            Fields.Add( new BbField("PERCENT_NBU_INFO", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Додаткова інформація про максимальну процентну ставку НБУ"));
            Fields.Add( new BbField("R_AGREE_DATE", OracleDbType.Date, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Дата реєстрації контракту (заповнюється при змінах)"));
            Fields.Add( new BbField("R_AGREE_NO", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Номер реєстрації контракту (заповнюється при змінах)"));
            Fields.Add( new BbField("PREV_DDOC_KEY", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Реєстраційний серверний номер (заповнюється при змінах)"));
            Fields.Add( new BbField("PREV_REESTR_ATTR", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Зміни до контракту"));
            Fields.Add( new BbField("ENDING_DATE_INDIV", OracleDbType.Date, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Кінцева дата індивідуального строку дії реєстрації контракту"));
            Fields.Add( new BbField("PARENT_CH_DATA", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Інформація про короткостроковий контракт (заповнюється при перереєстрації з короткострокового у довгостроковий)"));
            Fields.Add( new BbField("ENDING_DATE", OracleDbType.Date, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Строк дії реєстрації контракту (заповнюється при продовженні строку)"));
            Fields.Add( new BbField("DATE_TERM_CHANGE", OracleDbType.Date, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", ""));
            Fields.Add( new BbField("S_IN_PL", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Загальна сума надходжень"));
            Fields.Add( new BbField("S_OUT_PL", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Сума вихідних платежів погашення тіла (s_in_pl-s_out_pl) - Заборгованість по тілу кредиту"));
            Fields.Add( new BbField("S_V_PR", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Виплачені проценти"));
            Fields.Add( new BbField("Z_PR", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Заборгованість по процентах (s_v_pr+z_pr) - Нараховані проценти"));
            Fields.Add( new BbField("S_PR_NBU", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Розраховані проценти за ставкою НБУ"));
            Fields.Add( new BbField("S_DOD_PL", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Сума додаткових платежів"));
            Fields.Add( new BbField("F503_REASON", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Підстави подання звіту Ф503"));
            Fields.Add( new BbField("F503_STATE", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Стан розрахунків за контрактом для звіту Ф503"));
            Fields.Add( new BbField("F503_NOTE", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Примітка звіту Ф503"));
            Fields.Add( new BbField("F504_REASON", OracleDbType.Decimal, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Підстави подання звіту Ф504"));
            Fields.Add( new BbField("F504_NOTE", OracleDbType.Varchar2, true, false, false, false, false, "V_CIM_CREDIT_CONTRACTS", ObjectTypes.View, "Список кредитних контрактів v 1.00.02", "Примітка звіту Ф504"));        
        }
        public Decimal? CONTR_ID { get { return (Decimal?)FindField("CONTR_ID").Value; } set {SetField("CONTR_ID", value);} }
        public Decimal? CONTR_TYPE { get { return (Decimal?)FindField("CONTR_TYPE").Value; } set {SetField("CONTR_TYPE", value);} }
        public String CONTR_TYPE_NAME { get { return (String)FindField("CONTR_TYPE_NAME").Value; } set {SetField("CONTR_TYPE_NAME", value);} }
        public String NUM { get { return (String)FindField("NUM").Value; } set {SetField("NUM", value);} }
        public String SUBNUM { get { return (String)FindField("SUBNUM").Value; } set {SetField("SUBNUM", value);} }
        public Decimal? RNK { get { return (Decimal?)FindField("RNK").Value; } set {SetField("RNK", value);} }
        public String OKPO { get { return (String)FindField("OKPO").Value; } set {SetField("OKPO", value);} }
        public String NMK { get { return (String)FindField("NMK").Value; } set {SetField("NMK", value);} }
        public String NMKK { get { return (String)FindField("NMKK").Value; } set {SetField("NMKK", value);} }
        public String PASSPORT { get { return (String)FindField("PASSPORT").Value; } set {SetField("PASSPORT", value);} }
        public Decimal? CUSTTYPE { get { return (Decimal?)FindField("CUSTTYPE").Value; } set {SetField("CUSTTYPE", value);} }
        public String ND { get { return (String)FindField("ND").Value; } set {SetField("ND", value);} }
        public String VED { get { return (String)FindField("VED").Value; } set {SetField("VED", value);} }
        public String VED_NAME { get { return (String)FindField("VED_NAME").Value; } set {SetField("VED_NAME", value);} }
        public DateTime? OPEN_DATE { get { return (DateTime?)FindField("OPEN_DATE").Value; } set {SetField("OPEN_DATE", value);} }
        public DateTime? CLOSE_DATE { get { return (DateTime?)FindField("CLOSE_DATE").Value; } set {SetField("CLOSE_DATE", value);} }
        public Decimal? KV { get { return (Decimal?)FindField("KV").Value; } set {SetField("KV", value);} }
        public Decimal? S { get { return (Decimal?)FindField("S").Value; } set {SetField("S", value);} }
        public Decimal? BENEF_ID { get { return (Decimal?)FindField("BENEF_ID").Value; } set {SetField("BENEF_ID", value);} }
        public String BENEF_NAME { get { return (String)FindField("BENEF_NAME").Value; } set {SetField("BENEF_NAME", value);} }
        public String BENEF_ADR { get { return (String)FindField("BENEF_ADR").Value; } set {SetField("BENEF_ADR", value);} }
        public Decimal? COUNTRY_ID { get { return (Decimal?)FindField("COUNTRY_ID").Value; } set {SetField("COUNTRY_ID", value);} }
        public String COUNTRY_NAME { get { return (String)FindField("COUNTRY_NAME").Value; } set {SetField("COUNTRY_NAME", value);} }
        public Decimal? STATUS_ID { get { return (Decimal?)FindField("STATUS_ID").Value; } set {SetField("STATUS_ID", value);} }
        public String STATUS_NAME { get { return (String)FindField("STATUS_NAME").Value; } set {SetField("STATUS_NAME", value);} }
        public String COMMENTS { get { return (String)FindField("COMMENTS").Value; } set {SetField("COMMENTS", value);} }
        public String BRANCH { get { return (String)FindField("BRANCH").Value; } set {SetField("BRANCH", value);} }
        public String BRANCH_NAME { get { return (String)FindField("BRANCH_NAME").Value; } set {SetField("BRANCH_NAME", value);} }
        public Decimal? OWNER { get { return (Decimal?)FindField("OWNER").Value; } set {SetField("OWNER", value);} }
        public Decimal? OWNER_UID { get { return (Decimal?)FindField("OWNER_UID").Value; } set {SetField("OWNER_UID", value);} }
        public String OWNER_NAME { get { return (String)FindField("OWNER_NAME").Value; } set {SetField("OWNER_NAME", value);} }
        public String BIC { get { return (String)FindField("BIC").Value; } set {SetField("BIC", value);} }
        public String B010 { get { return (String)FindField("B010").Value; } set {SetField("B010", value);} }
        public String BANK_NAME { get { return (String)FindField("BANK_NAME").Value; } set {SetField("BANK_NAME", value);} }
        public String SERVICE_BRANCH { get { return (String)FindField("SERVICE_BRANCH").Value; } set {SetField("SERVICE_BRANCH", value);} }
        public String EA_URL { get { return (String)FindField("EA_URL").Value; } set {SetField("EA_URL", value);} }
        public Decimal? PERCENT_NBU { get { return (Decimal?)FindField("PERCENT_NBU").Value; } set {SetField("PERCENT_NBU", value);} }
        public Decimal? S_LIMIT { get { return (Decimal?)FindField("S_LIMIT").Value; } set {SetField("S_LIMIT", value);} }
        public Decimal? CREDITOR_TYPE { get { return (Decimal?)FindField("CREDITOR_TYPE").Value; } set {SetField("CREDITOR_TYPE", value);} }
        public String CREDITOR_TYPE_NAME { get { return (String)FindField("CREDITOR_TYPE_NAME").Value; } set {SetField("CREDITOR_TYPE_NAME", value);} }
        public Decimal? BORROWER_ID { get { return (Decimal?)FindField("BORROWER_ID").Value; } set {SetField("BORROWER_ID", value);} }
        public Decimal? CREDIT_TYPE { get { return (Decimal?)FindField("CREDIT_TYPE").Value; } set {SetField("CREDIT_TYPE", value);} }
        public String CREDIT_TYPE_NAME { get { return (String)FindField("CREDIT_TYPE_NAME").Value; } set {SetField("CREDIT_TYPE_NAME", value);} }
        public Decimal? CREDIT_TERM { get { return (Decimal?)FindField("CREDIT_TERM").Value; } set {SetField("CREDIT_TERM", value);} }
        public String CREDIT_TERM_NAME { get { return (String)FindField("CREDIT_TERM_NAME").Value; } set {SetField("CREDIT_TERM_NAME", value);} }
        public Decimal? CREDIT_PREPAY { get { return (Decimal?)FindField("CREDIT_PREPAY").Value; } set {SetField("CREDIT_PREPAY", value);} }
        public String CREDIT_PREPAY_NAME { get { return (String)FindField("CREDIT_PREPAY_NAME").Value; } set {SetField("CREDIT_PREPAY_NAME", value);} }
        public String NAME { get { return (String)FindField("NAME").Value; } set {SetField("NAME", value);} }
        public String ADD_AGREE { get { return (String)FindField("ADD_AGREE").Value; } set {SetField("ADD_AGREE", value);} }
        public Decimal? PERCENT_NBU_TYPE { get { return (Decimal?)FindField("PERCENT_NBU_TYPE").Value; } set {SetField("PERCENT_NBU_TYPE", value);} }
        public String PERCENT_NBU_NAME { get { return (String)FindField("PERCENT_NBU_NAME").Value; } set {SetField("PERCENT_NBU_NAME", value);} }
        public String PERCENT_NBU_INFO { get { return (String)FindField("PERCENT_NBU_INFO").Value; } set {SetField("PERCENT_NBU_INFO", value);} }
        public DateTime? R_AGREE_DATE { get { return (DateTime?)FindField("R_AGREE_DATE").Value; } set {SetField("R_AGREE_DATE", value);} }
        public String R_AGREE_NO { get { return (String)FindField("R_AGREE_NO").Value; } set {SetField("R_AGREE_NO", value);} }
        public Decimal? PREV_DDOC_KEY { get { return (Decimal?)FindField("PREV_DDOC_KEY").Value; } set {SetField("PREV_DDOC_KEY", value);} }
        public String PREV_REESTR_ATTR { get { return (String)FindField("PREV_REESTR_ATTR").Value; } set {SetField("PREV_REESTR_ATTR", value);} }
        public DateTime? ENDING_DATE_INDIV { get { return (DateTime?)FindField("ENDING_DATE_INDIV").Value; } set {SetField("ENDING_DATE_INDIV", value);} }
        public String PARENT_CH_DATA { get { return (String)FindField("PARENT_CH_DATA").Value; } set {SetField("PARENT_CH_DATA", value);} }
        public DateTime? ENDING_DATE { get { return (DateTime?)FindField("ENDING_DATE").Value; } set {SetField("ENDING_DATE", value);} }
        public DateTime? DATE_TERM_CHANGE { get { return (DateTime?)FindField("DATE_TERM_CHANGE").Value; } set {SetField("DATE_TERM_CHANGE", value);} }
        public Decimal? S_IN_PL { get { return (Decimal?)FindField("S_IN_PL").Value; } set {SetField("S_IN_PL", value);} }
        public Decimal? S_OUT_PL { get { return (Decimal?)FindField("S_OUT_PL").Value; } set {SetField("S_OUT_PL", value);} }
        public Decimal? S_V_PR { get { return (Decimal?)FindField("S_V_PR").Value; } set {SetField("S_V_PR", value);} }
        public String Z_PR { get { return (String)FindField("Z_PR").Value; } set {SetField("Z_PR", value);} }
        public String S_PR_NBU { get { return (String)FindField("S_PR_NBU").Value; } set {SetField("S_PR_NBU", value);} }
        public Decimal? S_DOD_PL { get { return (Decimal?)FindField("S_DOD_PL").Value; } set {SetField("S_DOD_PL", value);} }
        public Decimal? F503_REASON { get { return (Decimal?)FindField("F503_REASON").Value; } set {SetField("F503_REASON", value);} }
        public Decimal? F503_STATE { get { return (Decimal?)FindField("F503_STATE").Value; } set {SetField("F503_STATE", value);} }
        public String F503_NOTE { get { return (String)FindField("F503_NOTE").Value; } set {SetField("F503_NOTE", value);} }
        public Decimal? F504_REASON { get { return (Decimal?)FindField("F504_REASON").Value; } set {SetField("F504_REASON", value);} }
        public String F504_NOTE { get { return (String)FindField("F504_NOTE").Value; } set {SetField("F504_NOTE", value);} }
    }

    public sealed class VCimCreditContractsFilters : BbFilters
    {
        public VCimCreditContractsFilters(BbDataSource Parent) : base (Parent)
        {
            CONTR_ID = new BBDecimalFilter(this, "CONTR_ID");
            CONTR_TYPE = new BBDecimalFilter(this, "CONTR_TYPE");
            CONTR_TYPE_NAME = new BBVarchar2Filter(this, "CONTR_TYPE_NAME");
            NUM = new BBVarchar2Filter(this, "NUM");
            SUBNUM = new BBVarchar2Filter(this, "SUBNUM");
            RNK = new BBDecimalFilter(this, "RNK");
            OKPO = new BBVarchar2Filter(this, "OKPO");
            NMK = new BBVarchar2Filter(this, "NMK");
            NMKK = new BBVarchar2Filter(this, "NMKK");
            PASSPORT = new BBVarchar2Filter(this, "PASSPORT");
            CUSTTYPE = new BBDecimalFilter(this, "CUSTTYPE");
            ND = new BBVarchar2Filter(this, "ND");
            VED = new BBCharFilter(this, "VED");
            VED_NAME = new BBVarchar2Filter(this, "VED_NAME");
            OPEN_DATE = new BBDateFilter(this, "OPEN_DATE");
            CLOSE_DATE = new BBDateFilter(this, "CLOSE_DATE");
            KV = new BBDecimalFilter(this, "KV");
            S = new BBDecimalFilter(this, "S");
            BENEF_ID = new BBDecimalFilter(this, "BENEF_ID");
            BENEF_NAME = new BBVarchar2Filter(this, "BENEF_NAME");
            BENEF_ADR = new BBVarchar2Filter(this, "BENEF_ADR");
            COUNTRY_ID = new BBDecimalFilter(this, "COUNTRY_ID");
            COUNTRY_NAME = new BBVarchar2Filter(this, "COUNTRY_NAME");
            STATUS_ID = new BBDecimalFilter(this, "STATUS_ID");
            STATUS_NAME = new BBVarchar2Filter(this, "STATUS_NAME");
            COMMENTS = new BBVarchar2Filter(this, "COMMENTS");
            BRANCH = new BBVarchar2Filter(this, "BRANCH");
            BRANCH_NAME = new BBVarchar2Filter(this, "BRANCH_NAME");
            OWNER = new BBDecimalFilter(this, "OWNER");
            OWNER_UID = new BBDecimalFilter(this, "OWNER_UID");
            OWNER_NAME = new BBVarchar2Filter(this, "OWNER_NAME");
            BIC = new BBVarchar2Filter(this, "BIC");
            B010 = new BBVarchar2Filter(this, "B010");
            BANK_NAME = new BBVarchar2Filter(this, "BANK_NAME");
            SERVICE_BRANCH = new BBVarchar2Filter(this, "SERVICE_BRANCH");
            EA_URL = new BBVarchar2Filter(this, "EA_URL");
            PERCENT_NBU = new BBDecimalFilter(this, "PERCENT_NBU");
            S_LIMIT = new BBDecimalFilter(this, "S_LIMIT");
            CREDITOR_TYPE = new BBDecimalFilter(this, "CREDITOR_TYPE");
            CREDITOR_TYPE_NAME = new BBVarchar2Filter(this, "CREDITOR_TYPE_NAME");
            BORROWER_ID = new BBDecimalFilter(this, "BORROWER_ID");
            CREDIT_TYPE = new BBDecimalFilter(this, "CREDIT_TYPE");
            CREDIT_TYPE_NAME = new BBVarchar2Filter(this, "CREDIT_TYPE_NAME");
            CREDIT_TERM = new BBDecimalFilter(this, "CREDIT_TERM");
            CREDIT_TERM_NAME = new BBVarchar2Filter(this, "CREDIT_TERM_NAME");
            CREDIT_PREPAY = new BBDecimalFilter(this, "CREDIT_PREPAY");
            CREDIT_PREPAY_NAME = new BBVarchar2Filter(this, "CREDIT_PREPAY_NAME");
            NAME = new BBVarchar2Filter(this, "NAME");
            ADD_AGREE = new BBVarchar2Filter(this, "ADD_AGREE");
            PERCENT_NBU_TYPE = new BBDecimalFilter(this, "PERCENT_NBU_TYPE");
            PERCENT_NBU_NAME = new BBVarchar2Filter(this, "PERCENT_NBU_NAME");
            PERCENT_NBU_INFO = new BBVarchar2Filter(this, "PERCENT_NBU_INFO");
            R_AGREE_DATE = new BBDateFilter(this, "R_AGREE_DATE");
            R_AGREE_NO = new BBVarchar2Filter(this, "R_AGREE_NO");
            PREV_DDOC_KEY = new BBDecimalFilter(this, "PREV_DDOC_KEY");
            PREV_REESTR_ATTR = new BBVarchar2Filter(this, "PREV_REESTR_ATTR");
            ENDING_DATE_INDIV = new BBDateFilter(this, "ENDING_DATE_INDIV");
            PARENT_CH_DATA = new BBVarchar2Filter(this, "PARENT_CH_DATA");
            ENDING_DATE = new BBDateFilter(this, "ENDING_DATE");
            DATE_TERM_CHANGE = new BBDateFilter(this, "DATE_TERM_CHANGE");
            S_IN_PL = new BBDecimalFilter(this, "S_IN_PL");
            S_OUT_PL = new BBDecimalFilter(this, "S_OUT_PL");
            S_V_PR = new BBDecimalFilter(this, "S_V_PR");
            Z_PR = new BBVarchar2Filter(this, "Z_PR");
            S_PR_NBU = new BBVarchar2Filter(this, "S_PR_NBU");
            S_DOD_PL = new BBDecimalFilter(this, "S_DOD_PL");
            F503_REASON = new BBDecimalFilter(this, "F503_REASON");
            F503_STATE = new BBDecimalFilter(this, "F503_STATE");
            F503_NOTE = new BBVarchar2Filter(this, "F503_NOTE");
            F504_REASON = new BBDecimalFilter(this, "F504_REASON");
            F504_NOTE = new BBVarchar2Filter(this, "F504_NOTE");
        }
        public BBDecimalFilter CONTR_ID;
        public BBDecimalFilter CONTR_TYPE;
        public BBVarchar2Filter CONTR_TYPE_NAME;
        public BBVarchar2Filter NUM;
        public BBVarchar2Filter SUBNUM;
        public BBDecimalFilter RNK;
        public BBVarchar2Filter OKPO;
        public BBVarchar2Filter NMK;
        public BBVarchar2Filter NMKK;
        public BBVarchar2Filter PASSPORT;
        public BBDecimalFilter CUSTTYPE;
        public BBVarchar2Filter ND;
        public BBCharFilter VED;
        public BBVarchar2Filter VED_NAME;
        public BBDateFilter OPEN_DATE;
        public BBDateFilter CLOSE_DATE;
        public BBDecimalFilter KV;
        public BBDecimalFilter S;
        public BBDecimalFilter BENEF_ID;
        public BBVarchar2Filter BENEF_NAME;
        public BBVarchar2Filter BENEF_ADR;
        public BBDecimalFilter COUNTRY_ID;
        public BBVarchar2Filter COUNTRY_NAME;
        public BBDecimalFilter STATUS_ID;
        public BBVarchar2Filter STATUS_NAME;
        public BBVarchar2Filter COMMENTS;
        public BBVarchar2Filter BRANCH;
        public BBVarchar2Filter BRANCH_NAME;
        public BBDecimalFilter OWNER;
        public BBDecimalFilter OWNER_UID;
        public BBVarchar2Filter OWNER_NAME;
        public BBVarchar2Filter BIC;
        public BBVarchar2Filter B010;
        public BBVarchar2Filter BANK_NAME;
        public BBVarchar2Filter SERVICE_BRANCH;
        public BBVarchar2Filter EA_URL;
        public BBDecimalFilter PERCENT_NBU;
        public BBDecimalFilter S_LIMIT;
        public BBDecimalFilter CREDITOR_TYPE;
        public BBVarchar2Filter CREDITOR_TYPE_NAME;
        public BBDecimalFilter BORROWER_ID;
        public BBDecimalFilter CREDIT_TYPE;
        public BBVarchar2Filter CREDIT_TYPE_NAME;
        public BBDecimalFilter CREDIT_TERM;
        public BBVarchar2Filter CREDIT_TERM_NAME;
        public BBDecimalFilter CREDIT_PREPAY;
        public BBVarchar2Filter CREDIT_PREPAY_NAME;
        public BBVarchar2Filter NAME;
        public BBVarchar2Filter ADD_AGREE;
        public BBDecimalFilter PERCENT_NBU_TYPE;
        public BBVarchar2Filter PERCENT_NBU_NAME;
        public BBVarchar2Filter PERCENT_NBU_INFO;
        public BBDateFilter R_AGREE_DATE;
        public BBVarchar2Filter R_AGREE_NO;
        public BBDecimalFilter PREV_DDOC_KEY;
        public BBVarchar2Filter PREV_REESTR_ATTR;
        public BBDateFilter ENDING_DATE_INDIV;
        public BBVarchar2Filter PARENT_CH_DATA;
        public BBDateFilter ENDING_DATE;
        public BBDateFilter DATE_TERM_CHANGE;
        public BBDecimalFilter S_IN_PL;
        public BBDecimalFilter S_OUT_PL;
        public BBDecimalFilter S_V_PR;
        public BBVarchar2Filter Z_PR;
        public BBVarchar2Filter S_PR_NBU;
        public BBDecimalFilter S_DOD_PL;
        public BBDecimalFilter F503_REASON;
        public BBDecimalFilter F503_STATE;
        public BBVarchar2Filter F503_NOTE;
        public BBDecimalFilter F504_REASON;
        public BBVarchar2Filter F504_NOTE;
    }

    public partial class VCimCreditContracts : BbTable<VCimCreditContractsRecord, VCimCreditContractsFilters>
    {
        public VCimCreditContracts() : base(new BbConnection())
        {
            // base.Connection.RoleName = "WR_WCS";
        }
        public VCimCreditContracts(BbConnection Connection)
            : base(Connection)
        {
        }
        public override List<VCimCreditContractsRecord> Select(VCimCreditContractsRecord Item)
        {
            List<VCimCreditContractsRecord> res = new List<VCimCreditContractsRecord>();
            OracleDataReader rdr = null;
            ConnectionResult connectionResult = Connection.InitConnection();
            try
            {
                rdr = ExecuteReader(Item);
                while (rdr.Read())
                {
                    res.Add(new VCimCreditContractsRecord(
                        this,
                        rdr.IsDBNull(0) ? OracleDecimal.Null : rdr.GetOracleDecimal(0),
                        rdr.IsDBNull(1) ?  (Decimal?)null : Convert.ToDecimal(rdr[1]), 
                        rdr.IsDBNull(2) ?  (Decimal?)null : Convert.ToDecimal(rdr[2]), 
                        rdr.IsDBNull(3) ?  (String)null : Convert.ToString(rdr[3]), 
                        rdr.IsDBNull(4) ?  (String)null : Convert.ToString(rdr[4]), 
                        rdr.IsDBNull(5) ?  (String)null : Convert.ToString(rdr[5]), 
                        rdr.IsDBNull(6) ?  (Decimal?)null : Convert.ToDecimal(rdr[6]), 
                        rdr.IsDBNull(7) ?  (String)null : Convert.ToString(rdr[7]), 
                        rdr.IsDBNull(8) ?  (String)null : Convert.ToString(rdr[8]), 
                        rdr.IsDBNull(9) ?  (String)null : Convert.ToString(rdr[9]), 
                        rdr.IsDBNull(10) ?  (String)null : Convert.ToString(rdr[10]), 
                        rdr.IsDBNull(11) ?  (Decimal?)null : Convert.ToDecimal(rdr[11]), 
                        rdr.IsDBNull(12) ?  (String)null : Convert.ToString(rdr[12]), 
                        rdr.IsDBNull(13) ?  (String)null : Convert.ToString(rdr[13]), 
                        rdr.IsDBNull(14) ?  (String)null : Convert.ToString(rdr[14]), 
                        rdr.IsDBNull(15) ?  (DateTime?)null : Convert.ToDateTime(rdr[15]), 
                        rdr.IsDBNull(16) ?  (DateTime?)null : Convert.ToDateTime(rdr[16]), 
                        rdr.IsDBNull(17) ?  (Decimal?)null : Convert.ToDecimal(rdr[17]), 
                        rdr.IsDBNull(18) ?  (Decimal?)null : Convert.ToDecimal(rdr[18]), 
                        rdr.IsDBNull(19) ?  (Decimal?)null : Convert.ToDecimal(rdr[19]), 
                        rdr.IsDBNull(20) ?  (String)null : Convert.ToString(rdr[20]), 
                        rdr.IsDBNull(21) ?  (String)null : Convert.ToString(rdr[21]), 
                        rdr.IsDBNull(22) ?  (Decimal?)null : Convert.ToDecimal(rdr[22]), 
                        rdr.IsDBNull(23) ?  (String)null : Convert.ToString(rdr[23]), 
                        rdr.IsDBNull(24) ?  (Decimal?)null : Convert.ToDecimal(rdr[24]), 
                        rdr.IsDBNull(25) ?  (String)null : Convert.ToString(rdr[25]), 
                        rdr.IsDBNull(26) ?  (String)null : Convert.ToString(rdr[26]), 
                        rdr.IsDBNull(27) ?  (String)null : Convert.ToString(rdr[27]), 
                        rdr.IsDBNull(28) ?  (String)null : Convert.ToString(rdr[28]), 
                        rdr.IsDBNull(29) ?  (Decimal?)null : Convert.ToDecimal(rdr[29]), 
                        rdr.IsDBNull(30) ?  (Decimal?)null : Convert.ToDecimal(rdr[30]), 
                        rdr.IsDBNull(31) ?  (String)null : Convert.ToString(rdr[31]), 
                        rdr.IsDBNull(32) ?  (String)null : Convert.ToString(rdr[32]), 
                        rdr.IsDBNull(33) ?  (String)null : Convert.ToString(rdr[33]), 
                        rdr.IsDBNull(34) ?  (String)null : Convert.ToString(rdr[34]), 
                        rdr.IsDBNull(35) ?  (String)null : Convert.ToString(rdr[35]), 
                        rdr.IsDBNull(36) ?  (String)null : Convert.ToString(rdr[36]), 
                        rdr.IsDBNull(37) ?  (Decimal?)null : Convert.ToDecimal(rdr[37]), 
                        rdr.IsDBNull(38) ?  (Decimal?)null : Convert.ToDecimal(rdr[38]), 
                        rdr.IsDBNull(39) ?  (Decimal?)null : Convert.ToDecimal(rdr[39]), 
                        rdr.IsDBNull(40) ?  (String)null : Convert.ToString(rdr[40]), 
                        rdr.IsDBNull(41) ?  (Decimal?)null : Convert.ToDecimal(rdr[41]), 
                        rdr.IsDBNull(42) ?  (Decimal?)null : Convert.ToDecimal(rdr[42]), 
                        rdr.IsDBNull(43) ?  (String)null : Convert.ToString(rdr[43]), 
                        rdr.IsDBNull(44) ?  (Decimal?)null : Convert.ToDecimal(rdr[44]), 
                        rdr.IsDBNull(45) ?  (String)null : Convert.ToString(rdr[45]), 
                        rdr.IsDBNull(46) ?  (Decimal?)null : Convert.ToDecimal(rdr[46]), 
                        rdr.IsDBNull(47) ?  (String)null : Convert.ToString(rdr[47]), 
                        rdr.IsDBNull(48) ?  (String)null : Convert.ToString(rdr[48]), 
                        rdr.IsDBNull(49) ?  (String)null : Convert.ToString(rdr[49]), 
                        rdr.IsDBNull(50) ?  (Decimal?)null : Convert.ToDecimal(rdr[50]), 
                        rdr.IsDBNull(51) ?  (String)null : Convert.ToString(rdr[51]), 
                        rdr.IsDBNull(52) ?  (String)null : Convert.ToString(rdr[52]), 
                        rdr.IsDBNull(53) ?  (DateTime?)null : Convert.ToDateTime(rdr[53]), 
                        rdr.IsDBNull(54) ?  (String)null : Convert.ToString(rdr[54]), 
                        rdr.IsDBNull(55) ?  (Decimal?)null : Convert.ToDecimal(rdr[55]), 
                        rdr.IsDBNull(56) ?  (String)null : Convert.ToString(rdr[56]), 
                        rdr.IsDBNull(57) ?  (DateTime?)null : Convert.ToDateTime(rdr[57]), 
                        rdr.IsDBNull(58) ?  (String)null : Convert.ToString(rdr[58]), 
                        rdr.IsDBNull(59) ?  (DateTime?)null : Convert.ToDateTime(rdr[59]), 
                        rdr.IsDBNull(60) ?  (DateTime?)null : Convert.ToDateTime(rdr[60]), 
                        rdr.IsDBNull(61) ?  (Decimal?)null : Convert.ToDecimal(rdr[61]), 
                        rdr.IsDBNull(62) ?  (Decimal?)null : Convert.ToDecimal(rdr[62]), 
                        rdr.IsDBNull(63) ?  (Decimal?)null : Convert.ToDecimal(rdr[63]), 
                        rdr.IsDBNull(64) ?  (String)null : Convert.ToString(rdr[64]), 
                        rdr.IsDBNull(65) ?  (String)null : Convert.ToString(rdr[65]), 
                        rdr.IsDBNull(66) ?  (Decimal?)null : Convert.ToDecimal(rdr[66]), 
                        rdr.IsDBNull(67) ?  (Decimal?)null : Convert.ToDecimal(rdr[67]), 
                        rdr.IsDBNull(68) ?  (Decimal?)null : Convert.ToDecimal(rdr[68]), 
                        rdr.IsDBNull(69) ?  (String)null : Convert.ToString(rdr[69]), 
                        rdr.IsDBNull(70) ?  (Decimal?)null : Convert.ToDecimal(rdr[70]), 
                        rdr.IsDBNull(71) ?  (String)null : Convert.ToString(rdr[71]))
                    );
                }
            }
            finally
            {
                DisposeDataReader(rdr);
                if (ConnectionResult.New == connectionResult)
                    Connection.CloseConnection();
            }
            return res;
        }
    }
}