CREATE OR REPLACE TRIGGER TBI_XOZ_REF
BEFORE INSERT ON XOZ_REF
FOR EACH ROW
WHEN ( new.id IS NULL OR new.id = 0 )
BEGIN
  :new.ID := BARS_SQNC.GET_NEXTVAL('S_CC_DEAL');
END TBI_XOZ_REF;
/

show errors;