

PROMPT ===================================================================================== 
PROMPT *** Run *** ========== Scripts /Sql/BARS_DM/Table/CUSTOMERS_SEGMENT.sql =========*** 
PROMPT ===================================================================================== 


PROMPT *** Create  table CUSTOMERS_SEGMENT ***
begin 
  execute immediate '
  CREATE TABLE BARS_DM.CUSTOMERS_SEGMENT 
   (	PER_ID NUMBER, 
	KF VARCHAR2(6), 
	RNK NUMBER(15,0), 
	SEGMENT_ACT VARCHAR2(100), 
	SEGMENT_FIN VARCHAR2(100), 
	SEGMENT_BEH VARCHAR2(100), 
	SOCIAL_VIP VARCHAR2(100), 
	SEGMENT_TRANS NUMBER(5,0), 
	PRODUCT_AMOUNT NUMBER(32,12), 
	DEPOSIT_AMMOUNT NUMBER(32,12), 
	CREDITS_AMMOUNT NUMBER(32,12), 
	GARANTCREDITS_AMMOUNT NUMBER(32,12), 
	CARDCREDITS_AMMOUNT NUMBER(32,12), 
	ENERGYCREDITS_AMMOUNT NUMBER(32,12), 
	CARDS_AMMOUNT NUMBER(32,12), 
	ACCOUNTS_AMMOUNT NUMBER(32,12), 
	LASTCHANGEDT DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  TABLESPACE USERS 
  PARTITION BY RANGE (PER_ID) INTERVAL (1) 
 (PARTITION INITIAL_PARTITION  VALUES LESS THAN (1) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287049  VALUES LESS THAN (1290) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287052  VALUES LESS THAN (1292) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287051  VALUES LESS THAN (1293) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287053  VALUES LESS THAN (1294) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287050  VALUES LESS THAN (1295) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287055  VALUES LESS THAN (1296) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287054  VALUES LESS THAN (1297) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287056  VALUES LESS THAN (1298) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287062  VALUES LESS THAN (1300) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287060  VALUES LESS THAN (1301) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287061  VALUES LESS THAN (1302) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287063  VALUES LESS THAN (1303) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287064  VALUES LESS THAN (1304) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287065  VALUES LESS THAN (1305) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287066  VALUES LESS THAN (1307) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287067  VALUES LESS THAN (1308) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287068  VALUES LESS THAN (1309) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287069  VALUES LESS THAN (1310) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287070  VALUES LESS THAN (1311) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287071  VALUES LESS THAN (1312) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287074  VALUES LESS THAN (1315) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287072  VALUES LESS THAN (1316) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287073  VALUES LESS THAN (1317) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287075  VALUES LESS THAN (1318) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287076  VALUES LESS THAN (1319) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287059  VALUES LESS THAN (1321) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287057  VALUES LESS THAN (1322) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287078  VALUES LESS THAN (1323) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287079  VALUES LESS THAN (1324) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287077  VALUES LESS THAN (1325) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287058  VALUES LESS THAN (1326) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287080  VALUES LESS THAN (1327) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287082  VALUES LESS THAN (1329) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287083  VALUES LESS THAN (1330) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287084  VALUES LESS THAN (1331) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287085  VALUES LESS THAN (1332) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287086  VALUES LESS THAN (1333) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287087  VALUES LESS THAN (1334) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287089  VALUES LESS THAN (1336) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287088  VALUES LESS THAN (1337) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287090  VALUES LESS THAN (1338) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287091  VALUES LESS THAN (1339) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287092  VALUES LESS THAN (1340) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287093  VALUES LESS THAN (1341) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287095  VALUES LESS THAN (1343) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287094  VALUES LESS THAN (1344) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287096  VALUES LESS THAN (1345) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287097  VALUES LESS THAN (1346) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287098  VALUES LESS THAN (1347) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P287081  VALUES LESS THAN (1358) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288091  VALUES LESS THAN (1360) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288209  VALUES LESS THAN (1361) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288371  VALUES LESS THAN (1362) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288531  VALUES LESS THAN (1363) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288851  VALUES LESS THAN (1367) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288971  VALUES LESS THAN (1368) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P289111  VALUES LESS THAN (1369) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P289231  VALUES LESS THAN (1370) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P289631  VALUES LESS THAN (1375) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P289711  VALUES LESS THAN (1376) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P289791  VALUES LESS THAN (1377) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290031  VALUES LESS THAN (1381) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290050  VALUES LESS THAN (1382) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290251  VALUES LESS THAN (1384) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290591  VALUES LESS THAN (1388) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290709  VALUES LESS THAN (1389) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P288549  VALUES LESS THAN (1390) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290851  VALUES LESS THAN (1391) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290952  VALUES LESS THAN (1392) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P291171  VALUES LESS THAN (1395) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P291311  VALUES LESS THAN (1396) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P291373  VALUES LESS THAN (1397) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P291512  VALUES LESS THAN (1398) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P291691  VALUES LESS THAN (1399) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292031  VALUES LESS THAN (1403) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292171  VALUES LESS THAN (1404) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292291  VALUES LESS THAN (1405) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292392  VALUES LESS THAN (1406) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292671  VALUES LESS THAN (1410) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292791  VALUES LESS THAN (1411) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P292909  VALUES LESS THAN (1412) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P293011  VALUES LESS THAN (1413) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P293311  VALUES LESS THAN (1417) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P293551  VALUES LESS THAN (1419) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P293669  VALUES LESS THAN (1420) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P290989  VALUES LESS THAN (1421) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P293730  VALUES LESS THAN (1423) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P294031  VALUES LESS THAN (1425) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P294151  VALUES LESS THAN (1426) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P294292  VALUES LESS THAN (1427) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P294390  VALUES LESS THAN (1428) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P294712  VALUES LESS THAN (1432) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P294891  VALUES LESS THAN (1433) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P295052  VALUES LESS THAN (1434) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P295571  VALUES LESS THAN (1439) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P295711  VALUES LESS THAN (1440) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P296012  VALUES LESS THAN (1442) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P296293  VALUES LESS THAN (1446) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P296453  VALUES LESS THAN (1447) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P296631  VALUES LESS THAN (1448) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P296792  VALUES LESS THAN (1449) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P296989  VALUES LESS THAN (1452) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P297151  VALUES LESS THAN (1454) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P297310  VALUES LESS THAN (1455) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P297491  VALUES LESS THAN (1456) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P297631  VALUES LESS THAN (1457) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P297709  VALUES LESS THAN (1459) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P297851  VALUES LESS THAN (1460) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298010  VALUES LESS THAN (1461) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298211  VALUES LESS THAN (1462) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298371  VALUES LESS THAN (1463) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298451  VALUES LESS THAN (1464) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298459  VALUES LESS THAN (1466) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298591  VALUES LESS THAN (1467) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298689  VALUES LESS THAN (1468) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298809  VALUES LESS THAN (1469) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298911  VALUES LESS THAN (1470) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299071  VALUES LESS THAN (1471) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299109  VALUES LESS THAN (1473) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299229  VALUES LESS THAN (1474) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299331  VALUES LESS THAN (1475) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299452  VALUES LESS THAN (1476) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299511  VALUES LESS THAN (1477) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P299549  VALUES LESS THAN (1478) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND , 
 PARTITION SYS_P298455  VALUES LESS THAN (1484) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  TABLESPACE BRSDYND ) ';
exception when others then       
  if sqlcode=-955 then null; else raise; end if; 
end; 
/


COMMENT ON TABLE BARS_DM.CUSTOMERS_SEGMENT IS 'Сегментація';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.PER_ID IS '';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.KF IS '';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.RNK IS '';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.SEGMENT_ACT IS 'Сегмент активності';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.SEGMENT_FIN IS 'Сегмент фінансовий';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.SEGMENT_BEH IS 'Сегмент поведінковий';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.SOCIAL_VIP IS 'Соціальний VIP';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.SEGMENT_TRANS IS 'Кількість розрахунків карткою в ТСП';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.PRODUCT_AMOUNT IS 'Продуктове навантаження';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.DEPOSIT_AMMOUNT IS 'Прод. навантаження депозит';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.CREDITS_AMMOUNT IS 'Прод. навантаження кредит із забезпеченням';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.GARANTCREDITS_AMMOUNT IS 'Прод. навантаження кредит під поруку';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.CARDCREDITS_AMMOUNT IS 'Прод. навантаження кредит із БПК';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.ENERGYCREDITS_AMMOUNT IS 'Прод. навантаження кредит Енергоефективність';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.CARDS_AMMOUNT IS 'Прод. навантаження платіжна картка (БПК)';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.ACCOUNTS_AMMOUNT IS 'Прод. навантаження поточний рахунок';
COMMENT ON COLUMN BARS_DM.CUSTOMERS_SEGMENT.LASTCHANGEDT IS 'Дата останнього редагування картки клієнта';




PROMPT *** Create  constraint FK_CUSTSEGM_PERID_PERIOD_ID ***
begin   
 execute immediate '
  ALTER TABLE BARS_DM.CUSTOMERS_SEGMENT ADD CONSTRAINT FK_CUSTSEGM_PERID_PERIOD_ID FOREIGN KEY (PER_ID)
	  REFERENCES BARS_DM.PERIODS (ID) ENABLE';
exception when others then
  if  sqlcode=-2260 or sqlcode=-2261 or sqlcode=-2264 or sqlcode=-2275 or sqlcode=-1442 then null; else raise; end if;
 end;
/



PROMPT *** Create  grants  CUSTOMERS_SEGMENT ***
grant SELECT                                                                 on CUSTOMERS_SEGMENT to BARS;
grant SELECT                                                                 on CUSTOMERS_SEGMENT to BARSUPL;



PROMPT ===================================================================================== 
PROMPT *** End *** ========== Scripts /Sql/BARS_DM/Table/CUSTOMERS_SEGMENT.sql =========*** 
PROMPT ===================================================================================== 
