CREATE OR REPLACE SYNONYM BARS.V_XOZREFI FOR BARS.V_XOZREF;
GRANT SELECT ON BARS.V_XOZREF  TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZREFI TO BARS_ACCESS_DEFROLE;

GRANT SELECT, UPDATE ON BARS.V_XOZREF2 TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZACC TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZ_IDZ TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZ_RU_CA TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZ7_CA TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.OPER_XOZ TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.OPER_XOZ_NLS TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.OPER_XOZ_ADD TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZOB22_NLS TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.OPER_XOZ_NLS TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZREF_ADD TO BARS_ACCESS_DEFROLE;
GRANT SELECT ON BARS.V_XOZKWT TO BARS_ACCESS_DEFROLE;
--GRANT SELECT ON BARS.V_XOZREF_INV TO BARS_ACCESS_DEFROLE;
-- thisline modified for test SVN
COMMIT;
/

