GRANT SELECT,
      UPDATE,
      INSERT,
      DELETE
   ON INS_TYPES
   TO BARS_ACCESS_DEFROLE;
GRANT SELECT,
      UPDATE,
      INSERT,
      DELETE
   ON INS_EWA_TYPES
   TO BARS_ACCESS_DEFROLE;